#!/usr/bin/env python3
# Generated by Oxbow. This is executable Python containing an inert Oxbow payload.
# For untrusted wrappers, prefer a trusted `oxbow bundle verify FILE.oxb.py`
# rather than executing the wrapper directly.
"""Standalone runtime embedded in generated .oxb.py handoff files.

This module intentionally depends only on the Python standard library. The
payload is data; this runtime provides bounded parsing, integrity verification,
orientation, document access, tours, and safe extraction for the locked public
Oxbow wire profile.
"""
from __future__ import print_function

import argparse
import base64
import hashlib
import json
import lzma
import os
import re
import sys
from pathlib import Path, PurePosixPath

_BUNDLE_NAME = 'oxbow-tiny'
_FILES = 26
_RAW_BYTES = 57421
_PACKED_BYTES = 17230
_PAYLOAD_SHA256 = '6fb76dfb847a34d9fd5ab39dc92a3c00c0ca93cd83666caf4fa4f4ae09a995e4'
_PAYLOAD_B85 = '''
Qd2@P1poj50000000036W@&6?a{w9u8m$B117ZQCT>t=tjp%3#&?<Y_*@`hDl?%IW<3gY#jd`B$Ua4t()R837<ocyDrD^9PQuV&*
5ZrUwLPu7D#ga_g6mf@O2IZmvu&m9L_-e5BE<Fa&s*kTqxD6Vik#@I9$4fymWJze0#D;~8r|pLs5VZLrbS8SR-aE?mc)wAL)(AL<
mzAvj?HXPcvwI%qUS`lC!)Uv(BltSj4d-`iJhX-
a?wo+`oas|iarNTD#@CV3;vPO&(PdT8a{IxZ^OVPHdHAMx@Xr%t4aGS2u;sR~#Kv#~b}Srm)tdW*^wC+Y))8|Grged_E(KaNJ9S0
khNA!Of5hL~VV^$i-qm7_o$z8Ho-w+9eZDm}Zq7-
kbMe#O=7YhAX8hNhy{)NNtnp;jUn~<;CtE!N%aXA9tYuAlE#A5~o15dLknW~fo5-B^ZQAle^jB=OYNu<%v6$LVd@PV1!~m$i9E-
l{m#c4N?|V#IBp1Y^tL5i@nDy*bw||~<t%6<67o2Wucyz}1jp%}hz%WkfQ$@r<Nu(jokWtfD;@zjStXc%7qmxmvsFk1qH~|1N0Fe
lw6S@eRLB9p?72yTG3-}c3BCH1Z35W-
#1bL1EhXVHj#R8E5>I3Ks#}fJ=$61jz0Lp>^;NVO_LR|n6hz7^P2>7T^P!U&96sBRAdODoO9zbYK%nLtu=if1C?K0(;Nhtz2BPqP
8PKD|p$BQ;t@xz=u#u!vV=N;@O-q7X48!+UKzAwHRfBZ$0GXb={^k(PUt?ezZM{C!FI-
4{BG#ygxr#4q!)387`TZ<JgYg3rX5AS8Q=}Ya}U=d==!buAMOa=2a=IK9h#L%m#6^WRauE<+&9Dy5;$^}P6S>e8xM^vs#DBn2uYU
#Zp2zj2jB67)9bi+6Bb*0RT95e!JE-5*rb@Z`V1Mn&vS|SG}yey!-#!M@>?-
&NyH@{&VPmXBEA&LDp53xkbPF_3J<e?8U1&}FByp2HhR6GsPM9Uo6^xGIycuIPQIXdf%3}wb@+E_c8WluE>oQSn0JuG|{hS~qDQn
)EWMTjVf#Cr1SZ4>ym)xbcQOIG>fIwOb!%o}{O@gASM_1`a^D1$67fSl{q=`_oZ23wXK8~K*$|G!cX@`HuF>Tn#;<Lnk+zqw$Lc(
-hbLmj%Z))uqyu32a4BFSb0@}Wpi1_y8Puhm}1#e<5HS9qC)MgCX#IaiOhq?HpirN>kyHfYSITWEJG9^6D}gWbeYFPHR!$?o~N+p
DRZkJE2>U(1UZ(*0H>8LhjqGX3nipPP<GC98i76KL>!4-
Pyh$h2)2xsW)!`d&xQZoKk{x@!9CBxB;Sg4+P(+!yJ|baR0A<EYpAhI_cM@do{_GW|Ehg~2^alf)-
|O$0e<XmBIT8!^+P&o@x;Jyk?rVyQ+V<{FJD|L4<0^@b??8lLBdIJUW5Gc|bU1aUhK*LF2;1o=>ub_n|EsqGZ%&4dGWjXpI@4Kqy
aerbI{U3W5z!tCJ4d$~nSr5#7pbrEop@MY2b3I^*ZF~@ko5W0*Q4_h7IAP7^Kv`RtTu3Bi<NKxF+2=70OU<N_my;Nr(*Sjc}h`~W
d(=j2o*_NG=ysAs*PAfxvA~?n!?dx+>%tDb=w)#}uF;6H88ynak4O?iE6nL<7Py8_a6~qnTnqDS{epsv9q{XK~N6k9{e?+4kEC=v
&`J<Xebl%*Nn~d;!#;D_Pc9*+FQ_dv5T|cOR`xXkBqdHLhYH4B}8?yjoZTnBL(MxKV5t@3IEPOShTac)E+mgKerBZcOyqXQt{4+!
A`A3=7F-Pvn@_SOoUQZ0W;sSZ~<2WxrnTul(gzH5z`^Fb>2_LCU`xiK&3JO!-
1{HT5><7e3MMl9$FjmiR+pydyE&$MZ1^A@dQw806*R6XL!cLQSL#b&)Aug4gY+8sbwme@qU|Ok||26FD;$QcJ>ca<9caOvRLh!6F
?~!w%4R@;XL~LKzD~;#nJtqY)Ss4;(ULcrajdxk|#}dx>L-idcdGFm2t59|PnaMN6DUz}zQB_`jb(XMN-PuCba-Cd+B&MuZ63W~A
1A8m%7hKn(xB2u>?ois8D1gJ;0mY4@kbDORbVD+S_cchxa#-0wW5ni6xZ7pqZ0t*kj|WI9#F!RQVnQ2SRWh)E%W56%Vc+1dHK-uI
g9oT9;Mnb54#!zAdJka0oiP$avu%~dfr*qSwkeN<@a_S(VTbWg)*KdC#&|;_t=<5a#*X!ZqL>%i&!-
K1v>>gtakI}p#kSNT%|$(&CJ!l7Ye5m@I@?2dA4&(ui7Mi74i3?)FfdQ1lejmWvC<)R*n#U^2dDQ>*<pndg%_|veh!gL9)g~k^8=
kNW%J{>5Wi-
3vBPUuzh677kL%gIk|&3{xhUsIEWsB4cq3SWUFU%?S$FD7y=#nQqtj<?|7|GF_;oN^#!;HmHIBCaV4{oFDv&korOL3MY^tTTiO7i
pS*`M!vZ%G))%D`vUa7BSzD_(ZrCT$P75BlukLO1{jD+RXEAyv>cxi3tZ30L}jY*?Z0ifo#>LU!(jy7HFm*C3*``W(eG!ZXHk0Vv
bI?xCO&@=kBi#G_u;m+gvrB2~^vTP3RNJrY;{bl{(HnBCs@UrO+?crG$oPuE8Ea97sT!izKNo)=tgv&9g8<!$8XC7|2j|}<H6l3X
1q;RNT+DNZ~#B&aQu423vb&-OIxg=J-iV@kP6D_XrcZhK1gVZggfYzaK&Z~x-tzO;q70Qu=UbMuhu#m_{&Ds9c#L*=PuUD>jqW-
|4Le4z*2EJSbvmmwhVZ{uAQ1(1Y${FwyjOMGmnc75mxQrDK?e>K?!Jb5QwBc|}#0?-
(GcqCxL(msLeDKtDAZny$f=D71bJCD%cqH+Icp#c<S(bU0SvlsUFQ@q{287rgKZZH?67KdfL6qm6ff8Ol7;^)BbqI(c2KO<w3^0=
YIUUF7Oj^AHsIA6ILe5@K;1t}m93~sNv(S%~b$|^9TBW6A%sN9a7h3V^6bWH~2O8H~h7TY6f~_|3;7Sso7j>oYt(VrGlA|`2?A}x
K%f4DlXPcGdRl)AkLP%A^>?remRhOU<2^=$qf~<u+RX8NLJ9*a*<xdi+kH1b!vPtr~Fj`Ki%d$ie%W7-
4DaVSKV?@_n8qXDEe#4r(Ab|m)zH;<mFQxYE0~`}7y$(&w5Am!tTu??pGX%_*8r1b^z;aK1;@rd8tT*)J+x<>K0mTB9^<p{gVctx
pwts`3dLhFI*6DRLO2?CO#+1H5e22o5N;B@82E6lNC)b}$Zv5jMG{^px?d0nn4Gyj!Gwx(K1ml&}%?kIn*8&@rSt(jF^3H$@C#NK
E7MjVd6D4(m50*_g8yTq)h@AQ%0#^drm#(r5VgaJsrc5LyTeVONnB^3Q#-
D(T<4XHmcIU{HaD8Jofob_+wBaiGs0ZQ%Wa|}8a4MTO2bw1w1DG~inlBL5d(cK0B|VU7d3kcaDfy%w#L6Eb|5dMBMC}UOS5y=rRB
||3f9E?s8D17Lc~)C|xIzO%G_}k+my~svAV|H)d|M7{vHUAk?*5;9v83fOoGn5}5(Ish&D^}c$8H=Jd`iGJBQTi{U%j$w7hQ%~oe
!#vU*d5tlCIC-6<;oo7bv58-
}w&9=v9CfHt{|Zp09@fa@<UAfiqq;m2FkXQI|LBb@|1Cym^u<L(ifE61b@?IYZz>Y0P(sw@A5nc}O@H%N0_oY~r3Yu(SMbY7|cYf
|+uX(xB>X(4>#RDA;4{WsM@3_`S0p>zR9OvV<0Jq&5g54?z2C_afK}LE5;AaLTkBx4O^tO)LHxnJa9;M~Fd7sBK>{LhoJ@?<JxU!
Bm_61GRo`X7`vq<kY<*-6e7--hbx?3NJ%}g!kz3T#{3oFr+=zTR^8P1)y<X_MR-
_*mdc8XL>eRw}CBoK~cpWvmlL%%ch`UAxr$+@w9CbIc+cA)BW?yCAJHw%y(O_Qe>hd>xFfe+jVV@xTF!YN6#|LdtK?Ayg!Bm+eT)
c60D!;ih<K0dI|Q!)rZCBZgG&f>bVFsq}>WISll$oWGoQk(o?RoN?M`JhQV|P*Bi-aZJ*$^DkDndQD+2on7@Gt*_aXK(7R#cxaZ-
R1E1Waor&gtpyDcA(22CCl*D)2aM!-tmZG{8l2t+%==hPEb?!;1PYP6<Z9`nhfS59z4YSrs^%2Cit6aF2Q0-
*orK3@*p<mTnN@Khq9|<ELRe7twWLpGNtqk-
X{2)<`8WeAnJ(FuZ<7yBfC`U#;wKg**oxD+L{~0$_{2x>?qEJD(B}kJ33bUg}bFcbD7%l=+s;lk0Co6m*D=o`RYPq<$?hiq4z*SK
>tlV?t@~ys;6D8F_=0pDQjBXn55J~-2FKHekWXNfB8YFqO_D$`2*Q8}P;BJ;0Ip?b4-
)_=vF@Y|fx*upeO)fX*+uRrotJj3?lMZ>#0%l>hVtz{@P6nuR!O6Yc3oJ3+!a3utF*li?2W?bow3Nb#r+`3YccC8NcdSdgg!;coo
a3_p>sL|ll~UGB`JaZU<k$W1PLf(M>3W~~Xw5z%0ts2mDI<Mxwgk}bFhdj8-
0KmRbzX$yU|mDN0}c_*X=0Ob%R`s*%Soa>flf|tk3vz78%+VWT@j?2#Z{G#=QI4)LepSq7Rh_CKF}LMof1|5&a!q<#=xVz%cH;xx
X(G<)`iK&ZO_SX2AHk|?5R4^{(EthYjyd<61029(oaYRu_?&O3LJn1+bFq}Li*+M44Lm}$ni^Y21i`7sYX^y<r}xeVv3c(opP{-
@GG@FHQJ0_&P#)*Q6<}ygoQYLGVr)yeEN)s0#EULC}>`K^5ReDYk8-
9ECG1D#%skj_&<dWINWpHySXp|Nkj7geCo#$igoc1=6Yqno2BlW540f?1cR&#&8gZeYItAEko7Yf#glfC#U6nM(y$zB&$5@VB(N7
OS0oqRvLB+)qwEE>b^{@f9G>!=D7mneP{P-QK5r<QoE{##so-zxII97zG84<=tJOfH*)=wDf+K!bbw4y1kbyOe0Hf6$*;uNpc%X1
xi8!o?xoYW|rCIw&Ai7wY%yhLJl$)^y=_;RC{ysUnU7U4n4d=p*?)s)@D4)Wd>|JVHQlHl~UnT8ovVj8h6V4AI&Ua|uV?gI-QgHL
93ld>;Il|D$Leag^+W~=9tcm&fY(7j43+JJX_c^AjP?49R(~CB44_f$Omo>ayEgR~T{q$^ID!PSOU7rY4ip<ZCB@@EzO#;Ucp`rc
~aeK46@{$CTS1X$<$+<$r2YwFlsuNbEk`+bs0Bd!<g1R;0>B$oXl-
2&#1rEsZ#$fpgrn2QE_2Xa|k|qqN0+yK0SwcQ48L1wCoinOioJ=?;lT_!iRB_krsh*jQ)s0>{wK{hJj@s)qz<N!~v;qmt(<piAD6
$$l+MTA-k*xo!rm%6rUBS$Qv%+1r16tf34?j`e?qnWbA!0J!-njeIg^%-G#!W%W<Ij&**kM5qT(5|L@a1H-
mBX5_b<cGpG*jz<OvXTu>el3Ss3I)vm_R#C>Ty@y<%K|l)Fl(;r%ccs6U2nYPg<z(;S=(BS!AIQ_v)cmO9CftO{_gt66k6Q0)xJm
0KZFcS%LJSU*Q%s#De?QR&TL@@rkSXv^sFq{$(gQaj!I1EY?Gx0dD9;ar@Zb&Y0PyZ+$2$;sE!7E5$#6k$C~S0=+avWb~y<2k-
S}As20HG_-o8-
NZIB8*<&+dW8m`z{cNxgUZ;F_#3Gu$p;OmD>ff|ij=jSuJ>93+sK2Mr%_^e$!zU#pQ;pTaq_a#on$wnr>i4bI02v%K8IaS8$~wP)
Yng$5JuZ0gnGJ6a_560Y`6`kTgxijR-tNH=<~E#mIo9FhuF1GNiqV>1gSF_+}j<c5}UkkeqQLx?_7dD$p_HH&SGMj4@u+hi;&ozm
_RM|f&DN|J=>Q7(6K%TD2!ix)>g#i8W{5zv{`b<FVm+bL$1w%H$+nl=u2IPn-dNcYJ+_WzbT1*FTZU=%+?!U5SV47SCtMvCN0)F;
>@rj(D)^_eColq+H-
R?EhGFF|5xcDlQt}PZMEr;mRLQmIu&3IaWRW`yY0MT^3oLX)<bU7O6@eC2cC#`GX>)wJL%1bf46!1rO#NT)m4syTQb&eTtm=Px^#
S%KW0^WGF@rxemf&5FA1h~f$g9P2mneMG=l*RtzX2Nu~`y!2<&pD2fH>DQhOSB#Vaxtq3TOq+PfWaF;}^S8I~GYBj5(`u?A}C=`G
s?4tVTIvy~V=6d(Trh|ptBJq|Z&@nYHbP%0Lz>^&skt(<e^fh_LyunIU?`Xu4lWe3!Y>VVg$Pe(MJX5yYJoDQ+qGJe7PP^s2R`!%
FTwzz|<4WfnkHchKeM_}A%U}aD^Lee@SmUM0oGAIesN(jYTnjD0yN8~`E0bLRnaY(DW;oeye$hA_-;-
+@EP<~3;M9j>tj(O*sMtg=M5U<vtkE5i70(Wn-hxQvtIDZRCWL(~7!(Zf62wW;MabV{fb8~e0BNZzLS-PMVvf}Ic#d%~+VAvk={L
O5J1Q0nEoak^oVitOYQ1FmVn>3=U5hFDuAST5jtZrVec%)ws5sTvk&0n{)W`ROyX`?UCPF$V7wPsIj?2<wgzsO5vG$zb<){tgF03
;;{VwIJu4IKSC^X@`)O~b1W{nNbke5{ZbVs1!2(0#LarS<<k6H;CWy#Dh~CumUzds!IS6^z-
WVm760#i%WKG=I&EcQ?~@OD4ScdHjal#W%XdS9VE-
C0?@bL&!$5H>v;7!{@%bpMnm`2d$6TR0e{thmM^Uo~qXEY$>bavDxKWeAYcQJyyyi#}Vi$UzcO;$uth+_PVN#Syv_RSjaTPrQnrX
jIpx#`AS}nRjK}7Rv)XpJUDhisWr|1*worB%f49T2kVY^uE!r4qCYq(G2?2`**PeXZ6U|g#lD5l2=4kL``m%cKfHCpj_DpRuJEsM
O3mbWSgT&_hfbKk>g;%`u>H6eg~=C)2CIR86BXA?f0oODK^M(V|FFM{reIBXFx~p#l<UEQ%qPD15?{FEKQAIp%KOIZymq~VU0bKV
0Az1z9T*bGj<R&QTH|Qg#5Z@+rhCxZx`)!YVZdZa2|H1iGHp%Kp8Ez&4jVus4$XI=yaOzh#?8i^Y;eJ0Z__4f`+)@TzQ3w(f;X-
?MV<Om`zplcho!2V^PZ{Ze10olJ*AWJOhr?XXS|jFkZAQHTZ)uFp9&OwOie3%Z_ac~74UIxncyJm<lAP2-
9M)X*~5MnQ}n;%fnG}kH+cY^%dDw^5$?J7-qo!abSJTQ?6e}`-
9D3pmZ>8kHub^^k*Vm2QXA8~Voo$~SqF?hqJ7}d^SKZxk{DTFxBM5R2**GablF0|$8M*zRX(kgs1T^>?$t7p*8g+nogB5cQpk*!-
p!2uBp1%E^P<#Lx6;oRl)^rdnavOVHzdmqb2sElqg@T+c3V{yBfurRQF-V}n<WKZA)Q~X!6u4htdwpt3--a0{QfQi3NmR57Cg&#X
JSXKq*suS4Fe6IE)6XMA{k3g2do$iysbpiYJjzQeB9&R_Rf;jgU>HE4XSfqT?d{pNUNW0t9ySXGVCUxlN*{e|Dzm0HR1QH-
1(iUAG6a%sGXC-a?(IJfklL45#Xc}c|XCmV+xI})P=VnI;Xwm$$zoN*exn_(i>Olp<$pii~W>MeV}-
DPkJSBRF}Va!z(wAcWn5}HocBCj}zv4C6nYX_z2=ul2FJP0tXmp9h{0?{Ko-
=Ayf&mu@SPInnH8Y?BR8FPIJ<FEaMx4^(6nPdyz?r#w&Z5t%qvxLPR_lb$LUY5v^YNl-
7*o{JGisN7r(U&=BUMAIH{b@ph)KwyVRIaL$@S<5Zl++n64ca-B}b-
MSm&l2sGNUJ!Vtb}q`n!g`MR*5PRf!8w~niip(aJvXj(`G(iI?KNze;PXKM*zp}11-
|2L;JR27$?xiw?OuT7r}GT>9c=^e68kjjWs@*5#=mT}go8dS5VW%2IQvc4XwlP4oc-Y_`W|7fs7*6}E&&^_oHmB|tiRL1y+<8bV1
uf|pmEjk(wMXVIRmKnxy<3k3Tz5aDo?EWKZ38};M2X#5nAIe8jOtv&yP>q7Cq!QW&UB*VJ2LSsV5V@OT+u|yvvTo8e@wO0~DP^u>
cFPx*KyVnNiLc79!I{hVZNLaO;v_wyWyH9!h8oH$R|fQ+X~y2VB_VY+wNiR;>rd&{|`o6(cP&%g@C#nSCM2r0P@-
w|{rdw`L18h|l{POfUvU=d_P3&7!_R%DO$P3zWmhx*~C)fL;5_f!BC#WYrXrybO0sM9DSOa`TC)&;Z~55&uf9#IU;e(s)fZy?bVH
nG|#o0f$UU?weKmNvn>pYzHa-Rb|8pcq`@9&>uT*fN=;2BsOCBJfzxcit!4@9;q<T;&!;(^}Z}!;pgXkG`mQX1W%z)k@am{%!e8k
K=Uzs))0<Jb5}j@h0pJ{bX)D9@<!~&GkCX}e!FTiCxZT}y%OweJMZ077<d1&&tH-
1eF?r&IFMMd3p_Zj!SXw64Zj7Z$#AQgH(<D*XFK2fgD(RnX&p#we|D-
FRx7|n&0~Tl0xJ|I!NEzc6R~gRi#j7^4^FzcwipIA4w*+>X>Y_~mf6eZd0x?_Tu+>?cgNHgqaR2_VZ^LMb!)YY=iq*H$I}6RAS@@
=(q`{@?K97!4?hhn+x3B}ZFmg=^aZ470tgjAke8EZTOV2$@t%y#k3@|Rckk$%*G?3<0<0#C*1dOPUEB(chV_lPs-klsMJ-
T2iaI{ge92SmMP3j^eEpcY{cv-}O^?~wit*4@rb}`DN%t%Al6c+VsDZS!uCpz3dBa@P@c7=wX3l+Y7_pu5lV9*sN~zkj&M-
1@AhL77&YP^e`332s4*|^O{%~wD%mX%14pT*$B`DEKtMFK&Y&BB!Q18vitq2`95_6(8(p~1ng2hugA-
E7HBY>=dFN$T(E*^gxAi#(Wu!392*`lbqnM5W+sfdyvvNPrEwd7z~$U0m^fK!U^jQ}>3&9ba;@j;$N?C~4WH9HM5SB&VO6uBXlg}
2zBTBXF*MIg4fYh$6)gE(9f-XyjG6?rvc?DGS;Y>c;;Y1gUnm3cC^f_f(6Jv3G$K!OSL|3%z_qVhs7@qcgY4^!h{zkFn-
9#Yk^r9;=vA;AI-WqiQ6qk*_-
S*=FwMxcT^ElkCAUS6`q@3LF(lmh6=H4$VJjE?q$2{;#I9P)^f)RhzhtE$SY(uUtL>s4CNO(ssKPgOQI2foqfRd_9fF|M$4<s=;2
%hbp|eeh(@c%!aGf5D-
{*1Y&1cca$sz3*0@em~tj9!reO^>$9J@uR@cc=qWQJ`N^w17$S({(_g_q(H(6InH(G)JxLI1fU42Y{oF{{;(!rk|ks9cdJF12Tam
u79LoEJP&4rwM|37cfr<)L{acnsBEZQB3fGWdD<_DFZNs}=XJ_?E!_GYCyu0D&rL?2VDdl2Rn?WGG0S2oC~{>YDg_N(u4YBAhaIU
1-J<PX<ANwqk;>Ia5<n;62S4hVv`;87qt$Km#}1s;&Sw-WGuQ*@0HBkl+Ta-LGm&A7A#*?^FPHJ_Joc>y>sFI|<7Tco3ixG{2Di_
<jUB>!$C5gK4(CdMxHB*-
SO$RBbEj^@>WMmJtGndkXX=P~&kXwZc{jxK`|WvrRLx55Nmv%?P{Tni9veTdkZk9H*|q*Z!DN75aH)5kBb=jmgoPkGedW0f&7s|+
?$>l`fDg00H20n!SGT^@&Vl$ABftyQ&9D2(2dW2LCrCx%rkk1g*h&sszZ8UZpFl;Jl1Ry|v_;#0gi_w}bMq>wLS3qYH;0=W4h>O(
=fvG?^W{B+ivuc6S`9|F2$+S(*;hg{TqRmV@Kr?u^7@)I7l^!$f&OyS6Fyu8@>sP?5Q6K8yPKoOY^3r_-Af9~Sr4#HvO)9!VVP|H
xFDHmY3Hzx>`Kmi=tfEBg%BaNZcDGdjw%Mgf!RnirS(mvFP57qjc1L}DVy{#5s{*>g@P1*Jfq(nlpw@qjV*+jiGNi)4tMdv8*>xc
U8k2#YWYLoAFn4ph0ta9>G>77QMtu0a*oqy1(Dl@PK|@Cs|ZB8+GSTSjkz~8k?Bq9Q=<1CuX$S4sI$wK_l$(Hf_lpmjO+n^b(>f3
yWL3!Hs_7;?KD{{sB|fe35x(l)V_Y93?Js|Rx#9$kRNwdQhwv`jIEYg#CIkfzg5QVU*GT@RW#E1x2102+tuK8hC7MeI=g%iqb%c!
T*b8173h^er}Ra=A3AzF?n5KMRcsD;JuNwgD{ZmM437s`IvVqd#7g#iEiLQMQK+sWDgMh}(@@?k5^UUy?$P=+VhzN}0~86~{QL~o
l25CPOtb6Y-m2X&@rx?-S)_(A{<SD-co<hACl^YO*D3d<*djb)ff+!yU$Z0=pVKez8#(QdIb55v7U!3|9ZyuojxrhAQ<2jy0tZsY
Qn^NB;6qFEEN(Nm)FhQ?iZsUKFa*5J<Rz+0zk#^6(PVx;Ke&UowKvT`lKne~1WX-
;JVbMfN~ANaZTi90!(BwDMVHM7bm0FGs?Nb;u$`mwvcNhq6I$^Eek9(Y*;DdukG2q4WufS0d`w!v1xXE^M@47iabbL8L}tRfLGy7
DEfL5(Tp5Ey3~%LhDFAnl+6evzt&jP=C9@2Zzg>MGN!?WxNM^(NP71~Q=F@2rcqc3F6_G_)YSyyGp$LK;1Ss_5r>>GunbiSiUY!A
&&n+p6p*_Os)@e4w*ynPg$LPN~$<~kvu#%mGcQCjY7OsEMHtn!hnb+5cYCsYU*ZK@28n`)2lG~Kuh%{X%kXs+vkjw{;=M(@=)l2L
)WBw2jZ7R_<ax75b)@!`iupaA;L?mtY$p!o9pAkKHt??(^gKgd^E=LmC|B)$S2x_6IyyOgP68d?@bpZJR?PJz7F6$vv-zD-FuQa+
Ed%k7UPfLxwosKp$ni8j4d}uw}c|l?!aYn>2e%Wvo*hm`!3v69f^O?rbNlTCF!K<NhiH|zMS?Z<SM)+%_Igng%c}5Fp0D#6QuIPC
mkt(_^=F(n!?uq9Y4v42m2VIJ@;8UqU`tYI<*#iZ^C-
s)H@WHK`3jWOm+qN4W(WnYkl2}hBBTN!W1=LWFtk~#>O@1Qd!u`v@T~$&_n)Sqj<W%sS__I$#t1}Z;i!b8CM#`*H5~1%oIcBz}!d
lX6vE<Ns8*_SZ5iDv(!7)bcW)EsbmV|4OVQiIr=x{rbgILd!MpOHFN@m?Zy^}C7R=l+~Lh1P8qTS5Xq*!q<g{*q+*0c*Ep?{r;iA
+zs+?6sLA@YBEoQ^A5T?S@6<32(uFMA>=2@xVDeZ3vx3oD7G&ID!0bM9hm%wfDxfRlY`Vj;&wQIE7G$njSfr%VO|t{rV(Yz!)Qwh
XIu%=l2iTETS<BR8&&q!Ir`q3VONC?}0~Cd6CxFP42WPc%-kjl~5}2R<-uH{UU$j%dSB8)EShO+UG4;DEgElfmd+-
3svE=BPa7EuQa9i-@)YOe(YL<uR&V*VhWb$*l0lGDMiFkvc#Cg_+xh5GmS%&(xe*;3bhPeXSk<QW9+DhPlF2nUK><pYr-
PII^U54W$(}e=|fngD)Mafz*OD+{d?*3l7Y=hqyPVl!;bZmMieH+r~$&go&QWbJsLT*W|Y55-?Qac013MpFn@)1AyC!VG*OQaxB-
iC@7;1O19iKQQY8_B(=+iUb$Yx8{sh4i*g#!)G-gaOHYLT>%gXluePkZcwRdBZd!M4@Z*xXX(*z-
XeQJ{R;R3Y_kAq;k#vQ`gXym{0RR^hjw|BO@}(_8buk?Q`~zGkPc@5KqS}37akq3L@f7R=iCn!(fm#Q}>H#rU9PjG&3OeOuf{v10
14>BMz_t>n$TT{y9GXwn0r8;K%0ML#-`9OCir8DmOh#=}%-
C;lvvsN_y|1N3SGmjbj~s<Q)hfS%cfnEIU6LO{C_FsI%e(QQnH>op&-
4K3_thUnt4yQ)8At`L`NUMc9}PF%A|c<k+Ffk|=Sfu<ItUBcL8snwvnv8%e=><Yu7Nl>2LsN)3{R{;ud)|p9m2{1*pb$rg5Yw=HO
!|N6FUSYsfpo$yL+BqqS)YrSEl`BGE>g9Z5OL2$goZ3-
S#y_yj%&7ltr3;n6V~7;;GGF%dhm>3SGwHLWPPD0GpBiyjV*B*rdaFx0x~^j+=?ZlaUmg;nSxN2K<%$Miw}1WBFwLYjI~t&9`2s1
8b}L_{B|oC(FMkkw-
9gUtYc<tJFvsQc;C={`eSbf)3eA%u#*~3$Uu4D@Yg;5h~42oBgKy!Dc$}`~<^PV(&c$2fwRY12}CFff>=6m-
lQTMlS$p@ND#XSoB$8_^sAWb0GS2xW|+J=i)WIM_&4sn6K?3<Ax4D8XDynlu?yerM63__x2=!1mC5rIYw>_`NkZXNG<b2`kj@Fuv
d@wB5N*i^E2!pi+Y7p`=U$+3J3N23kLgmpe9Y<BQ7tFz}9DlD2umusuuR3ntv`4-
=CI@{+Isd1ko($12nUn9r?XBIr;)#pWLsBm3QwHs465nly7X1QdeWD*D`~H(uZTcC6U3Rtc**kuxHGPvw=d7oA7!+z19w`bn2ngo
O%dK=W2=3`YL9|=ve3%LwT@3XWFeuFb~#l>CIZbsGhm8@_UD^NC8Yg=J2%GmfSrI^^|D0=SzBc_e-WyLqtXgJW$--
A6V2Ogq#$jGY^F{EX7!5tOd5_=w_hysvW)z%=jg7%bv#<(wr<Zmb=wXc&hR|@q~Dg31>h5H<xYX1ea_E$x*lvJ5eq-uaSF=Q?<V1
GpJmo91D^7CHlry!GnsSW{@|ei(;uKU*;sOr1bRB1RH6#{`P@1YtjG8;(>lH)a}DGB4^FZ1ok;?+<2&O+{7kli|3_7t+9+cnS*~~
x2uyTq<)_LVKQ}0*mQ+y+M3gQll9FG>*oPoOc@<`nG_VHcnu)=7=}S*E<OtQDO11bI~7m?%<V|r1wqRAVi$&?-
`&MsbhQ+<93Vs)AcZwyg?1%0{{MTCDTW&VPY3@=s5&K{iAM0YL3Sgki5nT@Ly?#@RE8ff&-
sf$YFbI;X*b*3xo5$!GZx1`W?hC;;yu*iQrF_K^!Ds{A|RATIkbIfojt(qUczQ1wZ=7E$wGzm2!E^J2Y)B>EiahDQcihVokwm-ZR
kT|FclOgfhACqgd;}H?R<4XX-v;TfY%jD!Dt+@5(6yQNHj3eR*szNXdZ(Au}MR$Tb0@f`x^;sGX_$}-
vo+@fLTJmhg}^TMOkigVtQy7yCb@cwnsI?Mw)8wGASda8Qz?tVQORE(2f!vxl-QWhy^`Vao~JsXcLaQ_2I126yCXDx&7$^cO|mlw
|s`DR=x93Lm&<rUu8_Yv=DIJfSDYej`UKAcOZM}whjBI*AHM>4!>P5B?anFjD0sXKg=+CmvA%Z7EW1q<NET68b%;K2?*tg>xnzf{
|`T^GG*DvfUZ*3NzKD~j0BV1Q=mC(|BL8l)EWk)Hk6*>7nzL+SOu)@P)%XO+Y=NpwVJ=6ec{IPY+}RRuph{vFpEo^SCllV1+FlS+
l_inQJe0&RZHBZVpJzvDV@`+rs4pCi^N0ovB9p*a_GPd1n}t^u%D)sFF%ubiTJ_c8X^dM2-
hY3Vc2GVJS&r_1`9A=C({Jv^GV11Gy9cuKhT;+A;$RglM9H%W$%;N1CF*}=37GJ9AL>Z-
(I8i*$6KBwqUiNB>22v_`?4c9`lC}9_-
J>0xw%T2J_fh%pp@x{>`wX7ieQvQ8Yyay9IVfG#V46f~310QwPo|2`wkAbP>TW!)C*ycCwf9F$8%G)MA?9mhjOHyySo>>dhC+_J%
Z|c)7h-sTuJm&1FX8)+Bv*&=UypaF=;=DGOq5>%TD-
5b`d&>r{{ma)4x=6yEX=5ofSuil4*f1)NiPPG_I)kBxRxO^ye4tmfzRkQ(^{gQZR1n!qg7p823mxEhGRb0_gm7>MiG<wJL9tR^I#
4iCWQfUAXaWZm;#p_n+Dh5x1OYJJIKL~_s-GVtAR5IGI^S7!cxb=Fk$R_(-
|buN9R0;z2z@V>ol#CaYw4Smy$Gnai4PggdKqN4=miVD;Cm4#c9K(Bt{g8^#j6DMiYBW_;i$mjZwhR_rwi!IF1Tmad%0&J+1crR)
PC|=2(Lqvd5;wB~v33IO@x<Zte?@loBa^M`wERe6bTOy(GVvzC;<o;xNPo1GJaezEU9OULro{#nLg8N;8iFNYh`(+-
4d6VfY|5is7R2rSaAE5xWVSZu6<Q~yi(BH`;wou=mMl5AEt=_Kqy;dGR#{&L;u`l0R5RCkZBhhmM+XLf^%wC1ZL&~udWOQ-
H|ATqL%x|DjB(yW4)=o(QGPL@22_>iw>S$5&lIw;U&Lx-;&lXCe<<9)EJYA5$KNEG~#yH@dj4dSi-yU-
={*sCH!BM=ql~ytS<$R7G!BpSkaZRsxWb)NLnktL#1M@)^HcK*)ATgY#8rqjMX`_BB>?}(nz~29~LyXZtp}0<uW*-
bCvWPD7GR~KAbv6KP5fWT<0XGU-
M8R7vsi@)qw{s(B5!Z8*zlOh^fh(LOUr}pr`>WTOv}B!t8baC+6;Kosy6&JJMX!BQ+tPSSJB1)Tvtr(KcYBxxMf7idsGlg_ghv7X
D}FNRAItdiB5Rrv+fLz!&t~u>h4lD@JBjW6nbkiP^gLATl~9+|ao|5Z(_uHly=~uwED61Hwvdan8~SgiwBjm)$=y{ZiV-
<{0mWYQ7zSSB3C?-
S<obVMyxeKKbD_q#nx|DvhwdXjC>Bvwpvc#9Sb%S~Qro=rr`J#$NDDmy4NzF1CxZsar|O^(Kf$QS<NSp4Q^%Ix5=~2_w&$h7f5SV
K?MFiyUU7obbk0rFW%8ktc@DC&AFS&vLI5?w(X9=fDFlnJ0d=XwD)^P*N5eZVVOljTX@f@IT*gSaI~^?FtwhNkfMqeqkl&g%nVix
OhOdwz{J~}QQEbjBu_;o^rmxUJ!=1Zq`Cg#d9;bOg#d%WnL?v3H!~Oc!EE-To!Z$rlDi&70k2^GVGQJZ(m;Be2qw0u&TTvO041?L
I0&P)Ze$v2m&eiaRj<2zHnf7LtoCb%?6h|)d`^AXqTXB>FE=?VCBdhL32npheRHBu_G^m;S8X)a`w^*1|A{tL5`RwJR=kF~Cq}nq
1Rb&_4+1V1?MqVY<?t-
7XsfHo<rcd;>_2d@woHx+0H@?@rd2&N&9d8H5VVzWmILR(<4s%la4s=n@C|=8ROqygJoY>#TvUp0&xrvE;K>}Q>RAIeIqjy6-
nD<W|u%LW+=3ybu{McM}Hp=~VPf@f%pLoR!X$poMPj5d7tG=GLX4`z8+9@iodKa;TIILe#7e1@#)XroK=_u#YFQ+0cXG=MaOVJfo
*NtGa8Oa3j6f=2qi~2ZeJa)v`KyNFcydMW3YwjN?L?vh%=qWMP+UljpUv4<kUc~8blN!n2Lnz-If1}I5u_8ecK$RtIj-aU^G~WI{
ZUE~#q2Fl8@h1N5%ckgO+OcH|wj;C-
g}PxbQV+mo@{^sVzm~fdX6y4bUC0*Fiw+4+3px7D{kwXqctWWG_tIq|=9&wj&8<*}R_|_l3FFko>4QGtG?BG%ecLU{YyP|sj7+Tp
`ucIQ#j%OiLq#Urf3kU_<Se$6g7(O0q`W%*p%;h{eAV<ip6Q|g`Hsig_8CU|r&fWCCt~Jl<}jJ%ncLKK+m&(MQUboubl)$`k<3&S
3$2_B15l&IG&HsEM+*YF@=}bo%u6L{HH4Hbe!^}>;yWMr+%ZQh^Rrv9d670Zd1x@&G|YZ2P~jGPW3YkOz8t|fA^+}%@OcAh&{lFz
$l0199H5y*lw8HlQJuItX3^)a=8x-
}cVUgUUv8<+l#mTtIg%I^t4j?cGgTx#eq$lUD$7K0mT_CAn7?n~^iL3gM&@W8i{1=EZv>TAc+kTi*-
wE;+tgK+?Q=mNpRINgE~T(no#u%B|6Zp#Gh<nZx>#{&1+LOrf|6~d;-sqxT|lmbwARW~F-
Oyu<5+fS3C6!lqT6e)A8?(0@N@hqsm495m$Ft1h#w9=klkLw;x6yLDx-`{^7Qn~;c~7>UJa$4DnE50v5M%M>QOSo-
0JXW^g;XPde+TL<c9=9EcM_CHWKA72m$^lltu7?n92U8@?6pe<Ho=@q^n7|NOB-
2ax9AN4CZRK>8L)T+TI_sqjL95Xd=*8or9Y=^y!J%EXud+x9_8~)TaawR0BO*YfgH=GpuF?;j_Y#Vt{-
{=#~OWM{SoKuCC`W!ZB@HKd?IlX{gb#1<Lm{4{CzQdT%5}swM1nJDW*l)Y8cC-
xqepO~-~q`YXw4R^oxl>Zm#<cM26yXot7`nE0kAU;s}4pj=99l9Cov-CecHUibE+TYRzT#vf9j&@>0S9fcNFVjUF@3FRYtZTlBlW
)-KA6E&?!af9I=L5mz!6i2WP0ShEY-&Ho@VAqv)=3y6$ILzQ%cO-
b;KfJJN`yMQD(HKLhfHb9R^Ax#25<jCDCj~RiPRZjg^K;Qc4$&5bBuB~c<5T+Tnu)<hz(MY7xSRFRip~4;33x(=RqTJcQh{pbB%v
uccX56UqtJ*ZIVl|9$clX#TT!NV{B@H>B<Fjg1aPH1KZlMsi3^5=3!@K}T^bi=hL;IrmfinD^G|3LI#dl`9Png!W8{Z8C$kBoX|_
K9*oXjf11KXteNHFI%2H!Z^@wG$G0_&cATq=S+PTHgCwcy5<U_$tBQdwr7y*q3jbeeJ7x+oi(9;k78^X3D?HjC9C9iSX^tY>WGYW
{Cv2~w^P^S<{%w@MHZ<-JivR`-QNm;N43;jQOV-zsKmvv#=9IKgIwZa#vUWr}iSCmmt)YEZ=<5?U}x0(w{KXcfqh18`6%AnPAXLS
yia=<I<vV?sRe%&^5XNb?Rnd);^473)v5~=B;f`m&T8AOQ%aO&$;c%&-C9WVk#4o~Q9$D{c>AxZw+&ZiQFZCgDzJ-
p(P*r+DF@?UP#sS9}Nbv;xjc<?AS#GMGw^i0+QO1J^;yf1UAn)k3Rzg)8~<f3Q4$4R!H9JB559l<^f{^~Hik3CNArOp~*8C5b^9_
cJ7p<%U;*8f8zAZ$uwrAF)a*Tc?O0+2D7{0>F#`&*UVN)Be3A`xb^s__{_>RZVPHD!e8N05e{%Xb>q3(lyQHVN)Ln5aTuCVF271{
=+`O8Fx>bDW@Hsk=%;+*iI%NzUJ>tm*J<6m{XwuoNEGeyHzu@La$)bN+1ZW2b2hI|(RhZ0u?simC8l#YJc0iij@W7(aN$M=*$!%2
d%(DA(7B#b!m~%U8@GR;gyXv<}6*5nL98f|bLr0Svvwb4C+BtuqAmuSe>hOFjmpb7HDpvp^B~;wsQvDwQ!Rx(^dIStII?WGFSLum
LPccJ5hRnO~b8h9Um;W;X|A&K*uQhy;ag#HYNbpWQi#Fsl^tvDiUHB3DhiDA;YrZfJkGb1}Rby#%Do>>ft2`<t<vKSASAW+a$*40
-GH&Fnl{C~xB!sBzR61C_<u)&kOZ4B>OXu!|{bAz&>QsHGUUHgvcsLpw&jt+1JLonY`^zUjms_K$jNm(-
Ev0vy%0VJ&LPfp;`h(+)%CjqIZb$8Y|n0f5M3NET&`j|o35?kdeNp&EBX+Z~P_oaEjj5pnR^3Ajcw!XH*IL<`ScdynicO`Wt)yDG
K{akPDJY9~Ubjrv5Fg2FA(PISAlPBbjh*Q0)x$ENnY)14BX?9r534GIhY3jzGLH@wimqH!ELu|2meVL<|>X{3Uc{wM-
>%3+XD((*6PwiDhwP&$4{(CmS?9lZ+HnDo=S6dZ-
I!}JVqh`3S(^PwDruOMs3EE3aGjLM$IK$sNVwita$YcQ2#c;8K_E6%_%;j6fjo8b+>uIgQh|5BI3K79%Q+3PIQt1Pc{>_)XDiTg{
GfUXmYke<SptJ@j^fWGd;gYcgl@4`z6Do1>|*K?=%q=>sh1nqR;{Ml*3;>EIrhoS!BB0XYkt?~TOWHC$C_x^1Y_xE>yoJXo6_smd
ctw&H?XjjoC*$u~UXEhLLJ7A4@bstE^ZPLdx0|#F^aJZRPi?a}E06kSCqEf0q%yB=7$tfwL;+^QO(97#AKdb#S@u~YTh@_X!8)cd
`&PdHQ54Ww=IRRzTwT-zvu2!>-%VBsx0+z8VJyK$Oq~|lyW7W1v@l4@d*dG9@Q|lkvD~G@7e7Nhy>Xf+@@+4fZ>{-
%<4MG0U?5dO?N5}6!UG1x%95<iC=)v3^SmIgdPJr;<v^TOuTk(Ot5ExHzW}2H-oooj*%Azyrz$CjXtd`(o-
+2nyfwQDoO0EF6{kIcoh+)B$-
@letK=Fy|v;7F>=T4r?sPzJf+L)M#l1>DQKPC2|3+ASWbcx}w9c8PI5f~e4?7kdWejUknZ>2{xKJBC4zlpNYLB>SwH;m-
W!IE3WTsf}Z*nC(p^>c(Lc#xwv5)=!x`dywK2RpzGsVVH9v|^OFl!e?D9-
nDqN#kqoies3$Yty4H{ozrn7ykHq!!=zXMbE86i?gJ~5fzkur<hJz%h0iiu_@diyW@!O<|n#z1WJYgi_A1qXq^BtQrUXzPw|k1ZT
LZN+|wscdL|oQcz*93*V~s*F$CUY#ISt$p8G8qT@dSQsMt>!3-
__*bLK*%^r|%nJ^#q#+!<nM5)Po_DX1JWw|exe)$L)1p`yuch5pF_-5h0cafW;N4p+7DKol@>^S2@!jY2K-
Uno)axJ8Yfg7u2)XE%!wWi_%Hx!&Caz{s6`HXmUq*19FZt3`P4m)FvWiOo3<zB?-
<5JwhT*~vgl&8Qn^e%%(9eg}Olp4HKocm8AB8-11xnwQU-
2cw_ze<V1j0)KI=RYmkOSwF*givsdS_RSyD%9svhSdj4grRrYS<%nGL?G9ScQ@duyvsx42lbwb_AvWQl=&2a?ag!)GcCc99x6ff^
mJ3e<6U>_&BJIYC8ELkT5X6=z_4g+awqk?@fUe{9>*P@pjOW*=;R)@kFzvnXsg6?=%$_Qx<{pZN=FnpL;GKs&9t%b=9(0~Ti*5`9
+qtBq0ev~lUrBwl4p!&c7Lp#JGz)*M0OPztLW4d-#!g|Jm&eaTF0$0HlECyMf)DgNNT>dS^_K0s|FYV3-
MGSIv7JGRysJ9m3~vG8*-fkv#tT7zBDy~H-
jaZe;^ZPz@takMD%rYv%5JiT@y<)a^T6)Xf{>lxaj#poIN5}Dl$v(^+MBk89w*Vdnn~4BW}|3GQ#Q`_f5LqaN1S_p;2jUe3Qxphm
gl3b1Us8dml73>wU+YA<o~g2>0X_y5C=bq35-pF1Nj05{X%f_-ErNZ2&8v)49jqMhV^5#;x&OAqvid^VX=ZW+QpDw@?f$T(<V+~W
?qi=&r^f=7Adwxxl3af^xa;0Q~Fiz8?)6HdGGsIuP33O=iXplaENu6UVWJEzyexv%7L}vk>dQ!UP4GKik~#o(oZS~gB8bq#Z~A0(
G`>X&HR4fL{zyoSRM^H0E=Bx=*m{LTc*NRmd<Lg50L9d51av62{SuOUiuy+1~BCP#@hJlFD$Pizd<a3JbjYQ=%sfmUg~1CB)_}ml
L~K~F%L^oz^c4yPT+lkw)Ye!j8nY6AU2R16jJ=E)URUQOkpm`Mp4Y0mq)oAj8MY7Am5<4bv;RvpJ-gTo`JI4@SzmC4gqWxJM?;<X
mg&xWQJhrCfeyTA}Wd^rk2MCUpi8+0}`*=(@i$#SdrX4bI)|V=scjJXnU>kZchLE6;u^q2G)x2UcuG1v0AVTJ<~o5R*_&(JOI**3
=^g*aYNMa`Omc4k}oMw@YD8qD;q|h#o)4g+I&|_kGt-JrY}l5V1g`#{t@+Lhy>-
8uHk~KreGCt_mLaZB{?kbdd!^;<vY(zW1;OcT*i0|(-
rPXU*@>K?^aI*;cdc_Q|?Db7PYa^;3yZ*tJgNF?OE}JMR^2qNV+7?H=o*10E3?#X{Fg9HGg7q4w~YTKvNulakos>d)+UAr0OE0{B
!<Y1a*2%(QWnH-
`n%DO&i7M0H>rSHKH=6>tO_xr#8_}aGW;azgpOkeb$y173AKyeJZ}#zA@h55!8*R;M|@;`;9SYa}Y=d6&r>r3tRKuE?otyBo7{b*
yD>@WyuveHUK;dn;Qk9?FCGs#1cI!>Q-0(^l;$>N+}cqA55SW_Q_>8l6-BFPb9x8x5gU%N6=jbwZj>7g*S;_9TDUHI#?-
as<=W+MByAz5*Q@~W*I#lvWTMPDy@KG3ci~?4Z#=ezZN7Bq1xtE<ikk+1Bn-dS=?lmVQAJe?;RWvh}J%RUiBmuhY{=qB9PIQ8hG-
5shvb3vr9n#?4wS3<8a+^d%$VcQ+@?Shr8I}013XJF=&$ta`7<~IteNE^Ga>0w*Bblb(wTv@Fu|V*(Nn*d4>7g-
JstC5VbbWvd1`!=qwYjE#Pfju0y77`CZ&qY>dPN5^$jEMKg+77n~pu<M(s>%AHL=Mc92l{p!l;epmIl{r{DfIJ_$auz*ulrN|+tv
wXCT5oH_K0+GwrM(h6{;%%4KS)4+|2g~*_;w2kN>u85>jKFxp#Vk+6ox7nZy6ppcCqJBH4N5l5&okYhKv|PGu1WxT3Ei+*O}h#6v
6hfq2>USBKlecIZ6fVt`StV*cqHEc0N|D@LQ7kU@XN$NWC~o|iP|jAX}2#Upx9*EOZz?JsTTXGUsR}KI()>OOa{Uy4AAC!_|)m=<
M6MwTFsMPwz6RD<|LND#EPgM$S%3~QRKw+Ea(fW6|b+q?m8C}LiTK%lX^{6xCgK`{?Fr{kKb&Zw?ue___xAJ%ew<)jC^@2ZGU!(q
%OH>J4M;CCmMolRqrf?3d2KZG2i*8o!Q1Zn<IMSfiuj3m-^=K9&l^-
*Drw1>lhz+5=Wv7@)=s9##LQW&54p<yExN$vd=zJ7ih(_c}$sD@@zg&_Lx%>vpt+WN!(0v@K_`7I5|t%73@RerY(v&buj2_LE&6H
(c1SZp!H^Ic1~MP*k^&IDnkI@gbO2%LN*oTm3`q-
{wG`>=UAkr1IS)yv|9kEQ1qIpQNPNhMZT!5pW<~wPo{v&T&*0?*|S6|#5k~EVrLxzvGwR3)P%cUsWvykwRJ`*TS_}xjrxH}3hVAO
M1OldM0q@s3vIGpZo|@YmN>s8OIzRH8)CD#QNeZ`B4Qt#<D-}eg<-
J31{IZ8f;$mUE^+Hdxz!3tqP&!wkQa!uz<Z?NoYtRbzf_tWe7@F9FudwNrpnbqy6kfSZk(|$u0nvL(}Z3`qnDq)pD~;f$&^YV%Sc
D6)VEvhha3`D37kacat6O{%QB#tl|J>-
6hRTf)?J}^WQqDBO=CVs$Up>nw<n63*97!|CGCrOp_{fHbXYk)jr?Nxg9PEcLrd8rQ3gM8cSJ&mZJ@6%VBu5$<YWX-3C`#-
5`?rLq=B;cig0vrN>y<HD6Lgf!clR^j+>h1wL};uTshaBXRkLmeaiX`?mbZY;6Og`*N6pkKJ?dOVa%k0I^Gnu(+g_NPIv<0a29Xb
n{<#R-
te2^x=89vb!Q}x*OPne6u`PnKm{zEY2UiwjgJ%<e3K{L`AY+Bf!|uwa5z`r@&|yah+|YE7%iK@eX(t9Zn!`FlpwioG>1N&{2<J!q
<s&eFYZ{JhF76t(ryvmEurEVtS+to(%#6l<qjMv^uIMQ`YWi9ct;uM)Y|xb3a2%Ith>L~y}PG(=t$7zY9K%6h%ZO}AKfxku3SB(z
ExV~0NkCo_*=Eod5culape<RUafYCP1>fRheh8lLtreZpk>iD@DP(8B#5rutCb!3Cs4+aU}F0!Jl;sIkPH7rt))=A4FyY6F3fCf?
bridImxG_tRdD+0E5AYI_db*f6=rCi#mGzV-^CgW|&d$bUnCEB-htbP|!XUIYYhcM3#X)!ko{;YDAxCwj4IWC@R;EEp||?aeN~&(
NdvEK?|)5zrl;P9B3q|D0mWS)F_3h5IsIR(rWx{ujXX~n2RtF_xkapRhTcmmsDkI_1CVzK*@BoM!90R{UdHon8i}TBO+rY0bQ%6g
Nr9vOr{d(`4rU>zyZAFkHPZPnH*uwJ%O8VSXIqR(^%ZnbXIjRpM`$sw7~RHp(&kzOM`eTfQWg~qN7p=WP=uv_}NI3`fm2zsICwN%
(d0h%hCtgO?gDgzLQx%?{hi6$eye%%NZJ#IfKiTA?gNTuw2pDKu4!zz&o&`n)Txa?0igPH5U$!9{>
'''

MAGIC = b"RSB1"
VERSION = 5
WIRE_PROFILE = "rsb1-v5-public-kernel-1"
CONFORMANCE_PROFILE = "oxbow-conformance-v1"
MANIFEST_PATH = "manifests/MANIFEST.generated.json"
MANIFEST_FORMAT = "oxbow-manifest-v1"
PUBLIC_SECTION = "files"
REQUIRED_ROOT_DOCS = ("READ_FIRST.md", "BUNDLE_LAYOUT.md")
TOUR_ROOT_DOCS = ("START_HERE.md",)

MAX_BUNDLE_BYTES = 256 * 1024 * 1024
MAX_FILES = 10000
MAX_TOTAL_RAW_BYTES = 512 * 1024 * 1024
MAX_FILE_BYTES = 128 * 1024 * 1024
MAX_PATH_BYTES = 4096
MAX_SECTION_NAME_BYTES = 64


class BundleError(ValueError):
    pass


def _rv(data, off, max_value=(1 << 63) - 1):
    n = 0
    shift = 0
    for _ in range(10):
        if off >= len(data):
            raise BundleError("truncated varint")
        b = data[off]
        off += 1
        n |= (b & 127) << shift
        if n > max_value:
            raise BundleError("varint exceeds allowed range")
        if not (b & 128):
            return n, off
        shift += 7
    raise BundleError("varint is too long")


def _take(data, pos, n, what):
    if n < 0 or pos < 0 or pos + n > len(data):
        raise BundleError("truncated %s" % what)
    return data[pos:pos + n], pos + n


def _lzd6_bounded(data, max_output, what):
    dec = lzma.LZMADecompressor(
        format=lzma.FORMAT_RAW,
        filters=[{"id": lzma.FILTER_LZMA2, "preset": 6}],
    )
    out = bytearray()
    feed = data
    try:
        while True:
            remaining = max_output + 1 - len(out)
            if remaining <= 0:
                raise BundleError("%s exceeds decompression limit" % what)
            chunk = dec.decompress(feed, max_length=remaining)
            out.extend(chunk)
            feed = b""
            if len(out) > max_output:
                raise BundleError("%s exceeds decompression limit" % what)
            if dec.eof:
                if dec.unused_data:
                    raise BundleError("%s has trailing compressed data" % what)
                break
            if dec.needs_input:
                raise BundleError("truncated %s compressed stream" % what)
    except lzma.LZMAError as exc:
        raise BundleError("invalid %s compressed stream: %s" % (what, exc))
    return bytes(out)


def _validate_path(path):
    if not isinstance(path, str) or not path:
        raise BundleError("empty or non-text bundle path")
    if "\x00" in path or "\\" in path:
        raise BundleError("unsafe bundle path: %s" % path)
    try:
        pb = path.encode("utf-8", errors="strict")
    except UnicodeEncodeError:
        raise BundleError("bundle path is not valid UTF-8")
    if len(pb) > MAX_PATH_BYTES:
        raise BundleError("bundle path exceeds limit")
    if path.startswith("/") or re.match(r"^[A-Za-z]:", path) or ":" in path:
        raise BundleError("absolute, drive, or colon path is not portable: %s" % path)
    parts = path.split("/")
    if any(part in ("", ".", "..") for part in parts):
        raise BundleError("non-canonical bundle path: %s" % path)
    pp = PurePosixPath(path)
    if pp.is_absolute() or str(pp) != path:
        raise BundleError("non-canonical bundle path: %s" % path)
    return path


def _payload():
    encoded = "".join(_PAYLOAD_B85.split()).encode("ascii")
    if len(encoded) > int(MAX_BUNDLE_BYTES * 1.4) + 1024:
        raise BundleError("embedded base85 payload exceeds input limit")
    try:
        data = base64.b85decode(encoded)
    except Exception as exc:
        raise BundleError("invalid embedded base85 payload: %s" % exc)
    if len(data) > MAX_BUNDLE_BYTES:
        raise BundleError("embedded payload exceeds bundle-byte limit")
    got = hashlib.sha256(data).hexdigest()
    if got != _PAYLOAD_SHA256:
        raise BundleError("embedded payload sha256 does not match wrapper header")
    return data


def _decode_offsets(raw, count):
    pos = 0
    arr = []
    cumulative = 0
    for _ in range(count + 1):
        delta, pos = _rv(raw, pos, MAX_TOTAL_RAW_BYTES)
        cumulative += delta
        if cumulative > MAX_TOTAL_RAW_BYTES:
            raise BundleError("offset table exceeds raw-byte limit")
        arr.append(cumulative)
    if pos != len(raw) or not arr or arr[0] != 0:
        raise BundleError("invalid offset table")
    for a, b in zip(arr, arr[1:]):
        if b < a or b - a > MAX_FILE_BYTES:
            raise BundleError("invalid or over-limit file offset")
    return arr


def _decode_paths(raw, count):
    pos = 0
    rows = []
    seen = set()
    for _ in range(count):
        if pos >= len(raw):
            raise BundleError("truncated path table")
        pool = raw[pos]
        pos += 1
        if pool != 1:
            raise BundleError("public wrapper permits only local binary pool")
        ln, pos = _rv(raw, pos, MAX_PATH_BYTES)
        pb, pos = _take(raw, pos, ln, "path")
        try:
            path = pb.decode("utf-8", errors="strict")
        except UnicodeDecodeError:
            raise BundleError("bundle path is not valid UTF-8")
        _validate_path(path)
        if path in seen:
            raise BundleError("duplicate bundle path: %s" % path)
        seen.add(path)
        idx, pos = _rv(raw, pos, max(0, MAX_FILES - 1))
        rows.append((path, idx))
    if pos != len(raw):
        raise BundleError("path table has trailing bytes")
    return rows


def _parse(data):
    if len(data) > MAX_BUNDLE_BYTES:
        raise BundleError("payload exceeds bundle-byte limit")
    if len(data) < 5 or data[:4] != MAGIC or data[4] != VERSION:
        raise BundleError("not an RSB1 v5 payload")
    pos = 5
    for i in range(3):
        n, pos = _rv(data, pos, MAX_FILES)
        olen, pos = _rv(data, pos, MAX_BUNDLE_BYTES)
        _, pos = _take(data, pos, olen, "global offset stream")
        clen, pos = _rv(data, pos, MAX_BUNDLE_BYTES)
        _, pos = _take(data, pos, clen, "global codec stream")
        if n != 0 or olen != 0 or clen != 0:
            raise BundleError("unsupported legacy/global pool %d" % i)

    nsec, pos = _rv(data, pos, 2)
    if nsec != 1:
        raise BundleError("public wrapper requires exactly one section")
    name_len, pos = _rv(data, pos, MAX_SECTION_NAME_BYTES)
    name_b, pos = _take(data, pos, name_len, "section name")
    try:
        name = name_b.decode("utf-8", errors="strict")
    except UnicodeDecodeError:
        raise BundleError("section name is not valid UTF-8")
    if name != PUBLIC_SECTION:
        raise BundleError("unsupported section %r" % name)

    nt, pos = _rv(data, pos, MAX_FILES)
    nb, pos = _rv(data, pos, MAX_FILES)
    ng, pos = _rv(data, pos, MAX_FILES)
    np_, pos = _rv(data, pos, MAX_FILES)
    if nt != 0 or ng != 0 or nb != np_:
        raise BundleError("public wrapper permits one binary record per path only")

    plen, pos = _rv(data, pos, MAX_BUNDLE_BYTES)
    pcode, pos = _take(data, pos, plen, "path table codec")
    max_path_table = min(MAX_TOTAL_RAW_BYTES, max(1, np_) * (MAX_PATH_BYTES + 32))
    praw = _lzd6_bounded(pcode, max_path_table, "path table")
    rows = _decode_paths(praw, np_)

    if nb:
        olen, pos = _rv(data, pos, MAX_BUNDLE_BYTES)
        ocode, pos = _take(data, pos, olen, "offset table codec")
        oraw = _lzd6_bounded(ocode, min(MAX_TOTAL_RAW_BYTES, (nb + 1) * 10), "offset table")
        offsets = _decode_offsets(oraw, nb)
        clen, pos = _rv(data, pos, MAX_BUNDLE_BYTES)
        ccode, pos = _take(data, pos, clen, "file data codec")
        concat = _lzd6_bounded(ccode, MAX_TOTAL_RAW_BYTES, "file data")
    else:
        offsets = [0]
        concat = b""

    if pos != len(data):
        raise BundleError("payload has trailing bytes")
    if offsets[-1] != len(concat):
        raise BundleError("offset table does not reconcile with decoded bytes")
    indexes = [idx for _, idx in rows]
    if sorted(indexes) != list(range(nb)):
        raise BundleError("binary indexes are not an exact 0..N-1 permutation")

    files = []
    for path, idx in rows:
        files.append((path, concat[offsets[idx]:offsets[idx + 1]]))
    return files


def _manifest_records(doc):
    errors = []
    out = []
    if not isinstance(doc, dict):
        return out, ["manifest root is not an object"]
    records = doc.get("files")
    seen = set()
    if not isinstance(records, list):
        return out, ["manifest files is not a list"]
    for i, rec in enumerate(records):
        if not isinstance(rec, dict):
            errors.append("manifest record %d is not an object" % i)
            continue
        path = rec.get("path")
        size = rec.get("bytes")
        sha = rec.get("sha256")
        if not isinstance(path, str) or not isinstance(sha, str):
            errors.append("manifest record %d lacks path/sha256" % i)
            continue
        if not re.fullmatch(r"[0-9a-fA-F]{64}", sha):
            errors.append("manifest record %d has invalid sha256" % i)
            continue
        if size is not None and (not isinstance(size, int) or size < 0):
            errors.append("manifest record %d has invalid bytes" % i)
            continue
        if path in seen:
            errors.append("duplicate manifest path: %s" % path)
            continue
        seen.add(path)
        out.append((path, size, sha.lower()))
    return out, errors


def _verify_integrity(files):
    mapping = dict(files)
    if MANIFEST_PATH not in mapping:
        return {"ok": False, "error": "manifest missing", "checked": 0}
    try:
        doc = json.loads(mapping[MANIFEST_PATH].decode("utf-8"))
    except Exception as exc:
        return {"ok": False, "error": "manifest unreadable: %s" % exc, "checked": 0}
    records, errors = _manifest_records(doc)
    if doc.get("format") != MANIFEST_FORMAT:
        errors.append("manifest format must be %s" % MANIFEST_FORMAT)
    expected = {}
    for path, size, sha in records:
        try:
            _validate_path(path)
        except BundleError as exc:
            errors.append("unsafe manifest path %s: %s" % (path, exc))
            continue
        if path == MANIFEST_PATH:
            errors.append("manifest must not list itself")
            continue
        expected[path] = (size, sha)
    actual = dict((p, b) for p, b in files if p != MANIFEST_PATH)
    missing = sorted(set(expected) - set(actual))
    unexpected = sorted(set(actual) - set(expected))
    mismatched = []
    checked = 0
    for path in sorted(set(expected) & set(actual)):
        size, sha = expected[path]
        blob = actual[path]
        bad = []
        if size is not None and len(blob) != size:
            bad.append("bytes")
        if hashlib.sha256(blob).hexdigest() != sha:
            bad.append("sha256")
        if bad:
            mismatched.append({"path": path, "fields": bad})
        checked += 1
    ok = not errors and not missing and not unexpected and not mismatched
    return {
        "ok": ok,
        "checked": checked,
        "expected": len(expected),
        "actual": len(actual),
        "missing": missing,
        "unexpected": unexpected,
        "mismatched": mismatched,
        "manifest_errors": errors,
    }


def _tour_tracks(mapping):
    tracks = {}
    for path in mapping:
        if path.startswith("tours/") and path.endswith(".md") and "/" not in path[len("tours/"):]:
            tracks[path[len("tours/"):-3].lower()] = path
        elif "/" not in path and path.startswith("TOUR") and path.endswith(".md"):
            name = path[:-3].replace("TOUR", "").strip("_- ").lower() or "default"
            tracks[name] = path
    if "default" not in tracks:
        for path in ("START_HERE.md", "READ_FIRST.md", "BUNDLE_LAYOUT.md"):
            if path in mapping:
                tracks["default"] = path
                break
    return tracks


def _verify_conformance(files):
    paths = set(p for p, _ in files)
    missing = [p for p in REQUIRED_ROOT_DOCS if p not in paths]
    tours = _tour_tracks(dict(files))
    if not tours:
        missing.append("START_HERE.md or a tour surface")
    return {
        "ok": not missing,
        "profile": CONFORMANCE_PROFILE,
        "required_root_docs": list(REQUIRED_ROOT_DOCS),
        "tour_surfaces": sorted(tours.values()),
        "missing": missing,
    }


def _verify():
    data = _payload()
    wrapper = {
        "ok": hashlib.sha256(data).hexdigest() == _PAYLOAD_SHA256,
        "payload_sha256": hashlib.sha256(data).hexdigest(),
        "note": "internal consistency only; this does not authenticate an author",
    }
    try:
        files = _parse(data)
    except BundleError as exc:
        return {
            "ok": False,
            "wrapper": wrapper,
            "wire": {"ok": False, "profile": WIRE_PROFILE, "error": str(exc)},
            "integrity": {"ok": False, "why": "wire parse failed"},
            "conformance": {"ok": False, "why": "wire parse failed"},
        }
    raw = sum(len(b) for _, b in files)
    wire = {
        "ok": True,
        "magic": "RSB1",
        "version": VERSION,
        "profile": WIRE_PROFILE,
        "payload_bytes": len(data),
        "files": len(files),
        "raw_bytes": raw,
    }
    integrity = _verify_integrity(files)
    conformance = _verify_conformance(files)
    meta_ok = len(files) == _FILES and raw == _RAW_BYTES and len(data) == _PACKED_BYTES
    wrapper["metadata_matches_payload"] = meta_ok
    wrapper["ok"] = bool(wrapper["ok"] and meta_ok)
    return {
        "ok": bool(wrapper["ok"] and wire["ok"] and integrity["ok"] and conformance["ok"]),
        "wrapper": wrapper,
        "wire": wire,
        "integrity": integrity,
        "conformance": conformance,
    }


def _prepare_dest(dest):
    dest = Path(dest)
    if dest.exists():
        if dest.is_symlink():
            raise BundleError("extraction destination may not be a symlink")
        if not dest.is_dir():
            raise BundleError("extraction destination exists and is not a directory")
        try:
            next(dest.iterdir())
        except StopIteration:
            pass
        else:
            raise BundleError("extraction destination must be new or empty")
    else:
        dest.mkdir(parents=True)
    return dest.resolve()


def _extract(files, dest):
    root = _prepare_dest(dest)
    count = 0
    total = 0
    for path, blob in files:
        _validate_path(path)
        target = root.joinpath(*PurePosixPath(path).parts)
        target.parent.mkdir(parents=True, exist_ok=True)
        parent = target.parent.resolve()
        if root != parent and root not in parent.parents:
            raise BundleError("extraction path escaped destination: %s" % path)
        if target.exists() or target.is_symlink():
            raise BundleError("refusing to overwrite extraction path: %s" % path)
        target.write_bytes(blob)
        count += 1
        total += len(blob)
    return count, total


def _info(files, data):
    mapping = dict(files)
    tracks = _tour_tracks(mapping)
    return {
        "name": _BUNDLE_NAME,
        "wrapper": "oxbow-self-extracting-v1",
        "magic": "RSB1",
        "version": VERSION,
        "wire_profile": WIRE_PROFILE,
        "payload_bytes": len(data),
        "files": len(files),
        "raw_bytes": sum(len(b) for _, b in files),
        "doors": [p for p in ("READ_FIRST.md", "START_HERE.md", "BUNDLE_LAYOUT.md") if p in mapping],
        "tour_tracks": sorted(tracks),
        "payload_sha256": hashlib.sha256(data).hexdigest(),
    }


def _orientation(files, data):
    info = _info(files, data)
    print("%s  (Oxbow bundle, self-extracting)" % info["name"])
    print("  %s files, %s bytes raw, %s packed" % (
        format(info["files"], ","), format(info["raw_bytes"], ","), format(info["payload_bytes"], ",")))
    print("  doors: %s" % (", ".join(info["doors"]) or "none"))
    print("  tours: %s" % (", ".join(info["tour_tracks"]) or "none"))
    print()
    print("  --read-first        print the front door")
    print("  --tour [TRACK]      print a guided tour/start surface")
    print("  --verify            verify wrapper, wire, manifest, and handoff conformance")
    print("  --list / --ls       list bundled paths")
    print("  --doc / --cat PATH  print one document as text")
    print("  --extract DIR       unpack everything into a new/empty directory")
    print("  --payload-out PATH  write the inert .oxb data twin")
    print("  --info              machine-readable summary")
    print()
    print("Security note: this file is executable Python. For an untrusted wrapper,")
    print("inspect it with a trusted Oxbow CLI instead of executing it.")


def main(argv=None):
    ap = argparse.ArgumentParser(description="Oxbow self-extracting handoff bundle")
    ap.add_argument("--info", action="store_true")
    ap.add_argument("--verify", action="store_true")
    ap.add_argument("--extract", metavar="DIR")
    ap.add_argument("--read-first", action="store_true")
    ap.add_argument("--doc", metavar="PATH")
    ap.add_argument("--cat", metavar="PATH")
    ap.add_argument("--list", action="store_true")
    ap.add_argument("--ls", action="store_true")
    ap.add_argument("--tour", nargs="?", const="default", metavar="TRACK")
    ap.add_argument("--payload-out", metavar="PATH")
    a = ap.parse_args(argv)
    try:
        data = _payload()
        if a.verify:
            result = _verify()
            print(json.dumps(result, indent=2, sort_keys=True))
            return 0 if result.get("ok") else 1
        files = _parse(data)
        mapping = dict(files)
        if a.info:
            print(json.dumps(_info(files, data), indent=2, sort_keys=True))
            return 0
        if a.list or a.ls:
            for path in sorted(mapping):
                print(path)
            return 0
        if a.read_first:
            path = "READ_FIRST.md"
            if path not in mapping:
                print("READ_FIRST.md not found in bundle", file=sys.stderr)
                return 1
            sys.stdout.write(mapping[path].decode("utf-8", errors="replace"))
            return 0
        doc_path = a.doc or a.cat
        if doc_path:
            _validate_path(doc_path)
            if doc_path not in mapping:
                print("%s not found in bundle" % doc_path, file=sys.stderr)
                return 1
            sys.stdout.write(mapping[doc_path].decode("utf-8", errors="replace"))
            return 0
        if a.tour is not None:
            tracks = _tour_tracks(mapping)
            if not tracks:
                print("This bundle ships no tour/start surface.", file=sys.stderr)
                return 1
            track = (a.tour or "default").lower()
            if track not in tracks:
                print("no track '%s'. tracks: %s" % (track, ", ".join(sorted(tracks))), file=sys.stderr)
                return 1
            sys.stdout.write(mapping[tracks[track]].decode("utf-8", errors="replace"))
            return 0
        if a.extract:
            integrity = _verify_integrity(files)
            if not integrity["ok"]:
                print(json.dumps({"ok": False, "integrity": integrity}, indent=2, sort_keys=True), file=sys.stderr)
                return 1
            count, total = _extract(files, a.extract)
            print("extracted %d files, %d bytes -> %s" % (count, total, a.extract))
            return 0
        if a.payload_out:
            p = Path(a.payload_out)
            if p.exists():
                raise BundleError("payload output already exists: %s" % p)
            p.write_bytes(data)
            print("wrote inert payload -> %s" % p)
            return 0
        _orientation(files, data)
        return 0
    except (BundleError, OSError) as exc:
        print("error: %s" % exc, file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
