#!/usr/bin/env python3
# Generated by Oxbow. This is executable Python containing an inert Oxbow payload.
# For untrusted wrappers, prefer a trusted `oxbow bundle verify FILE.oxb.py`
# rather than executing the wrapper directly.
"""Standalone runtime embedded in generated .oxb.py handoff files.

This module intentionally depends only on the Python standard library. The
payload is data; this runtime provides bounded parsing, integrity verification,
orientation, document access, tours, and safe extraction for the locked public
Oxbow wire profile.
"""
from __future__ import print_function

import argparse
import base64
import hashlib
import json
import lzma
import os
import re
import sys
from pathlib import Path, PurePosixPath

_BUNDLE_NAME = 'oxbow-tiny'
_FILES = 26
_RAW_BYTES = 57889
_PACKED_BYTES = 17356
_PAYLOAD_SHA256 = '23dd91eda9df7cc5ad5704b30e0c1e5a4d8bdf6bbee330ab2346eb748bdf3e6a'
_PAYLOAD_B85 = '''
Qd2@P1poj50000000036W@&6?a{w9u8m$B117ZQCT>t=tjp%3#&?<Y_*@`hDl?%IW<3gY#jd`B$Ua4t()R837<ocyDrD^9PQuV&*
5ZrUwLPu7D#ga_g6mf@O2IZmvu&m9L_-e5BE<Fa&s*kTqxD6Vik#@I9$4fymWJze0#D;~8r|pLs5VZLrbS8SR-aE?mc)wAL)(AL<
mzAvj?HXPcvwI%qUS`lC!)Uv(BltSj4d-`iJhX-
a?wo+`oas|iarNTD#@CV3;vPO&(PdT8a{IxZ^OVPHdHAMx@Xr%t4aGS2u;sR~#Kv#~b}Srm)tdW*^wC+Y))8|Grged_E(KaNJ9S0
khNA!Of5hL~VV^$i-qm7_o$z8Ho-w+9eZDm}Zq7-
kbMe#O=7YhAX8hNhy{)NNtnp;jUn~<;CtE!N%aXA9tYuAlE#A5~o15dLknW~fo5-B^ZQAle^jB=OYNu<%v6$LVd@PV1!~m$i9E-
l{m#c4N?|V#IBp1Y^tL5i@nDy*bw||~<t%6<67o2Wucyz}1jp%}hz%WkfQ$@r<Nu(jokWtfD;@zjStXc%7qmxmvsFk1qH~|1N0NM
zK7P<(ULB9p?72yTr3-}c3BCH1Z35W-
#1bL1EhXVHj#R8E5>I3Ks#}fJ=$61jz0LX&@;Nl=bz+C_lhz7^P2>7T^P!U&96sBRAdODoO9zbYK%nLtu=if1C?K0(;Nhtz2BPqP
8PKD|p$BQ;t@xz=u#u!vV=N;@O-q7X48!+UKzAwHRfBZ$0GXb={^k(PUt?ezZM{C!FI-
4{BG#ygxr#4q!)387`TZ<JgYg3rX5AS8Q=}Ya}U=d==!buAMOa=2a=IK9h#L%m#6^WRauE<+&9Dy5;$^}P6S>e8xM^vs#DBn2uYU
#Zp2zj2jB67)9bi+6Bb*0RT95e!JE-5*rb@Z`V1Mn&vS|SG}yey!-#!M@>?-
&NyH@{&VPmXBEA&LDp53xkbPF_3J<e?8U1&}FByp2HhR6GsPM9Uo6^xGIycuIPQIXdf%3}wb@+E_c8WluE>oQSn0JuG|{hS~qDQn
)EWMTjVf#Cr1SZ4>ym)xbcQOIG>fIwOb!%o}{O@gASM_1`a^D1$67fSl{q=`_oZ23wXK8~K*$|G!cX@`HuF>Tn#;<Lnk+zqw$Lc(
-hbLmj%Z))urE=&UO2nw?L%=x@rNH*|&VMgHueRGYZ@Uh<5f9;yh>B0g?w<iJ`!Sn^mJoG!G?eICeC4s5sf^Lj@!SLRKLiklZ59K
W|LbooMQ&i@ZOnGWJG553>%a4T7h@v&olytKf2ar5w=LX*I~dT1r+)uQWRJ11Z8jhx&GcwmR;Tyr(!7*y#k*S%z5LyurGTMXbUga
Uqw(y4MFu+#Vk60eB{kG%<i4{B!Q8>=asHpP{!f+N5m_a~wd&ZO8IsRjisJapoj>0JLtn?z3$vs(mISJ|8$AkN^0y4IPH!Z9U1ec
A9p|FUMg*1V}Kw~;`Uy8f7@usde!BF^1`R4VOfW?Bnxv@8Oj7Du}fqyJ;Zc=}-+!=FMjm?UBWh`M(}ph>Z2q-
>#<>gGWwZOwPmOZJ?0{~b9uf6A)=d*t|UEF}-Q#_9^{5&PlO;S{M;aPSH?FNz_~Vx#Q!3I_EuKcF1b;e=A7B=c25R-
DLJz0O64by2s0)I{j=(fh+~;y)v(iHN-lgZ5>O4}E*~c%t(6S8R%+2%nj=@b(5ntb#>&BC<v!-
{e)4g!F&N{}=<+<`qMzgcbpKcemS~tg;{oiPR{`fV!D?4Cwz|$OdoyQ$qPXB*uz)9)sK#udibYOO^5~#TW<5)p<uTWs_h>LjTPfD
5xMp&9@u>OuatsZXf}oYr#Qum6o11T|RbIMf53zIE<K^NKQVDCQzL%dd$=h%+ee^nbD(kqv<E$(k)te)Y9dG?%ipck%tuy%np`P4
9i&O>4Pxm9*c=^#*2Ey<0hTUHuiq;`*5D{99E{apgbpAW3L*f0JpVc{aSVGwt(CV{g}+xP@g@4R<O8B^iwZP(8VWp_0w==-
7zlNgrL2lfD;wHxBcXgoPt}fF%mzgtq-
E&umM^YJ~zfVG{hn|H&B)1ccMoMeN745_(7&<L3ENT#6_~S;4yS?lSiBCrV&W7rCa0lt7s~qHq+eJm>^D-
f7WS#qJL*(M`JFcISWE~cUqKRG*>4)ja(|KQVTbQc@$`x$9*hfH&(do(okR*FxRtp(PKKJSM<;O!6KS+GRfl17nEW?Wp?d}T_WzG
t4_k0+^V<>s*y~-PH7NSPaN)QD>ZinXaVN9pcM~pkY$|)S=~JkT77mBhq=&-
;Tm8=e0ZAB&H$!b1B1^7M<3Mk*pxTI3lgzqUkp@^UEEGn9?5s%E}Wb|#i76#A#e1(Y>p+`*my5Fl}h}jZ}m&d>TO7U%&74&;mh@X
N!oQTZiJ#Xg$otyN-
6(#y~LB?Vm6kupa$O9wlqXhN3luP*=Q4h#5ywGG*^5UeV=@;t_`4;Cdm=wQD0;9GBnrHz~@{e>e8MECG{|MEnO>ro|c%&9QP^M4I
{1mW>nD~pXv%yu4Ub5@?Kg-Uhn6qiq~8Z8Q~L{;N3k0+#fV-
{<m>JKT1R^#)8`~{3$Dqtt*>w;9j{aHE8|ChW_isS?B$G<P(sJ@@9p5H&9&ZkxpUig{YYPw=GAE*zoBpZN>wWta>V;;tRGclfFZF
-8Wopgs5!)djkpxM6Sl-e9%R}DAa-DhIs0MWbE{+m}6OnWfR**EQKfZ?1-LOcG+{BC#C-
n9#}TY5(cb&vlMe4X$flO*?4^t#xu2^SI-@C%r5B?hKxSBv*)rp&OU9qgPjQ0E{bp*yAi{kNv-+2-@%>FuaBpt8*%_@391NL-
Id4%VX#*s=b0SPRW+@1mi7_?raiuPQw>>UT}c0YP`x7gF%3d4O_j)we)o5QKe}cLerw9$yMn@lN#LYjLdT-Ye@_iq?>vRJ&2v|t`
;&n#wmP|T=roeOwc_j4vprnseHf%KJ6iLYHMq7PP79=dlNFWWE{4;;c|N7OK341*d7PVqM$R>*=Q3yGsB8I^4DG<HEH;M(!eaJXn
mC9KH_DOefGJO9E+S)BV*Tr5Vqx+%O416U8v&r>^ig%P$Zg!!Q;2#TQV3?fY2#Zkm?PZ!)LMg0njwRJxDwh#hT@#0m#9XB#60MD5
^*XCFKbkZJ!Ib7Tj?;OTOsS<4DXwi`?TUj`4Rv<@f{IcXh;Vo=|=rX16Ow)rd}bO8L-
kGhygqi1Xi*|42MYhn3)h_qEKt;VR}%mw-|V_{JN1r@;(-
V(mygQEWT=D2E+>RWZIh<xS@KB(pQBy97gdak4sJeB^%^9^94bg_geV^=ZqX6I4pK8%iGPc+KD#J-
bPDv5ZG3mz$C6`T#Sm(=kRz>*DrfQmw00`I&?i(M+=-
N<jM_`fv$r1$$xz`8s7m7rsG^qI6=OXuGB`q@Oq0Ii?NB&JuGf1<5bkuukhFaS+K&0_VEua;DCeXtLHtrDW$ZE;XLI=F}CwrXDYH
Ei8R@wI7)+*9Sd}ooNK10-
hTa(kMKx9if1w?V2L6<{d2;E^sFzCg%P2Uc!5gsXQiu#OhJhzP{cbfnvE*K=oiaiPQ@5436k%`%=_IrQG|&`1Be>tOM4D}S2K=45
1qLqpf0R+R}`Geb8uwsO#7AV<K)|Hpbs%kLD>cHCMD1xkK$XF6Y|dbLo`%;isioX9AeKRL=!@lZl0Vt6Snl;QI*Ir@V=YS9Z8wJ_
WpLO(e`7oj~U=KDsiP2#(w|NBtuQOG`!tcIb(-6H$+ue4cQB~8PWB}l$%Jw`boY@ZS;t`<9+1!6~>$aYn8#&U!$S_N*8cZ-
%F{A5spZ_$jKxdS&Ze?@}J6b<T1Oj$oYr9iZMTFP%^xFfv)MJkkW%i?DxSLF!ItStmfNVNvJ8}j8UMx7mS@1s`cj;QPQ46$vh|;m
zgHSy{sMX$be8s=no$th#}C%TQ)e27gJF6hLFN9C@-
3nIUps7LRPh<V_Z+fj7W~vN9CyQ?c7~2OO$%7!MM#$cLTZZ!N|!8J`x=h)W~bi*ly<%hLImO*rou+%lkWYKu`4JSs2-
(qltL9+1z^H{CsGWT2qaDj!mO(%!aOu)nGG(@N2`1l0!Gf8@)1)@wbCNRhZ8|_p#_$oSm^fwv{52#t!3BW}%VeB$YToXgzEIc7j!
;OPCexfAK<y`syvgMeEb?kT!TJ>^_CE>ec|yG!&{)6o2;`p~(x=$o;q2j;2(hByrnC^VNQGRFE#odxQj9j4+!TGcR(xC_%xuQ>Mz
g=ntO~&M8@z@ei#g*8w5A+0bTGMEbI|@Z~|`8bE0d?L`YDIBu294V2bX9>YV4pK-6!kMM^;;7s&?v{4->o>ph+hB_W5yEb2Q@O-
9YuwbcIXV(tvS%8PasD|6lzoIn}dg`!wQ7iY<=NCO%UKXG^VJMM{Qyu72O3*n;r1T%yS<rFx<)N!*@_jHMq*JmnD-CvN{Q?uhYq)
+;7N3ehUbTjV!Atz;1;Ga4ldO!OMgeIY2AQ#6ltfBT+H-Knc8{RM)?@O6Z8I=(u-
bPAB7(Z4S3T>VmkYQg^vN79|2cNWx)*W#D(M*1^~-
n|H$NBAkx$X5Ydi$evuLv`$|zhZVrB=CjtNnr&kt%8SI9*<#B}yTL;ENonI~4GrWOC&Z7_KUuXpJ$aS#Z$*aQpOsBTweEaIN%v`1
Bmo5T0HG}7?<{UdIW{RU;y-b_os?tF7pRD-`jXk(JC3yk-`mC?|F+<4d}^w|n{`!vq4eLk>{gNQP8?!53-
rmLp8kn+!g9QK!RQxsOXatj|l85E@x;|Mxw`@UR<r#dvLD`t04g<=cboxV#tcbd0|Uz=EL)E^GL!W{FFz;<t>TX*=F6#-
?PvOox@Ha}jWj#LFx59_<tZF&z?C`sP|d#=0?WissMkv%SJNv$+0jfN(UtT<BDLa1oGbq=g(kCypy+hXAq=_0|LNYh3wYnc%;Tou
fKW2`={`(N8Tu*tVL2fd=tvPjJCd^I$U#9oUqH@oA5>9zY3_1MJ7(H3M1%Fwnb>0=t2_JQ;-I%1!}zVxei_jMJ8^D!-
_9rHQ%5RFE0wQ!-S_NT4#Ek$(VKMOmp%_1+?V1hl7(fthSTgNBkR53RDJ{eB-sg32()sX5M%KGooOLM&ee9{$Ocx3c^54or>(DxF
PfaLY{pQD*23#E#1<$ZOI^_iWfEB<N*)TxFpi@07gDzZ{yL7F7rOl=G>|7-
F_5GLkb4nz~}W?@#FRAXJRJyf{&Djf_s?BKkde5`V6$bVDWj!*}Xesoc_45j#PDIQ*{MD$Hb>#vaG&#6a!a*KAP8`<%o)8Q@eG{<
0@nwu7OwyQ5SG|p@lK9Zfg${C3c85i9jZoHYi#I<qS8C^KCcDRR#z!qg%=TL+f=l#4{<5f~ZgVwKQnw+PPr>l>kvPjU2)$QQ(Ee(
*86D)#lF`g+An#_4*mbWBxxSL+=&7)XZD<|`Qymg<6ct%LIN`1G7BoI;6OlXUk0-
nd4v2c5)KvK~u({z_o`uM=wOP7%+C=a<rT}Hn!f~uNXQ|KBHOB2%ZBQ`@S#ts&b^PqMwy}D-g4$uuhipk-ghx%6%#tNELU#F*~oD
s`mZ!!41Z#q#Rqn!|+4$-b73f~M6H$7oMSzAEPQj6wc|Mm0t>?M@EJO&OfA6XvmFs9jBo-
|2H^Ie)iM$Ih9G7j7(Xjy)OAFSr(HoSl~lt&8MuoP|yoe96K2MN!4NwIWe01x&UoF7`XRO9PpKz{PXD)9)oSAkMtjXlgqmciL0Ih
+h@0(FAEyC4^`$HCJ*EzB(wFMM+x8H0@$gQJB@A&$vzR5}KVIGSu(;Q{}XBvgsRWBFYuNC6Vu_vO*;^Z+<?c0&c4VtPb?*2%)8zl
K8Vni&{R11@mpA`?jPp!ay++ZFOmq`<dZTjHYYU#$A~@uaC}mG<L*pKRW`dt7%bSYKT+?%p2pk5*D{{v_fDh%T3*`fLPYst|djA0
=I=H=z<q+W*VnfWaTWB@^a5JW<6il*)>@H6`xOgULZpX^Zgj)%Uc4_#>_A-}`^NEV0kx<CP$@D7gvr+?2i5r7Uzc<FqaxJT8D-
79lSYV`I|Yez6cJlS}us+t@wkSCq~5JIM75!aRn87Riyw-
n_V4eW3)CXrJXz=F5g;RRD`QEEXy`?x4^^-R{}lg@s*^nJE9RBy3>S%hCc(e?gP#X_-fbB=k9b_$PTcj663uwI{9g=1Y2gDjW6e1
=nF$WFokFU?HShfbh$h=DQbyK14GgC=Cm&MLr{PP-E@O9NhMvE72emYBn=u9J8Es8n9pf8&F6-z-XId{zA><45gvhRL583?CY1-
>v1^3=oBPPlY)=97FDs74{OYR(C*7_VP&!t@qo?-0NSFG8*0r~m-
!CEyF{AYAxwATOMY19ppV>AXnJ8ysC6FZ=vB`XnK|fRbQq)CNEq~7^`g-
I`#Avn(cKT2JnKm}Am&fbdeeTiqp0ynFhr!+79!`gtjb{atn)K(y@d3<WRyg8SCc>Ipog(xFpPvVrezKBmeCAq$zx){i6VBd@1}0
xO{PP<i>n-
)bt0Zs;gzYoJ_l@`JD1~PV%Yv=VS68=e7?S@5>Me^89_qww+XyRGgkHuC3IB;eN8P`&0Lj{c$^V{5jloEmyRm`DEB~PLQar9v;4-
mf(IIy2%HuVEpMCtS#|<{CjB{Fa)30yB_hENf2AJqCAT9Psfz99$+!3bSLN4f)*6i9Yy^C*t#h*;(@&s$BH&F(OAd^gAw5!c^GvV
F9H$N})(&F^Hlf{EB)33a)eJ(`q*F<@unD-Li8FwbfIO06!QQyamhelYS&RnA1%I#mrPbmDp@DvbSxmx9mdiPKa>!&)nFe=5f7bn
Xu}yE#m1M7SnL1ptLfplV@j;7jn^WhJap~_hKrzOO0T{xatL&$o@b&RMUuY4SKF7=N73n{dCj@5eU|5;UO3?^IlkFhkT#7?L^LpJ
mR4pXrt8z-B^Lh~(Pv%cD`H31~-
$zq<F=*7fJf4hAUPJUr8i0NfJ15`Y)W~~ks)H_^ych~}iUyyPm17g^`4=`N7ut8*$H%a3vT4MdO+k)9U>=-
w4COM~d@*w8%kyO2Q6z19tS7u|rv9_Hu<rnhO78@Zi=9|at2&FHBNb@NXe890J#8O;s@&SDiXQAN_j<+oX<NJyqZZBfnO=7g=C0@
3str6(?;C}3W1YJUeQM0U`RkoS)teWvNx|cH>9y?K)clhYmlp)Qw+rIuxrC?MbDoJ|LJOYoR%Ao``A7U?87K2U-
8^R4EoH^4J?kSrBoPPsSnf3+7>@B`z`z#BNPDJ#!0ZidlCpuX{t>jm93rmSdqUoQi5E@!!JwQW4`ZRhFD_8JI(A)W`Y37!G6UPo8
`33v$9vl)xA<+Yn9sq=3-qs5@2MR3n1rHuKa*8-
7SM<E5GE*?)VUrpu=%r}T|qiIf8!icDkn<r7F+;wM=rqGCE=)B&MA*hwaS%@m{I{I4la_*LFcXWnWRndBE#P3I&(uniFxYE%u~&?
LaJ_226Gg>1)2+UIQ@!2I2|nEuROHS>n*%siuLHtpr1(iYV@sA{QijkEUsv}p=UajU@$8cbxdbx^dcjVWO7&x7a8K1myzOjWw)J_
PABL!=0f0wIk*RUg>4B4oK{4EDZGnm)4o?mq5#s8=c!Q)z;dRv$FD3Nx#I*0=bFTS$gp4B>=i$#+MOh6E2d#?svwC6R<!BS6P)dA
6!)y+)3phuvMkxPQ5aMsQ`(b5=|+vFHWNfeatWZjS@pNu5NW`=?Vy@`^*3YkS!}P1r~%Ki|2{l#HR>q7pGbpuUkVlQu;9oDh&lC{
Xr3~HG?7$5v<mu^<cZ_H!zt4peWfz|+7mdhtyYK?l4xkWWeq(WFT|fL>itrRfK{Pa0l<<a^wZqE+>3R$KBXv<F5O=_$?!%trAbh*
<mx!s#kQykgTQMOT^_<ehs)%Cr8aE|WTz;f-#GQScC%=87r!3tK)J7{(dHJj!AjuwCD-TZ<Y-Ms1JOGqiIR#g^x0yId84}-Lr-FI
KcOa!qk6N8oMb^JT6T|F6KN$%)4BTK_VPsAg91=O2L0Gt5|83HaDpS`znb9Gg%9gJ8Qu9azWKsF<C9pjE0Aw2GWPM`S|tKK*I!qP
KvpUF#MC9{unSY|dL_HFqmA*sAo+H0M@k4-To!%F^HLIQum#5^m9)zt5}*a#vLf%l%9llu@c!id%Fect>IeJEI2-
4azaW=#Xa?wCVrNn(7Q?7V%unCZ!e(miSQkOG;YZ16l}sOya9ql;91toN_F3?t!`wG{+2i=|rQM36T<tNStV!jC^0yI-
Z_0-<x<BUhJwT14;!P&j<T_sN-ls(917glnJ>QSen%*c^0Co=UHF<J6Tet_|p<u>C84rXuGqQ>B8AYj?W-a2i+oDL`g-
wip;|;J<@BH|m#iy|M^!q{-<b^X7LGF+*kK0NTA&!U)4U(GE5aOz0bn0!p*srnK;3M;~;D*QNm@fCS@nnW|etrXV*pA5%-
d3^+#i_s9)CVU^*4fi`ZMh;_1beh;q2KqfPyA@ht%uC(Zg$;~k3pjauMNXl{`KWs&h5Al=777iRc&SiJsY-
mV3bt(#fKGo_Gov`BsZd8YTwZ>8SVKz-`SnPyJgXhe_TkG8y@dmEAA>Rc>%2--
m38n7sasv=_n9K{GQkfjHt?j%pHYbjD?j8DM=B;6rC0Eav_NRQb`h9&&F|csx_K)B_l=AJOw1<5zHHG`>?})YOcE)h!Oq-IMR|CR
rbf1{)-m#rT=K3C*-_VBSf5zvDt2<o4&y3-W{1udV+4~N2t)-
cV$N+TRdExZFzkonuF^EEQ&JE872CuYU<9#J|tVheWcVK1*Si)s#Q9q8-9Q^ul1zbO`#D(dMtPAtj7`^j-
oi&)C`l!<?iDvW<6#G2ocR!qz*mpRjy$o_@K1_ZfxxQ9$Um)LXNPhq><m0znp&AAa)|y=8gQ5mN-
Z;nu>rZr4VOnaATpA?zHa%KILeF=Bd3{qd}8>rr4zKKgx~6j8cJjBI78_zS}~YoSd0aB+0Ja21XCu;?{S9A(I&Do!#5D50E9=&bq
5mWrSkUI5P6ttKSQVEm<VK7x7j^HjWXX`5jbWkf}ZsfN|s$624q4=0*cA!xtrEeosWhROsaDwWV2$w=|l5oy8EwtYKr&AN`EJCWH
!*yK~DHKI<o31z_sArKz~#?Q!d4-
O?R}QRgVQD@cP)w*jFM@T~y?nmjl&=bv<i&SFb`iEG58lT|1Q1tPv?V^)FT60f{%fnr4W;5kSW6R_6<*Na8~n}K{TXbK(<gX9ZkB
1<}Jpcc!Uo91=rGN4-a=eg@T__$0i+u}F8oPg7{1?H6lC?F-
ZKpTb!n87<ty9HvF^o8DO<C%cCuT({+8h1>wb94i{ewiA9$ps<*9`6~qEuFQ=j#}{}rRk&!f82{ukuzqeVM5tz-
2@=oX%C(fIQF6h7tBJ<b#~U;VQyT9-wV68Jv91)-3cpWD#s9q$Vc5x&BXmZhnfwDW9Sq7!es-
J&|k2@`_Z!EPr}4dKBM|zuw)x3mj1o>V>g|>*ccHnS{>bYz}VGYQO2U%cQ5MBpIVf9DZ#W^Bf&jNCCXkE!g!E05WBN>$nVsqfxBa
RmZb|u`24zfLc&Aujq<m0q|-&#)?S0rtuN3sMQsjAHNfZwz2ntzoeJBq{yH5z%)Y<-aO4%?Ycx&-
uA>&4+~oO)!0yIGs{{!J3AW=GW@}IatNB9g#J#fs8~N@0{tOqEcz6J9g2Uk9+q81tUe8>Vd%|Rmic_9t@O&+qHfl}dbvySKTc<Cc
I*|$yJ`J$l$61@M5JY(mAbI_WS&DUHPr9if`ASsasEEy469q(&qjI#XTf?UFdU<=#rqp6Bz#zSGu#*lf9?UNw%`0&{1ehcYdtzWo
wTOEVNSWAO*|P3%oYD=q-I*VTfcamON2c8z;+XT-+jy3;n4;JbXn0$Z<rHk(E>3&a`S<kAo?m9LArho|vmN0rbLH-8!4X{SiwV-
xS<2l!HFg-BI}&L&p_y-=h@jU1b$Rlun$4=l-
J}}Kj>Y(fHgmnvw)6R0{12Hds{)rB(|hn*t_e*LOY_6m#b`?Q=swItMQ7Zi?zq?5kJ|1*;|W@RyCOV(6)WJ;Z=h6sg_OO?zQ8~&G
vxWC?I;)3Tch<ROt+CYhl6JoY)t_~v(c{P(iE7Kv8n??@^I;H6I&VP3PWyl%XiVT5HGzvjlG4ofw2O;HT;n4{C09jY>FTpzq$+~f
BMi0?oqhxt!1P~DN^Vn!cqMjw)zQQpZCx>_GPqS=6qr2F7<W^1p{a$ki9x6!}+)zWB_lY=~A}u-CoGCBw_YjW0{IZ1+I1m&-
|0XTKLX_r;)4PI$ma=!3SMr?viceVhOh_wDT@X_V@3?qAN4ITj?BKQ{(+w(pBO*<Fwt=yROEy$+>#udWpOU>C35Q#qP>WNd^gk<{
P=yQq!}?7B)=`>bMZs1f;u-nd-(2;e{W^$j`M2m)9WQhXQdA%)|6`Oz)Yyyml4+ls<s@>fza-QOHcyPjyPoB~-
}L$JI=@{sVTEDZ(ZP)K=}IRKkMZ(X^=BY|>}f)1VxuayKM_{qV%JTV#x^$Xou7<w!tZgX|EXf5{~AtXrV*8RQ>YIr`TljjJRs5m5
%hL%;`0gdj{4qG}W<<LO^%+rsJckj&cGV}9d*umur<zE-6YuzMp5Vuu5k8Kl+0A*0X2J!fzr&|@+pU{=|BqmZ(;dCwP&L-
11jiU@bVW$4!Z-k{}CH<^95$mnh--EP6?#MJSm&gz;T(L_la%A`qQ{23+$|6OzplUsbFbsYj!I(n0GcgYTs{jK+k=4VTdOi^i0{y
fM@j$O8PV;>NPV_$+K#*W8yl|`w@>WC5c<JM9ycUxdX3h-qyyQ?~R?hF~8%7~FR13TM1<a-
>uOT_@!2|8oM3HP%Xk83IW_l0m&i4tXI*&5O_3jAk+;b*fx2V>xCQ;^j2EltH@=wD1tBUyJU(C=2bFk!jw2Gzz+#0*T09uX&^Ig_
`lNkQc0l6vUjR)ONG?+SdbaN=bs>Qqw32ttSAc`b@v>L+>MuV}0`vUZmyDV?v6Aa(H;LSd@)97zk;>ajMsp#Ak~2F!VgmO~1VNDs
){Jig_e1>GBQU;fOeQP;-
e4FUVwCWN3s0C7VXQplMy7_2QMW!&MhO{_dz;9M6>XK^*zcz1($BwV}yE4I}{nJE0YeeuAV0<n9pwiTL1B2G<QR!`nXBItse|I?d
+Y*(5z)5XtrI-?1e?E_iaI^-
Pf*;at!#$e#<to~XOb#hnq>Ax9(y(O<SC(wiScD18UD&9n)M+Roou6m#l&nUywGPXnsgV(y4XKF!%?#4tEANPAH&!@T)@Bxdo3EG
jo-AXh2+m9-@QjH2UKdriln!-R^m-h@0su$#;*rCpBBJvpml4<JcxJX!8pj0W>?e!tz1>-vN#D~yYK|?BFMKN{14UG0t8Q-
*ZUkV<bU97FS5;ho;+5?lr9b~|IhQxx|*zcbTlio5IbRE*NkY}<FyX4?LI&ii#C<V9WutGmS7F0P#=>)x0*xe5Opg$_`Fm2D335M
tyVXDDRxbiu1jNjpw*Sqe^k_O`FUh2mE(K1-)RXSdfqEc*fB93o1D5$#m)e_h(jPfctnTT??yC%(B?9caRt8uiI=<z<1_-k48-
OcOKcK3CQUc49`qf&4Dtf^(}Y|yY?DFkuo>Fw?xrA9LhkoY<idx;k<{pitMCDBxzF7S*uaNXmu=I)#`BHF&L?^dN5St5hCL${S9=
l%`_-
`Gdh>xcV+^ec$Sa;enpW;HGm5qhd@;9b>ke!^y>Zhw`zC0AR1=t90U^4hH56!P~dHom${>&7p*il4d!^+2;V9njE1;U$Anm3{;59
E-Jf-B-0{e0J;J+XfK1=x&u$ZiAYEd-2Tbx1(jOL>kAUtb@Dyp*Sk1G;VzERqQtXU-
OKq$9<aiGxl(&gZ%}!K=K4FQsC1~Q;;6)(h=dfc1c?tFC)UJLS{%l;l60K!{LtL;t9K>QEihV3R2ju%5ab>ncH|ky$^kz-MnjxP=
_DViSy;Q6pR#ie@^_()H>q{4g`4Vkkym)>2G(@;*en@H%V2~dC#%H{jQh|i(^Kh5@AS-
+M<v6Cwf9Qqx_m@LY|fBaySplTH0~Y6^2wjXYix*6xV+Kc@@QUmd@s)tvhZ?0K_{)C>&FX>RwS2UH$x2p%zpqY447hi@e^<wvN?H
wZh-RiZs*n+e-4U{;E50A$o&V`B;`Zy?BYciLf`+q-|!Cm)Ft1m6KLuE9HI73`|wY*BSu99`sW1-
l`|3MNG40K3s$=XSL~v7@iNuLs_9;t{3-CoBdU;omRjp$)hvB<<s_>-ZSBan-+15sNe2C>j>L1C+!2uH4-
iL_)cQdcv&cdWprLW8x$3$@dZyqP`K^OZe0n=TO!{@1QX-
s*Ts09EVO^p7}ED#Ce9ma(&~9XWR{2t?En4*l*^3p%>%byo=qhX&Z5VOXtnfLT$cFi=FG~ld*M=^ZyyH|Siu4oTugWcHE_*VeC|p
N8c(gFpUy1yTZ>yaL%rlPJx+qQXq<BXgGsn(i0tsoy2M7vYDQPYq!1M##9wuM4~;iDL*<_jV&96nd!hiT;Bs}lHELJj?K)+;Wsr2
ib6diOPNLJVF`I<M6;Xm<$m^-?;kkQ(UhkyKb|)BU9wp|bmehSIy0ov-
d5ANInjiy1)EWUTG`DuH^d)O>D1E$5FJg?`WI}A3!|Mf5lf2-
%ytz#<#;;is8ig~ebfvPoc)jfn?(EwYIl7k7`NS5IQ7cE3!VCk^a7fep_449Yynn%T+**tI@!Anmfk(duu~M9(w~(D=QV<fH9&?-
Z1uGX6EH-teX5L~uk=p~UPYA0oIO>vv9y&Im-WM&)f@o}!1vO!T@r!Y7UBo0IM5zU+_uCb%<HFE^Y%*2SqOX06lc__b`>#58&ch@
3>RC6oj|@E(1`8o3>4o1cm>5PFO28#M^i7Ts_iWRe`@tjOgytLQ)*<}c5>Tj<y6TJ8GxVy&9d%_9;P51_9edTtXp-CyQe~n4N@i@
jC`fjNTKkP(5eT0Xs4iO%Uv5N`MhX*n<7u?Uh#Zj!Hm&o%B#5X4@M)Bs$@N!;l1yb!+xADaYLtL8W0VxU_6#|rA<5EYKXoom>nrK
{+<wqZZHs9$%nqGC$}4{fAS^K(Qi~I)M;DlEQ|qYUlLG>%;CJiw`sG_RgU7ToIS=QFTy2EU!;|l&ivxzge{z1XltJBmyP_-
&%+X6GlRms?2ZoednACbyzFzEw?=w1cY4`O8QeW*mtzdNAVu9Ez!`5A{Uo5_4GDQe7cQe?+=VG49I4x#=?%Forx$9=#E}abmTLv+
5rth<lMj7P0F-ylgy^@7Mp+qXMouw6KKyC7ws<4g@8m&#CW_XktOZV$=mtFo9j7uq&A$5J(Mf#vZ3^bW@?7uu9Tj(B_$1j-
~VSnjUNTorjEZsNu2^S6VDxGj=&F=m=7joeNw#OK>9@puTIxo%(0e)ThCs?lN_Jq(xA|?SgiUU!2>jL}4WMUB2+KE-
?R^#n*C%5L7#lc`CTUX4dj>`ne@Ds_6YFM=GW65P5uH54QN}bcGhMPJNf+!wRINE%7klqVB4u)bsOqz2=2IjFIx{o_WGppJlR-rX
^6$L&141VAB<0{!_c=T9|q#>`PH!eJ=C&cw?yJ6g+B9^k32qDOg0rqj9InJ>WwsAsW2WKG?!|e(1m-n@04FS=-
BW|?;VE5qX?qT^#?E6RSrm?GH3H53Y*<+fpQF+dW9m<SM-}740eIM(o4F98Ie(B&19~0E+cccXk-
4FtSMf`^72qM2LmJDzj<;(*kZ+JV2rOhUEP&)vKg$gvhz!5!%9APv1<eIE!Zomz0a`Ar_TgF!(;eJT#rc>m<dsY{-
N)FF$1ZCdFyktnjI^jglv}4t+Z7~Fn0xu9WrYGjWPLULrZNPn&O(h#oztT}hC=={9K`Vx|+OZ9<wE3V<LMcU6#L~U6`PR^}2X`_6
q*aWRs#&4WQkf-Bw4C<Z{)8ZX>v+*4l}r*D58|@!(5z?dx~!b)1_a=_sj<;dql5y$_ShEd7L|TU;f)@}Rdz};<gIv1s;%<@P;^TR
de{8Db6XIi=+Nvnm5e;F)aL9E)M61o1cOD#=s-
$GsJhut492&Y%9oEys=~b^RQMw`gB<3wPoXAbtTSdW#pyNt4s=$`y*>sGjODj0spC41T*vjZiZr3dbV`j17Ld@>MN9TJrd_w`9s2
d_BR+v}zbjf<d6XNY;RBGgUc0=sk+)e%5^Ie(RegjYk=}u3e!%OGb=+K0NRw=)y_^WhGuE8|K5wAatu<@gUq$gg>e3?2mI=6ti)?
hQU2tTuFRUXWygy5{1>xG2IzZ9O2X_2v`-
qz6OffX|x??%etM&`U#K>;4{1<<izgE2=#JOSax4^E+iB|^@kNR1xYU}In`AZY6^g{b6rAKXk!)7s1#CIA!RQTuGzMd|)e9Cd^qz
I4c<QhR?`9112B}4m=E`;MAOZ##qmk`#XhGhX1ogJAxRX{Tu@TT08{fb7`{{52ql-8562Z!9Dzt41-
6r*cLhz>K(0!8d|<|Ed{r=#xGZ|(l)Jz1w7nQ=ZuH^TT7ZV)C>CBO|&sQn3+cYwcccji*`a5q+HHoDMAf^Ldk*1G*%Q8CA#AhLL#
Kay2mEL~!A0<n=u96WmjxSx#HFKL!rks#^5@_o!ND-XoA&eJiSM_4!PQak$LFh6vf)7yQARu3GP>IxP(s$<R@i_VT~LRsFO4N-
ngZG_tutP2tj9HenSpRCBy5lL$9h)L3mbjUM><Qu`g@v?>swxJ|AJ0N|HOEdbB(&A_rQEj`!A7`_?(RUaHjdl4Gp6t0Gi{q@MOVj
3TfDJf^*sAIyS}ePWw$h9XvuN0N;H+Sojqu%M4IfrJ4a_E2*=v2KG9Ky(CLn=G#Pp8@zx`h!$Quf{Xg;t)JXoCJjO80O6-~X-
avceb3C6PvuKGt?0iyC-FmN|5fu5(}WijE7N;X34x#Y3NgkRS`89^521IIxrXGRks1}=kB0&y|m&9bEAl{yODLJnWpOW@#ywqm#A
Ju6k^CbAZDfywAQKG5D>=5#FdjVEVYeK^uHhrlaL7cVCcMh@j2lXxJSs3?q2uTa;vt|jA;D0<al+C}-
uM*vPIrbQ<D)k?+|Ge(?EEheg+xh39nA)!y*r-
n(GKrfZY<y#!R0zs!i+F5R6!hlvLfGO96yf_acnAOHkkjK2uxXo3&Cd4Aut6z^WcZ^z@M>C%;&yVTiO~WuXbFeANzr1SHgXh=rHb
wByQ6Ec5ef>qS-
>+;XHAzQJ?1_=Of`o@B0eqzI5HaGm{b^$UQYMfs%{Te#ns&VCv0u{#*D<ovR{m!;GL@urZDcr+3;#u_410u8mp{=8%32Xus^O`Z5
4`&mMZS>?UkFXvRSZs-
L7>CGji8DoF?qURsNmD5FOME!ahI|X$PE$QYht00{{_#KZVsHS9BqOs7otWUhPl_mjX+PHzqY15Ak*?sE!eA%wCj&9G#$#g@$SX`
fH>lyAJ#s=$jQ*rqWH@c<0_0OuG$E%TBf6SpbO&3@JXqNYb2Lghw!EXYlpK<H2HlV2@kWisHC;*$M$N*{+nwiU5^zy>3F*gfSFHl
c41eXjv`7#=sUxD;1TSp(rHh7@ymaP@nNrij3^vY3l~b`_Z**$nrl~&rZ%<1_!PZz<+0?gId>q>cNZG|n*n-
ur2)=lnag83B2snVorh-_RtGYs|Aw#djvGjPQ-HHKe1#u5wM+RPjC!O0QjCAy2+%-
CK(npJ(Uw?q<b;TbgD_ld3BEkSmI~XqU2vpb!r%8)=jf*1Y&>dpAjw%d({`-
P4;23%*N?Omz~Pb`%jB(9#xoKw<hOhke)){<OeTdVcn%?iU$OPi`{`sb4_!T2jlzjRRdt7FE5{eZ@s4~U-?pY&6k!Fv_Sv-
^K?SR`TD7;(k;(+Ll>2~)I?$GlyRh6|c6Uz~OE#6rPw2I)!oA2JtOHLgsja8A#ZA&`Nm7-
>o;%Nr1o$eARQ3D%zB@48XmNLFTuVr%p|}sgLm?8_V=ISwh-oE1FIFx;e$(U7Jlhi7)DmSl$8HwfnpP@<UbCu;1p_C*#9S2mjK`W
=u0W8%HJG$*xP|wq6+csejZ@pmtjd3y54g2F9ohkTV6CtLmHq9znlzXFZ+Z(%bjLE}xcX#EO|=!teh?I$1c7x^&??<K3E*NmpR33
3pl;*$RU2j{5<14c+PRh^_W5JkU?DRYF5Znix1T--U`|_uYYkkV1V&3{jp^HqfB3;2fls=G0VklX-
2RgQaB(AkYU5NbbIBb|8nlbcaD2I={~^%Zaj$%Ze{n18$|omIO?+_jfo)w?=iiz|4m&jUs2h88w$ciB6Su~SL!ZifpUv-
#0N=iTmv#yc%x3G%Dx;M$J5I;BpjVy)n}kXn^Gl0(=6GUo2K3>Tr<La^qSFE6POkI|uO^Z`C|G>RVNh{9ZnU0p;Ifj?bM)>L$pID
ua1D}`hH=fG!(E-
h?5>ZILC?`nuIxfT3=9t{`3d0Q#>ItV;?=FYZjVr4=$;3Bo#D6NbOW?y_*vzDg$^F*0xZPV=w+`9C#99fXDB>@B_}^Sf2OHeGnvl
5t&`N6(GTN1PFOUn$(n-cfN^21Zs)xpcm;6IK;ZbvS|~|+g9_o{a-;QvftE`a;-
X?QjPADP6+Owq_*MXtq>MY`3RAE_MZm<>AHM8NP6#kC=(|Q9Kta1(gi7uKB}$;fx(#0;sxxBdANOXUV-
@=!%jE9npdN18#*!Hs4R(JLVMGcVS~uA?&wKgGz2mOSG^avhFIK$6+t)+k(jx9B+99W7jJ|X$DQAmgGRAc2R7Fe|5GQ`FrQTOu{7
uW0HBWs?r+IeBJ+kNm)(O1v{jHGumtPNG(N0V8v_Hf{ThjQYF=4-
Akn9Z9YXQrQ)7Mu6;z}$0J}KgNr1SXm%;Ctn^J(D*2Mn9~eZ?2^uC6=OzhZz<iTb6xMpyW5DGCm(;(wRf$Gg8E6g9Rlw+;Q@wg#v
w?afuUzZ$_>>jnEkqQp4{AHe5hBp(F-
D>}X!{ytN(UW(}6N~*Q`W)u`TbpnHl!92?(%C4U54*s+6`ge9y^95OIqN(dQe(~MW?_%HY+b2ocz<gFTGt(nF;iuAx&J1qPZa=<2
%;XpsUlhqS+0o=^tLup5=CnYBag09}NV<DKt^|P^iFz|Lg~ss@+F0xY0keW|yPcl#LlIFeHE8R+-
yP7eYR?f^8g7!eB3WB0y1pcH?W=Yqsfe^WAoQ~RG`MPN6<>{T%q>zJ|J_9bl=70~t0p|h=(PZ>P{ogq$eZ)4K?Y#i<a0s_VxCWW$
u;hw{@cw6+RvV|8S4RuumhyO8%zW>QQ@V5g#Cpb$~nZ4XegTlkIBfgN=Y!$$G@^fE|jtUJ^q23*5X?0^rEnc?0*jS^``Vo^>DFJ4
9oXB%N{mLL~>nFmQ-DzX*W0`gBx|+alob8OhEFMVX>fA-$?<3+}NLp`N{hsr}=*mA9{CYc5+rAYc-LINd+LpiTx)#t4I)4N~(=<g
vhOp#%YCS{6VTeu*k#?&h=+s+TQ**+L+l{naQ%@(|2#D6$?@kSmGEPAwgD0ppJQ9YZ7PdmuD~>TPF8rF0pNg&)u;xn^f|t;q$0kR
MS3U{UOsjRY(jwt^=6vrW1H<JxhP5Pfgmp%N^`G=g>pz>4-U)6kKBfcvMa{kRw`SFr5TgtK-
K)HS1ETV!^{*Ny*>i2`!fRff`w|$N#YWK<lxq3=z6bba}l`Y)!^(1N??vuSkPTp|c>0mzm}Bn11O<^yW#7KRY7SD707@SV?gD<gY
{BHb%u3;qzB7qV>gDX@I+XgoTMQF_{by02uN2Y|+gHS1SYy9tkYKB#YeThZj^0!BDW{K$3fK4R~Rdc;XELn~PS+RtH1_r|}VHT@Q
=T49_J)@JrmO%~le++5or_ftel=U~Y=S;Su>j!XBA2P-72a9@W?#D4%!Jd;Ky%s-
+_E8xa$(D#0*o1qN_*zFE^G!WWYl2L7Mh0*l*k<RD!cd$;#bb`~88+m<=EMu?Z@Hg*&4A^R#{0T-2|f~8QC45#-
8eSOWwD*q(B3LjTj8PQLStxmYkW+g(;wA8*FRPEe>C@&hux>@#RVh`1~lTMeMkTeg%l}Rc8tR(atB4GXfe0<kMK&DM?P=IuA)5@X
ejf*L`Pp`V18JJ*Qcu$ZhzRYD=ZwIpcbFg3CA2VhIXd(-
lxC(7w84iRA%y4@6ymru{6#pZu=EeC~m{kwFV?uQCXZ~@jQK*yXqh<lDNmTN2m#Om`3wmN)m<W68WloX=#M~vRCls|%yvhPSl#3w
W$o{c-Vh38Ug5CN{LsL~kzXC5|8Q4^Z0DTylu=i0WW=Aqv4Z&zOxVCz23ImmwVn-
X1a$+)djjl1r8I*O6HkU&Y5UF8#GmvSF>0Nw99y@aRRR});mwcajzTf=~9|5(X&CeS#3*HndG<YQ8HHVrJO#Bt~2Y^;GciVCIP^_
ODQb%A=<H@nJe+)k>s1`BGmHPzoJr@=N08pIIw2`xdq3z<HpSm*Cc$a8QAtL5V`4%fd_ROXc6iRZ7{8C;ybbEibeqAB$*!?8o%ka
QIf>52A@q$-G3I}6_O4T}!9k=xmWU}bCRe!d0qfXD;<%@0>d<z#jC)R5#N32JK-
D2pK56Aj>8c3u2XU@%#WQFlEW3{9TOa?R{_4O2n|5sUt6_SChpDbTlyR{Nl?VkmTgDzG(mY>#S_21sl-;Q&M6QYNG(uY-Nx@r?tX
%JY8g<F}6ycl=gHc~kFSbua?Uq^uK3c0`&xcqznt=7$0bJvI)NIMw8u|{<;wyRk53<ymee+>?Mu2d$x&t;Q%VbXYx7$tnq@Go0S-
1-@uAVV#m*?c}^|Dq-V5kjJN^p-e-DESA*Yw?8AC_JIus$z5cp5<U#o!02I=pDEKT7r88Nb~JegcAp?L@FXck#EiGyJy1EFQR{-
+$T-
l>GJCCgg||{p)Zo@81+OSj)j~5QMY)Dy2E=zI^eY4fIY;}#sAuQ?;gF)1qux)EvHTPW;{@}Yl<wRq9?6*aM5i}!6ArdwGV|lXtkI
YmdZqcz&4)W^*hAxTEoR!flV~SY<zD?6C<yr+9sbp1>|xliHNk8-
ftux=MEP*dH?e<*PDWk5=N5igpC6vXl)sxB%<0!DRm(M!PB09HdzaYU=N$g$Yx<72xbziI?ofyZCVa<WD459;@i9gvJGYSylLc=w
Qo4d_C8@VZ8@|7AI7LwmYGFi&0gp~&{Mbgc4~ZWKn@pz$7p(2a-A^rZ)ET+7!f>|p#o0Nfy8(dC<up$-
QXtUG%b(!SRAmSehA}Rpzvz3Ny=swLdi^qy<%C21Ztk{t@c7!4dWkK>N0n|V@f@nydrMObBR^K&6YqwyIgZhMMvIa)$%=lC^6H|W
ByDXk;)OyOU69F6JVDj11?!oY&=iMlT{HdxPhzm-
+h6F=9^ipC?*S7_TRGn5bFrNllhLe*s>WM%n(>{o_5jo4^hl301(e_kIw=2D@hsU^<t_bvbCZJk|O88RR*mtm#KOD%jkXL)C@{pf
n+xkMyq=5>=YLiUdVvA++TzKSrj4Uu7M1+_6kOlpikXoK%N@MC6P;=5&ua*w)wn>o5^Q-
nO!ru*AX?wDBh)|(On+R9#nv^*ZxKLb4~Z2doEjb5CuMi3l!Q@S0|LkvI9*C5eAK+zuUunw9i<fr$vXj?9<vXmclWRp$mfHsDhhX
5u^FA=!^4@W{`VM%y<Y@=36R>9^b~@OMnn)m5fb^;&IdIJEEM&`1b;0xt~4A-
<V*LX4)!DiKqM?E7C?O&WA_b&r>f@_`sf4r9PywV(F(DMEBt1umEO}P-nwRmmV*Z^}ftvcUt<p5-TOhZM{-
S#$avZsO@A!GJ0|ZO`V-iNh%L&3IiJcZDSI-_P&bGSj74T0cl)OFnSx)bO<|d%i;L!hT&P|w?<xMLksxGMnAEjh;EOZft3UbZe`q
<`g$G+JyATy3~GYOQP8AuvOm!zSDR7!Odo@_?x2-X%4*;8fcqoxRQyCb>u3(pLC7P#jm+61(2Y@}K-
G_}c(2zZpTCsoKXdX6rPXrT+M96Q{QhAIZ;%-
N(mx0#sdUsU<ZLO|1nQmSF5War#3y&d+Jfm|^UA0z!p>K+pVWc_Bs$iIyfYM8WK6)3MSRn!qhPE4Z+I5x4Db|NzKPSCvm0{oQS#l
=h+m^+_;~I8pl@2*e0xpB(2O7J;EX6KAp(6%xdINjvM|2N#gYnvPLTPh;})b1Fu|Q$@un@?`54V_<V~xWMTO^(?waEU?beX<9nk(
Z=z&ineHuYUFMoVPk-^~ew{koLExXARKh||tVtfonoDmY7cW?*fjrz<($(1F=2UKD(&GQCi!K;(rzf86#tZx}I+@DxxGZyA0Ha-
~&@C}hNO3wbHJ@0!<Ws-
s1F`0PQQS(VfYy==Ol<aHH0zT@E)n#)u9_ezKp`UU5<x{RkueojXnIJ=uv{xn&r?a!txH_RGY)@S}&<X;>#U>qWi^<<SVFWN>p07
)pU-b-
4N^746ofn*Il&ARGNlFALiW2#IDN_qj?6b8jTM>ugxUMo4tTg>_C}PB!HFsTj5l+RNDPR`2FgHO$T80l*o8oIG()(z8oKLXZoV2O
4(nRpcnw4Iu=zR5bcQfI>wz#XnK=-D)xz8Yn7Bi!o;DcP3G2iz*1v(|uaNAs`Z~lv+D7AspX)Mb@_-
?_1;0Pq&Ik@(b1ej0t+>U2eKZj|Nftc)+1c55-?014veqh)xA}g%}N1dSSIaB0^Z{QV9U*$UNdBTG{_32Rol>2<l--fcs^-
O2#25QQ2l)j~@`X?aJ(HJqMGxxnA*(p}cIccKB4X;h@I$98hpq4GO+ycd^S_NsA0qvZ^1^xF6&a7F4Ro^#Om9f+)OZL<aB;%GgUU
`hbv3+~DeUa$Z($jAjP==(oLt;RS;_U&!asY!ccL$ExaTVvaGDe_MUz-7~U3En8w=8J%Dt^itF|7q4>^%19-
s9zi15#fCOm#WIR8ojrL94d2EJvRPu3IQW*9iWUqatH%Uu~bbk~^52={98M{Y&kag2N>$DqPK(tE;edUIjN+`CBMH>DhF>W_b?nP
eo!bpf*DtCoWpD$}wG(((aTRT_)-okyizkXprc_VgtFI*N&Kj@eEw)eidzhbighGfnZ}S+9tBb-YSe097D$Zj@)%w?!r-
%W&nm$r`M$BT(#%<q0(7l#K)5wa9dnjU;1akK&?Y5Qm6Y5v8)FpfD*!Ft%bv{pP`WthMH{F*;j^30m)wUx4Bq|S953>LZ77ZC^aC
}m1kjCR?YZVWoi>tL5CT#kM7%&0yhNo2>~o~8cg#eAH&vcZd5CZyS!VMVCos9ITV<8CigwNT@B*kqA5*Njfe_a6DfZL-mosE%~Ux
C2&?V3I&>@@(LXG)-
Xro{neJntiriNbcgwv0G_3@4X6>!Vy2rXfmc1O_ECCsgvNm0MX?XS7m>sktQ+xzRaoct?tGDK34u4^})TD*b0wCUc){mcT&*k|b6
C-C#i5zc=ac%}q?pJKc^(TmV=m!H~iZkL7m0079-
6%3)d*Tbb=0i_q2xEbQpEY@QO9NVBGoiiV$+O9U1)_rK{;h%*m1<UohlyYOjMF*n1w?zF)%3&6NrVLsx09L&0^L-
Dh`f+8{0yzzUpVrt#ij)b_M{FWK8OHKfi&Pmf(BV1?tdCTOMk<27^3k~j6*z3C};ABL9H?M=(aKc!Pr%c4hb;t%744r?w;Q#Qq{G
_CAhH6i0Pb?t7V}I1uC)k8B`S**T`%<Lhl*Zky~eg1UvEXHF|~O_%W_K&8(DA?zH0Yh)gvI+Bsj%#e&;Mq|JZxvfjJ~xE+hD8$c%
&7z~HuDXRi^nsM@>!5UlS)K;UC0!F(+XD*79*dR{P$wjSwu~}$jG>r5tZ{AIc*L@8baY!#Wb)toU*viq)!e1|-1byITven?-
Eq2(s!_O^nGEla!&dd>b?#2Hj<sI9i0>zVR_`)=OO0?_=${c`V1l^)D%^5ar5zX8>6{z(O&AYbAf)>xeIi%{;VGev<81!ndWCfj|
AHX4~<Vat|Q1J}a+MbFwb|~CU_?@5=sQk@h2Iy!^Rf-u`g$-3bC7oaZG$-T@yX3<rcrJ5`dun}zplL^x=0PQq+DEn-
=2l*ggt)0;Fuy_igGNT+&iNRK<o>Q4=jL0|4{wK2SZ(Xsi&**g!?QhS5eiOGBP1(7Oo`$B-Yn_>
'''

MAGIC = b"RSB1"
VERSION = 5
WIRE_PROFILE = "rsb1-v5-public-kernel-1"
CONFORMANCE_PROFILE = "oxbow-conformance-v1"
MANIFEST_PATH = "manifests/MANIFEST.generated.json"
MANIFEST_FORMAT = "oxbow-manifest-v1"
PUBLIC_SECTION = "files"
REQUIRED_ROOT_DOCS = ("READ_FIRST.md", "BUNDLE_LAYOUT.md")
TOUR_ROOT_DOCS = ("START_HERE.md",)

MAX_BUNDLE_BYTES = 256 * 1024 * 1024
MAX_FILES = 10000
MAX_TOTAL_RAW_BYTES = 512 * 1024 * 1024
MAX_FILE_BYTES = 128 * 1024 * 1024
MAX_PATH_BYTES = 4096
MAX_SECTION_NAME_BYTES = 64


class BundleError(ValueError):
    pass


def _rv(data, off, max_value=(1 << 63) - 1):
    n = 0
    shift = 0
    for _ in range(10):
        if off >= len(data):
            raise BundleError("truncated varint")
        b = data[off]
        off += 1
        n |= (b & 127) << shift
        if n > max_value:
            raise BundleError("varint exceeds allowed range")
        if not (b & 128):
            return n, off
        shift += 7
    raise BundleError("varint is too long")


def _take(data, pos, n, what):
    if n < 0 or pos < 0 or pos + n > len(data):
        raise BundleError("truncated %s" % what)
    return data[pos:pos + n], pos + n


def _lzd6_bounded(data, max_output, what):
    dec = lzma.LZMADecompressor(
        format=lzma.FORMAT_RAW,
        filters=[{"id": lzma.FILTER_LZMA2, "preset": 6}],
    )
    out = bytearray()
    feed = data
    try:
        while True:
            remaining = max_output + 1 - len(out)
            if remaining <= 0:
                raise BundleError("%s exceeds decompression limit" % what)
            chunk = dec.decompress(feed, max_length=remaining)
            out.extend(chunk)
            feed = b""
            if len(out) > max_output:
                raise BundleError("%s exceeds decompression limit" % what)
            if dec.eof:
                if dec.unused_data:
                    raise BundleError("%s has trailing compressed data" % what)
                break
            if dec.needs_input:
                raise BundleError("truncated %s compressed stream" % what)
    except lzma.LZMAError as exc:
        raise BundleError("invalid %s compressed stream: %s" % (what, exc))
    return bytes(out)


def _validate_path(path):
    if not isinstance(path, str) or not path:
        raise BundleError("empty or non-text bundle path")
    if "\x00" in path or "\\" in path:
        raise BundleError("unsafe bundle path: %s" % path)
    try:
        pb = path.encode("utf-8", errors="strict")
    except UnicodeEncodeError:
        raise BundleError("bundle path is not valid UTF-8")
    if len(pb) > MAX_PATH_BYTES:
        raise BundleError("bundle path exceeds limit")
    if path.startswith("/") or re.match(r"^[A-Za-z]:", path) or ":" in path:
        raise BundleError("absolute, drive, or colon path is not portable: %s" % path)
    parts = path.split("/")
    if any(part in ("", ".", "..") for part in parts):
        raise BundleError("non-canonical bundle path: %s" % path)
    pp = PurePosixPath(path)
    if pp.is_absolute() or str(pp) != path:
        raise BundleError("non-canonical bundle path: %s" % path)
    return path


def _payload():
    encoded = "".join(_PAYLOAD_B85.split()).encode("ascii")
    if len(encoded) > int(MAX_BUNDLE_BYTES * 1.4) + 1024:
        raise BundleError("embedded base85 payload exceeds input limit")
    try:
        data = base64.b85decode(encoded)
    except Exception as exc:
        raise BundleError("invalid embedded base85 payload: %s" % exc)
    if len(data) > MAX_BUNDLE_BYTES:
        raise BundleError("embedded payload exceeds bundle-byte limit")
    got = hashlib.sha256(data).hexdigest()
    if got != _PAYLOAD_SHA256:
        raise BundleError("embedded payload sha256 does not match wrapper header")
    return data


def _decode_offsets(raw, count):
    pos = 0
    arr = []
    cumulative = 0
    for _ in range(count + 1):
        delta, pos = _rv(raw, pos, MAX_TOTAL_RAW_BYTES)
        cumulative += delta
        if cumulative > MAX_TOTAL_RAW_BYTES:
            raise BundleError("offset table exceeds raw-byte limit")
        arr.append(cumulative)
    if pos != len(raw) or not arr or arr[0] != 0:
        raise BundleError("invalid offset table")
    for a, b in zip(arr, arr[1:]):
        if b < a or b - a > MAX_FILE_BYTES:
            raise BundleError("invalid or over-limit file offset")
    return arr


def _decode_paths(raw, count):
    pos = 0
    rows = []
    seen = set()
    for _ in range(count):
        if pos >= len(raw):
            raise BundleError("truncated path table")
        pool = raw[pos]
        pos += 1
        if pool != 1:
            raise BundleError("public wrapper permits only local binary pool")
        ln, pos = _rv(raw, pos, MAX_PATH_BYTES)
        pb, pos = _take(raw, pos, ln, "path")
        try:
            path = pb.decode("utf-8", errors="strict")
        except UnicodeDecodeError:
            raise BundleError("bundle path is not valid UTF-8")
        _validate_path(path)
        if path in seen:
            raise BundleError("duplicate bundle path: %s" % path)
        seen.add(path)
        idx, pos = _rv(raw, pos, max(0, MAX_FILES - 1))
        rows.append((path, idx))
    if pos != len(raw):
        raise BundleError("path table has trailing bytes")
    return rows


def _parse(data):
    if len(data) > MAX_BUNDLE_BYTES:
        raise BundleError("payload exceeds bundle-byte limit")
    if len(data) < 5 or data[:4] != MAGIC or data[4] != VERSION:
        raise BundleError("not an RSB1 v5 payload")
    pos = 5
    for i in range(3):
        n, pos = _rv(data, pos, MAX_FILES)
        olen, pos = _rv(data, pos, MAX_BUNDLE_BYTES)
        _, pos = _take(data, pos, olen, "global offset stream")
        clen, pos = _rv(data, pos, MAX_BUNDLE_BYTES)
        _, pos = _take(data, pos, clen, "global codec stream")
        if n != 0 or olen != 0 or clen != 0:
            raise BundleError("unsupported legacy/global pool %d" % i)

    nsec, pos = _rv(data, pos, 2)
    if nsec != 1:
        raise BundleError("public wrapper requires exactly one section")
    name_len, pos = _rv(data, pos, MAX_SECTION_NAME_BYTES)
    name_b, pos = _take(data, pos, name_len, "section name")
    try:
        name = name_b.decode("utf-8", errors="strict")
    except UnicodeDecodeError:
        raise BundleError("section name is not valid UTF-8")
    if name != PUBLIC_SECTION:
        raise BundleError("unsupported section %r" % name)

    nt, pos = _rv(data, pos, MAX_FILES)
    nb, pos = _rv(data, pos, MAX_FILES)
    ng, pos = _rv(data, pos, MAX_FILES)
    np_, pos = _rv(data, pos, MAX_FILES)
    if nt != 0 or ng != 0 or nb != np_:
        raise BundleError("public wrapper permits one binary record per path only")

    plen, pos = _rv(data, pos, MAX_BUNDLE_BYTES)
    pcode, pos = _take(data, pos, plen, "path table codec")
    max_path_table = min(MAX_TOTAL_RAW_BYTES, max(1, np_) * (MAX_PATH_BYTES + 32))
    praw = _lzd6_bounded(pcode, max_path_table, "path table")
    rows = _decode_paths(praw, np_)

    if nb:
        olen, pos = _rv(data, pos, MAX_BUNDLE_BYTES)
        ocode, pos = _take(data, pos, olen, "offset table codec")
        oraw = _lzd6_bounded(ocode, min(MAX_TOTAL_RAW_BYTES, (nb + 1) * 10), "offset table")
        offsets = _decode_offsets(oraw, nb)
        clen, pos = _rv(data, pos, MAX_BUNDLE_BYTES)
        ccode, pos = _take(data, pos, clen, "file data codec")
        concat = _lzd6_bounded(ccode, MAX_TOTAL_RAW_BYTES, "file data")
    else:
        offsets = [0]
        concat = b""

    if pos != len(data):
        raise BundleError("payload has trailing bytes")
    if offsets[-1] != len(concat):
        raise BundleError("offset table does not reconcile with decoded bytes")
    indexes = [idx for _, idx in rows]
    if sorted(indexes) != list(range(nb)):
        raise BundleError("binary indexes are not an exact 0..N-1 permutation")

    files = []
    for path, idx in rows:
        files.append((path, concat[offsets[idx]:offsets[idx + 1]]))
    return files


def _manifest_records(doc):
    errors = []
    out = []
    if not isinstance(doc, dict):
        return out, ["manifest root is not an object"]
    records = doc.get("files")
    seen = set()
    if not isinstance(records, list):
        return out, ["manifest files is not a list"]
    for i, rec in enumerate(records):
        if not isinstance(rec, dict):
            errors.append("manifest record %d is not an object" % i)
            continue
        path = rec.get("path")
        size = rec.get("bytes")
        sha = rec.get("sha256")
        if not isinstance(path, str) or not isinstance(sha, str):
            errors.append("manifest record %d lacks path/sha256" % i)
            continue
        if not re.fullmatch(r"[0-9a-fA-F]{64}", sha):
            errors.append("manifest record %d has invalid sha256" % i)
            continue
        if size is not None and (not isinstance(size, int) or size < 0):
            errors.append("manifest record %d has invalid bytes" % i)
            continue
        if path in seen:
            errors.append("duplicate manifest path: %s" % path)
            continue
        seen.add(path)
        out.append((path, size, sha.lower()))
    return out, errors


def _verify_integrity(files):
    mapping = dict(files)
    if MANIFEST_PATH not in mapping:
        return {"ok": False, "error": "manifest missing", "checked": 0}
    try:
        doc = json.loads(mapping[MANIFEST_PATH].decode("utf-8"))
    except Exception as exc:
        return {"ok": False, "error": "manifest unreadable: %s" % exc, "checked": 0}
    records, errors = _manifest_records(doc)
    if doc.get("format") != MANIFEST_FORMAT:
        errors.append("manifest format must be %s" % MANIFEST_FORMAT)
    expected = {}
    for path, size, sha in records:
        try:
            _validate_path(path)
        except BundleError as exc:
            errors.append("unsafe manifest path %s: %s" % (path, exc))
            continue
        if path == MANIFEST_PATH:
            errors.append("manifest must not list itself")
            continue
        expected[path] = (size, sha)
    actual = dict((p, b) for p, b in files if p != MANIFEST_PATH)
    missing = sorted(set(expected) - set(actual))
    unexpected = sorted(set(actual) - set(expected))
    mismatched = []
    checked = 0
    for path in sorted(set(expected) & set(actual)):
        size, sha = expected[path]
        blob = actual[path]
        bad = []
        if size is not None and len(blob) != size:
            bad.append("bytes")
        if hashlib.sha256(blob).hexdigest() != sha:
            bad.append("sha256")
        if bad:
            mismatched.append({"path": path, "fields": bad})
        checked += 1
    ok = not errors and not missing and not unexpected and not mismatched
    return {
        "ok": ok,
        "checked": checked,
        "expected": len(expected),
        "actual": len(actual),
        "missing": missing,
        "unexpected": unexpected,
        "mismatched": mismatched,
        "manifest_errors": errors,
    }


def _tour_tracks(mapping):
    tracks = {}
    for path in mapping:
        if path.startswith("tours/") and path.endswith(".md") and "/" not in path[len("tours/"):]:
            tracks[path[len("tours/"):-3].lower()] = path
        elif "/" not in path and path.startswith("TOUR") and path.endswith(".md"):
            name = path[:-3].replace("TOUR", "").strip("_- ").lower() or "default"
            tracks[name] = path
    if "default" not in tracks:
        for path in ("START_HERE.md", "READ_FIRST.md", "BUNDLE_LAYOUT.md"):
            if path in mapping:
                tracks["default"] = path
                break
    return tracks


def _verify_conformance(files):
    paths = set(p for p, _ in files)
    missing = [p for p in REQUIRED_ROOT_DOCS if p not in paths]
    tours = _tour_tracks(dict(files))
    if not tours:
        missing.append("START_HERE.md or a tour surface")
    return {
        "ok": not missing,
        "profile": CONFORMANCE_PROFILE,
        "required_root_docs": list(REQUIRED_ROOT_DOCS),
        "tour_surfaces": sorted(tours.values()),
        "missing": missing,
    }


def _verify():
    data = _payload()
    wrapper = {
        "ok": hashlib.sha256(data).hexdigest() == _PAYLOAD_SHA256,
        "payload_sha256": hashlib.sha256(data).hexdigest(),
        "note": "internal consistency only; this does not authenticate an author",
    }
    try:
        files = _parse(data)
    except BundleError as exc:
        return {
            "ok": False,
            "wrapper": wrapper,
            "wire": {"ok": False, "profile": WIRE_PROFILE, "error": str(exc)},
            "integrity": {"ok": False, "why": "wire parse failed"},
            "conformance": {"ok": False, "why": "wire parse failed"},
        }
    raw = sum(len(b) for _, b in files)
    wire = {
        "ok": True,
        "magic": "RSB1",
        "version": VERSION,
        "profile": WIRE_PROFILE,
        "payload_bytes": len(data),
        "files": len(files),
        "raw_bytes": raw,
    }
    integrity = _verify_integrity(files)
    conformance = _verify_conformance(files)
    meta_ok = len(files) == _FILES and raw == _RAW_BYTES and len(data) == _PACKED_BYTES
    wrapper["metadata_matches_payload"] = meta_ok
    wrapper["ok"] = bool(wrapper["ok"] and meta_ok)
    return {
        "ok": bool(wrapper["ok"] and wire["ok"] and integrity["ok"] and conformance["ok"]),
        "wrapper": wrapper,
        "wire": wire,
        "integrity": integrity,
        "conformance": conformance,
    }


def _prepare_dest(dest):
    dest = Path(dest)
    if dest.exists():
        if dest.is_symlink():
            raise BundleError("extraction destination may not be a symlink")
        if not dest.is_dir():
            raise BundleError("extraction destination exists and is not a directory")
        try:
            next(dest.iterdir())
        except StopIteration:
            pass
        else:
            raise BundleError("extraction destination must be new or empty")
    else:
        dest.mkdir(parents=True)
    return dest.resolve()


def _extract(files, dest):
    root = _prepare_dest(dest)
    count = 0
    total = 0
    for path, blob in files:
        _validate_path(path)
        target = root.joinpath(*PurePosixPath(path).parts)
        target.parent.mkdir(parents=True, exist_ok=True)
        parent = target.parent.resolve()
        if root != parent and root not in parent.parents:
            raise BundleError("extraction path escaped destination: %s" % path)
        if target.exists() or target.is_symlink():
            raise BundleError("refusing to overwrite extraction path: %s" % path)
        target.write_bytes(blob)
        count += 1
        total += len(blob)
    return count, total


def _info(files, data):
    mapping = dict(files)
    tracks = _tour_tracks(mapping)
    return {
        "name": _BUNDLE_NAME,
        "wrapper": "oxbow-self-extracting-v1",
        "magic": "RSB1",
        "version": VERSION,
        "wire_profile": WIRE_PROFILE,
        "payload_bytes": len(data),
        "files": len(files),
        "raw_bytes": sum(len(b) for _, b in files),
        "doors": [p for p in ("READ_FIRST.md", "START_HERE.md", "BUNDLE_LAYOUT.md") if p in mapping],
        "tour_tracks": sorted(tracks),
        "payload_sha256": hashlib.sha256(data).hexdigest(),
    }


def _orientation(files, data):
    info = _info(files, data)
    print("%s  (Oxbow bundle, self-extracting)" % info["name"])
    print("  %s files, %s bytes raw, %s packed" % (
        format(info["files"], ","), format(info["raw_bytes"], ","), format(info["payload_bytes"], ",")))
    print("  doors: %s" % (", ".join(info["doors"]) or "none"))
    print("  tours: %s" % (", ".join(info["tour_tracks"]) or "none"))
    print()
    print("  --read-first        print the front door")
    print("  --tour [TRACK]      print a guided tour/start surface")
    print("  --verify            verify wrapper, wire, manifest, and handoff conformance")
    print("  --list / --ls       list bundled paths")
    print("  --doc / --cat PATH  print one document as text")
    print("  --extract DIR       unpack everything into a new/empty directory")
    print("  --payload-out PATH  write the inert .oxb data twin")
    print("  --info              machine-readable summary")
    print()
    print("Security note: this file is executable Python. For an untrusted wrapper,")
    print("inspect it with a trusted Oxbow CLI instead of executing it.")


def main(argv=None):
    ap = argparse.ArgumentParser(description="Oxbow self-extracting handoff bundle")
    ap.add_argument("--info", action="store_true")
    ap.add_argument("--verify", action="store_true")
    ap.add_argument("--extract", metavar="DIR")
    ap.add_argument("--read-first", action="store_true")
    ap.add_argument("--doc", metavar="PATH")
    ap.add_argument("--cat", metavar="PATH")
    ap.add_argument("--list", action="store_true")
    ap.add_argument("--ls", action="store_true")
    ap.add_argument("--tour", nargs="?", const="default", metavar="TRACK")
    ap.add_argument("--payload-out", metavar="PATH")
    a = ap.parse_args(argv)
    try:
        data = _payload()
        if a.verify:
            result = _verify()
            print(json.dumps(result, indent=2, sort_keys=True))
            return 0 if result.get("ok") else 1
        files = _parse(data)
        mapping = dict(files)
        if a.info:
            print(json.dumps(_info(files, data), indent=2, sort_keys=True))
            return 0
        if a.list or a.ls:
            for path in sorted(mapping):
                print(path)
            return 0
        if a.read_first:
            path = "READ_FIRST.md"
            if path not in mapping:
                print("READ_FIRST.md not found in bundle", file=sys.stderr)
                return 1
            sys.stdout.write(mapping[path].decode("utf-8", errors="replace"))
            return 0
        doc_path = a.doc or a.cat
        if doc_path:
            _validate_path(doc_path)
            if doc_path not in mapping:
                print("%s not found in bundle" % doc_path, file=sys.stderr)
                return 1
            sys.stdout.write(mapping[doc_path].decode("utf-8", errors="replace"))
            return 0
        if a.tour is not None:
            tracks = _tour_tracks(mapping)
            if not tracks:
                print("This bundle ships no tour/start surface.", file=sys.stderr)
                return 1
            track = (a.tour or "default").lower()
            if track not in tracks:
                print("no track '%s'. tracks: %s" % (track, ", ".join(sorted(tracks))), file=sys.stderr)
                return 1
            sys.stdout.write(mapping[tracks[track]].decode("utf-8", errors="replace"))
            return 0
        if a.extract:
            integrity = _verify_integrity(files)
            if not integrity["ok"]:
                print(json.dumps({"ok": False, "integrity": integrity}, indent=2, sort_keys=True), file=sys.stderr)
                return 1
            count, total = _extract(files, a.extract)
            print("extracted %d files, %d bytes -> %s" % (count, total, a.extract))
            return 0
        if a.payload_out:
            p = Path(a.payload_out)
            if p.exists():
                raise BundleError("payload output already exists: %s" % p)
            p.write_bytes(data)
            print("wrote inert payload -> %s" % p)
            return 0
        _orientation(files, data)
        return 0
    except (BundleError, OSError) as exc:
        print("error: %s" % exc, file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
