#!/usr/bin/env python3
# Generated by Oxbow. This is executable Python containing an inert Oxbow payload.
# For untrusted wrappers, prefer a trusted `oxbow bundle verify FILE.oxb.py`
# rather than executing the wrapper directly.
"""Standalone runtime embedded in generated .oxb.py handoff files.

This module intentionally depends only on the Python standard library. The
payload is data; this runtime provides bounded parsing, integrity verification,
orientation, document access, tours, and safe extraction for the locked public
Oxbow wire profile.
"""
from __future__ import print_function

import argparse
import base64
import hashlib
import json
import lzma
import os
import re
import sys
from pathlib import Path, PurePosixPath

_BUNDLE_NAME = 'oxbow-standard'
_FILES = 54
_RAW_BYTES = 233265
_PACKED_BYTES = 55797
_PAYLOAD_SHA256 = '17f91e0c71f75a1d448aa7052d78d9dd21f4ae4036cb63dd09830af50d81ea8c'
_PAYLOAD_B85 = '''
Qd2@P1poj50000000036W@&6?a{x8~Hp~U!23i8dT>t=tjp%3#&?<Y_*@`hDl?%IW<3gY#Sq;A>GYVc$uWCSEqBbbhc;AZV)#GI}
M@#^OVbkGnzve({lm+Qyt%KOI!^pU^?eSD$qj>{?I%%@-
1d?#GjP|_O5n~Wh)BCJF$0z+hBvbHXrm2bBmDSI6Ep~!8EF_&eV+e$_L=ld!T6fjPGKO6bPQuuFj9F?^DrA=dj!qbrA9%={G!}f;
Uj+ogYyT##JNnO$63fY(5u~Lx%Hy1PUdrUKRnDE$;2^CUE<xyF>c__?p8r!qo#%L9-
waQ}jvb;eQ_R)%lw*j@{LZU)1NJW!6b+J_r~abpbc~_^X$~S8ZZVS_0jBI~ok<fK+w)3LYT%~Zn=o(w7bM3mZka7SDH;wQ+{)DWJ
kw5}iIva8lwBv>BC+sgXf+w~bb{mv|G2U{<Td)b%%GikfarjL%Q~q>`X;te+4-^rhE}4}3rjbi4vkiy51i8a0y-
QOB9}k!^Y}|STiYZLt}t)Xo#MG^>Ruk}sumisFAHRkuW|PN?gDXM7>ItwsoN^geLg#br9fXCn#B5#tnTE+PFRgxLG|@rCk0YR*p4
{4`&E}HnKJ+E-&$w6bveW1<eObAgZmD%{gj<hd>Asg8~m9FOv-)G)Tfh0uZ|E72l-
R|34aV4b1^2RLzEQ4oC|zi)a3)qF0r{BcF3_z4<djSuyZCDe5onZe)i<8Be?=sR}2R3NW<;0F#4uI7UyZ@!39F_+m!TLWzYia6y6
2G{rxZ`F)23hAQ~;t))NbWKsJEzdgT|t3*;FgO=Mm?mxJIUf4NozyVl`GSz@?WDer_uUZdVH>7mDcLU^0xm+l~;J`aMs6<V|hMR(
o%7G(@x%3xGT7-
?YbhvE=M575w@+24Pr3X;I0I($2S+!)goS^NnOxORYHFD?!W0)PN;0RU?N+6a~}h8C{~x&yrknnAw>@D<?&;|ur{$sV>C>LRQL_z
8#yrUZG80*3<k0mTB50qO(j3da(@1>8f}2dG6+l@cSAiUG$Mz9X{R0iZ19DZd?+paJ9)^E{m<$t1^F0G)r!3z0RQIDkw5nymxlk1
*DfT>ue?2FJn(_^3}%5m!(YreT<RI-JHHKxj?O3qN+}-
!W+IGUb;^DFQenDZHsph3X&2i#AyC!<;+D7*s*$9qcCF(B;D$FyxNDFTNRn{6&*90kpmJX6M?i?JciIYuAK2n=}D59a8M4HdkKLu
s}9jixn<wQ<%vQ?`5^=OYPcV5n{{2Necf=1@koK=|6D9(5t8wiI|tJ$Xjn5fg6v?1xG|#;l7qfRIW-W-#GVb>AfKcd7if-a>-
S6!#D7CrOb*PGy-cbDLJHd^s!h2@G2WxA_pbBETFx{Oe?qV7zWrkzhN9tj%ddriTyPXu|&#FUOUy~p${_!kSR>OjX?EOJPpu9%N*
JC+Za=LN_vMmI_r!KWyWgSSUZ_zPc;mjh_xj>EPNJ*+5fCkxG6zJh$x7}dh+RQ6Zp2(z(ANwR{7#OBZvdc8+^0z9-q7Q-
!GmhgDfwAoa@!;G|P?#Tb3Lf`IhPbzfuqKgN427a2(L%>=s|YxnPiZw`_<*9lEmC7PJ@WtSao9olm*wZ_1uGbcO9j{_LSto4EO2@
{FJ!stC^_K5lE|z*;_7@>m+2F0{;j9>`J-Y`6CFdPg%?=1qx;n-
?7%zqc%O`9f*V{|`Eu4&pEmz2E6@D_M*2v15I_w7`0C^YETRlfb=tXeH>?qU&KhCtvW5oZJa`V29^ib2Z}_ROv0(y<}iRk6<!e4B
#t-
0)C3psd6B&)A$AwuZaeay$OI1YG&jct0|i{#g(jrBfuZ`C!!F}q}Us&1_dlUbmE!mT>nO!L{Aa3TLe^B*_<69&ftZ*)|rsPF(o~H
+3-
OBvSz#1ys0d=kwBEWTI*NtNCx0V5n_!ho=CG5(`mA?8v$0#wyw_Vs?<h*Kdw>!he`TFmUKtQ$##CtXDv;BKVRw*r`NghV3~6jBZ*
jFs#9?o)n=9KZtIWV_HrWR_%W4<8V1TNaSIow$(i2mL3Rq$XLwI3DyFE;6Vk7j=<Zz+X$!5FWCnJ-
!{#<4bB12cdJ=}x`&6AVGr2)+uYiL3#2~R{j9qjSJp*&0V`lru5%?nphz82EGF55ZpFAx`g{gc+sDcMXgQBH&hLxo!&i6WW7c?qj
-na_4ja>tfWEq`O@Z|M;*T8IrFjhT5Bo<uTp6A{nCYA8vLRG|}K+$d{1tiAJ0sr(K@}ws$&#UhE@XpN-
4#bFh6{K=9P&n%3{PVIGAoxR#LZdS+xsm<-
gnrx;{P<A2nwjmeGI|a2@EpZjuC=DZqD%zf09POZ^NFPi<#tdo;ALhYc(a!Lx;*kt+C=`Mw&ppfu*a0bupNwDC13to+f>_ZA-
>eA)deWL+|U2XH3B}X6o?ykj!Z!b^<7_cS;2Br&&U6QKvH$|X-
|pUs2_V2zqRSxs%bPqC^dw%vEs=#A#t^)D0ABTtlN%fiJ5jy9WTuegci(LxJ`p>5Ef7Qq_Yvjdot?UcP&ovh1bS-
8w_mdji!bX>Q@uL2+K6$(NPdlGi^q1pyK-{Ku$*(p8i&dy^y^F#En-Ov;B&F%l>((mjfz7#Wz`cyogo0QRgm1;Z*#F*S?Er`KbJt
9%edM%f0li^@GPQCBLaxz}%Bj<xFvaMr8!Clu6%V<&=w;LAwJNUgJhNo5i8y2+_5L5C-
sC5zYPrR3FYdf7%3w4n~q7=wDm9wB2>7#YCWVNcknr@&}R4-
vuO3YE72tR?rF5_iuU^=VK|qhFu>{BdWg7>0q1=#tV;bO`&W{Y^`4N%;2R^Oi$0ef-
KOtP%rn_ca?#3dt<-j6e~|rfgn`*2%;M+t^Ko_W!qI{t$P8RidL-TUJIDA%R9|^4hkSA++DY?tx6ObJ+tyNEFeyygT-
`$Re<o3_57)2&P=cLxz?#ppH@`0<rZD}zEq1@LjcGS^nA-
6g+}W)gO}ppXX;8HX0O4F%{_<0mqm%6N2Qq&`{oo(ux`^fz3&2mzUrq=opy*d5S*nW)~g$dWaIc}Q@$m1kJ#p{Pqh!ZfZ=v&;Uk0
0<sg(u7w*)$vdxAeZEx2A{T8XCdb41Mz6-1NsQzFc@myiIMJhZQ-
c2fzQ)+nurRNpB8NdE$9Uyza9FpG*M6uQ7zNypT>q`Bo$}q_MRwk*C%My4Jq=Oh0&$GQC5GmDNdH7naQwiNsz6t2porskvmE5u<q
3K$ibZ-uQ92T_B#Ju|`_1gxdghUqWEg~8!o>sTX)wKt;I0?lXEezq>nPN_Lb`b8As8qW6%y_q?_7F0d#Jbz4gAbVJlBxax`*=E{B
S<GdKQSh`LDg~L-
s^CJfEZ1@*t#L6eqGICs3^j998CK=4#6X!hC<23ze6bZ2&#!{OV&6&_c!>;YSHRAWZFVMuboJ36J)aBS%kyrtZF>E)6NjC?pl`>o
AKK>cu)NsFpFMCnB{4LXp&~zG~dAHBM5#;2vniPxIm?_y`zPV9Mr>37Cn;3oo^_-pWVYD!Azch{{7u^pA8Va2~qI*Q6zwld`$?7-
99k;|91;f6m~s5dzsH4JS)b1yxjpVcw$LEpyy-ZsO;zon(yyWP*f(Fsk?@X17D=Ce!${JPw#18Iz?wPE<84+oXkjckOuvsPGxdz!
E0Hy0j^fTP!E5mh+zA@)f@XlfaO1Uma;p<7b%fUEHynwbHc)2m{(~$9Ay)L-
_ASOPt;WaD+scDPiLGRbD1anaEbk@2kzrCs9kJ;g|w)O^HYgR<R4}-
lC|P^39syIpt@NcQ<6*wj>Te4g3QC3T;C3Hs)`(~x;r}DC<t#nv%G@X@6ObV1L<Lu=)s|CkNLd9H%}w=5CE|@*wR}_ik#TXsJ`6~
35^?Ywi{tR>xQ3}%1NSpi=L}=4du`tY_A&5R`Kg^c7HcE!eZ~8>zYzcb`r-
qRLR9jAS^{Tb)Mm<8C~4=!Ph_L(^oU{9qkPS8TiyN%FO=czq-dT>x2&=r=XIGGLny~#56<C20SQCdsTaWsE{piweiGboD03+PLjK
UHWtpwQGAyzk7F>RUd&V5EEw{G-
wpmpmMGk+hO)7%aj<Am!$%a8{|(4?oo7~{7`U>D!j0VsAUESZjwLcDp7GTc4g0VV0z;X8)kx{inVB0cjzKbG&SGx?Ju75ZGu0Z#N
Fh$wtp5lKC!IYU^7n<W4aNe%-
fFql+gYlw7EaKc{SZ+0{T$Gt8>MINcq$2kz`Z^&YyQ|M)DvP3a6RJ0Ece@r{2{+Vq26}ukkd?Pj6Oz;R_8g&YTEG)-
fWoNjMwus0mw_uA>Hx8KaFmzb4zP~g+th`_FHF>ow2t+AX<7Aah=e~uq_zPqDGf_w_>3fR*GtR8;0ckk8UA+J?J&Rr@qtv;bn1J6
Ta2-qCi025@v}cS>^5!ndKPRapaHVvP#910G#{$&-?B6u;n(ko#;EUL2PBzm~y#n*uZBCyB=Mb7x21snVJ3=K9DNEa-
r@bXu|omsNDr<2mD`mGYH8@ti<^V&+6Pnsi2=;jd@}kIIq5kL2oOQ{Bd9RKUG9b_JXVVVZ}*R^`#EfpyQxYl<%X^_^28@%ZbbC8=
$XB53&H$LS;{vL3tUnjk(Og5PC`rwQUuT*foM-#v*s9w~zEVMv|HtXpsb<2gc-5AAdxj)(AABOj6hFu@XzHjM-
`~Y?M6@wlT&4L<#@jt|D0aV0n5dcrhJ?ogruV4Z94Ja*YC{qvHv~qV?Y5zTFvrIha)H(L4HyCW>wuTBs~XIXS)=6DL@^;5z8Ja{8
VdJ00oWfL9gNz>6HH75`bMhu_uw^{9v-U1W&fe|PPalfpS~QFSo$8zE>itC<v-N&Kon$2r5-
5@}_TDhZr!$OwdNQ9(Qq*unxhw^`}5Ceg#fgEo+bVmVudymU*(W}DSmrUpn_BEW-
;wVQ(M;5iytY3)b+=*{)ABzEGLJgZu66pUMT7tMAQK2sk3%09zdD&rmro-7!fa51Ay%USUoA1-
1@Q~Q0W$$UjZVLD~MAH(4BAps)AxonUo*%~Qlsq|!`zz$cQ9;UH70YzW~8aZGBquNSraL#HL6SFK!iz7uMMXQvfTMq+3;$B9#00E
52p^WqOC=yF{yrGQdSO?7ZFcx4j=7@8Srd4akD|k&EC}k#5Z}(ylq&sj&W{$YP#9<t)VtZZ1C94anhsX@*pmw%DsqKACijR`DuGV
HoUa#rG0%qv{?-smBGS&9P%e=&A{w-
yYOAdDi&c3gdh|x89N@N)hgkrq$MHQpy|EYXt=xh}w{u`^38)t}e9W>KxAqMSlfHe(bMWnf&CG?gR?P{ao&q@)YMKQk^rV4-
|g);DgW7u-eAF%-Y@5pDXDArI1mM|aRQul1(*E-
?1DfSO`@@DDzzoLot?1$;9W3t%1Wx=xn<We@>zt*NUA2H5wv(@1%<}%$RCb2;rELYV^Or8J+<&;yAC*$?@j7Io<oIT;P0k4fdW)<
E;TsgVyjQ&X0Jfg~^{su!@CVlIi3Vqly@%hCl@piUUwr_0j+CDnu$b6(zK|5Rsf~CmN<xOq9;z-
#X@%ZY9mSaW=qCK4Gpu1JOK#uP@t(3VrW%bD~g-O|xD*97$t$usOS~8f@soDs;3U;s+^BXcwr}}o3M-
_L=cywagG;U^~la@_=_RUyWrXQ0_ebDM1D~1{Thp~);n*6NsR0Z4xPfY;*<ij3PuV(h{$4-@Hq5}vq1wn}fit1O#F(U<b4;`^%B-
WmxA%~_o+}~K8lPcxK!JAu9q=3*(VPH4^CV-s9<TP7XsY4f~XnRe;yN;CV&$mEGMQ~nZ4T%+~D|c_Rt%6)mP*nMV&%-
ljpj?|i)HtO(^H<D&SYLI+uO|G?a`!}pc`r>dk`xlWxDKj#>`4fzlH;sm6!~r?V+85H+iC4XXqn)FWy_CxEz**Kvxws2^waov)zT
zhOhH!$4N0q;_Or;LkA<<k^00Z^#n(JT`-vSrFDjYGN@Yx35a1WvjV+tWH&c7nTU+%nuQD^4$-
QjAtPdNV!MS)<USyDI9dj3}#q~SD&kYV4+$h$b$ZYC;p=%m3k%<iuN`hlTLX$gCb2XzO)FRjk$s5$nTOQO-ff~h9BY^h&ASS%eh7
n*37OV8Yae~~@tjX<=A-
EmBav|Mon7QDvO;C1W>dUJjk7x%QGB>FT<|rY{^~2?5t4^fAZLl=_8};dLA&1fm1R!>)_phukY7ln7m58+(WCglebTy9DV8kx+PD
ZY+3cnIj5|R-Qo%CU>)5dmZ?NOm0nWr$$Yy@od?h8w*4^c>Av{Lu3w^&d_W{B-
b|EgB1Oh9a)F=n3>ZCa@OX%8XdxDY%9hSL4kR#mK&hE=*6!7+`mU+J|FP&#Pg*?~Y&$iKL)ZOWsG!16K;=t?_F$3wS)Gd-xOqVux
nPcX;$_6ff!y9fPuFsHKwfeS3a#^Z`30oFK;@}z2ltEqC|idH5zyq0yoO<0MAD7UUv=ht0bva+hdZ)I0tAu7@Vo8Uy~)lO&>EZs}
9Yc|+cGpD@BY>VvWD%YbN{7C2ncs0ES_{p7$J(bvS4?{@CnGnuuN@_L>J0VLnXk1;w)l|sq)u@;hITG0O9(LDP2C>O~6&&l$fZPD
;vDRD)iF^DoSj1T?lI5)#d|VmXet;SYP{kf3F*ZvE*5+%JQO>-
L7|xBI^}p2fm(g|wlZZbv2>4r)XkKs{_QFd_=LrbgQ7+=!n0XIEx&wG`T#mF5`5Pk*C`dazx>F+kR`ArBh){AOk2Ewqdc1HkCwI9
XVY*s8_@5u@Ek;gIRsTx1e`3Sk-b{lS`P%_qLsoa~armxOhQL*-i8wK+j9>%-UHNFz<-1v2*8uV&I>=-0yn<O>1Kv&K-
Qs1izt#c@2@MXsc@Q@EDedw4QK-iq)07sK$yI0l$BcdLhUi)ewg^fDk0_sWt6|K+<s2lx!&%i5afL<A3NzoIn+u}$;>8EX;jhjOa
6JT>HMs;3TTFGn9tce>U-bG)BIaEMTpC22GT2I!wN%8ktqB2)X6jK<1deVXZ_rebT_!zGS*lRIM(@1m!qZ6)-
!=CWzLao9EXQj){t~?mqN1dTvSg1EL@S?0R35Pt?N-6zziQm6Y!O*ecHt#G0Yn$piuapH7W<>eW55LBb#Pv(H3v%<V(R-h&m>-
&u^Z=u(@NkRaC(^usF|l8?V|bZ!4ZR6o)TIW)l6~tL1&z=-
sFgkniJeaT~`Y7bUC*1Q@J}2CX;$Lx@60&HMYlyp1*^eLtu%7?O)0i&)OaigLleui@q7O{Jyq+p(`q3!5OSt`Uro}1V4mXZw#(jX
P#hwuLW@!S9&PSB|gX768(|5oHSF;9&7&Cfh8ar&D^%#)_@yaoGLaF-
R+66#3chh(xzFHGo;4Tc;h*)@|^=e;!vwac1sy^PDV~>KhWH)?q#w5k!e(ygau(kzNx>>@g>*o*Ktx)rk_$at()7l?H2FpuYHfRk
7&o6@48>@J45UKdZtKPi_8iOizsmO7h$Q~6B`u4qH`sxy<ozD)}}dI$b+efY8bUf;ds1ydK5%#6BR~OD-
q9oZ%_7(>UF=FnExKdl%b5#6aOHmc`t!A!7Z?{TC`LkuFiJ#XJ;#%4?;p}*W(o9?8ld0g(O^A4rP2_7I|u0_^q(0-
&h^#UMmalmU{IC%#{4~2JC|A=GI6A39AsOjg+pkWc;$O^Q(36LSg|e_!;}G+b5hG=gFUn+Chqt8>0#(q6|WOm!zlvdQ1e(@7>L0f
Q2t#oae#8Nd0(*uPF+Jd=Ty*sm93EGNBL1>LOgYne+?<f_H#IYz<@)#+k?1ju_Gre*xg*=?T0H9Ai3+mZQUR+8zUjBEOG9TowxOt
=3yWaeQ4^@}O(LC(=!%O%ZuG!mD2?;$Y44KhI(hwPHkxwZxhxqQg2B`LWeH!y5RXUX9R+PYMlc$+E+>q``5%Bgx(=1DqVQ6b%O5F
hm}L@;c_ywc>~V6xbRN$0!Sqc*&{jE<-Zzf>MPXzNKqIrF_?zD0L37(7_kLn*`7w{uMVq@I;AUghS&-
lI2Aq{?;(9#;>Y9HU0$xaul!VB{iMR#V(mzFNg0=7aee0!y$kiSnN>)=;e#netEsGF9N+6%Bd5!!2Zx?EUbX&_=p3Ec3|^bb}2em
k6jwm_6s18XlXJ4KGWYwEN3qVM8NuC&lQKFpD=)!tt)Lgs$SdmU?LZ|tQ!<dJQOhs=L{;-
{)rWlawH)L`xEl^gZuy_QM!(EzRt|lrIHHOq9R`2vOBKiTf9uX9rjdk(2XI|lo>8wB+`Rz?(va=!8E9VSj&u68hN#;m*J0h;r5}-
MO)>V!0KjjPb&%};ZNVIoD<E%hzIjd(Jxa+Q_G;Z0uqqHAQ7Co`(&!va>OH*mAd}yC7B(Jp2)_1I#e7Q6UauBXAI*aBT_|rgZL9x
;c&~-t*!1#%RCVTe%;hD9+~+P^&g5&%%?70eJq$OL}h)NfUT&~Y!pO}yq3|l5vZhQB=I&};h`H`|M-
xDV!@z(rBU%J3?{eNf|VUekV@G&Y<U-xrW$eiKvetfdSh8QY2U9pbz$-v%ZvXitgd>dKjwK=oi-
u!!V{{2PTq_Pbeuebvp=Ip%&P(MGcw2K{PrcS1w^|`vbw~F%hY|_&~}L2PvN)VP(gWS4VykJm&+$hrcDWslgFTF($OtMPJQZF!=?
h6A!(|qIa{#b=jiXQz9=vj9^Yc=6^}^>ZB+Be&(3NI>gO=wr@r{|96B|nF;pMjO<+xD`j2Qlj|8mpZ09QSkStcZ0@hH(ONK$?Efm
Vz)0+uOsREO`_%);GYIp)LPlFvpA?d2#XeGW#xxQj$2o4#EMM*X>Kw-gPCD{^Uy`e+9MU6D?>e#1yvz?SSi6Z1S#1IaFj4lHQY9A
Lkufi?iV_BU0;PFnD4($$%@(xc#yaja{zw*F*2q*nH_A=MC5d<ZX>3B!6e6ts?JYj+y+|?UGNjCqxt0=tI4l;p=kR8h&hr*>Q%(9
@?`cd>=dR&~%iAVM1rcB<q95_GwS-8j08rH>{l5u_--K5S+4K4fJy>cl^k1+azHjS_m|C~R38Ey9~6&UI+cd&z5_IeE`v6Lhv{71
b#nW<8rpJNQ{r9E{<nS4NX9tnsBT=MIHBs5NWdrPtZOJ^GyrB(ZMz9XGVf(4&{9YrCWJ#$%JhKyOt)OlJ2Fc(|oWIH9rh~}JB2Wx
Ik2InlFU!zDKJ@nOoH+Z1pv@yh-jo;cnP{QiGj1d`vm-i%a7P|1C$=8uzm-hQ+Sys`Cycg&dlDf-aYDkI9G4yGhR`{|laJ)paW`e
|VC@h&{PXTAb&{0?7KhHvW3;{dFcC5reWw^8J##NfXipTH=9>&IReL}7r<@5Gl8M`&5IS^Uou@_DgtA0bzSO138c)W}cCF4|ol3h
TuGo#|utE_a#c=iwKg_pnY11un9{w^S)JfNnR84#ZCL$bPja85j6>Y`ww@Vn&G8T5Xi!7JA*w<MEZEteu$JmYi<>v?s)G0TDfDes
85*8|Z%U=F9P?an9hB$js0>6j29EaiHfq$#;yM2)lpOsL{$@0P)4@LIn%@vCgbc)V8^HK{8A8w<l^{-
`BtbE$yj6Ia5glZ(c$y#Gb;kQnU{Oq{|D(>5zw>vjF{)dE4f$^Yiytth4qIh(zrRygjUW^wdE{*=))TUiNs!~>%($f$txwAgbDKe
i_ianQppaNX0Ym!?6#9%!vhE_<|hS?h{(BnLOOGtJhdHa+vFvzExOkRKe=6Hv&=3^Sa~1zc4*P@?v_sR2O&IT3Q<?fba6F>?L=3Z
b^i?_HkJH>A+GITv`wfdX%w+Gu=-;t|=|OS@f!<bM!Je@`Z-
G%y#`w|rL2*UQWPkUVWwovcAy+9i1a7JF?Z$uW%y7wd&!QC}H%px*)gsu}-
LBS8V8WbM$t>qo=tm^x`;gnIRK@BA)oMsMrt6#^(84ue^QWHeuovLYoJsrNcfH5`e-
USBMJ_uQhrmfz0=U<+^W5Za@TP%6}PItOl#ujScOAHo~g%`?kM^SgiAsXdIw*vbTf%bq!=!4tF-l}k0M*g~Z%&-1hb*kbonfIil-
uPb&X;z0)n^TSCNRYq)ysfja=p2W5e#O4)iDPn~mm$_m_`TyKZuUeMQZ}^RQ^^pHSLz%qns@6bP;><%|98E9@#Q5>6VoW>A)zOU&
cL~-fj;Sa>Fg?VO%CKm7dbA^M<T4We;-+>%MZL)(ic-e(jE#m)O;GrRCl$zbXXu!}mIu8vjan!-
KY)BJF)We>1Oz1r(Sxq}U3m^Fa5N1KQ=PrIYME&Fa0k=_bMhp`4#6M4el}gZ8c&(SDZq18e*rVt;l+y0{L3fUs1$GlT=tkY*k#i4
%9+&$xnuz~?(`%)3|<foYE(2OnWJ+#B3hGFgTxx~Mby}t-
dw|L;@puJR6A?)Ta!_3K7mW$mI#ZR2vt%N@`*_z;Z@?CgeN?n{x^su+d@G)3$I?Xqr=f#4(YE^qhi`33Qb}tqecW&-LC5HEy)yp-
zx;+SZc9=D^WQ{OxK4GO-_Xmh+!}gvJsJDV;h2(Urj^DbM&uVRE`A<tRl@;LCtI{vrZbTAUTE;@t2twi9wjHY>n{}ZqqFvJd`u<N
L4oBD4Fp&j%AeJS2Sq`G0f0P@~xg#Ou{-)5P`vcm^ng#<=Uu&%;93EdDIsOw%uwfYHz_LM-LCr9Nb&2tzgCsByvEIH|L72!$yGW_
Fe5EAu(e02{ybWoL=K~cPrE7)Jph<5%xOlIOC@nr#723v_%C1(IxDS_Jx~KM&m?d_lDZOvUH5iXT7;QAQVhuGbV?UsEF@gs!ICqz
qQ|Lge)y65{3cjcghKW1^X!yL<Gw_Qcwj9Byx2IWOy>g_ooNdQ=8l5{oH+HKX<Hj9cw-
$yv8iM1Gd9f(M^%`aMh0F&lYW#o(?dmxsvm*E;33l(A$Nb`eAajcX+i4wOlfQ`+-
2R{WdizPq7Rv?|TeC$DHtnu_piV4E6<?z)b_zIAfj}P=&Qm+ujq^j9|YxGY}{#!(5W957B1a$CI(1O7i+<!(zko4m8(*JiQt@8&d
|xRV6v3aNcoRc#-8>^+^%vN_9vQskXKkn5?SE<FqTc3qIt@3<<3Kq9fp+Iyi|e+TeMLez|*R)sE9;R>RF-
PAdl13P`a`qCwt2AIBbGE-
WvIb)|~d3n+qgAa=iROd2n^@XJY51h_AK?jv&kT`&K8e)_(_`%`79s`-(jJjd+FDP-;LuEdtTs=Kwd8)Zm5zVCntp`-=rcE-wrPU
%!qRbEA(;6{f*9x`<a;2=`;)_w>o+f|^pC1w+XOaOA*DrhaXQC)uszPPd9k8nWG*go~pSOdMhiOo|Bs2hEhPOYSQK+p*KVDit~SY
3LL>v2v{K|{5c^L*pwp|^{r$G|W{g<%tl%3mEyMf;Kd2+hFcn0;KV<)HTh%!i@&LFG(Yk$V1EFHrz-Qn#*Ul6xk1Apb`diZhA0#%
`rQ3I*jf1X-UkZ!5BX&2>`ZuRwoywau(PdJ#)OnoeZ<usb<^3x50$?hCl?{(s^S_66iwJH5C#Z(R~<9E!Cim(!(nUwH9<yb^rz-
=-
ayTZ?&2!lRkgijQ5;M$^0{hxkCv*N`mT&1jbA|2S$_o?>)+K`pMZGUw}JxWh}IessZzq$Hh;(IXqJ?!z2*o9*h9YHCnPUH}giPkr
bRir*uOJpNqnpur%bv!`c8v#8U#@@And*bry1SuNaI+8GXLR1ZgfZFQd~A2xxoDPWe1aO{WFIob;2idm#3>5y4k34zR=U5VU@%oB
aJG{Lsm(yQON1U92}N(b<JtZhXA{w7|)ZmV^Qd<>v8Lc5z)S7B+|=6^Q(`CHt+U}cFP%i6TUz7gNewE$O|oWYd1sGMwDkM#wx7vC
vbKNcfvq#yR#a@=vEVBYV5iBF|9ZjCCi=^^(RqeixJe+qq^VJ}tF@)QafcT>#WTVR0a!(@jvXf8PNi3Eam*qIXvX?+nmrBFTczVG
r4i_ph-pi?GnArKD!bHPVI@JQZQ^(C3vOl(yPo-zw_^;w^f>stod$EGL$Pa3UpeW9D=eUz0Tc5AJK^1#7BF5%YrgE^cy4#6sJ^z$
#*-yCTEW~aieb>f&Ime^SOhm7rMb9&y!g+J(q^^-
8kG<6*A|9(OJki$Kv!r3obwl}C3Ub!>`pYIPk=t}n&v{s@9wR#L^PPt#<t*%A)S(?sZY9|C~UXcA#M#sCj%~;bjt+1&13XzBUw*;
N!lk|RX=Sym#wjwQx63{;hEq}bE2h1r|(x2HOwUB2Ll!GVlknn=e*=STDTIecyBcPA~h}CiQQ?=QAXfCEm;wMVeS8^qo`Sog+ArC
o4b$9Io<~V&%IZfd6t>)rqUcW?|2R&AsqJP&NB0p<nGV!v2FKz<cl*7ubKX^1t2g9lBF+mV+kAtZ}z@B7Z{lSjLi}VuVrqu~F%c!
0*T+aS}jqt)$8Ko1@1;d<-
uU~f<2yqK|dt`>vd<s2GUrM3R879ETF{(^NI149(tU!v=q!%1Zr;0fe%bmaGQKr{bv9{$Ee+glt)B&dNUFPg8;GhB743_Wo!jfty
Qm|5GRA6`{;+7Oy;T~8^JAwDM(Ow9O2?HIfL%=++3M&7y*fDZcS?10=j%0syZ%w1Q`FB%>K2<jk@VC_aT4YJ0H#egUe6!axJ^h`k
kKY;3jcW-ppUxcOQOjkr#TDezA1#oGY0>^}q?X$(U%p%z%PYF^%lky0ypUepM+)_VE&3$clI<eQImOW(X5?yQOuej7S=kLLOI>I<
@rv3h!R6*Xojw-Oh4!1r!JN}Kd(N2J=4B|_%yr}!rHys=EQsC7DLFMTVBGp_`JQAAw24cE(K1mMjX7ak#SYSi_7!<(IRReyhoMPv
J#Nd&0Kh$b#_?<wp|OJ_Ybl};&Uc_DHII4jFK~|>IDoVCQTq@94T>eei-x(qGo-ER4K2?Rj1YCfMg<d+sCapB4qA6y0NfF;CPRJu
0*>0zdWeF!$=L>sYgUwcaw6xGp4(oWmV93h_lts8G0lmwB9)oJwp{D#$`1Y-
_|&*83XNIi?)agF`Fjmfc_;@EJQD;<nI8m~Rd+DZ4tr+TgPfP`IO`@X%y@{Jgw1%lRcx^S;(OtWUC0|ANug(syLVsH#<EP?Jroci
$3}aB96wX)LwpckhA>U*;=g+e*vx?w5_xfN5js4X{Jxi8u&pDVC^8}`IEn{%uIE@Wr24)4C#NsULW$M>1fin@&80E~SLn_#TMF8S
lwtNB6aDs_>L9~)mzjM>I|`<|zSTmIu+{qdd@$mi1>}8QqvhFolUMRf7o`qN2!GN*`4uW?`Z3Vd#3{9h@Wem=%1s`$O!OqhxYEhj
g!;t)L(Iwlj*0eR6(30IBhangGmX$f7V>|4UleujYg|TQfV4qR`2mlVzzOLZEfiGCa)|j=UU0$BpXG(yKjX(gDjTe_Xnq4osrd2p
6NTG{<x1>vA^4)$9d`<-T&9Es$wBnMY-
2P)Ek5=!^8*WRO<H1iAfw#2Cdu+wA1%x*1|Oe=F~cuA<<vCLqD(AIca}a_UUcyy9IBJ1=MffF$vr*2q!w1JD*LNE8?x$+QwUz1#>
hYVi@*Ke>QBGemJD6>bjd?MJM51a=~c(YJ<<@L(&e#5)l!5K{2P?&l;-J-
US2t{wL+xM3gH6jSp(+oqijmd{YVLV2Pq3RD+q(?KRk9V$)xxT%i$<O?t1gc%y#B66FUtcZD_s65Ta3gt8CjUg5<<?FQF9E;L&Z(
x6+#anE5TN;ZLSOV|Oka5EWj3L6KUH&_E0R0iPYEBC)g!^O#e!$T}0H#*NaDrr^kjsZ|+nqQ)b{bJ)TksM6Tc*~Jy=FN~Z4sy;v`
ve-^&*~}yFS}kC5k4Nl?R?i+?p{AsbM(-A*n*;JCAvrCYJh-ltvKiI^QTaUf?Ur#dai{=w?L&%%sm56#j|?5yS2~TE7JO{QR#a&H
%uHh)P`~?;<1lTHC()w=#{<pdS7?2($i@B-
;O}fdH0rNmAc7mB$<~(>Pxyn2^^zh7cFU!&Hj8vJd~+%F+w>Qi#d$Xdda4Ov`t(245Rkx=z=8io8q0o6>IXBNNcZW~oeGjDSYVe|
U|wADhyua6`)xP*z4Pw(w;x>5sy%c8Q}gdlp%7f(kM6Pu^;!j;ayKNbjXITd&Sa!@4REqQO$`p<o4ec@%@%jhhRK9msnrPh`4SLP
u)!@t&@d9y`_SD`ATC)O8v!&l<;RQVXeJxo_t*D2kR`FK8}r2YD<*4B5FeOVEQ&fiVu9oj8mu*sr)0*H+>`nPwSo6H*QqKQGXuxB
3Ic+vRfR%2wk8{jcf;=gqx?$RKfo=8wk)^R?IRY3vvw-
V8{=Sis9t6x`pH_<c+j!H&Ywa8BXU61*V2tFzgoOC(g8$3yO#cH51U6KM*p%3UPQ@H(!5D5BdRa~8au|?AH;t42fqh@m-
1{1C$pAQ@zRC<5ORzMLq6Fg(<oda4OIfqzO4nD0$#d09?@?xvkW6=B<?X!)rH;fh>!!3v@oQLvjYxfFDWxWM-
$FkA`J+^M4^gYzYAfCi<T{4@g%*Do7k6K0?WUO8FojAJDV}}kh^q{xWx{-wK#C1-
=iRHM7Qi4%f;{f)^^C*YD}2#=D9HJ*Q64mJi4Vaoz{ekJ^LdZzK>izQXdOmf*A|EkS4VrRkb{}J>a=IYl9&L5l8`A-1X-
^ra{^JG*(c`e%RH$1wEyhM_u6d@R~>Q%>6KT??L^FmTZJ$%03Hri!iHIBMP0~@H7`$l{|%&rD5XcA$i;6g_I=1vM*PWI%&Lxslp&
KZ86%HF<#$U#8Pb&TYfCnnLOm#-
_!n$Kk3I3uPp4#1@g!3+%|UDC_?H)s%V^3)X!*YScQzir9OC!(DY%P*U$b|r|3^F6+UAY*FAZ;p^cZi##w^n^_yeHNj!-
UHhP^f(Bdj0T<RW}%t}}fFKwHX6y*%Eu6#f7Fd2iqB@mb$W_YgjH5G;kiyG#xLy-
B|B56t6?2M?#XNpP1vfR<(2zb8fgVV|AQcMD&ax&*y1ay<P$d40^pWx=3_<Tej#hikyMQRN-Xi_=&nBg2br5iy?eTbdAh7MyRjj1
mL?z!xR@Z8oMMu?A#pUJSik19<q2N-
K6pudJ$G%dt8H^lOJeQ9So6nOz3L!h97ifVy9#DNrf=y@#IsA}OV6zqw@870w)d6?sofe~cOVX<A0cvX5?^3TmOv6?YID<5TB!FS
Y0K;31`jUoHgmRLh0g3Uz`zA49<APB0aqBWRt<PO0@+cqmfhZI8~+gkiu++EU%PLK>}+_OEJ-
1AGHO&o4ow4PqbXk|Bh%ly_l)=o+0xh-m#^y^-ou=5&N(Qq-
1<!lg84|&72LajECbblG3%35WQ`}7bsZGB%_^?itX>11uZRIy87P{Y#jgLqfVlr{{y2JYkRg$L$Nr+R5XJ=&@|i1TLeCzvGwhrgh
HKVo=QR@FCbcwoN(fOfIk2~*%#UF%4^7;<eE68eXlaqc)50Tb~`eeQ1I`{dGR*iDu1&0WmMy_mk5bc<<u#uCG7W}C4B?yj^~pa;J
J>yra$I8>$G5%8YhMpwaG!kT{jOq9ZRTN9YBYvRGq)7X#(G6jq%c;Or9#c%zP_NYM=+e6Ap=1CkoQB20_Iw%I8ds$Lm&2!Kp^^#?
m&5Lb;;OI#ej_SX$lC|gt=kHE%WK-
!d^+C(t95l5oncJQD>(!HukF&T*tMFedoslR(3*Zk8Ia>xwmctMYIIJ7FaKW`hl3Jao5U#w#+x5(o_r$s0)9&DPge#xvnu4reG}F
rA2oi$+NaFjSXkssYT4nJP1To6*xk*Zm#zq!KTV|8=FfJ>j0S61#*b_kl`JVy|q*=+HA}=G*RfY#c$U9X@Qj-Lsl6fJWxJJPdwtD
}<2Pv))+fgQ_w1#+2gQY|HR4f;eo~9WFTu5p)^I6kOuExo13SE8~)p)Zxm+aKbkLWYS+n5T0J2z%tkt{@d;zcFUjY_9|A-
km~GAN$3dt4&`;nIv;j+KU&YH@pf;yJr|xzocmW9Y#KCdkUkQ~078&Hg#S|5Mej`j1bB`ji1eBx7Ze3Q;vZ&gf#Unvx(3lE?w%UO
RpT)aOb5vTe&4@t%J{psIP0DxAIbV#e{-
pfo~m@cE%MgcsysVXqohpxqkUOoN+Q>Q!cf6c7&}AzHT0C<mUZT_wS*HjXksq%LvmLuYeV#HA_TJ1GaF3*a!A;cjdsB0b0A6s6cY
^67Q3kw6cfxC3(oXP;ve2z{1eS!wnS@H7Za%@Hk^V|^i<aYcipT11^|4m{M}uk-3ee6yhC&B8JAv;j7lUlxhY-
V0qx&@k3xI@33B0%gtU$Cy1h#jBUlWe{<f_t~D;{*ThB2kkEaH?pjug78ZR#D2-7wzGPPtw^{w&OBU>tG?wOT0870P1&J7*w-
NNESYlVjkR$&A&@2c8R}^7{c)-Qs?T}4$yz;V^j+BYM|W@6PUroMPeSn-Cw|u*Pycs)hT>OJj6tZB3ejh2F`#YPijA1JNK-
<3ZqIIxPN=)ABmHOvn!oi#u*f-LhIV7EuUppTa+8q>?x*ebow(U0GMFOt3jM<qf;Pft`v+tZr4eZ3QG-
+HJFGj@QKM?UTWR+i&Z5wz!D6moI1#B;21bq(uYn$2z5X@&`-
St+F{*!55=#f(`Vm_#b=ZM~)DXJD{JM7Z+me6IJ`hxiu+<UhDk<v>S9TKwTR(V4@E{z?O)8$U`eSBur`1W_*!2G-
9u1_t^s2d(1;{4bQl9K@MVpcvPl`+S&0Mbrhf1oAR?$hi#Mui3)i{x2m_6rc%+?e01mSVs(_T{ylrpV%Rl<z28r1}-
1=h(olv2g;J#1(C9!@W5;S;|B)91_;ZZ%8%BvmhKF~8B|U`QC-<Ks9bb7o-
eswb_5rSs#n)ikNOPDxSsH{+$pM?T9lq~w7*@G5E!Mjn=W*RaqC?XJP1<F2K25Xzz-
Cb#6_;YS2bayH&*AvEV8tkmOUZ<9eceWUxExmobLEIfLUtQDTQrX-OvHg|i0MTB2sN@jL%L(t_=WYMA=x94j!W%{C&e0rdeyV)3|
SaCQVpR@AG_ARU7KA4M7y~(e8)4CocIhTKU(YHt7*21aZ8QSH0=@OQ5<PA5cgA&e@oFJQlM|X=}RiBL`<Q$CVml9H8{*h7Gkx$5Y
VKeJjP32nz1GYB*C3gq{Zkw1nZBPWcAH@pm0#^0VtWo)Px@IB}Gcn~W7O?lCK)7gmI7uC7%>#0j4qXmP3%Q&APi%YMrf*+tsw;SU
4e|SZRfS3LraE&4YkdRfRk+uwr|;j6n-%o?-
gk62+XusrugAkOd82dSgKIG78l1=28}G^uK*nj@;&+i`RL4g`)bh?ak%N15@YEg7K6d9GrS|lx#Q`2wL-
O|Ko^UPQnU+d4aJZ8@FRh!CXmVKUCUdH5<3UFRaGBtoDMNwSt_op*X!yICwld3`ts<PShQuEG6`n23ua~a7ho&9i%W4p6<F=<=6R
r#p2!?Q013}OeE&+eT_uuAnCN%jTd%N787enWGSM*l`4M>C$c0v;W2L7Sihrq0$mYXgoWn~6C60fKp&>XGVGW(tZI(YL<DY}%sHq
fS^_iW(-@(Yr595k5lG23|;@7nV*W3F^UWiKmT{`0?M_Y|;z-
qKJ)2^vPNI>?$#5Sv4Xp<XdPh|!m=5epaWrqZ)wj{pF)k`Z<|;?;FgmeE5R_bL|*k_?E|yaA6d(>l+pLkF|SebW*<q&su9?9lb#z
M1<2q#gK`v2E4L@8~(%-
s5`nB#1#=>gf(JD~+q(b#Y!Pwbnry_QC?lJh7C#VS*8wVRVkZ{XtO8vg4QUl~pyzl=!J5i0<hENE>5@2VTvAZ&>Gg0Cf|}dt}Z)w
snmec0jcB;4cyDJ$0Jc%0*38f{AK2-
82G&i!;RcELn36JD>P{rp!knG76*kY`T*73QE7l@>qAG4}%@RsKq4&M3?=gSrSaRpTNpK<*vh@@~Nf8jL}#j)lmzy)B|1HPl=EwB
qpsgblDS-
;;`yW=BH7QP7SJKY(6(}rBgz(TNYTzUjfG&waO$&WzkDluJY1%0h(qfJPxw1_ld*KHOsT|M5v`Mln9$HObGhtU$x##+qDU>+k7G3
$=M2ksEkbp0bpv_Cd#@E8ePW^M^EIN7KIEa+DZ&+@fmlJ)D5O3vu?0&Wb9)GWt;Dr3n=<z`G_mof7SG`LOY^Y%sbcKwrgVzcMD$*
*3xjBQ}4LffS<mvg;eP`^!Fc)u_ugWz9WMo(dbsaNXBfA#^Cu3(DxSL<>XvC>;XwxH>X;LQgMIs75;V;d0u{!5*YT$j*BddPzw3E
Yni?;U{U^D2JVTaF**Z&T`(>v8%8=vWrz|*HAi}3d~$?MgDvYO{K$U*a2%~a?NljRmUS&)pQifO2q5Nc6I%@In&ANs;EOlcF6-
i&MM_G^7E&0GWk*HO5b?+c&bi}wEbBMaH?jJt@w!F-
ToW6@^fvy5i=Y@6VzsSsR!9BsiE%xMl%B4fuc#$VekAm}K=xzL24Iu<g{?w<t<q)s^w>P@Hznhy=hYJLu|N>w1@F>D<*9REYgzZ;
y49)eVlL2ZSUZAS@!cQysf4wB;!I)ii+N!ItKX$4u|iOo3FetUD%zO;X|WSV`<&G|K6(N{aj8!@qWe&%5LWQDwlb;mR3}uV3goZl
9%?+SRO(gBTa{Nfn)^Jzmb<86eMZsLuR;>j*2%a`&7@>}F`ca68x5G#T&=3Mu%TY<_nJ4xplnrHFJJm`s~HqNz6nj!2ei*#*#nU<
1xl1oCASA;Qvd|`Hr!m&3l8H9i@IB1x73amX`8FsJuDRjGbfTjbio)>XdG_2+dJB*($(Qe_d3<nTi%IB^M$8B_r;*!FRelRzQtg5
{>F7u{KZsLoG6$0^U=+uK5|q&_z9t5Qrkc|vTM~PnEyDk@WVPt61dF8*$?RNBL`KHwY7ByithL5gM;Ssc_^)%3(#$k425|2jNKnv
R^U6xHkEA{OCgo9&S=aPvmdP-
PIpsV=EFuq%iUvt1{~`4s>I%-ZGlE$Nj|43e>cZParA;U^Q-$D7-Z7~^}1`L`<wzz75XCrM&v20Z|kP6{p?LETvOvd(fg$OY-BlK
h5!tKf{RJlQ0(_?x>Yqv7je5~FT~o~d@w;WZV)~?2;+|<4d`_FR*j^vX)?Y@g_j#POSWnX>?X#y9kIoFw24p5y)dH=wvfxO?WmQT
wQ5=!w-
wD_<bAGNjd}=R@I?KJIF=i~lvw+%j1G|!iWe7$GL*UFmLuLL8^)dq4y2;QOt09SDbuwLwv}}DNQ0=Ytd4)>M}2MgoZmwy?smjt31
N#+iDd3?dlLF33#CEc*%S0ufw>&(FrkXS2Pq*?YM`9^rQdc!c+|T4d=|{oPUt_5I52HF&u=sq`P4l_0fx8Yj_Nssl=jrg)zL$aGz
w{;#OtL_uZtygR%6cS8=x%2?}4UI@`Vm;u#;7<M}2gt*IwnCdaKJ6;tX}R<TYZW92vZ9Tq*<e%=!)*DJgCow|m5kYGXM>h($_Xlv
V&B!^n(xHiT{9em){hU)8fvv5E}09|7k|b?6cL`~32l36OFIwat??w_rgpvW^MkbA0kGUgbs-l%@@7#;Fg7TdiIY#Gf|;;#qt-
e=)2kDgxoVYJeE;>(G~hdv<uy<F%iE4cjQ^1_|NbW=YHU_h@Rk4_b27wtIx2LZy^P*(MH7ng%PIYOV=KiC9@;E)j+hRvFkTIV<uR
{6n)a+)=*2`WFyHS#Va?0|BiMQ=l%ruI($TlWSODY&8-9z$g;H1B7gUMJ;>p)yxggG_>5@L7m2h>ePUbVU<s>Gx3|S{IYe-
$RIo)G*iy?86c&rO*>0t)g<~Ni7-F3%e2+$(gJ(0E~0Qwcfd9@5OdQ@{o>!#5i-
Z+Hss`ATb^6JY6waAB?T_3kl5q8o=6}M9GuD;QdOqtpg<g5U=GC^+NuD|#Lkn=rC}Y+O9T&q<14lImj8jz2Euzw1i~}yd2Wy$4;L
9?YPWA8ae40dSfo^%2x7*vBtx2+1`yh|p84e$rfv*`+<9`KAWAQcC@6whEg-
@D7%Cf5$GG7A$}<n>t|}csgFS8o4h%dO`P?~NU4LSK%C)1$T%_=KyD>Rrf>zoWw<nDXDlD=y05-
829mnhT^GLK=N#ZGAcFGXq!<~~~#K-)6N-)6|uem9;I>la5UnU_DB+O7!TO8H9h$4=}H_YK_@PGi=yBPZ_!7rVDr2&Tjn%k-
B(%);+T>D94-piWm2~XG-WbF7C^`Q~ln{fP34Gixx4$!4Lzi7=|g2y?b@BIXFvH-an6P$>m*U~LBWW9<Xh4$J|J(-
%KT|AEZH)hLSp%(^8Z|(vP-@05H|9Qb5-J=!B@^x`+FGPj0OrV$s0gjU!lIh)!WO8WflO#(NLQM3P!%L-
i()=%H9I6z`3hK$B^g~>|F_|KN(UjH-
z($9*P@*o4dL`m`81(nIQl~_|nrs0dP^c@lcc??Wq}nand+7QgWnDz+8c2S;bmi}46BOp?^6D#B8kvGqLXI09*dcU4K@C7@<cUiG
_HJjlYmH6cFc#&Ct1-$p?Ad2xwOdAKcQUxm_51Ve!2(9RzgYDGymxbC0_H9qU*<K`|4{`^44$QAW|bC1@OqfK&GASF_x;)D0-
I*lr{dm+LbfHXglMggq+;C|HHA<IXR=(qE>;wK+stfoOj4!4sHC-FOv(X<8@Iu<17NO|a~>OkWprhui6Bv@fzoOHw}vs@@0O%aKU
O%o1En#50vl_WEY=ic8@|=nhDkWVoM;F+|Gfc3)aBCc-|&pMoH}>RQ0{2UK>Q9-
QfMcl2&jNU)t~Zfv=y&XSDpa1KBa?;FnzCfBoX+v4Y*XI<@G*{w)gQ_k=~GM)z_aFGAlfqpiby5*9vP@?NsSo0x2w&Qo>rLzKpsb
nN4ZfxQkR;!9Y=s6t)7`Z6Q&0w05iMG9JoDj2uw2RQ&<+*pbY&XflSNX7oD*cxTyJRc`k@yV<sN&g0L!&W8eG1wi$@?VtWp=V&J8
WaKHmwM#WBF9-
f?)43|sc+>lbPB@pSq+)xiVb68cTMDF+A`?N6_SOl9UZI`CVd)mmQZD2b8CgltKfol!1i_zmhSk>O85%nZ5Xgbz`dhCjIl1pX(S{
@w9q_^{bS5S{Js;zdqqP9M591=_*tQQY10>jBeB(c3`nrimD?FP7L(SiyU~X8AozlvN6h-
u~m_J+hpuY59Qxs62_OYFInWFJxY4u;Ng3pSd**&Ym27&VW{4%CS<*a-$T7}E9C>p7q{ZzQ-Xp>67_QObrDLiRtg^xqQ7~uLR_|p
!F!)L<_p389*8FDCi?^y(h({IKQ0RNyG_j5XS^rbwvQR}+)<2%<lNmc=38o2I?Q84Xuc+{KVsb|yf+8W>hiB132BE!m#s8&EwC!;
2MhMwY}&&f?qG|18-F#5N{`7IU2^B9OO#IHhb2Ze7=pSbmc;ZddkZl@8oBB!T^Hrmt95;oD%E3?~64&)@Jn}3QTU>-
zHbp~$ZE)5M^ntRaHQiJKmw%yS?1<q1;Yh8mI>t<swi@eQJiYk=AMvQ}PT1%$jh%<D~NF6E#1DkAWKkUAfaEJ>z2=6o5d{MHKV~Z
KCh`za_<%_%nQ)lx}hT0?1Lyj%pHxK@^j6`{12-Q0i)8teXG*)AhFVe-tfX_W7_`~=}|FI!$?*}F;YUf+F$MD_P*>A`BDqRmIfu;
qFg78spcO;@V2*!Ov|Kl(&KG$QNt;c8z0^*(>H#LHNAA$Mf{>g(mvxj()<RB005l?U4gT%+Dc+sgU<c|>0N!$Fd;;EcG6erX!I`#
r4M|$o>C`D20oQW9s)(YHC5BO^;S4x_oWYL@ug+X6-Sc2ASe1M~_wiq&k0hP6bN)?M?YkAk*=qYDpKJ{{$i*}MOeb6YU3B-%`-
}ClA_~N$w>dYMUYNV6}!1jQ}KPw)N#7$4-
&zVwo{T(WGT9MDcdynWrHQd%oIGhLaG~<}oayimrfkK^h%~b&^ZB{Lm#H=h>sRvES@Bh&2ekj%WHC;to{`sq^V1z8_fX<!h)d={K
R&da}#L9;FT692$tnd_;K^NG^Sh+#{u_|n~GZG0e3-Z&A;-lvPBtPTA7-
yobPl5=>s0q|{qj2s}klCiRgEr=9bxW%75Wc!vjWBP1<c4@zTg1I=ls*B9&MlYt@u0t=`V$er+zznLw0gk!=1_s+za0c12mB+`7d
<CzJT{SuQ-Vs;+}g1HhdiH85Tr`aZ&Du77P%ouDa%s=p*Jj+_MK-ku^emCpy7j%iynO0dvFt9ro|2=<Khk{9YrN~_SmX%mahzjLY
w=r^EG2S|A<>*Kd#zvwcFPCc;G=<?bWYsvV6#{^g3vCB$HW7D|tyDqmW(uHfQ?pHi?@gu_zYyZv;wUuMY|8X(A{h`dVF>XQfs(NF
c;ZwA%^UG7CGxY<R)4CZS%=B#1)phlAxqZ`>E4Y3Nq!?r`P9+*bZuEidTw`(mzZYG6XOQa`JB?iiBL6m4V~wc2T)B|&mFwt2Mr2$
I8nTI$ODO)`=7IT6A{N|zPvZSn^XHmYR7h*Db^aU`X0{ViGp$=}@zD5UE<;cnoqeAl8M#-
^y>@J)88w|pNBAi+n!sKY?Fc71R4&@fQEe*A%Mhm~b!Ip!|rThLgb?F2(ux}DJVMY=joHCoK-Xgj-bSr4wnJ5&Noxap{Jb!ql$B8
2y`8Zyi`XjWvGM@wp7CnrW@#>~(eT5yyzzg=li8i#b*fW$WUMjE0TJiO7~F~<1Gu#t7)rMS3R@r+;`pd=Une+6C`YKqDf$0Y(8JS
J^~oV>StJ9Ycl%fBX@!?+28b_kq1-
mrnqLvdyL?VZ`?+U*ZsDMrN*26C`UCbC0jmP_{NaQW1;4{iZ%kJcv%exx*=H)tJ~w&|^1ofkdpOVazz3QPvabv*r4&ywitrtzXYs
KBc!<D_AnKO?UmEXuPnB3G<vaR2j7@FfT{DL@!U@D`w&5X}VE%BC0MT=o>gYTVdU>#RJm00ic%8gTS}Uvoc{+%SNQpxYDKUpPR>O
Z07(9V1eNiR^gs36#5#QX13RgfJ__7QFBmAB&dOT-km6l2f#+aqU{z2!B}1NN}l`6v+oL=)ErIF9!^D+o*sI@Y(MsN#qw+(|(@Nr
T2&u?r}1geFG!_CEUg&>{ZOoxZn9S6Tqm@N>G!a+c7K<pmnOkCs73=JfEX6Wr_5cbDil-A-fN<>`~%ecH_{Gf`5HPP+0eS{Xub>U
#HBaT+v%RU#HSMNe-105ZA;;oDouX1*z$>1QBb@kDOX&!ynT@h3UFO?4*&JeFTt+j$CM)m7=2TO(ESQmc8`-
vl7z9&$c{v5Ip}aj*wu3C{r~+z@um}{>|1-
>hVo+s&G`W;20>UGt^CaGRl9s4m#bOP<r9EuA|FRo1Ie^;gI!V`)iih15g!;CXB*r`^qsMgYNG%<rG!xU7sT%PIDtjpI@dCq^wA5
B76RC8ERwJL>6xpe?doI*cm#geANA8nzEWJF~j&%f2>qmgz(YSDB%?4OhwQgH%i<;wU&lX8e@$Z8JGF>b=awAX%>l~mHdbfWDvGb
NTN^s`wsLehheaOFj6U2#Ln#VAyr~?b5F&@fkV|-BW&`oh5F5pr&MD&Vg6PINqBp#-
5~j%E1~KnE;bvj_Eo$tD&+d#*@6AeMz9#pq9op1^zN>e+aOT!GURMj@Y?t4bT9418}F$)*|8dpEx;>{TN_Lm*0+9;0SAyFWK6RbF
d4M>g*e~!$MB$-WcPUH+-+tFyM3id|GuIXeMu9OcnAEuhCS8<GJ#JPP5m3tI?b@Zk-
+h>7DXfbwoGUGaD|=$=PR?qL+gGQXKzV_MIRy;7-?3KAkOwTX;?{ph>cE<ZR6o@?l;XLUo?kQ+m>AU-
XlQ`hM_9viKV5#K&||)!=#93c6Aj?nV435(#xZ#zmMpr@ucQC|3`!H6A^sDY?nDjA+#}AKK-sCaLt$#{<3!v&PXnKfarj<HGofx#
aQIgh&y+0#tE1k#8Sf9-<iA+y+bGS%;0rPb0Ae|05q$Y{)QAQq(RlDpAl5s;wPEKm@10`@IgcIonH))Sjm)qNP@rPT>7G)_mkLq
--41lolY6GfNOiblkHT0<MUO~4j1(KTA~f8SER-Ib>;h$b;rLeZNy5e*PpEnu@S%*nSkkNJ$sP=TjVSN8%!KA1$yZ8wK53bXl)($
y=<Buih`Kq{41+Q5-
VbKA|$n=Ig=5NgF5a&?su$FRe7MdMt}z2r~h3fWiX=bYaeHU=Z6TI!8lpFdaCF!tBW!Xs90V$9C)BL5gz*w34BsLI(v6T70Hv+B+
qYMLmZJEHozD~p#6u&^_d+HSY`!Pa=d@T){0ST^{Prrc8>#1CAG2>WqP)IBkB%t961-
kbQ}c=<)Bv4<5l2AWHd^&O0pCY&BGclY!|mSYg)T%4$@v>ZWk2|^>b*k5eDY9>GVS8!z;A9^PfuCe#!Ab6D{Pst8-
JPm$y3TexrUS(8(h^@uVw3;f#f0v0N}Eio6<HTY6oFfZ34h=jic!fmoQC*~bVYzL}jc<PbR6;qquf7x05T*WO;?=JH~#^pIs=5we
J-RpF#>7%qkKw;vPsNJ74QFmP-Bqs6*0a>1{IfbS<?K&PgSl(Ia_wxwKQFvvQ&Pf$|I$Nk9^mlcP8CKmIg`p#>Ux)o=*BV{2jM&k
0?Srs>%mvQQ|OmFJ|`d@7Teo{LgRwsKy9d)cpj~Uy&H`ih{8&VNJRD&tZ_910r6((3xUcmX1E9Svf+>V%yK%8STqHNK&rOI4I_Vv
ozrZA_2s%9+JW!{PzG=t5Qe-
`pe3G&9@czF4=22y76e6rN90p;_hV6kC%O}r|TC{f4q$vp1D5noH|YvD7dm#U=)bv!)3gxB3JS1Ee&D@IY!r9xFZelg1nGFu=N+W
&!+W9M85gX-BWBvmx$XiWA>T#DT;`nmUs4GSTsZl<f}gBLsY@$)dE@)x3rgCW?q`HRVht|`{>QWl2R!?*8<?czw#v>X$9{4VXuS>
OUD{5J7ZuWxcn*^&a5K(l_o?B^K!xjSzQVg=~F^VR5kQj+0l5eQyZcDVRjbR~5h`)D%Ja)J#;R$pKtoZdh}NDCbfQNvG565_xfil
%qFij}AT=?|>x(iD9csA&C3Mn=jD-EDsOa5fKs#;ch`T{$x^xcT~}E>~q;*lVi#`zB3K;eu_INp0nSD`n`$t8*y$1veX(OemKXwC
X4o)Ys{~)K=1a>=a+i11k9T?>rA-)^SCUPYr+1JoTeSQ8ts<F^@UHX`Z1@c2RWQisb?G1(BqJE3o3g9atS5xvXG^R2H+*-
d2iId(}DIK48T2hc0%SVm{5~3lh<=TlNQXHfoE0ADeD69D|W;+Aq7RnRecDtVVvh_sgx<lFt|lYR1pzq9U`R5k?oR*oOLjya@VM)
yiPWpasL2X_Vx%&LbpV5EE*ir97{y$xA~W{Q_vDYtzQ~1XzmvEh?--9G!D$WCK@x@`f1~ojhe+i@sUygq;Zj+o=jv08bJ<zds?4;
%4P=sGW;LA1^SLEoZ||cLg17%TkRQ8R?hXFIb{~RAaclC&8NYq!AGgsq$%A--Tc~Yc`?Bp}K${{I6c>?r*(-
$3+SKEwmN;M*cf(EZR5W*o#^yRSQ|qq%p>$bA^+1RB472AAT3AIRMTqhAQ^bRyqbn8Evu)K@rCtksI#}xp)<b>tl`1!B7!o$XpJF
M+me*KEAKyZIUvCCV;_D*c_R$Y3wh<xL=G5;zPHP3P&k&qvj)xoTn)Q5q-
D<5qyWDSD3EE)RjR>n!v%vT>*vC|2kpFFIb*<q3G$Fjoht%U6IB%3=dW-Rq8FgK3-xVn*0y&aoP|azHH<a_a@KWSQn+-
?N<grUS{u9B{W%s6o)q7KRL^&m9z@7e}Ll-%A)Oq-
0*Z0n^DvzN3Q~h^M0Ft|J$ZW7#kBf&c!eOj(TvaTi_rsTcfUU)UPP&XoRiRdN#Ed4W5~3QBtzn7>W{#gpEU$ZKy`P00!~*pYxw@1
tW)TQmT%_id3Vgj}Oz=@UIduG2sKS%XT^@L-_2DHhuO?m@AyHP^5s&=^G<fCS0*pWQLp-
#u>EBSMDl+K@Q?iM7U@hjXGQH!ZKwpFj_hx3{kXA(89{HmpJ~8a!<PodM1bk1v&Qc*ys`J<2WdF=w)%z?>Zs)Ie2s=bt)J`R{&9K
4st-?H|P%%;{;A9V5HblON=h~w4ngqO<Ml?<2)5-
<obN$k;XUyo%i2f@+#Z6@s%#r&?RfJZ1Ed~^PXY(S%8GU!mM!yi&b*IXn)Rh<T|uSUw1mG1p|_QWln8B*S8p5r-D}SaB*V3T-
J6bMROcOsOWf>>KB6O({G3Kjy{!R700oT>NJKD;Alm1Z|dZ%|MAb3aGi1w`A$-
*r39ah^)zt(8R>I3<^H~xL0DaN5yrta5o15~ivBuKO+6;+bE6fvws%+??L{<eShq3(shzs2vR&l56E%g*Zc!=kY(us_*s3^P&rZU
!y%x$MmN+r5Q(mIjO??o2xfNK^7ld}$B)B>h$S~?%Bgt~SGTV_>qMX!~vnmP!oTv?z>tL>-dEMSJHBtyu_q^^MBI-
1r9pk*`$<Bkp*6ihZ=J@I@%T1FJUkE<7wvk%2gtSj*Lsih&A)h=GhhSYXbv!1X!6ixLT@d3YlQtdo1km5oRnwE<$#24ZaaF~|bj}
4@#GE_){oNwVD`=0l<Yx!tc(bm4O_goIicfx(PnUy7=Pch&hqBcx?s6#H?{uv6wuy+yw2)UStsK&G(SB75m1H7{L?XPF4%SVgJI@
|clQf2|8PRjB9-Vg1#1UxDiOY_O^eb@b*>)jIxuU9ok`Z7Je=sb0X-
M1oJ`?4yPFI<IlE*cXH6iv8aM0}H&F3cR&!V<$2C*>s`llX0KE6^@9QQ7VG~XO*<<-UsrK!0To(SujT@Gho!6--0GTLU5YxPXupo
saFY~U#kvVfhfJGR@8FMM#3R9(0f(3tq-*iI0JF&pu?K{vVi7-
1E;f_vn&?{P*3>G;i^Ol>h$`i#Z5Da~Ato<71c_>)1}An&^7j2!ZcSMsF9p2N6mVS|?0YW&<BhvG`XwY?qu%gf|ruIA@>s`tL&CR
})6=OMK3og2Ist8y3r69(Ti<0&{is<DU+CffXbvAybKj18)opk}Ml<WkqXhV|QL;g6D}YjGQlEs+M{KEOARX41u+)=iOR`hGofXL
Q~8TDg=Ol{DVchAW^q6~!V+aH3t9Qh5GUN8HWti%0$E71q8XwL|_Tz=t~_tsW=S;PBcHE$wA|S-
}s16%x>|H7F`QXAREzo+QmGwN;)Q5vqO+GAmh2hS4$!+Xc?s6tx&EeIu-zOM#M33DZrVp<h--rIF%|Dy6X_P@Anomj=sTMPYwO9p
r9Llo5t-Cr$vR&4J;2YEDwB@OhgFQq<Xf#?ps3GI8mzE!BJqK@BxeA?VTG_-J0_jpsk1twv_rDCH5l-
2j^LtMG8&E7iRSgs*|DlFt^8)0>6|Efpd#^Wm2K5yMPsW`d`S@aM`Y?yEQ!p8HwAAHDCaLUw~#TcX#hNGak;U-
9i+{IWPj3R;p%+?Yc-
`>yF~Wwk`WF?lQ@g>9w!bC3)cSQX)DwyEu5LsNn;{GLLe=1fm^C>Oh#?)oFFwIT*MGyuOTUV~p6M4u#pF6yb)JjFDcOgxf(Z)>zH
!J|Xn43K?6$-^kaUGAEb@!B=Digt5x+Fb<!Dok(-H6kGL4m!R&8(yyr?TlhBk_7^u;#Gn1mJB$GTE+xNr(hKi?GAj4rx;I8-
@M+&q<cM^x#hmqM@z%pj0m72W$sVfP<(b%J&@pKR<JyeH?1vX2~ozqqnIGXgYyL6>dzsrl=ZZ>yx#1d`)l=2w~R|OMDf$qLHCPz&
TO`Hp7{JGFM%Zk+eZ-
=40$y6QE7+Sk1Rt}#6>^*#q~pRm2Yp>1f(HRi<_?>1cpm0c~CsojZ5H(fr|wT<cgmmr<&a)I2>lo!2@_dw+&*8pJb36&d`{if;fW
tzx6f`vc=ZW1lhbz>OqTTWkMTAw_!RQ(Pxa$*O;)bCU4|<)%5@-&b=%^8^g-T`^e(PMUoc`zF-
5~BYPc}hddXY@lO+=*vxmJ$|^6HqkxrJG9VI-Zi%MEwuO%{QsDx1IN-)Nm|T%dl<<Jf<=Jr*%>}R+jsc#WBO`9eg-
G3SOIgBco*`ZSLM?KHa`&>W;r;xG1!7M>E@Qy1yu{*Cm|TOP6_${c!<~e8y4(2=S0#*T!dizW`w%IqO*PrER5lzdIHiLW(E2}l-
VQU~5V^%$mJoTL6Pc@$UVd}Ji=`d2#Cc7}k_Nk<w7adTb=0l_L(F0W=#;U^lTGFfC00}BoX9^FymB_Ugp+n1jMaMKIyA-
^y0<b|)Ia0!^UC)lD+g6~aH@G7Mu^qrH@UKlGqbg8=FUT=l>ajZN&%Z}a`^_dxIX!L?}&s^{%w=Jm)E*~n!9iunt@oGD3CvnGhe3
?W|8~&^@D2viT5Suxl?VBwyYx&6U*+gzBLZm5wGVX9HJhS;^8t*&%X*_N8!#9KX&iH?T|Ee6J!RUx~cO#wzY{1AoNL88yYxbvGSA
TtSHKJRTYoP&k7xMis<ebA}1esw$bbBvRXgErkI5M?9a~USx^6B0%X>S#tUYGqOES2qUHdsX~`$Oc3Mdaub8j@1CJ&0w3Y8+XgOK
XGo>4dRK7abh`|8~@T%sktxox|xR}o;G!xSIzby<`DX42+27aL~XZmcw`B67-
N70j1ql~dhVolF)@8a%c8>r@gU7db8f7zg+?~S?D3`3*zbz`xg&xD3$CiD8GY6NhVPPYyUQ7}4w{6FLR9AyGY9uv7Qp$=1-
Nrz$yp>Trm%Y=kGESN1J3fs&hc-oDQ60(Uv1-O7~d}k=O)L7;Cs*CAgvT3kWOBm7mY#U15KJ7g}{6d-
S;K9^BjykpZ5=e@=TCY$eGLDJ};|o+)cba(--
KEgQGDq(Vzx0c#NiN{O)lNxq>1ndClLyOmMA*)3p%ah3t{22@3k4p)WX%kg2kikTA3olGF#b1)SzPj_M2sR^3huAe`V2igwRG54p
~K&9o}7S3+91O!fo9XkVM)8yj*t~>NDcPefiX3JJQt|F_6A+*9NkOJp{PdLFq>4SN0fL@E4Hb4EbLto<(nj4N|SH)5dzXx#sy8rP
SJa;H-
b666ef%xLm@7TSIK8W0*>?ms1M3T@Fl&?)2Eu`OZ1M<E$m5DP7|`Xx=NJW*`7UO*oJfqDfLUInL`Fj_=j4ShKxsv@2g)0ojN`uW3
)Z9bu3bY=pPaJYuXqE{)**JnY9L85Fn{X{)G3t#)SVL2sNLIpCsFVDHC|ASw@_HQSy-UGt=1v=~ItC$D$s{O84=^Vgkt%=M&gW#m
1czB!K|NxjOLo^#C4SizMAqy(+_K%~jjtd^N^SmvE}byg3YDnzFyM-p^PT{g!RXP>4c?a|0}unk-
9IH+aqAKWBlI+G&EN(*eCf$u=funb&N+hSEIJeAdnPj{pZdCzP&5$jXYcWTe1%<n8<he<ft;J*-
9+jwea8B@qm_SBYE<RBHh7jV*%$Sq+|(W9-w~xER~hOx|_nN{Dr#Ofk6-gJuH(7}Xj-
d^4Lc4j6(bC#v{9!K5%BWm+}~JDT~O)HI+w>m!ABWqyO^`Bv9%BbK8cuh?@$qSkNSOZk%)Ffr<xtOJbQvWz!ik#uR4^BsGy=f13D
wcmXUEVa<8UvAC^v3^UFtz<PL@+wpBl*8NJpo2BUOj;P657;5x$foi<g7s6;{edeM2-
=YhLEiqfLiE__(s8Gf*K@$3&7RVFITOsUWHqKyOsH(6)vnm4E*)(NQBp^rysW97YpS_8=;B|`TL?XwjP%U#<6vViQ&~YDs(F9ck6
@Go1$9I!bxgLce6k{BhmWAP)aHc-Q(W?hlD5sq9XD<(*Os{-Fb7I*`wopOdruX-*XZbqz^(t#qYtvHwS-Vm*I{R@5ZsN&B~C2ymm
^|Xa_wWw&qNL+vpV~dTn-^aAp^JA>A%vY*Te?|a^W*?Y}<Fzb3FKZ3_QK~iJ7L^aXmfKFXe*d3onlQ*OX|9fC+xu#yw4-
r4>a}P9<!c(}1};A{4801-
<_}o|XM&8k9`Jx%>(XZgO2DVi;Hpl=T#B1kd8?Oe}atZS}%)rpVhB*vf?&r=9EPN6kX>Q8eQBpQDWb0#{v&2jb2whfZ}J$te%o!p
;ibp}_R^ekTFFQ5LNGd$zaG%CWT_b7&&`^Zn-
b)oR+(ljkX(o+<1N1gjY1HkF{zAE?bKRmkI4(H!io&Ka;b*O1YbE<fmI^J(tJeFgy2=@k?usI$>OnVIt1+zh?_U1{?3P-
pSD=4_=n<xLEh=}j?cek{*h_gK&n0w<|=L$vlk<?q4ZW23w|Qe6gW`=rl+o>mnUdRIdsfA?h0k5XF3N~|`}^!;51N15V9E>CAQNU
ne>`y<#Cg`s4S&Ph8G9Ay~QnP|dVE-k18rBi3aTAU#P|LEJp*O0w=)-G=j)-
wNlqJgZ0bj~p_a#5fD(q1!j06?pK9iU}1^15gog&7O<4a-a&N6Q<JSbX~16<?aD=m%7XKfeS!$ja-gppGWOse6_|CHz$Y`au&3BH
y!CSzkrlGUQ#Wz7-
%CcA1%&AcnLSF55hAxtNtS_IoDDp0R&YyE;U^63QPclikewX&reKvU{odI;D~AF}bb;qnGTAXmr?LKFvZ%A=RmQ_qAP|)}{yUL6k
)m7|i?*U~yEDqaY1O)$(X_X3-
|BL0o>aORJ}6oa~QOJ@SvTS39vMNYFy%<+tkRRx%3oy;LQt&p{bUPv&hE2+iJuTAcJa<Rab7Fi2f`Oymt;d8e$EfXW;JMS)@yDE`
XY5u^Obl^DwJcjTe~qZoC*j6C)u=gB%iLM{{OS7i7p8X$j#adkTdb%kYh%&$23x}0C5*CcwY&ifO8%0gJYbR{%kxKY#KN}{1r3Z$
3ipsPslOHX{?5O?_l2Q>}QA6aR(AWO}8$&EjkxUB#+WBZY<1ra&*rje8Yp%=T-eV78U*0)0fOpWYAHPA|%*xS>F-
!d?{*&RU*jE?Bak%Kmgd*Mop>>tx0Rjj`B*cxx<s}|?1c92`&QnG$#OKTj%HRJ`!z|cS+Ky>Uj*Aq@}p$75tWk#d#xrb`F4^t{U!
k89YTA3x%fduRpxdS}p<(K<y>t$5$&JPny7e5Pw&)oU2Rpt%?+iyC-QHR#IZC$=&XVW*6QXM<7*R5LmG+kaZ@q9NRt9FLt8va6ue
O|WW>>KNRnNSu;7G^1NOHL({xrlQ?y)Y)7W;89ah_}T50QL?+T06wmH~EGUn)@ZeL<_#8)TB}#=uP$IH{bps5oO#4EH1W%>}I}(<
J2*GXM#N{rYlzK8P)232IE!yVNM612^in@MrHp*@vk33BN1KX_@(D62Y+EaeY<X(JQ^j?+j5#!Ir;O>ol;XU*TY!a>}PY?a3!9J_
lX(u_MGQ)m0yKz%4}4m$2-
^ATI9IiT%eUbflX>`(VBvCw{CLgglZr#MR_GK)T%>tm1t+a26fDSygk6Ar<*%O!#S#vz}G9q2n3YW9bO72(YesEYb6{voxGazDpN
#H`*dDB(!9g9A%Y(C4cUGsUumUThLT|hRo)b-
nYqvDQTTrw%owLF_VS`cB(&D*Mnm=Hb<Rqe`}AjrX))*E`e$jq*&gvi%9T_ij=J&rI;s@yOHF<q!Ax4VA!Sq)%KjtqPLa_ZCkOv5
A(yP&UOK=OgV#Z?Tg9nOgfusiS0vW0B**9Ljf>rjG^>6S<@^UfH!yXViKA+LDF_$;fb0zw>k_nq#S93y6_UZh)pPp~+IXwC`^619
jY3ukMP~IbY@dFHxlyV=*q^vgFsDd+Iw#uIM06^%X0$GGg5_}~>}*k(VYq|u*Jb^6;m66_B#MFj{*o`dU;sk5V)$89`$IMz$L{Ca
UP;1ovSP8+p>WPmyg|wfB9p$3wJrFxcKaYnu)L4r_gWilP-
7udn=_)RmJs|hum#TCCnB(ebfL)f8;I=zU`SH2L&dVzz1AjOEbIFGOCc*3z2bM;#d=Re84o9_rEU&MPNdW3dU51}(dk|KZSf4&8-
>;8Km}V321XtwfoU7XpT^4c;}BU=u2rB{Ka(AE&L-
h4I8y}hiJHQW)8<V1OtzP|sIcwVTEpkQEOa)feYJ`@2e4IN^y{(!52@H@ZooR%*7`iW@ixa)-Z+?4&^&)(h)%mE8v^6Ku-
v3?6w`~DJZ4oKb&Df{-H&<+p#lDDLyLs%B6*ILU8Klqet85`a2d<?=mI|J>i@s^1DMnN4GtBm5bj#0AUwGb!`Kq)wdKwy0teDL#C
--41xnSGKx&t8gl+6XxE|m(&~Tq8lNE0?I-
CzKU32;eeyIy>yodb4a~_xe%uoO%&>bqjh2n|#MCULi!J2A2m#hUxzl|$7Xih1thn5v!)Slkm&em9IvNVOFNp8Y0GIlk&@=yXNMt
vw(c675U20(SCV05n&D~uO7!Xb?zc<uB3ahALbx#iXPNfD5Bb@}kD?{qMi1sjt7?zz;|uMUgdVV57sNgqKptx+SLZNi3SH9pU`d2
AZe9ntVGzjj#G{a<(P&a$!v=p&IiEtx3m5SLkRR5_j0!DJ=lzPI}SVa2cmR3D|RDR5f_nYF1G;#%QcC_ZOM)n`@<7O}9PHAjY4SF
w*@ww8ouizwQ!oM&jb8m6$Ih%u&QI=B=PwQYPeYjhyH+vE;;L!%%qTXQ(oxT)jeYSUra?4q(F+ye%)h&%JXAe7b9Il{oK^xyr8O^
G+Ka>;&bwb1<68R<fyN_IQ6$nZo$>UL}aBm(xHZEck@_qEh-Ti3d`6a10OTwJFnhKlKmX0Wx{f}4~+=*HW0=XYWL*Zmw|XJ3*@>f
}%1P7gr!H~qu^#$EXoXIse5Do$Qk%)+fAB@$)54(^xS2h-
`Ix@3!Le5_mYiZ^n+qTmv<L0iFV40OQkLU<e!BU_^7(r2cPfRcC1(fGGthrn)0Tuoe!Y6B-hjF!S%{_Qrv^z@?=|2q^I-
^&#ei_gg90qQ9}aa7gQK%baOzw~AO_QkX7Da0+e{@b@f%LqbMh<WH@KKWUSvw1Iq_Qy!fT_VsqSrtJ()aaM{qAg=}$$6oUH>*?B%
u+^~wySHtEWwfT1FgpS?={c_edGzkc^z;1d^G<@8vB!c<J%jWUG2_`_#-
s;|M`xoJp!quXD9nU5igq2zBPP(hZ=*5L*v5Eg*jt{%_Srxt4%^(5&s1c(UD2X^lut0$j95n*%ug{9^Eo@-
bBB{#&wVhzn*R2kz4}0H>g0h#1Qy@N~lXGeKl#^zc@Vw>!)9NoH}d;*n_M6G?~4ABu?C{GS^RF%XPxJrf65Oo~^AB`O42M2dZuIu
}P=2M||P4hHs$c^;DMFNYg9u=bR9_;}(2#8YJx^UY~>>0^fK^`uGu;3m|amAw+0gw_HVx-mLA&0)T_KuAaHvL09!ej_q$rrHW-y_
j_aXaUqW1VlG4-
3gsoh$(K@eE=rX@JGY#>spHd<+7)3X|0i3bw<y^Xx$U>ZXb`ac(g&vTb@Svs<&&m^_N8c)HCh=cm7!94$&$N0PFp%%c~LL~YA=1E
js*D{BS+_)jU>H+Dy>8Ym|4Jg_7^_1Lon@e<;j0RBVb6(tv6v1Gws`fg9dw&MJ#XfRwmGsE}?`1IdV<<=<vc3!X>{abzml9&Qa1{
YmouAVUt3}!DoTX2~258G7Y>FwA1@4)Z#F3o7t2N=E4mP-
dGA#_!>d=jW*)=R>kS{AW<gQ@<-XtL6Rx_^)#cw`L?Q`J@)X%IpOUn-JzS-s4@si<9_t;_9EnNv1!B6C6@n-
sg2^`;X`ZGJa)Iibw$tHxPG|%`kg{DROMbXO6Z506)Nj>;nC-
*<rWuidy!WABfke&V?A=<wI&gQCo>1uOLx3Ht?IM=7!@IS#JBriuHgGqnE<<fjF7oI<wQ@Ge=s{~9Mc=IVjoM(G;^ze8+CPi9?`P
j38*OfvEY)WLgwuEc-
&ZCrjH%s0~m0<FXmAFjD(kU&ak1l`b;C7t|tczBLMWr*nb#WP;7cfG>3Yj0+P%~?`m2Jl#d=wgA>gU13gV6xjF}AM;P~hUtUi4UA
Z0$bn`e|>mtOqi@(&35^2ADRC$Vv;IH>YTb)aUm{>AoX6*-
|*I+fRKB&VA<FR)J=!Q!j4PxY;fu0D4%L6Kap`%I5z_6>?M~!)bhGBxE*+b0Wo{=7~jFE0$=*qX$ae#~chD`y#K%KM~-
lQ7D65T<<Xym4*idH{LJP_7tH0XJ(qPR(~-
@iF7W~nBYSAG|vrde`RI|Hy(rI?PK*qX+C>4UpYJ;QcbaX7$~3x4MHtQk6sI`@u{1fT`sk5TIZX^bMI>WpTkO+_CnQndX)7R-
==ui9PTVmh~=N*A9J++w;>J0vsZ=b<H&ZXYmHIG!$Ul_?H?L10Rw+_j~1UlAmpf;sjG$dG{@$0uLhZ{x-+IjJXE|1c=e*^fr-
X~@eSeam1Q=|4Dk?eN&zfH`iVm7Q@p!+be5%cFqXDt+}35hvdR>yaoNXT0JCxk9a6j00#<2BP4i&*M!D%;@m#1;2Q8nLTb{6o`t<
exb()RQ%NnF$HS6kC651<g$9auDti_sF|2{>};WC>G^l#e^GVA!_G;1<6pl^;cZpq#a2Pf*Dvy<M~kfO2$SH*n$BRcKJbQaUBm)Q
Dy6`$MeKl7P&@gH3MiANL-=;3-
!z#Nf;T)2!?v<2kX^<x4i_4_OHXku<|H|cE5yL=;1nc%vdFekGOulf`xm3qy0s5>Qo5iBRCgGOOn>}e0+yLOrw+&yLyNDks^I?qV
}<)d@_Ka1hpjelVm(~pR)u`EpWRk7dCYaL;JmjXgdL1*cC?#2Ku42`xSeEssPh~+ilDAqzIKP0(9R|zt&GT0>0G|!IGbdRKvhK_#
dku0V-
ZP2a6_`RL*G+17Dk`5b6i<Uf)IGp!OEUOmy<+s)1$|sfRFT#07f|WqdTROg!X7Z`MLc8N<Z*BX3!x}kwK?#c^*C)tl~0v_W<{U`l
k+26W5&XR1Yhk`4%8&M+7M7_^@fF-F-
~WBF&fit;_kXNc;R$mN9A5_gE_HG=W&Fwfo$=B!KEG0u^(lA%Cf+Bpp#u0}!F2hgIubydyie#5H&&scRum<i75b{N`RJ$$qZ+TmB
OiQm4=jS|s6WSB?4E!G*T(&C`Ss0`NWOJ+M~fJOcgqX<IKq>D#~7xIp@#<tE`>q_4?PzFAb8$Hnq4Ds!+-
jM<RefEkYWZUNka7V*@|WN4K3|NcRr$+(FH%nmHr)gi+|zI0&*i*UR1!C^0K58nrtRmpUl+|@7wcT-lN6ZJUS503~u)?ECflY{Ql
2wLHjZwdA|91aKrNiL2TBn2tN0j>@NKQKAyCr~BQozZt!yn1koI4CUDB2G_P)EmELiiO57gi^H>vRS_9R&`}kCrV5Us|ubN^r!g6
L3|xGz3`vD*qGzZIyK$K?yOx^^r}m-
2O<Xon}{HKhsXgmW|J$?V&j^IZx2*z4(=`RdeXvC)qd+?%4YoQOwJ|!34Fp{U<bd8B|j_&214LX(=^zhsW}+nU?>dwEZNi6X|{&N
HRMsd649d#o&ECrZ;j8`u7TWv13|9e=v|yt7HbkiuLd$D*vO-GvXc3YC4r+nM~afUBu8vINqvSyhbd!go4##kQNCUNn`ko|&FK7U
vk!Br&HqbgMlz&&n|nNV*l4^4iaX`7+pmb(E2`FX)}+roB!M^2Ke+@p*QS>5Y8k^ZEOEG@)~gBqFf&^0>aj)!G`7iQnjTf%FD1y?
cQi|}H5r&+2Y{<i()*jso%Wl+O|nYC?4aSwu{7Jt4|W3neyqRn(Sc{n3+6s9yzroB7m>ZR2q|5*5xZ>fLpZFqnxM(1U&^fhi0pky
l}pim%*Mnzgg1kESL)dXSsjYEc|1$G4M?G~U=cvOeC1ndIbT@Bk09avO6lMm4jf;AVa)tJ9mr>_fFScdJBe*8qxFTn+oeY8@Ipjg
Gw``zjbj=^jm@3`kNQ<a8Yttuo@*HuI}X9u@azsuGm%7E8v=jj!+Zd|bPC+lSFeS2g;TVBcZtX;dXJ-
9is9G`IvF1{t!O2$(uhtcwC~A+#$Cr++eNue+kPEHEi05gu-0|<*k_*HGk5{Qz*;-
@AY1jxk%ipngZ1M|r17m_tq2hDvzqLoC`I=x)t_cM(NoDv=b1&0%E9GrIvN3HX#J4X$N&4*e(kD^K{TQ0$b>qwQq4RP&5s8*iVxp
GgC1+2(_*V%ocUQ|=9T?X^vW)#7JeJ^l0WR`kO_MnnsQ2Mx`c~l5pM1JAa-$A1U*cozKb8sIbGut1R8B+;DypfO-luQsF(AnyKup
w+=ti7(;RKMu$D}#u3$p@G|?W+5Bc&6&=k@hg`0_G9X4%f$zG;5bDRFMd3Pb0Zjco~S;#_x0!2vG0G?%+`~at%dJ*6JgTiJ4OqqQ
+kMugzDe|0+r<3y8@;BY~4LK36O0%UNj|I%y6kGqPl5@3&btLRChJ)X5mFDpSgxV2JN}NEu;<`wSOw$U&{KsbnKM^DdR?Oc|C-
&DVkASliDZjABm~qTzQXA@uomB<mdkmeM)T!8HQOT>hMb4`E8y|5v5PoK+>#Ou0EGH;7F#6f2c<<ZEmG1)W<O)C3Nj1LlODto}lX
(`w3V5Y~MIlz<e^l=WMjkFAUcr_O5*KFpN7SA79Vf~0gINbgeNu$7M5ByX!1HJ{zf7h0PARDegk4E=8gZh$!wCzV#ykf{YEM_S+w
?aBxsutp;%C=KQH{0fs}C65wZPlufDN`+K+UFHnl14@)}lkbmM~4kjBs>)KJl?O3c=cktr&%ybRnkEmEnady8HVAsZg6TNCB25kg
uNd)7R|ye&yT6ei&D>`9OdIp`Z1QPa$C#MPNwe1&lC9MEk#xOn@KoNZO0B;JbN8EOJ)#Iv*oP@Y2l{+E?%=4Z)K>0n(9qe++?1Ph
sp`9Vted1eR9ISBOwY6y+yBXGe1p$fd~{n~W5=)_fk`)ABjFZgkrWm-BY>iXOUj8WfX=*n3ZHtE?_p>LMwJbc&2@Nt`RdhwpvKHX
jof^wad%<(kL1=6XnFgZg7`spz6XVicX+G}{wRJ4YuU^2ZMiH9irA=~xA7U|9SwR!#W^zkl-
*))6NcV(f+bKVk=Go66qd=Re|fQ`#}WEy!lRfELypuNjde8Ak9ag!qx6$O|wSr`^x_uz2+4L0JPA%9Zr<ce%i#8}-
>5YRW{~tlk*JdcDK*+;>(5;lDq}{x2jet5w7V=k#h#Ui&(7Hu+pUE}uYa7^u+kU`&PQR>4TC+DP2*reb#}JX4ol%rnH0CW&`>kZH
KW)!p^m?;6ZpFlfgsa%uN+y66cP83%OK-
3k>c>MO0$9>>ZtgRPDvl((;x%MF?5il2C3WpoiY4`u>99{&jboftarE&xWsd3FoX+#}o~237diDff|vq6f(l9LK;(sg%-
|@lV0AG2Z~lb~wPs1=ug^0ui7S6+DX%LUqEalXsNf?+1H3;7zIJL~Xqh<>{;35_D(>=ET&rbxtrIy(gb9-
I1z_G?DsBr5t6r<seQ7Psyp_p%>AxufGd=VkPXP8k5h`aCwR1AU=N&Y&q3JFQ=G8UvS<+eA<`vkJ`F$(=hERo3GA5MJe^IU@So+q
*bp*YveD50fh8>gixZ7qyw~-
OAN**_c}f%WcH_(Oh14F9CM{G^OQhcNV09h>MgS}Tx&tR>7yTgO~)$i2(nyMPzfkE&K5a)jBT=FXHtM032pA#0O#Nv#xHzd<q;<{
&pRB^U4{#ZnqWCJIcpDOXb~mGvfQW3qUdRZ+zF2|LpdhS?bvID^`rlgM6n2U*b#<eq66Syf~2Jt3pD<MFE$c&)v@OgfNip%kL}RF
(d$cMRdxyXsQ-RP0w|X1!Suc*h$1@Gtey+$DBBm`0WMq!C+=obKy%u>oFH0bN!_1j*?aJ{H5J(2Q>QOnaqp5zbgjh3PZ!y$n*do;
frmN;V^#s|fWf|w<EBXL`30?40WLh<N^J;=xPJe13dU)js<;Ad3>RV7{%E72w_Yc(zasA?#n0mwe#A&0D2$)!A5HM}4%|slXUdg}
+F|e65_6lY#(saQmtWH%%p1MxHq+Z-m34O=T9&SR*~{~DDYZ<{4}c|`Fu-kw`j}@0QE5JoA3|OU1BD5eVS3zHWzb;_9Z8@jr22Ta
{1uD|;YIAAGKBOc7SmG9_X!JIwZ*@TKynKNJh(ZW7|_u;wDsWT3wJWqj_C<vEP#YkSV~xd*{49jPCL}_*|SZgPbUw=Ujf<~$eFx)
e4TQPuEL(!U$yWSH1DqM#+w;a)y%-
a3)^qvXk62#7u*?Ag;lCb@gWVQl)VD>|G&Ub^Up8cFku_aT=2`FAR+t;=E^(ouU*LV#>7L0e45%c464d6tS%+9b09LUWT=aID?zI
T3mBrVCCu`IZz{T(j|npc;kEmt(Fm1kU)+%KZ8Y7r5K>oT5x<l|r+)n(J|kEaPe0xc=Dd_PuGA$?D&RO+d(UT+(nXGmeom*5<CZV
&yW3zSaPtNYormK9*R2)$u6i|VzwqpO_W#<r&SfGC<NKCs?JjiTpW!~qV80>2`%(be*lNBE+w*y~kj>D@@Gd3Wx&2@<dnVXk0*ox
S1OY>QNm<dcUzZzJZ%k;=KMAfMCw{I|Cc8h2WIF7D*WK9cy8f4-P4$899MD;>h$lLExeOB00YUL)_VUz;nacK5<JY!-
HSI`V{x}ZtM9=fAigK||&xjdww>2`BP_1M>fom4gnMW21FJGB|#9Z%L+<L5NejHDeUuSxa^viG>^PU?uq{SJKl_GDk=OLCyLjD#R
?_fepw>Jg4Df3_KJW7>UiMueu@D*yYs%2dICVASJb16et>my_tQLa&jPSUOfSw0dl!17&KA!^(OeXEJWAE4&}rb!u@UU8bS*}ktz
jwUna$ME~1rLm>ET!q4p@02{w%!G|%K-
QqkrYu^9B+_4(+5EV`y)Z@Q2UGH=E=qR|%PR}}6)d2Fzcps1MO)X9PBgXA)1LHz{^%xPfExpbg&>nzim+_AJUf)M?`j3~_ps5^8#
UzbsW;+A->esjA$Yk?_ZS9k;kgo(O31iZZ5NjBbUNXZSYvg0XQAT#+O)Z2i0KIsjW~OoV*SdvV(_ftrR~cv+LKcV-
@WZigB`*H>rLOSEf%yInH*+$JdIq}43i`G?ORnq=0xSWr=*-Te>&Sj&b=91sNJmp$r5%<=+WDqK4Mii<()>D1nV^X{G9-
o3;7D|3}BF=we{C7emx_h*jTWO(z#WDiM%oS*UdJ|pfX@BfmP~%=<#%3V@JTe3OR(5pG7zN2svq>NTaLe#Z6bil=(KPK~Y36K9vm
m?`6?e$5RJJiE@~4&TyMOjNvztdR+qK=pfF&>)h5U#{E8%awgZ%nC+6i6k3Y!cB0z8;9=+qdJXb}c0o&R)Q*mYR422f!D@wpHQOL
MC)TEg3@KnwehXz&Rl;lDCjtVA#C}opkGSHxIP(KEQ*m-
~pui6nz5&Erf~nP&M;9OhI9!nXVI#NhQGUW_8H|Wnj4iq(NVRc7psLi&t@dxGmz9MR2ot_-
@wj6LWT5`$rZeIjaneIeOO4ok+j91F{iT3+Eg5>9IYMJJ-
U~5I0T3SlaJt@Nhmi$wuV1?IfiQ0vKtI<q?|HzIa8gsmBnlmi@Ab6cYI|6quv2CJdok%5n|PI0^1MSF<gS)T3>ODhM}mUtJc1Wqt
n@9lg3#F$WF3bg`5$>uCFJASev~}vV!U4>jC@evTL5<#kLHRikrlG}QE4Txz-!4-
xiqTVP9Z$o>7Aa^JMH4oz=*xpb@;@`={9rj(ej?f-$_H`LzJ1dT*=$i0lriQ-
+?JWlkkL|QNG+puV*_5X8nU`4kX9JWAd;H(k&l#Dd(s=PXvohrlkDn{Y`IAy&+4YjcGKdkYu23fk%oP#3HdL191tsGoO_eum$i^G
2c7Ec_8%=-
Py4*6ACIU8f{5oItEask+AzT{A@gFSmzOEyHP`yUzc$}ypWk`DsHZ?N#dh`{k1DL$Y^nb%;J2<tUl=gq)=n!ph0s>&kut*+)FcOo
-A)Gt!s(A{dOJ(@+5C<@=TeFN)FEFw*>nRozW|~&rEmShR$g7TwOIz!}r4Sk6q1NVUtB19bo@O9F+lz2&AinNTA_tdeG~?t;ja84
$SR1t-U~&*V*<S?U~>dHhc&M0=3lb!cHMO`-
`cOQc{Rh+H>Ia2q|};b}nkvakw7JmfzqAZRjZ+K<$(qs?r~_sPZEbtYFs31~hvG)|N>|3`<92X+pZgsX=FFe6zCk`{30PClsdU$O
A&pr}J$_q3^SgN9{AsE}1ZzXaag7x3fnNkg9dXJ(<kF*(vZzza!B;haoUJ<~={Fa&n8T-
`r7OqcY>myC1ug4JOL+e2d$JYHftKr^8u_45_er^sGt_4Kf=DicGVr?KL&u4Plro9H>Krs;4i*jS}Vb82FJ<{g(+0L1EoSYjiIj!
Y*nKd$_Y@Z3}*4P|#gB&!!|@eWxQC9%vN*ys0^^M}&N{BFl&HH<$5z!%7uZwk+Vul(MSvMy-xCK#Up;!<_c!FnacZ^+BS5XYjJ`R
V;flG|K+2SD?h}mWQJ@Ys)dYJf96@%Wfy(tVCOlfSh06j(aJA00F|k3AsujX_Z$^_LxjGgBScyL2fRi#Db)ngz;^Cf-
&V+E+Xf(VF%))f=$JA4O_j>Aq;hkH81U8R%8R;SaR9OB7Ggue+|qb&qwN2$_!~bFqM~wzyZQ6H3p+}Pr5&k;Y<^xf9qdJ%mTH%hz
8=0+Be&L9QpdTsSUEQwx$j}xQ=;4W4iiqOSdQJ%XD)#Ix=%d9tJ1$)#UnmDi0bFI~+vcfAIV&!9R<5$l%m`1G<W1Co9yuBiE^MOA
aEAXp~2i72aGpn8qm;X3F_G!<IA6@Yra8OBVB#FHYR70#ZNmg3k2wdZ%&0<Zo3|Xk_ru$Xx3Qh;HarqqSji9t2Q;i$?R3!GRacax
gTb9@%B`u0+ZkVW>sf_R`gT{>EG<=}8673_%3prcES{5D8|FELEH2WtYpoZ3K)ksAG;?!Zp%swlxgX{kGh{@*tannAeN(F-
{nklgJd*pVa?92@?Z>|Kf%VUi}P;2+8EzOYnxd<nDHQ8I?uiPp{UX5;k&rF$baWfD83B>Oi#Z4`#D&sIz}rumd9aEpPTTbV0cAN>
Qy8g7h4omT0RO6x4K+!y+CmmUl&n*)Z<;4&?Mk8pd~#m+O%>kLGApA2OOFjl{Wk;%Frn)LLjykPk~R)<z=C(({&ZJbtp~u*e2Gqe
i0cRDyVnRm&ifjy?=}glVzAz62BvJ@58bqh9F<KZ;6W-}BlA^usbaRXMiSLI2`Ywm-
E4D3?<{rm1QkVkOClO8u~rfsKU2!LYpgI#%^PCb{wjN?v)R`~ifCl!pxJjW_C{Kz57E{bc_U>dK12xg~ExCT;~)M!h;O19R$y7Z!
9q(6=3;B?q$g8-YGf>&eYhdrCn;DC5N5vNV8!52DKCpD2(>d(DQB5~V#0bh=YCpF99u)Faq|+*x;l_P7l39GV)=-
+C#}RBRcLU%FCEMKte4;5^YCS*(mi4N*RSJFQ)~>n(l7_Z4r4nUHy!9zdgFqdze`HZ1<7mGP|wUB<ac(@ejz)AB;a@975~?cUjIv
C8o7B))o~+T6gT6L-zD7)*H(f;jn_Z_+<^CCo58BZMzGhaoEw5_N-Yi_MM#JZZNYe&<^tW>=J_8tSR0K^KPcsS1vRen^A9T+$%@K
2c7>tG}(WSFtwYJ80ci>qo5=GRceAn}xLnku1~yDsdYbS8t>Q#@LYmwHgwrK@Hm&3u=Q={gem=-
r(8_Hs_i|EWY&!b%GsbUiDYyQV=U4MCmXAfnth9va>aHe9B}3;0Z(M_C=5H_`yq1m*cr0?B@8x*_lN1&OmHZvZ*aUh3w=SF<4yWc
u`FpG{{yd<3>971!hpeoYlg^gSx@QNW_<;NHQKZ1&~8)JKqZ?AL`$9Vx8zkwoMm&E~ucP9|Km+$lKX*JYL6bn-
H4TFZ$U}KP91MI9id40d#S!kaym>+`*4P8ui!wEd_alJT7qTpjyW-
{buG?0%ZTY@n__~2$;13a*3mV^LtJ17~p>3RD7_n99oYvth~+kj_3;cOYBed%%><QXDvIk4~nAU@u#&~%5gqn!6;7nL=fy$;dgyz
FyaP(QU^bR2@>T!OW5*8tG|ug&j_9f$SUsTA4ZLs-jSqAvg`y%MULkT62qHivgJdT$7-
Q$!f;?pN*rxb&WOML795lONJ??TWb50L6V@7O_%w2joa}#N^I^N6?6q_sO3osP3NN0Y0RbzbQk%YTQUB@vrS|+j>%1?*L(UobAJ$
yYEpsCe+NPnAi}H^3AYgvCtA+CKR}oqow@QD`$6A>&^zfMzAhC8;hOzBzlWy^K>y7>FhpDdQDjaitgM|izED>reaVz0;K<|~QnAk
GXe7=DFGKXzD7HPU5WQyat@QI^t9fLqkn2FY01lRkxI$zbJPcD68uwg|KqM{3(4Q&_Dddt7m#Xg(j)wmJqi=%bA87cu4o-z_6&o-
z*J$3GcZbnKgzh^e&-Ta7bJl!Ega#-Y5fu+~cd~N5N1WzBj_^|OQ<_R((Ttp~R3#-
w2lk%H#l6CSZ>__%={$aION=JChgDFU6!r^{X8^A5KHQ|TX<9H)m<h|2@uiDVq=pRRo_Lfi_n|M;0i41#6Q!9i}9<I^xlnMpl+nJ
FP>gkbhqQkusGKfKM9BSX+49Fr-WL<}tOM-
{;bQTx|8h$I?#~yh6S|+Dlp|R^~)di+5ofS?6w3Jn5N%8?aZ~l=Ukbu4)qKfj`LKW!uKp6ay=y`ce_k2<MW*GNqAh?#ef<Y=2y>H
j4A13w=)QgLheha|q*%Tg}6%V)nIfUi)?VpwOQ7DfEH<J&8B>Nx#|0Bi4aNTiV`PZ>Up0r?SI~duly`F|@W&2Sp+hA@IE8(~Dr{u
^gH_1)(Lvq9sN3VBKU6?Tq$g3dS@&3Dk<8@Du6YPs>0uK)m<d(a<oO~V=5*HQE|CF-9$>KFVZOpO=DGRO(TB-
t?1{_UA1It~GnCUSa(JczL-Gci?9W8C;<^Gz_>fI0Yjq2ik?W`mA@4uw1@rdup5XvBJcjLb-ah(+Vh~LiArKokDMD;KJV?GNOM+e
Y;Td3OA$;>-
~rce#hg6B3aP*ZCmS9M*hdA4+OxR106x}|;Q|I`qX&+od<XvZreX=BYT(kaXj{%py7ildU_rOfOCLJrF=*rPwQZmJ;$5&SkQ@cWx
zW*|(o94*vBf0?7w!Jyivf8PFy#sdu^<$nTbWVrv=hQdP=uhxQ7HP1LY{Kg40Shi%5Wo{%s{S(%iHJg`@Y5}v43bS;S-
YhY8k`@UACJd@-?Hu=ODS6q`Y7oE&Njvc5mr7qsX@5bco)b~M<i*wYe_=`y?|A}5U9uy&fgv6BRuj+!>4wt!YPrF}dT?-
(gX)MJg05;lNDx(pT5Gf)>5W}<hVL%gZ9Vh&r6qXJjH3`lR*xJDPcWO$SVLt7PtKBrMxedHf2BHI)Rtl$`BG)oHOY8v#;NZKeSbq
{@%xIY?w<7?wQuola@C|j8X=3GBomfs{oNFWMOE?}57`)`LQNSFtMV>XPP6_OM!^K4a=bm@Qc!J#-
R{#bUFTa%F+N#d868>^>FJIH=9Ld2IC&y~p|ER#<cVdc9vnQ@-9<|>ac+`N!RLLeCIJs~j-
L`0pix$|aduz)B>`v4^{u8STnVqo?H=bq>c4zBxb=;qpwvhy<%*2Eyc`(V0T1gEH2Sa<cBZZE_;s&}pB(e!QR`O`Y78Yvj3aQ|xB
^F86@@upWi9U<IG~Mqlil!u4ThAkytN>}w(aOmUF*o7O_VRoo$maPMb;kT&B>8RMxU)<0AVRX4C+46BwJ#GCj<oN^yFV0#ver#B%
Gyx8I_QFVKi4{uO~YV#OPVu5xdwW#C2a}@7R>;<}2;pd_x`*a_|WivT-aLTdppv@0lG??evHmetSoERV5E7Z={v#*i4>;2#3^$iH
p7yl&+rKqAzG*BjAH<74?naPckn9bsSl_Mc@?5<NdtA53zlbG1NOUIkcZ~nMYs@r0QnqiYy?h@u;B*6*z$f4T<X^5$RSs(G%8JUp
LCJIel*MNC?Q&Q?hPX1ZB*6AY}Zf&X>P(k1CExSh9o(@3H~YRiZK+x(Ci86;Yb1_NvC{!Sf?^QiQ!0H7<^$_Maa`#4D7DoxmW<0_
ipfg)5Wlv>#b2AhjPd{A*OfLAgd0Urf_VTahPJ`}mtidA`XbN^8LlBv-XEL)OyVthOvk;Eo2LzP`Vh+ZR?oMvou(M1z?^XxYiBoS
Mx`M~JbcG&^~K1_;T6Gm$m5H7)_At1TW8`xorKbcAo?2VE1ykPgJ)t;4YcZwcm9Hx_xn(SF_3KES%|+dNZK{yd@y;-
L+f4%tcJdgd7&z#f%o!6&Gb^S(0YMVv2Hb1+ksVmF@dAqWO~03O_7_cbbwZ@qQF^kzxdy!oqQqE}pKRJCrr)(=bcoeA_!E6`It95
VL2rh#>OWf{9sNf+VQ^aFcCt1Jz`3eFykI#I@0u%vldn%GbyH0T+BxsC%wFS^_dff?;ZV4W<J-
8v=@i=^c)iBbHqF(`3H0ji0@vlvsw$aI6fCDC@}vsNjm232)DF<ujr0zh+<lmxM3+u!UB9(hi8JZe;cFZa3104#Q>+`vk3JDxgKK
b6gZkv&V>=4%?hxCB#J!>#;@xV}|DB_D(n>VX66$d(uxV^@B{93`2Igr4dfv1An!0u-+?6_JL1^--
?vh7TPIRHJ9dudzr~H>NY~bxbrfcKKA#mT(<?^z!9Y5D^)Cufn?P#^p5LFKG_p*W@KJ_DLZ-bJ%gYUp@Gm#9C0Q4a@X0A&0sJqv;
CtD_RI+EP@3lP`N-
<xe{=pzmj2)bkpR5;5TnZY6(J$l^bFUm>jaoW5R+(w`JTPndgbEz@Y?{Fl~mq<p#(E@Y%E41_g+`S79Qm1~f*feh^FSA^^RwXT+9
R3akx84sHp*PC9eB^xkDnj;gX$mb5QcRyv{GK16ce#y@!JeLN}H0-
Lnq!ra_CWVmFgWMLEgN>}o61=<c`I`Th1Se5AP4F{%|LDM=f$!)Rg^*VKg;g$Kq5%;6qEcPr&o!n2N{5!(1;72#I@HTBKtI&(ojI
!&mlo*0V@)9!28IjLJtCGK5h$od#hd3e^yo6F(>f$Ne^<Q_XVQyvstAor}TE>9M)Q-
D!yz!vmg#HFm<BpPzw7?!Jz9M=}l{bSj2Om&Q4fi9^WAu|wQ+jH3N%(-
$5@3OWad3{My=wSrBdAQJqjPT=He3)$hmTv;8PI?_Fpld9qX?uoi_hi?1%-
<(4Eju2K)$@&y4d*{u|6HCL#)f(wqWlRE}E_xoM*i*<`mtF`w3F(4PyBjvL2vAL)JwP!Lp@Vnr{&%yN0*b;ukW2|B6FpngBrJR*!
|3D${w}mI6PRrv>pl8-
8QM*;L^^(?e~t@2|T9O&eO1yB2CoBav8z+$Zm`E||$6g#SHU&7&7(vO0jJRW7rh${jn8QOc8_8(U=uGHAtTK&+9tQ!TJj$@x4r#7
>?UpUe^5oNkwcA@<yb$GTRitaz>zG=ffj;7?auo~Pvl>5y1n#(1LpyDj~^0JP{P(r_BKKrL-
8m3xL`rjY|0b&lE8`8~HIhL>A;HfF{~7S*+p?_CT~W?Iu^h+dpB$^R7`EshM4?nCztA^U%0@ZtM{@QqF!%Rna3;P`vYcc2MZQX8i
S(mPO17#NQjc;-A_@`EQ(pA)35tMycEy81YS%AZ(SBU&s#3CpNZJAymNq)z))Y#Y+R_oywPqLL7q$yqd8W8GL0;dhHAp_F$-
oaGMj-<~YKRsRw$|F+Qd0h$;y-WS-WD;nD+DFDqVjzG3Ii|yA~vxgDsQ*-
)C)WCxA<(vXTc0Q#=g#37$ETyl@WkwKV<W`ca7&hPThL4mK%#^Ue(r^G-9r!@u8IP!G6R1RZ7WYs^mquGO7uH%!Hy$XeN|X-
>>bI_XJ-=yc#m-
6S8vQo(kNZ4Y)<ve#^L3r&Ns#KIYd{nS@+)f=f$r<xu%OB47ct9KzxeA*4!0{AVJ*FC4nZaFRcs*UV_e{&qO3Fl#Y_|BcH`AzKzk
zF0L~A(*~jFGc~T9g8f5lVZ$U%$m1fSrrHo5M#m&xrCbS{bhvC>f=Sqaf=}op9jwoyJ%n)|D{$NO+h4@3&YRuXRF=ng)--
sAA_KG9~qejWpOq!(8$s7nL!gU#gY@hU;(jebIgEBSj`UkE1Yp+01VI#G<9r!;|QJt}3X2G0NW9{r(C7@+clmy4NiW;BsfD$!fQq
LvTt@BP223Q!tih5_4!t~z+eDS$lJY;d19o%_KOd+>Dk*Es$n0{X_mIQdn>|f+!r(pa$esIn$cBKWyMeMC)?UB$ih6sJ$_A<Y%hD
7C`^e1BSLQiE_@hL~?k!+CJpn?u6#9Mk6VdS6if?x<-<FAWEF-
$*~s#zC$m2iR2q0q@z@oKHl1~YInbNQ}8sM<e5SCmD^uJOku6*;J9Af<)oUd$Vf1A^%d{zYkzpo|#JF-
c0tJyC%+|L9D`%47CVPhFNIwUQI^oWqN3Hqv%3HHXdilVVLrSVM+u37V{DAEtv)6`^KJ^}5{>VtjqQD2SCRW^t?E94~{|F{MqH+*
}5OX?s5NQi~!<=#;3_zI1c=M_WC@he0PaV~VZK>52!&Hi_rx@kb|%?eXi#Hl|hoV)U^Vl+yEv-D8vs%B4zxV{-
4*)zBVbwHjj*h)Qt&N=`ddlC_v3okVaAS){4bi2N>tW_oGDQ3rG2ENbLo{)zetoA^St^26>glbLhj_%#Iy-);|-
SQ_KrU@T)V(d%JQg{>j)rBHte8IlHWG%j}TJN;fG-
9<*;r|jaP%598I;%m+*gQEBUwCuwKy?!zIbOG#*EV9lb(q}Y2YhWX!$1Z7GeS@TcqMz;$>vE!P0&Lg!eSWYrALlv2p&FVHzo0Fqe
$kQHV&t1&EN1Z8)@Rmn6sJzj8nbs-@nI7)Nnp>eUeu<5XPE=5H`87ZP~C#uJ!ZTuf6-
{?ZlBwtw}R^{1l99r>>Eal6e$N<ne)yRl6HXApd{0MGw6D5>{rxHrUL?jNMju^WaYphbloM0d1XPQ`v@AJ*;f^d*FmC)gw(gJ$hP
0~p72MZP~G~5%1o8dkV~iNz`VX`Y3EX(M#!lIg)i=UR{|iPsa)$`5v8yu@Xk|jtMgYKa+C_Di&Ltm#$aY!0O0|{)F2JTia>f8He>
+RxDd)7RL{jGWYi5RfK!%RRyB!gPt?ITnlKQ=l=PkM-8;x7`PF<4jJW^vH&!u%h%Ds#TwpdS3thg(a};Le((rKIm9?t_$78-
JjY?>dw0B#hbW2+au<%sr|9mY=k<(YMs(p0WD%L7YPRr`}@#AM17u>G+4PJ7`=Wu2=eiCbRTgt|xZItrniopUmv_{ISu<#H^dGHr
976Gg$L{L^R+D$L&-W^8|Mi1NE;w-
d^KC`l>3X0}+KLTF|dv~h09O6Vkj4gXlkjcULTDWRdbEM?QHuWuGSH|ZH8#UpFvtHT|5QhAFCYz0U7!b-
<#nQ<FK8Rj7aBx&P8x)9_S4qv%WFoqA8F&_B*tn-pvBtjjO9?+mI3%p;gHUj#)S)A>+m@$7ToEfeyrfOD;k_D#si&CaW>bko#nDZ
y7agwo7XVi2?oup%)PqmSgfw>T!+zdzuFA_AJI_M6B<7A*KNz_t8W;E1*39>4lpv*f1(fJjA%@;0qI`svNWjoFUL6#jP7N5bKiyJ
{FF1c7fOTATp0QKEzV?28PLg&ypDdNryww8d3x<0tJ}Y|WcAHuY@@@jEio%ZaeN^yg)3z;lSN}~nBI10LH8a^-
|9zA{JnpJE^9P*$JYoZBSjiI<A_y-7miM<yz7lD;&xa4_vBi?EKCy-
_3~9F?2ws9pN>Dz1SmJch?Ue;!_(&B5Jq97djJ=8&WG5GU*lQiWZfTJid1>peaXuBnh{1E^(Ni=?_>=6z)i!BP#=zg+ZYK&hm_zn
cEN*K#X)-=_0;KNlX-P03(~nNFn3OM4I|Y$?;~!H79=g0t_n|?%Hjo1SRVhZL^bVIljX4@2Jf-2flbm!FkOA-
T+0(Dik6rzLyb(QXd}(AYj6hWi(o{pwx516BuIsb8FQCQMvN&W@E?67}BoDCRPTSGz%}aHVY3SA~wS$%rHol77j_Q6<!TNBWMzlX
z3;wKgcTDNdO2<>p*OZd}5+I-
jwpdvep8HnuD_E0A1Y2#}lvxdi@{WZ|+A3<nY8A}H7k!ECM$k7N3PdFz3$1Il@N5H;*@LcHdg%hF+PAa@)vm}`jDE(SubL&D%iDY
0bIo>;E-KaTYJx3C6mPM77-S8V=7?)}!}wZ!eLjli7b;70+4StI2DdTK${`Hx66S-
y@tIo5epJ)9!Vd0U<m2sQlH~8Nk2#W1lAC!@Ji5IZeq9In*<&*rht~&(avv7m3xM_TUJjZq{tkmWL>}O0JG#^+L!i{+osY@+t3UU
07xfKAnHET!Zz57Jgm)5?hkOw;SppDO&jyT?v;pl3Tb<EtdvOjh2P9{<<jk0Z9q8KNbQy8ZyfXV^S3vnEc1Pg9fs$v#JJtZXWP5h
9MoRc`w_SWp8q1xs`0!oa?vx$4{PJ(+npspFYOM9=ir_o1a`5O0Ci6o|Nw*4=BZl<ErP89l7y?@6Yink{zW(Kj4H`!C>rj&~GERF
XPDY&Ao(K`&91(L~*GMGDB1v1Ld0?zV*?R1in6jWQ8eI%x_o!=4V3^MGG}F7$IG|`bI2MM>h9u48Ru0br$%a3>uBzBEw7&><HAaQ
mv2{jg-Ym0a_e#}GpmZiCndDGYGM?!cK@i;!g8!wvssY;mZ>`>|;gWf4F=;Y+&_H&j_QL%Fv7kr4QMVAz*?%QkNgzwrZYbbzskV@
`c++xI+@*Y7dfSeXhFbsk%QzuF-
2_xwDZ#OB3DfK_6I&0lu2T`Iae4@lp0meE0JCD>T|u<1^9HhM5q+~)Q8zg{_|_3b8;7tCJCs08@`#k;#CwzXk+Tr($(_w7oU;&m^
eaH^=fa`~;s!dUy&G=Qg~%Zhf-JnOK_t2esQxPSAW6|gU+J`ukT{3t@dIOfOU@oss>unT{Of!CI0v}eUF>G*3)jOHNrwS)=F0X_d
Tm?rd%9^_KW)1wl8A|<<t110Qee^&HSj`INYYp!29Ra-
4w^k{AxUs+$)ww2K<w?iJYXU|V&<Rkz{JI;(BfBA;pAqf!$g>WK8i?&RGXCpeZ}$OZi1!com%ycrw`_3ZVyo|-
a7#s*!W^bPmPCN*c-lo#iT`kK@TD}g&7JQyyYehf*7gay-
FWO0H2J7-uLnQSyobHN@JF;@f_!7S!fx2In@8Bw8u=Fi`Q<J^-DRXhvPjRHqoggK2#+JsQih2jdt-
LFTIFQ(p@4SNhx*!{#=R9?7Ix)3<Lqdczk#8Oy56kaetHol}TbRu|=_ErEnZR`>;;eX-FcE7UZ!S_E(u31`xY3jQ%wr<NI-
C+mN=&ArrDt^p3v4+UVxQE1@b?yOa_dksS5*i}1hqGGy@yRV|ofUN5sUNC@9{6gbn%mz#;QSMP0}=+zvu%}i@IBE05zL%`bi8lDT
CZB8{nn_u!grb?y&0vZb_1z@d8oY9Q54`NV_V7VA0V-
}cXAEwe*)er!xdL`@0t)SdzW}03Q?7kvDisT#dQnE`pC}KJ=QU~pD_D0wEyueYHzmO>KC_!7<m#8g~G&9&GK6dlWMW9Z2!e<;T2p
fEs@9=j9TZ`RQC3tHLH8@D?{}b^_rAMRdaN3bF#{LZI%LIb;J7?OFCAxaXl#XAJE$Ca}>6Ey-mJN&oLU21Tg#B4c(y%Jdsk~5bs+
veO_3=V6WFlcJ+{WTRzkw2iwI$>9=1o(JAQZrXq){OZ?rF;);VMe&dI&KhV2QjRVYKZBJUVl+?8|$=Xt0rHq%QP)#eJO1xOq3feC
Qas5+?Gy0k=USth6F~XN8%qi;U+!al5-nx4v#g$}T5n!f72&s_!L_tii;gG4ex_*G`Ld*d`dUyd;=^-
Wlv1K&p8_veNoS2*4K7?;S+L1cASh&fDy~9O|O1dX#~zRPT+-cNHj%=cZp!u40rh$V&!X8pZ-
2SvB&MH2AU~VdJ2llzW|c+gWT7!kwLL*n`X_m9<Il9v-
5fD>wQs@0dgF43ri6L9T4|=dlE|B@l$00lFYxs9`DmHS+DXIrhp>FLyy4+#a18zuWBHabX{~RU8`D$<P?wYR;h5^x(vy3Gt~Pc(~
dA$Khz5Bz3Ceo>cl?8qf1~bVii99rv$%ZXv}8s!>;`;`%*PUC-~)A<(FZl^y(1N!<P^)f0h+995{oxmbb4ncp5E^O8izW*IKA-Db
&L5Q>W<i44JkkpFz~rYlFUL1Bx9Xf3|F)3L;1d;}h-XSI_OfE~w50JK#4qOe-
i>7e}dv2WcViH>g=Ex5b#yqj$ZZYnU(vY8&ma;hj{TjekZPnY4iKf6tUt2-
X`EXao%q=5B&j7WA$7NEHFhn8v07X277nk9YAgj}2&YZqNVC3;z-
+B1nSV&e7qLawT}ew8@sBN%{AaIDdiE+4z9i|5K^n4`&I9BH1-S^-m`n$~+FkbpI!%vF@vAFKq-*M+zDAzO0COkFmvMI8-
84rtlYz>cR>%jBkX{8fNptiiTlxVbnA<@xrU%R{We5y{X<n9Go-zA))a;5A4l&UN18^mhMvw68R0eqKp^zCoa`d}CkG=>&Zp1KB)
*yS2jY@IAcnyGFF3C!9*?o$`No3m78OqgSwcbupdWT|u9k@84x|SqEhuCHtBWO$Rbp9oH`H`Y)ZFN%codN-
2%y7pUN>sqqzbP(1FYhEeK>vn?>8OK5!+g=p+s;n)AvoB9VoFxt)~Dl{@OlScUd<M&_R$Y6_OPoCzCb;D`~(D5zSoPe`KKiwM6eA
}2i5-5`P(Qn@Qy$-F=g*Wl&b5w2;$5kVjVVh2l<`BM@qi<-X#5!IzaEBfkHEkHEBbosfDPjCbh=8hh#L?;vUtc-
X5zJ00MxfP2d6R;~SC}5jr4a#0I#9*rm1HXAqz8Hz#?P`svpACg)tor+cS4F*G@q7lGyK5@DJ_0ie26la0AKs?3zc-CO`S0vIcua
V-
S=kn9Y4n*!)H`p{r{S92~OwQIti54mC(&aIb?=?S*ksA84cTIe4&jN=nS2<hpX2sYV=4tYm(i1qwB32^ePs0iR`i&pFb?h<uMHs&
wjDn-#bWj%-%)-l-
=dL6;5uNB0<xncZfvUN*FzQKfw;jviEnwi2j}6P|k4#ha&>fI<aohA;oxo)o?n1Gt8X9shY#em>mgS&qXAw&(3h~34k?~Euc}Tn1
4&ty_BT2UjvDUttY7KO#GVvTj#|LjWgQvt76T5DD=4@pHP6kvhl2yFVu0<DJ-N-#NJzU9?-+vs>b-
QlE2y%Ks(<+S!u)MQN_pIJ!t>{5kFr0_|?COUPOb##g{^>SV(#}VRQY(HR@D}EmtmtkPe#+2UMr>=DL6yJVAU)nP1u94x~|u_^#$
QUf%LbR>V&Jp{o;L&Qe6Uu3nOnwLK2c6MRRklvrzQLeCqoL{A4?_<&p-
B!EE*1}?$yb}BYF+KG{pe_mwH5W~0(nq6}e5*mx5%!3~!mDwX3OVj%eMW2(DH<77GBf(WXKRWniUP|VqZ#Vg5{v^QbG>mYUNC>WB
)rvS*ectA*`yB8F$*F7xooZnu9<S4H+H;{^wH^Yp-OnFWI#?&%$B8ygO1V4}C`4O+fJClh@jTJ&+N$@ksW<LYk>xcvC*8Mpu6gsl
a86q(FK7N@&dKkazyOYog{|^!W%<e*bl09+`k%YGq;lw%O{LEgM;>T43LfRw+Z(55H>{4@&&`OCVz{y~qdNL;M(+)q*_<b{C%%b_
40IZeL=;jl*kTI$;#ZgmT(|$4eJw9~QK{ig=DtBQEP5v+hTcn!76H^nTjWefP2Z7M=%*^tiQT39e(~F~4AV^>;-
qGub)a*TYkyOQg#S|l=4ez>AR!2^P(694lCR<yuIC&sj>-
x}qDe+^9W;Ap46(+vN$rzPx}ETAoyZ5HpeujoY%P#+wl?8H?U;T;`xHa=2P?|9`1zlyu{s3r0zF5Vo@8L59ZD44K#!Kx!_l!z5i$
;;>v0xy7MfmY6|<~jAz`$YUh81XI??E>Z3q8uYH!lB!L2Qq-
~*7tH^`Y2Rn@d0M*UNtnBDc*Qnt3UgFh}NiQaHZ{$D6c$K%`~U06&=@6g%_4r!XJK3_$tne^d4$)TZwV>ONv3=#gyf&*m$p%y#;_
^DJ+4?<~(LRxVM6+Klu6n2a5cr-
i+u={QbGet@Y8JDdzpZ#v7e+MP<=%>~MWp*yK9ODz`AyFv`EKVWBk^ae^#VBymSWT#Lm!_!D*g}W7zBs9d3l*JZiGi{5BgJ|PRBd
9fAr?!f1TzFBiIu{^H7CDaasE}Q8Ri}y90MB&Fcs(SmN8;^M~Qr^(8dY%10t&)S~L<*u4!6)UcoF4k~wIiNpRnSL8)!}oO87CTZG
l{(m(fV?`XD2r2~|5x0~~`&~*+C4YX*!WpztIM)KE7_3&gys<ruUu>9g@rL45WM_H<5q7s+fKXw#^Wn1tb;G`c-
WZhB)1`hW)hX6Lh7E|<D<_J1*#5~^Ji7o}vU%CCdoxgk)J!bRSJu`WXvU-ihGMql@13w)nhQ(pP-
(RNEpF<}37zmZf$GH{W&m5dA#iY$esxWD})*yrLB7n}B?21>er6|pIyE*%ZFCZqHb=JXsER;7}?i+FVv5qsrLzQfO$ww%^(>52nL
_3-I2()u1T@M1f?on8ExoW#bMOfy?#-
l;LtgkrJfHh<H+r0|<+P_;Iq1z^2h#hKf!E(Qu!do(7)pmb3Y#H_FeW$Bk46#&j+?JR!I0`B|jHQos5e;6TXvg+9FkWR`^=CyBTP
vJV+u`FGgR_HawyILsYfH{dxXimOgH#4@dh{ce$91g(2u!G!YdHG1k{0cdk=Z5GC1HE^uwv~|_4t2tci#AE;Gpe+Tt&?PRyT^ot|
O`5o*^N)_^{ssFL?$FHB*Am2m2*T?COPcRdY1=+nB^(W>|QO6lNtJdErW;m}KW(#A9`n%ZP|Y)DLP(0R8~Q(Xgcvv!Ekp2@zx09B
fXPr9LXs4>kkw8{J(2d|W%p4ujS&2}CZn+5gb}5(7nF<+&gtI~GJ3yZXUpNa3G-
+<=KiU;b9p?Gp_83eBiRe}cy|M4K!=Jil|2)2;TTE3p`kmM5_Z9iTSJ0i298@5m$Qj?k1aAgIjSAjDc`aX2e;6ZS8wSJK1iLa7%0
<w^T~yb4n!oY^af44N^&c8-s)b+zh0vjEpqClQM>%<2E%B9?s_Jh>PptD9XOn73Y)UWp>sGK<1m7&{O@P{<slhX-
(o!MMdEZRsdX8hiB*_m>L=#4+zGxNT)wyr+j@`4Al<(JI<u#?k=d-
56SZY;LNP>21_!d#r>V40nE(G|G;;w<hJzUSE*1F7~%Y?^2^K1*5d1F0n_sfJhh*G()}pPnMVs4S;|;a?H1^DPN4%6?xJ~xQVo0z
Y0{^d?7#OD>}*CvbLkz5m9bD)UQfUbJRyA`Ow@-lY&|{&@8d>o-
MSmQz{?_z4Lv>fk>ENYc#UUIpDsxQ5!>L<V*pQk|7pFkm?(^%0zfDhzLl#tdqj+D=oWmF<S9JIwsN8oXyujjuMv_B2HQ_E`Qy>$6
$6qDf)_0qDD*}`Pivc`=3)?8Bz7;OUjJfL!9lQ2!$&>tT-T!^{8jreI7Y#8;sVizM_qu5H>%muti?97cHmK-
|6_o=@%%bh&f12BslORZX)0q>0htW_ANu`F-
*2XO+{$>G*|R$MMKI`^9RInqbf52>jlV;#$a#z6mTu@UAyi4vM0B_^C+<a(Gue9>w(t$?S;$pQWG#nn?^MF(J+Qfj9pbesjFj6Oa
1DKEZ7bmsIOFz8hrvH0FZ8$P(bBWak;bVAiyj?m4;Jxcf`VHZgbO`j3aD{n)9)TRreh(vFViRWH0{)^iG4?|Gnw@BpkwNHifXj!c
G~~(UV_(b8Gr_53<S{QYV~e5{j{eb6FQtuNJxBi|^?FZpFSBL6PTVGp6g$DHo@8z3^%%`8M9cD14`urzSg!Q(N<AWgOH$zdkaFfI
-!w;xx2vuaa24XJRp-{yv$E3rVuwb?{%-
GY7Opdq><Y3R#<$QletK1hvhTvp6Dv=eV1TVr@!Z@J6XjsfBvY{82gBR}#<`YPP7YLx4hyCe@`;<A`#~${l4#i3ttqdpn*qka9ON
_qc9lK51ek(v5Yg2=sC70$}fXO^CdYs@&M7jiE~)RS%muMRV57ZD|?|beTF>J4q2=jWN&oUS){fC6!IOeI92bHiZnsc`OszM)h@g
$vP2y)I}`J_3b#H6hK$gndtTN6t%l2iz(M9ylxw4WSuh*jK2^!GtS`%LU)37m8cVrjEOJ+9BSNty15g#rl*#t39eDVsUuh8V7ch!
4m#A*a}bLO8dVy(cnHXo*zZ)E?{_quK~-$9c4H_eoEpe4B2rfOXj@J8SJ^Ia9fmmiZMT=%CyjztOqWA9$;2*sImX2k-
=<M_tOiEqqK-)wS^fDjMPA&@3M$SJotqT)3p;iNA^9+D&l)S*^@ccr=%=h<XDAyUQS$}^2QCMBe5rDx4Ua)d_qF-
9K`Urm$ZZF8?hNtSiQkta9Zz6oySF+`cq=T8C5U5v12F+%6o8a0y0EyrExhR@)bE{!r_<must-
8~xX9;;@1+U}o!?LR3dU*A$TNR2N`*Aa)NCxxPm5X8?u&o|)Z)YdUk)>nh&R8fYAz;+nzbK7m=^6bErGo=8NGR`?sbtJS0sCLk}>
I*&;0wd7nv-#7WVoeVup0j(37p5x{{oqV#MxT5^k(xJJ*j~5~Afw+)M2=Q2)<dWNY*C3p=CFyqo}QIHz@TxeQNZS4-
pcDJ3vnBV@OkB6V<r{}s5#=JbOB1}mDcgBVRD?b%n@vpVWeif~~Hw7V)cNr^?(b>vRSC94ucb>Rsux82Z8pdgXfD{IN2S@jy-
7#}K4X%D7VLiQ?1`Wi5e{T+*!eqqgQ75_=UQeuCdO)7f*fl$vMTx|Xy|Mn#y4pf|$S0_;gE#^L!@i(oH=flPvWEJRfIqyM`X|5H&
N=GNd7uxTTbo)CD$YH+kqgSHBEma}=Sl7wBQaU-sn<^w9^&iuzvb(^Bm<;2+S*8+-
s|S?%CLc7E9Op1|p6K82)J?S;%8pH8iSbB>ohE;S&puD7H{QC2j&qWNYl>PRRGt7*_g;+2KMU5KvXpD>^u{L9mfCvOk-
+pkm<LN*4ZaE@N=f3ez6-pcfB_AXVu2Z}YwUT4fl7J4RmDBA?Kr#RvJPuC`A>8gi07yeDcooUyx=6rOBTDTvlCYDJJgNi-
Ibs>ay`BIzON_PjZ~u0*w8+$ef9J3uF!4#i(7?JgsP9tNVJ>&Fb!I&=dAgW?)_xr2!iUf2GOlBXLo9-l=K|}OO-KYA#{tv&9O86C
kgBw$ELl#Nx|9Vkq+`Z%4r=}9Xs(E$*b_T90@X2%8(L3AC%MIJJD=PAtiD7ykSPDgB7aj--
`nGsHG>wv7+=z2@J=2DSUeOz_>apS^>+7mL^79Uf}E2x>%lp7^n1;N%3*d&S!xg1N!_h;n3=?^Tk|IqeL?EW(5}TAIfr%D2qaweg
>0;bI9;1O1ql$jhL*rrngN4!=+%{M^ttq8>R6r>}VuMXw5(r%C@&hvww81BkU>S?U6O4z;X049`6JWlii|W$>nb*EV~=c3v=SlE4
C27=0go=6W=LG0pu944ST`jawzwf{#A_0J_nz9$3g{eM7S0P3<eEo6__2*g<(jL8Kc5c`W<i!N+-_a=2!Djus}zFf7j(3&^H0LA-
KnY;-7u*=o=+8&+Ur&Zw-lV)V$0|RY?oMR=0o$ChPrySSRZj)uQ{oslj66C!csLH{W{CXr=TZzTy%nM0%S`5Q+`$1g7V#vX7upD*
Jrmjolk7Na2IBCveXBBI4JkPrWGaR4e35sP_J2C$CM8ap?A;c8sXs5PrgbAtzMyro0N|vWcX>Tf_0?CaL!FO|X9LR}`xRXHn6jPw
guvm+;FCFS|)!o<h|Ib4NU=G*+L+OU6;&Y`{sC)7ec&1RT17C!I@4RBeXoi}N--B?RnCF9KdUlj*TJb-
!)Rs)`Mv`@c(9FljB*JBx_Mc_MNKODDCQ?N3qW6~3gZBRd+%cW)aA2>}acU&a_W8cHmOY{;r6^&hYBHEhZ_Yu>pv$u4{ew{Mcbn?
_aJq4F7~ix>)fR;$fV4#S<32)5W|Z?o>#REff8D?L$2;E|)PUAW<Wtxs4$X#!el)90_8$@J_OAoTvpPt1emGTKK4_NX;I!w3>6!$
bw?y?z(q36mlfYx?)`yz@ZJzE-
^I%P#*uciW`VNtUK4&A;AiKd)j|t>}J$tH49f9&)V!wd52s!TQYw4v${(8qzM;>A0<iyH|lqxZ*K1VZt7Fo?O@sRpJ;LI`jl>zC>
(l<RA56A73aM`}mJ3FnvE~D|&zO4Zou9Xb@-
&+%@JSSJA1l%mptyhZp85jk`sUm4D9eOxSX*S#%mMY7r0!HW8;mTefpthX{Xo3Gz5Zz?m2%ClFwA#kiQhtx7&Ajzh?Ifv`fOXzZX
`LZC|fn0ywOHgC$Pd>^TwnZ@q==oNR?{8*;D!TPd>ZD{e>V&>sjoXMSAyv+1gzOCdf52AhW82gK^PKc&7EACR(^2(M-
5`9*i2#6{x4z`>JzkLV)XJ(5YLkc!Xg4LlY(X_lvq@*8sJOJ@h9%n|;c~(+vA)5md%{fDEN(Tzrvn(KFs&+Y+BcCE}+3dO@%@T?@
S1GQwMCIpo+>9oXJT|9*N^HAr<QI^&yj|cBRRp?sIE;VyWNS`+l=c*mqU|T`%~X&q@33qS(H7l`i7^qOl{69K&8O#dF7u<91fWS}
YS=<H(*z6JId)V}C8s@UYI!v={iO5bqO<U>wWBfBU_)BA_E9Gx`z_ztBcVRj=gq+_IVHH8^#s@gXy30Y@!HdD$D~bt{ypoIQzs}<
^4g?r<!~2rMTP$%`jm>;w~fSnh^s@VWAY(-N+Klx@VmuEDdiy!AFX{7=4?iq&1r-
Zo7vgoGeDU3c9a%VQG@^o08qc!#HG*19}`}{Lnd?}q2W`FaMHa$?UsTe<%P_|F9=m^e>=z@W#@RMPp;9)D<duRa1=J|)a`R=UDbS
&hT;n4u3*w_A!OPDbz;r@bA>1~o%CG+IULPM53`e@9pJuTW~$#OEjnD{w-
<Cplr?ePu!`*m(xJ7BqQrFl*2p_F4~<~cnxej524N~^Yqit6w8B+799bA%-0VHv`BBjmRhHEZISju+rRHahX-
kE<FkG~nmB1Nr%+Oal*>b6jRWVj^v4E#VppSZlwi~4u)O4!!=z#DeL;5xn*V3QzeUNqeBO9VNjYQ5s)RLVC=x-;0t}AIMa-SlD3Y
myx`V9aw=vv6QwsA&$yG&m_z)=jTeEE=BYNpseb4^&NwQ?IMXUjNT!gG_GQ)#7fYM=eEO?#grSgGN%WdK!6fSFMKCsbCtzZwi~fa
kr`;{CjZe=k?}M{tM^2+k@W?N~<I8t<~2OZ-*Cc@EAptcej-zDipf%_~{ofnF=#!0MTRG3R1~Ut@m-#;UzjTJN-
Ny6<_(5%D1hLq~od*d)4?G2NzE;kWWxX-tdxi@r$NxN~>bcMHQ$s&_-
pCb9?#G+z?+;Z@?_K&Uy|Ywtxwgg1YUL#{zWxD!y&LMMjtXRiu7&x?n1m-;CcgH)Tav2b%(SkmaSK^H8Jq-AuMM%3|mUydb<0H0X
OWlwq`BN<Hu(%3ld|HOeB694yVq1p?OFiU7Ko!PX=^x&|{u8Yl7Dwb9^XaXom%uPKMvq@`rw!UnxIveP9=_8b4kKrL_m_87&TL2f
=#db`8ESf^pRWS}BxuQ{3PZCH(6y=P>^fbzqQR^emL}fcjsOADM?`lo8l>Z+@3GGon8&mX7ydR9mq1p7D@|(al;&h<ipsKA=MdyT
@Q9e_Qur8!D@)c`R(A~`qM`Q%Ict^n@ccSFS9_Dq;F2^)^%ibY*Tfo|%JdPO<aq7%ALQ2wt!)udrFda5gI1;Lr1m6S4`P0HmYgEl
l+!|2Q$6m5GHDe)@tpEHqyvOW^#*~hNwB*O6@TZxem%(Kf7?JB`W^Zg1gR>~{R0*Aq)XuSt@-
YO}3z7}@7w#;3?V=P;G|X^_pF_M_oTz@zqZIS0VLO7Egd4c{KuAJR)_A{@i!wyB@9Lp<#U4C+JhhhvFkW;a$Rd~w9OMC`)PjgltB
=6MMLf(VL|MujcFn3ZN)W0Dw@a-
)db6oMd4Ap1VS3Afl?+P#I||PH(Eu_s05SP$EdM?!X*=|_!~o0UhQqhgBSgy;rXdtUR6jqpl&%~7pV`q|RxgblkUrwiqDbucLXzV
X#QVU>Qg-lUy?16hlmiUMTj|U|6}bl_3yv8;%TOp>;{Fpvg9Nrukc1Z(=t&gFK0^fnGt!~e@Mw)FUS@HXh_=1@8T+;BAnrEYQQm0
3NKtR{dWYB?A%1|=m@6;ST#7(hW6*ruVpLhol%z`~90*CqI$gmdyoT1GgO7Oyno+uCngfWBry@+ie?sJ=su|w#4W$kLPBmsl<<iD
h45I>A2Sq$71*{ZhA5#L&C`49&D6p9uf(Xw7j45%2y&Vq&i_f!GPh+Irb@}bBQG*J>5FVM7L_wD>-
=(bG^KgAq7=X&Awfj~YFZLCFF~GqD!;&$j`T>B%!R#2<87IAeZ(iuuTq`kAdc=VWFZ+RIh?NXTPKo@Op07-
(I*7Y=l+gFfteSseSi#MsCm9wmD-
2}$pC<AXxVuKoS$h>#nxF&9%ml<_=bgr#N^RS!$xA7Vi3?KeYlxaD;wTk<Ej9|8zNZ=nIi%SuI1H86t%<XvLjOy@;Pk%N8gtc8Zu
|GUs6$zgRKeYdugr}d3*c;K=s+RnW7vjhz6Uj`#A9j5)U!DZS$4wK2<mKye*&dX(nK(y_2tVu-
h(CpfDRnd<<E#wqbppxbVw6MM}&XqHCgy*PTK0qWlpp9_Oz}vpfT!l!duHu%$jZ|MNYNG^mnnriQGTde%$KzYZB?h{G3CKac#dG$
;tbhNsC7N9-;T1D@*P0HkE53o1~!ij%Py-F~OYAdvaRdLFD!PyyI(y-;UfcjCVDkzO@rV9F%dFl8H0pX{OYac|G}Pg-LSEOVYShl
le7%nGaaP1DBU$i*doj3}?Eg#W0hN9sB>hJX;8A2S&d!(KMX(873uGCkljTx5NdTZBcy_WzePj;UdZ2cHvXJP`1o1;KQ!?!@w4nP
>DVP8^LZeb!!wk-2sO!vF(pK#Dd<tgKROD@w66B7Vp{WL8<CV0`-
<^o@^}L``xUtyY*bzvmc`V0{A=q@tuxd^Yu;gc3}g?B=Pt}<(_P~@{ixSt_+6SpnLn`&U{g#&8OI6Dz~D)C(HH$Xi3jY2AH?8N!T
0JvGXMR+X1m)T;95(4%9149ydoF7s+^`LZX(ihWRd4<7GY`#P^B2CJw#RXQPMHXpm6gCo^=;N7OnSFm;Ij91}2sl}?<T!9#e#g^Z
)Fy7_^W_VLCH6&I@#u0@~z_frENXg96@ZOT(mLf7<Fg!26HQki`4Z@o%_t2>kDeLj!o%*GdS7KAsYmv1KLb^otTg37hLP(;thx@)
&ZWGL`Z<9%?WkyMl!F#ud^STQwvA0vRRrnS?Q^dQ;hQ6n8}h<HL>{J0w#Dg=kJpfA09r=fH4z=_R@*lyfQfzs<jmoZQBkOG%RU5E
q7GGOd$d1&YDV{?ZVB}k?x5IjvT=Ap(j2WMFZfPaFZ;>z_j{epTpbbC$n6KdMIR}=RUFo<p%_WN~a%WR`%e1Bp2Ezw)(HQGCBrem
)tYbh|X5X%ak<ua!1n{bhuOE4t>vaX>qwwCF90-
jVltLZOuUn%T9C!ghS?5XStZgr4(*=_!gk;!VE3=~29CS599<!Rc(tqUoBuib^f^9BbV8-KqOyVA<;*;2f<v|L-
}{KT}|#(%21BwrBB;_7(xAN>HR-
X*NtX)`bwEX_GUfD{gO=zSBxA#h~M&lNbgP;eOYM=b_HyHBryzgb}oJMPl<`pTQ(agWzFYlQ$U9i-!@Eu)mGKkML`JtV(-
Jq#KwUVRmF9PcU%H^IWC!yZ@-
$+E0L?+;o9r@>X<|1~7Pv1ukgFDL>80`dhH<9UQ5+YT_Nx~;=7iIW!0kya)!<c4K|p``Q<`<DLT2oE2#0_&sKgT_AgC;s3kFC%`o
k2O<3o{CX&Fp#2mxni#r>tQ%yF9>-
}FUVx;QbDu0@2DL6GT9`ET#Ia#Px?0FsJ4cHJCvD?9a742td+k4S2JHFWiU6ToDc{yv#*?}pKw5yKGuoLrvr%H?_5-
3IX|Fkj!*XN#_NC_?U#a1k1B{aksp8mx(@Xpyjm8^41km)d#t7l@WT9BEx0S!g|=B*TO-&|R*cIZ#K7ep^5505<{l*|K-
(8>MYas^PwaFPd(Hp+MZ5)nfI*ejc=68Nm~Uytj^=8MAR=@>ki5!>TO4cXUofe{TV!|kJ`h^2b?GoD4&z9Zh!x-
Xb;<A<xOfvoxr@0MjULB1djG-
a%S*wwxri5y*}7CkMi5?XQ{8eRXC*i+5VYU>Bkn9bkG;o5DuR4>Lq!pA+{`I4sy#nbYa%65cr;QAqc9+HDN!j$%~CQcVBb=Q-
KY)U2fky`yE%CF*2Hg;>xKOW-3Wh|HP#aey7dL)23*jNit!RCSxL&$l?@dMOQM&NF6>j%5j$A-
I&tX}{J@D}f&%c`2HE!RODA;j3Eip}NzaNAPoO%~dV-77cQM0VR0mT%?|S&fqpx*_KO>DWCDK-
E8tp>G9`%KJJ#!<^Uur)oe55jevJEmnn}Kx$I?p!ep`t9w@Fn$)uz5hYP$tqkLV?VA4=A~=!ZCP_yf0|;gP4CKQFvt+1HMAeMwJx
E*)qwO&P${lE~Vpl;J(f~NsoL5Ejv!R9drkI_%1mkwNjgN0^8_1qRz?42Bl!i)rQ<Oz2om)#WOwS(}bpahxfDK8uV*S<cD#bL!Uv
UrJ+VBi-P-u<D4(~b?ovFyxdXTv{9e7PsJf-Pk=gLswHPVD?5+fL)e%O!31EPYh>c8)=*Be&a_~)_@b`Hq|YWfkmWpF+oEfG-}-
ZU$%>z;IQI`s3fnRF%p4JKV^2XFmY7Kdg$hW3H&dMxgmG{D4}Q+xr9el=J4Z)u67mOR<6JdWHvf;@Plo*KMq0{4t+tSb8KRR}`;l
#{F$#<+xf=GeF&r5eZ!}xozapi6yKur8z;VeNmkdjL0K&6h#$^<@%FA(h*)*^7b{?chJ^ghCO8lsd<TgFa$_`PG2C;bt6W9`w76i
{uX0L|$6Y%tmqIAPy@=s%*4rXEacVUXN`Rf*oynBhHpOFJx@6BkCtDy;-Rw0FT3_1ZxDsGW)JcAgNozV{O0~Fx-sdh<04BBF5k~Y
N;8_M=;wvsxmY{_0Chos}H?gZ=E&y)g`*+TipJj`zJ%iQAs_L8WsqwpHg&oQ!#`3kAaC^btj=f(&#{gg{)b2?NcuIQaqdh2I2jMt
!0`GXYyjcl;_>!_ZNg(2k+@|C~@7ApYv3G{4z>R<<K4_JQyeA(f%{(|!~yCf$q>7y`1WBYt+c6rV7jzG|tD@Wi)Q@Xm@aoR_PRS!
(rH>3DWdmZchl<lT>DB#9+z|Ne(EZ&0H0?}7b6paYV`o4Pk_;Dm2wg|&o^HPl0z1o7o#Kt|_dkfeA%x^c{7yX9t5CMO)Bui$H>OY
9x0gB1TrSTh@V93=MS3d_*d}<}|$ztq)x*UeoJjq~7&eQr=5-
s&wG9{kwHsLfgTEXA|dF$9ec+Ye_2XYTNo3LF!vcz;!+Q>?Uk~*0WaBA{s!<!q`(H{#0a6^yMZ6n&hZB3q0fk^s8<SYd&nhLy%*d
^IHLfsTE>wr}VSNoy<Y3rS9nj6z64&fB1fFI&?j<eT-V?JBY=<-
){0DVAYcyf?xNz5|zeyL*V>z!f1?t9NJZ50EDhPD)8ZB^0l+gB3+<+L8ntiRNVm0Ph0G+M<l5$@yidXMxKf55g<z4xjhmJZEjmgX
f+PIg<Z7je~pf5(WQUPZ%#4Z@_Rg|vM^$p+tA^BfOv!Q`a{7<P5dSDW*bYo|dEz=v}7LZZ#v6?4^ht}qx28<~dKFa&ZErYwpe0lf
~-
1ox+zQ26idKHvkpX$iu|QH9dZhX9anX2G|j*N3AUuT+I=7Ll__;D_<cnDxG^=%Aetu(~4_$RWw^W1ijC;?CnkmxJ=fdx2bs^pgTL
Z0AHN_-jmz)BtIFl|zAHL%d|siSCWJV+EP#0jDmM1z{7i<$4qmNS5yb*8<REpL!^~SR+Nm6;qy>acU_cI2&hIp*K*MH=SME&v?X#
rt57MqJ7YH;eP>bWYA94GZk%3%_1YrZ5#k!l0YYWtTkz4c6gx@!dKKDqJd%s86&dIyS<f#$SD~})Ij<`rHiKs*32XY79`k9Wp(#Q
42bi3F1q0pdTOYhrjbT@opw>>%n;A4!jLCLAUve1snL@|106C6<#~?<Liupc)#m0w=R<jEUt9a^Ql(W^lL5jpcx$=3{2fO(95{(1
lGP|K@&y4}Gy^>k9J1Y0o-D;|%{dGF)qVh)iT-U3KJ241;XOW$TL-
Tnin?oAzxWR`ZtF!J6&Br;;73`G=EZ?3Trr$BQD>`-JojfIoi5W#76xvk-jjQGsh3I~M#hm^WOofLuHbVy8`e+uFZc96G6UXyrIT
xC7p$aZ8#f$!fcVmG&()#l2PkXb7~WH%Cxb#)Dp3V#Pz5+o-
EmDOiwYO5LSv|NnMEP;czZMac{>GT{G+Ba*f$b8J5hK5L5k~l+eP+HESv2V(RrmLzaR!b^`}jet^jrwN0sT1nyYtiNKDs8*=I$dv
|)KZgwN!<(*dkglnixKhU%(s?cG-!EVH8Yj8ybqSgauMv-zL9>=`~sr*4TxcQb$`L22>ibOOs^Ig?tI=Xjdz2;;F+mxwkH{VdgH4
We}W<y<~Xm^KJ#kl`3M`dL8Bp>NX#L6Zm6Q!PYw=g_vPcYv`9ic~IzIDGtQQuFtQkm*A0lzv&xS4x=%s9FIihn4>b(r!96ncK!|b
VXdnVJ+R^(}KAU3l(P<o|H7r^{btalSLn-eav4hux9$B;n0?BkZ<VGf(HQ_FcqK=MoI%Ib%OjwxtcIx0zs1gHGX$j-
7gLmHiFLL{LZ0nIM4XH6L%TK^boVN4}yP_Mnm=@*McI$)wxIOB}iLauQNKJ20!lfUDGHwFTE%adyDJTtDHfHiB9sv^b^O?)k1DE9
9u~q!N?-)zs(}&7_iEh?ksMVZKa2JR-WrI%|*-
uB5Zzr{*C}Za;c}p;GACb3(P(^Sik~8c`H$kafSpvxRhZ);XHHtJh#JTw{2nqYb%kP&tzKDw~#?i1AmC(riNs_^;NyUw9GA(tu(Q
LI3<C_H!}sF-MWz1kui>ym=re|SE1H8i9NP1kMLoEsI`A*@KKez52WB*Enz#ru8{ATygufR+}GHZz6=pN#Y_oZv5l*-
mF}EVL4nkIQ)eea6&b?Vb2QJZ@0rD#Lt>!+UVZ4sU)%g=?7#dfMkKlWfFQZa9<KjBVzAc%CiT#5xz!@le7r10UIF+@B3G7oiz@SQ
oS;D?)?7b*9Wc{GoD)J_(By~p=Tu@i!AlJ!NI69w_Z^9WU#ZmzrJ1Y-
+iIVYrJYd~j0d@It{Gt5$e5^J=r(1vee{uDe@tua|J5((4LS-EtZ5k-o`?c}G8JnjSs{9-
Qoj*5Sa5g{^u<%Vai&6|3@P;wxfig!quFc^vtOcBtDFpx4b_V3z)vW7EOygEN|b2U)-h=7G2gb4pf~b{>*vjVj`<@pj#@H-
qgT^A_<uv-HBeQ9jKOz+g!5S9VITVUK@1!hUNXLg*?2zTiB{<4>3-
?cHfmb)L;=mo4ajxo&dJU%<pS<mVP0&kZyMn7SY7<GzOSoh{>NZBrl!i5n4%7&@_t+^<YQ%@2XSi&)N5$@r*Aq%t9!K?A3WtgXJ1
U7xyZ;V3t}${bCInjoZ(;6V1fsngsoQ0vOodC(9{VfgWh`3Er#}76jO~k=oF0kerH?%N+UeHUZI(H2PE~;_MqoTjR7r*1>&HiF<w
<<-VoYaSPrS3*Lyd0t|UdSI2Ch()?-
`EbL8*8_gG53{6p6;AZDj^zp^Zl%mF`k0!HsR;$rBqKh*l$0C$}CT*dhA7H(eOR^4K|b;tjId~P}uhLs(9y7PeY`9rg@81KpAlO%
l{#?}6<Os;&wu0c2kJoZge0rsJBCaAfyP-iTM2cx^$f-F3#XroWN824uNCoZ2tRO=DyP{%JX*R)XF0xqKAviihL^-
Pu%=#ezf79r)NB&8{lDkjl(FItDLP8tb<XS>5`@J-^vh;|OA#}aiCyy-FhAw$Tv(6(N1rKj^at%z;BtH`s^5O&g3K&f;^z^Kz_uU
QL=b}9=FH+Vq*JG(K38o`~%isG8o?}=CR9{%}ph6nVi>;9&1yF+$@zj2_*55d#AO_Ee_mK%#MKjCUNUf3lB)!zRF#RSACXOdvZvB
CZgzt?Z^L|yvOZL$BK!9#&Hl#n^aU<EpX=VJM7T!k+q(oum>FBa>gMh9qFMZjtIW@;HeHQw9R!@I}UyQhKQKOoVvNW@O*n6T=EQ+
X0E7~~%iNBUYLC1~^4YOe!OS?faAGTVnR(&6$bgAlk@0Z(PI*g9$%xgZ1OQnHd756q6p^|67|){xQp*k4F{f1#{cKhvG8?99V6TU
MQ!0`evxJpLmPk=$8r)zL7RblkuMWEy!+kq;$G(P_xCCu!8o&1gr&9sp)Yw#!rlXJ<Ku;Ec<jTDt1SHHL-ChN+QQ5;dWg`*IIpsC
Pt&0OvFr{j-*}f+}t>o17l(%{u-
L8X|@k)%i+TesQoUZnCldzM_UX1eaAs(E6{_=HJuXcJ236?R}{pq|iWG#x_S*f{ODvAdDMv5Ei|N7Fg=iPa@<8U#}{&c>mvjFmeV
uqh*(-
v8)ljs7FWuOo~0u0x#63H9w?%GuHMD%t6U_2OT`yP~892dr0{a7x8bz2EmPei1MmC1SNEHBm6j`K||F@k;^^+kZ1kTkIh1KWkeyI
`!U%_Ph|5WC>9VDxZ!RZoG8){+>G4?V(k?l&<k{Ws<)Z?jImy%mM3?bo%=}Kk~5<dJ3yygjVMt7kIKUEG)4r9V>TzN_BhkWrlODE
Me#NH_^cQDA@*7nnS7fMTq>k9VODx<v;M5n4oiCc=E1>vnRL4fRDZ_@Dk5>BiLXUZN38tFe{VTqUn|sMv=xU*_I^Y3!Mvn6XQ)q(
h=)r~gEcmYw<;)D+5^WqXWb|WWSs=*S$$yc#XesaYzzJ%<Ce6fHr6J9vxpuI)vRtx{ei;a04)e{eo^`Y!<Hi~)tug&efo=tS=>k>
02^Eq=ngY;jAwG97ZgFx2>jU=Giek4t5mt{&>=tdZGamnM710Mka!l1Y|4(U`3NK(JH<~(SJX5FH595C`u|<>U^GS+MHK1pAyEza
cPrC(=?j?T`fdvJVQV~h5J?E@;q>00H-m`jP6RV~5?b;9EwH8B0#F@Cd*PlYrdpoE77mvK<|U;jvKi0J&|ApIi-
t9FC;zjvePi}Ul@bR-
(hVIS0Pcs=gA^6H^JeINF9Q`m>F}@7Oyb!+H}<ZB)_l%Zkb0PVRg^wc!9#+ZalV~mU)bVK8!8Tt2yH&ZQOHA~%9PjmR!ns;kTN3H
=%PcMZR5oSrb*-4TuqnQ(;y8_YnuwgT>4^XL&U4me115%+!Nykq=gk3t^xp-T_)w%h_3>P5!IDyMSn*BxI%qRXoGo7v6^+j6opDb
!G!-P%j#r~#N!IW5DVy1BTk!?S$Y;uJNNC?7+Nqiso*>9xxy9J(3WpU`MgWCt@r{-s#kf)HDGw+a%}mR-
YmMb$iFtFtoMmM^l}vlm;UWu_*|#;u@``^x4w{svxOv(15<hw1TB49UZJ-CYSU$L52#@l!WooSuhirE>YxWcA&Ip8QH>9c*sz+SA
r3eQeEpsQ@}=kRb*v_nWL!a!(N{aR|NR83f-
zIrH33yOU1@kxHM&KqNpCMxPBl%<f7dy#!A8{8PfV6weGaiX?(Hs_D%a@#ka&bkQ5PL*gIDH2Iykp`G(llHJS5<$7I<A;CsILI^d
=Ox+qKfnzxZDfIrFfHOD0Bc^F{>Y5EphmU0UI@cHdMfPrHq#ayLFGwdg8df3IJ_UmD0;S^t;g>)?!I``NyQ{9OTB5l(NUb{z(`Za
AwMu)Zm6QxFW61-lFS%h1q=<P-4v4|E_=Jilj6Bu=<<#F@GshA%nujcWFj9H9JPN)UhAe#K7<UN{jQ2-a>1V!W-
M?SX<@MkPtZ$E<dRH+?NjE+s>zcBc97mp4RXzxl$X-XA5iMivv5jZy1}8fP^W#qigzXn?QxHSSOB<Pz8HI8p~-
Eo(|Rs6$5kzeniz0cg1sDbc>l?}`&ce=qL`4bV{THH=P><7^ipwu){Cz#_ix8_2MYJD0CtH-
#nGF0<rXPf>hjtK#^CDEK$b(wYTtP-om(r*D{jo`bXjIOS;Z&Z_uEVlp|rF{stHZf!IM&)YsGAfei$K<Bt}qIH_W31v*fUl6^LnW
Dl!K1l9VtnoI8HRL1XW@76{V-E|f?T-7bGU^^A?9K~21bDVh+c@un6N<<@vhDcI5nGX9V(*L&C>E1fD$ffUz~yT%-
cK&HfLabY{ZHzA=@#L{7&u$l@bhgRUBKv|YsnO`Ip}9X34cocJVn@Zq3^4UU_>6+lNEWJJtrmd<$XINp-
R$XcxvTGOhtd{UA52g^HV)Pt?sc@f4muKAn*5v=mI;WC#LH^OdMxdQSbP)7FDl5VHZujKy}azD}^2rh$$u`x3`NvpY@<lqWx6eI0
K^wdZ_^`W6SvtuYBGyKV<LQ(Qc)cbdZcBkJePwpcz(~xZ~kzReCo?-
DN?p97^r9U)L6a727)_fEZDwXKrY_Ezr&U{@$={wgB9`?@d>iN?|^Gq3&klU4;Tj7^Mi~<=#RQoXRFv&<+{Dfq?h8fl({*RPw+Pl
mAh_+JAFjgg<#5hq81znkyJN=?Qo$p1+s1?RtAC(a`e}#y4$|OCtmbBE{7?kTr<lpK1O$bMkW~#mf7eodi6uAI0pI5cZS#oTKFPQ
5>TA#JsdqJ1ye09g6_+f|c9IKW(0@2lzj4p+B2#IO;z=3R2XA1|t-
ZEk|m(rj{C@T0$QKN!)Q}_(LVIz9b<Jzryv4LDs}wFCM_=K>fCf+PsR7s)a<{1rrtk7grpE{7EWIx&{wGJ_jdDM_K(phfxyjXI!;
Q1tjdjf{CfWR8JVo&|#@#E1R${PS%RJ&(wePAe9m;_NGD%p+8p)5^Sc7zHb9y_KTMkqZ4HFr<_+>Gy%;oz)mn6c)iKc{_{YUgtdW
MxnB>{Yk(Ds6Yo*1VW>R`=&SN3?b+6e#4i)rJ*lt^*Zf6j3rdSlzAqtZh|Il0Dmx(Ua9L5O<P4{1#r$(o2B;|QLksw!U?UZ2Kej_
%^k~|Aw((>H%?z#QF*}Lj>zuyU?n5iZxJNEN#0=;Zw;5w8%1YK`|57zA2lsB|<fX*GoF$spf{VR=2#xb3<XgCMYy1-
#9lNdJx17Z5uhon|w6#(NVt{ffo{IPXf|LCq58Z4Q9~f-
umJo9UN7H7;IXj^KtM)mP+d(gfzzQDfD$269x(>)`I<qFjqm!ndJ`SX7ss--0r0(MZ$~UCXuu}v6s@pmQOu3~Iub=$pvADDzfms4
EZ@G@z7w=IfF(4vB?)hZ<!JWThNLb@=R-
H@$i?|F#1R8&K!d&>=r_S&s6VEqr_&CjP0Bn{a|7!w$hD45?y0r29e_e@J(F^w>xxpSyAgOQn#joDC7HeGKC#v~*t$8e8|7ohm-w
ClCVG0F8A!Cs2mJ59jaAP;Ty4OG?EaXYANGxK$sVxm238Qhii@JcBbmlaB)gerBIzS&AaJJ7Z?Lg~#pMjR@ma=U_L&tRa(p)|{ft
m)(b?r;H_TrZ0X29h1>qJ79GXF?`kaq^N45#gNpTvM66tqU38T_6umz+IC9{w$up<1NtV^u5wytDp7v!>@hjF_^3g0rZT-
o#U}fMNgT{n%@GPaVc%a<#zLV)8uhce?^B*FFG(0X9z+TXQ^<+jglFIWnw`u?-
|5s_(~+WC9}TYYYpZNE(lj+d{?OaxnXcr%6fL?Lm#oKJ9c#Y(cAxUV#BPte)lZ^tIVWOa+`huSPjESHItx&HQ{M*g{TNy%@n^@9$
eW2l;1u_n#@tL+{@bRp1{~IcZHgIuUP%`}Ek3kvyF#BlEwD`^s)$&oVr@)p(Q$9yI0AU<+#;2QYVtAHij#8iw{9feitcyfr+E0jf
dSoM}*yuF~`I4eUr-F?n{<GQs^oFjy<78sI!}DmoxFiqp1lF=2I6&{H`(sk|+i)$4|w!M7ZB3DwbNYLA-
O#=vo%EBAZH+OeK<jvuHUpDTY8_#ilRtgutuDc2BGx1bmT>gYgXtU;2f3*)4B^3ZN61!KRdca19+8E1L=-
1f(R`D9S8I)(DN3fMd}iHvB2HKeo+M~Kp4Ex18|`iJMya7~^g&w^TosTPXm9ny{tv(a-*{sv-vwov(=W1RuQT89(Izl}^94=h9Xh
6FL=g#?Em<?|V_nfqj5C<}1FFCd%tSiR(NN&ZS-
1G9`TVZ8~OgI!TvVcH$6$NWLu*F>54qbI{j)Y)Qa(PuBXQiJ;@GL=n6L_10Jd+7RA7<un_88&ax+YztqM9wx!sw}RM_7@+wy6Pxa
fR=oNCk|}d<D_$%W?<0N)LWOcSx%IeYWH5&MjGR+H{tny<;4nAAbYVvy`1?uPl-
!Ui;Z+x^}Ip_)y<`==SK({u}`W+#}~@z?l$@ZXv2px&@vSK`v~+1@at+kag2U@3NDj#oPGeQ(JpIMOv5qAN1xu!d;e+GAO|sqM#w
Kh7Ac5}bk_~XYdyPVCE;<Mbdy_HJ`^oBW)b~AVuHwqG+WjcYt|WAoGP|BpGE?RhX*i_*>A1G%X;2c>E>-aQJn{$-
OC%ZxJwjFR=Fgc($Y~K4S-
PGRmv$%nH&2F59edP$d6cwM!`UuKRsTY;u~CRAl&%X008|MZ<+2`liePj)%NCl)mOxpOo^&H>#N6btBcNKrxM=cd&$Z^H7B~7?ZU
@oj~DhQ6>}CZoe!-
zJ?&C`av#$7K8?O&YO9P9%M#pdDe9yQdnEWMY&QqrnUT`IWwy1A!ITq_m(FU%`FhL0sIpe8_z1lm;uJSclY{-
*JZ`hJSk52GO2LC$=E<cJ4Qf62fW*edD8ppLHj-*rVhSKC8<Ldzg=XFj5}+GH2-
WA8o$wp{b_!UofLr>M{fOPuCfS5t2(CLd`4c!~XIcKjS<kfFtn(Qa8kQh;kn~W$%Ad}HpZuwl-x6(g<eY>U5-WBuW<Z?@vE@)uS-
*HMT20SvNGGM&waSneSu*4=xhe1yWO<eN3Y!kLSw2?=)^}NCL^-P~O7+Y-WT;+3ORfCq#GVD-Re0ref15%dAMI@67skGzKu$zoHp
Shpm^no@bL!K}7v?!U3N1W_)3;F=ym)f(W}QIp-
X=!?Ihlx4ms^JE0G4iWVaXv}U$&nMQyFiNMeXBP8o!%;hWnW)$C8mC+TXP|C5#3RT!`Pbt$@bSR(cF5dm9AjBf_x44p=lBH6D83f
nGl_vJp}A6ar(Dy^Q1m4(E=M*Y0A^{SoSblSmM|YWa<B0(V>(2Ognb3$IbOMig)yItj9)rfwiy{tHpCWClnt0<|%<)`BWvuotKl-
!fJxjKmP>xm@W$Y5`V*TqyeGWkA=np9Z{|9a^tomx~!31u7d`rUP0RDdC#50q&=#1{AQRY%969Rk>}Qjsol-SPID34x=NA#*4tgI
hHTB!XBgA0AG^e3?LMMke<tuk&E8?Ek(i78vY+_S;GSjJzs59W|CX>o(9O?U-
*_BD;#mv8`+*6^QH5f>U7WWSaDxZqjdOU!0yh=H%yK$W}Q15gg&+LP#^y<@nN!&bQKUQ6Y8Anic{hVo^+XLhRr!r;max}gEAuOWu
krMswf`Q`+>$Y0At`Ex)I7%smQZ1m5FT}CDpb)Flt+b%-HZ@P91eee-#GrTpAqWI7w(Xc<JFXU|=QqG-HMUpGYX*@$u@Mz$D{5#*
yr!yi<6z{HkqQ{78uq@NnIg1!REb>0@*Y=mo<!9Q4P5+*K1=Pc;gMpHNZVci8LHsqIuK?FT@n`fqq^=#_r08f=udPd-HC9V!E{v;
U@jFEX|92v|$-
Z_9bc3}51d;ihw0D>)E)={ucNjgYR_vW~980SV|mR8~X}In+bN3uOQEzda7hEH7mHzkIpL6iI13n|hahmBed^^!E7{sh-
r`%?_4=e&vjAT@<^l^^!EWMT7gX3S#`&ETqP(EAd9)-AK|axt3&1gH*f*!<&-
9Qlncca_yiFO8a!&As+%fOfN|Lc4rp#nwR5|TwTeXH)$)~bogpP0fjgWOlI5!uP1pL&@9GqR9rOjZy~&6#DR1PW5Tx2ckiGrlpkd
h5z{dlipmhABb<Kh!EmG>PnCmt&nDF$+)e4rf=VmIGY7<JVbY+<7y~qy%t6?jD6uD5krEXx>&s<<fSdmgwQyto?aEl$s$W(WHI6{
9ee&iSfPdEl<&sbp&`u))L4s!WiTFHZ*!2)GeD3;E?(E^yTtba-IeDabx@smhr5VvG*o7!$1wgEPwh{(t<P4tGr#4EHjgqfP8m0B
k-%zkR`E$l#bAKFv>hxVzy8>&YUg+f8@=eY1D3euvIW<ZUD@t}B*ibP00)-cQL89LrYwtWlx;_gc^}9UiD#DY-
%|0R{sXoT`XiY_e1}7^{_hyWYt6p%k>}Kce5DK56WR3eF?-?rjGQ<p=<GjJ;`}w7%PUt+J-
@#Qmt+`RP6c}HTp9X9evLd3vT~oQMenb47_>_l)bdG{6V{e?2M{M1fZZ2xMPQ;rL42`l4BisI#<#^gXPU|-
Yw{d|bl>K!<PLVRlX(tAlqn#g;wWjg+32(v_jx~D=(yrpT$oC?^d~ZAFl2LJ$sL&y-{B;YLoF|DR)MLK2b<aHh%b_&r-
Fy}~hw3dC01iHP`<;>j&==B=cEG9)ZKKAf)lNI(^vgiR=sta9S#`eDhk7JBP5LcAa`@wo7(Lv%nhNgzdR8<Yk9H~OatIuTqrcL|4
Y|Y)rgKMiUEmtJTP1?P-z!C$PvLg2vt_`k$`X(m?ImBxt{>o?-d1hC+mXn5*2MKy`7`QS$(an1z2bH-CGjQ(12-
Jhpq8lWq}iDurQXOAFO@^H$e+DLlG`rn+)X;Jij}*jw7W1j{a><8cfM$}*5WFE8lQbn(p5o^rQX*dqetH@O#ybKPS(nNIBgjU8=w
l!J3di`bwnw8F#TeQ`_)(O4}_GK2Ll^EwX2BkrpJN~+x4q4SHd2@0TiOoaD*v9J)kSeBgG6Ynm4Ycyi3Dlqw|RAp?$9^g9o>|oVx
|%hh-BkaTz=*6H}#3$jAS0z%w?&hNhOSRb$r+G^~54R97~mnMeRRF7Ztwe!Z=`hhO-
5Hhdm?zAZPj29~Q;9!N0<WG@nc<HoUg$G1SxB$x0-Arx-Y_2Bv!dhA8$3Uqo4@FmDYS4lvksZbgt!Jlfiq{}ck{!%REunFcBMmp{
JO#Pr7I@|o#l}6-v8BFcpn42ekg>Iom5oPSbiE$qZ!<JFI0SWT$Ia7wK00
'''

MAGIC = b"RSB1"
VERSION = 5
WIRE_PROFILE = "rsb1-v5-public-kernel-1"
CONFORMANCE_PROFILE = "oxbow-conformance-v1"
MANIFEST_PATH = "manifests/MANIFEST.generated.json"
MANIFEST_FORMAT = "oxbow-manifest-v1"
PUBLIC_SECTION = "files"
REQUIRED_ROOT_DOCS = ("READ_FIRST.md", "BUNDLE_LAYOUT.md")
TOUR_ROOT_DOCS = ("START_HERE.md",)

MAX_BUNDLE_BYTES = 256 * 1024 * 1024
MAX_FILES = 10000
MAX_TOTAL_RAW_BYTES = 512 * 1024 * 1024
MAX_FILE_BYTES = 128 * 1024 * 1024
MAX_PATH_BYTES = 4096
MAX_SECTION_NAME_BYTES = 64


class BundleError(ValueError):
    pass


def _rv(data, off, max_value=(1 << 63) - 1):
    n = 0
    shift = 0
    for _ in range(10):
        if off >= len(data):
            raise BundleError("truncated varint")
        b = data[off]
        off += 1
        n |= (b & 127) << shift
        if n > max_value:
            raise BundleError("varint exceeds allowed range")
        if not (b & 128):
            return n, off
        shift += 7
    raise BundleError("varint is too long")


def _take(data, pos, n, what):
    if n < 0 or pos < 0 or pos + n > len(data):
        raise BundleError("truncated %s" % what)
    return data[pos:pos + n], pos + n


def _lzd6_bounded(data, max_output, what):
    dec = lzma.LZMADecompressor(
        format=lzma.FORMAT_RAW,
        filters=[{"id": lzma.FILTER_LZMA2, "preset": 6}],
    )
    out = bytearray()
    feed = data
    try:
        while True:
            remaining = max_output + 1 - len(out)
            if remaining <= 0:
                raise BundleError("%s exceeds decompression limit" % what)
            chunk = dec.decompress(feed, max_length=remaining)
            out.extend(chunk)
            feed = b""
            if len(out) > max_output:
                raise BundleError("%s exceeds decompression limit" % what)
            if dec.eof:
                if dec.unused_data:
                    raise BundleError("%s has trailing compressed data" % what)
                break
            if dec.needs_input:
                raise BundleError("truncated %s compressed stream" % what)
    except lzma.LZMAError as exc:
        raise BundleError("invalid %s compressed stream: %s" % (what, exc))
    return bytes(out)


def _validate_path(path):
    if not isinstance(path, str) or not path:
        raise BundleError("empty or non-text bundle path")
    if "\x00" in path or "\\" in path:
        raise BundleError("unsafe bundle path: %s" % path)
    try:
        pb = path.encode("utf-8", errors="strict")
    except UnicodeEncodeError:
        raise BundleError("bundle path is not valid UTF-8")
    if len(pb) > MAX_PATH_BYTES:
        raise BundleError("bundle path exceeds limit")
    if path.startswith("/") or re.match(r"^[A-Za-z]:", path) or ":" in path:
        raise BundleError("absolute, drive, or colon path is not portable: %s" % path)
    parts = path.split("/")
    if any(part in ("", ".", "..") for part in parts):
        raise BundleError("non-canonical bundle path: %s" % path)
    pp = PurePosixPath(path)
    if pp.is_absolute() or str(pp) != path:
        raise BundleError("non-canonical bundle path: %s" % path)
    return path


def _payload():
    encoded = "".join(_PAYLOAD_B85.split()).encode("ascii")
    if len(encoded) > int(MAX_BUNDLE_BYTES * 1.4) + 1024:
        raise BundleError("embedded base85 payload exceeds input limit")
    try:
        data = base64.b85decode(encoded)
    except Exception as exc:
        raise BundleError("invalid embedded base85 payload: %s" % exc)
    if len(data) > MAX_BUNDLE_BYTES:
        raise BundleError("embedded payload exceeds bundle-byte limit")
    got = hashlib.sha256(data).hexdigest()
    if got != _PAYLOAD_SHA256:
        raise BundleError("embedded payload sha256 does not match wrapper header")
    return data


def _decode_offsets(raw, count):
    pos = 0
    arr = []
    cumulative = 0
    for _ in range(count + 1):
        delta, pos = _rv(raw, pos, MAX_TOTAL_RAW_BYTES)
        cumulative += delta
        if cumulative > MAX_TOTAL_RAW_BYTES:
            raise BundleError("offset table exceeds raw-byte limit")
        arr.append(cumulative)
    if pos != len(raw) or not arr or arr[0] != 0:
        raise BundleError("invalid offset table")
    for a, b in zip(arr, arr[1:]):
        if b < a or b - a > MAX_FILE_BYTES:
            raise BundleError("invalid or over-limit file offset")
    return arr


def _decode_paths(raw, count):
    pos = 0
    rows = []
    seen = set()
    for _ in range(count):
        if pos >= len(raw):
            raise BundleError("truncated path table")
        pool = raw[pos]
        pos += 1
        if pool != 1:
            raise BundleError("public wrapper permits only local binary pool")
        ln, pos = _rv(raw, pos, MAX_PATH_BYTES)
        pb, pos = _take(raw, pos, ln, "path")
        try:
            path = pb.decode("utf-8", errors="strict")
        except UnicodeDecodeError:
            raise BundleError("bundle path is not valid UTF-8")
        _validate_path(path)
        if path in seen:
            raise BundleError("duplicate bundle path: %s" % path)
        seen.add(path)
        idx, pos = _rv(raw, pos, max(0, MAX_FILES - 1))
        rows.append((path, idx))
    if pos != len(raw):
        raise BundleError("path table has trailing bytes")
    return rows


def _parse(data):
    if len(data) > MAX_BUNDLE_BYTES:
        raise BundleError("payload exceeds bundle-byte limit")
    if len(data) < 5 or data[:4] != MAGIC or data[4] != VERSION:
        raise BundleError("not an RSB1 v5 payload")
    pos = 5
    for i in range(3):
        n, pos = _rv(data, pos, MAX_FILES)
        olen, pos = _rv(data, pos, MAX_BUNDLE_BYTES)
        _, pos = _take(data, pos, olen, "global offset stream")
        clen, pos = _rv(data, pos, MAX_BUNDLE_BYTES)
        _, pos = _take(data, pos, clen, "global codec stream")
        if n != 0 or olen != 0 or clen != 0:
            raise BundleError("unsupported legacy/global pool %d" % i)

    nsec, pos = _rv(data, pos, 2)
    if nsec != 1:
        raise BundleError("public wrapper requires exactly one section")
    name_len, pos = _rv(data, pos, MAX_SECTION_NAME_BYTES)
    name_b, pos = _take(data, pos, name_len, "section name")
    try:
        name = name_b.decode("utf-8", errors="strict")
    except UnicodeDecodeError:
        raise BundleError("section name is not valid UTF-8")
    if name != PUBLIC_SECTION:
        raise BundleError("unsupported section %r" % name)

    nt, pos = _rv(data, pos, MAX_FILES)
    nb, pos = _rv(data, pos, MAX_FILES)
    ng, pos = _rv(data, pos, MAX_FILES)
    np_, pos = _rv(data, pos, MAX_FILES)
    if nt != 0 or ng != 0 or nb != np_:
        raise BundleError("public wrapper permits one binary record per path only")

    plen, pos = _rv(data, pos, MAX_BUNDLE_BYTES)
    pcode, pos = _take(data, pos, plen, "path table codec")
    max_path_table = min(MAX_TOTAL_RAW_BYTES, max(1, np_) * (MAX_PATH_BYTES + 32))
    praw = _lzd6_bounded(pcode, max_path_table, "path table")
    rows = _decode_paths(praw, np_)

    if nb:
        olen, pos = _rv(data, pos, MAX_BUNDLE_BYTES)
        ocode, pos = _take(data, pos, olen, "offset table codec")
        oraw = _lzd6_bounded(ocode, min(MAX_TOTAL_RAW_BYTES, (nb + 1) * 10), "offset table")
        offsets = _decode_offsets(oraw, nb)
        clen, pos = _rv(data, pos, MAX_BUNDLE_BYTES)
        ccode, pos = _take(data, pos, clen, "file data codec")
        concat = _lzd6_bounded(ccode, MAX_TOTAL_RAW_BYTES, "file data")
    else:
        offsets = [0]
        concat = b""

    if pos != len(data):
        raise BundleError("payload has trailing bytes")
    if offsets[-1] != len(concat):
        raise BundleError("offset table does not reconcile with decoded bytes")
    indexes = [idx for _, idx in rows]
    if sorted(indexes) != list(range(nb)):
        raise BundleError("binary indexes are not an exact 0..N-1 permutation")

    files = []
    for path, idx in rows:
        files.append((path, concat[offsets[idx]:offsets[idx + 1]]))
    return files


def _manifest_records(doc):
    errors = []
    out = []
    if not isinstance(doc, dict):
        return out, ["manifest root is not an object"]
    records = doc.get("files")
    seen = set()
    if not isinstance(records, list):
        return out, ["manifest files is not a list"]
    for i, rec in enumerate(records):
        if not isinstance(rec, dict):
            errors.append("manifest record %d is not an object" % i)
            continue
        path = rec.get("path")
        size = rec.get("bytes")
        sha = rec.get("sha256")
        if not isinstance(path, str) or not isinstance(sha, str):
            errors.append("manifest record %d lacks path/sha256" % i)
            continue
        if not re.fullmatch(r"[0-9a-fA-F]{64}", sha):
            errors.append("manifest record %d has invalid sha256" % i)
            continue
        if size is not None and (not isinstance(size, int) or size < 0):
            errors.append("manifest record %d has invalid bytes" % i)
            continue
        if path in seen:
            errors.append("duplicate manifest path: %s" % path)
            continue
        seen.add(path)
        out.append((path, size, sha.lower()))
    return out, errors


def _verify_integrity(files):
    mapping = dict(files)
    if MANIFEST_PATH not in mapping:
        return {"ok": False, "error": "manifest missing", "checked": 0}
    try:
        doc = json.loads(mapping[MANIFEST_PATH].decode("utf-8"))
    except Exception as exc:
        return {"ok": False, "error": "manifest unreadable: %s" % exc, "checked": 0}
    records, errors = _manifest_records(doc)
    if doc.get("format") != MANIFEST_FORMAT:
        errors.append("manifest format must be %s" % MANIFEST_FORMAT)
    expected = {}
    for path, size, sha in records:
        try:
            _validate_path(path)
        except BundleError as exc:
            errors.append("unsafe manifest path %s: %s" % (path, exc))
            continue
        if path == MANIFEST_PATH:
            errors.append("manifest must not list itself")
            continue
        expected[path] = (size, sha)
    actual = dict((p, b) for p, b in files if p != MANIFEST_PATH)
    missing = sorted(set(expected) - set(actual))
    unexpected = sorted(set(actual) - set(expected))
    mismatched = []
    checked = 0
    for path in sorted(set(expected) & set(actual)):
        size, sha = expected[path]
        blob = actual[path]
        bad = []
        if size is not None and len(blob) != size:
            bad.append("bytes")
        if hashlib.sha256(blob).hexdigest() != sha:
            bad.append("sha256")
        if bad:
            mismatched.append({"path": path, "fields": bad})
        checked += 1
    ok = not errors and not missing and not unexpected and not mismatched
    return {
        "ok": ok,
        "checked": checked,
        "expected": len(expected),
        "actual": len(actual),
        "missing": missing,
        "unexpected": unexpected,
        "mismatched": mismatched,
        "manifest_errors": errors,
    }


def _tour_tracks(mapping):
    tracks = {}
    for path in mapping:
        if path.startswith("tours/") and path.endswith(".md") and "/" not in path[len("tours/"):]:
            tracks[path[len("tours/"):-3].lower()] = path
        elif "/" not in path and path.startswith("TOUR") and path.endswith(".md"):
            name = path[:-3].replace("TOUR", "").strip("_- ").lower() or "default"
            tracks[name] = path
    if "default" not in tracks:
        for path in ("START_HERE.md", "READ_FIRST.md", "BUNDLE_LAYOUT.md"):
            if path in mapping:
                tracks["default"] = path
                break
    return tracks


def _verify_conformance(files):
    paths = set(p for p, _ in files)
    missing = [p for p in REQUIRED_ROOT_DOCS if p not in paths]
    tours = _tour_tracks(dict(files))
    if not tours:
        missing.append("START_HERE.md or a tour surface")
    return {
        "ok": not missing,
        "profile": CONFORMANCE_PROFILE,
        "required_root_docs": list(REQUIRED_ROOT_DOCS),
        "tour_surfaces": sorted(tours.values()),
        "missing": missing,
    }


def _verify():
    data = _payload()
    wrapper = {
        "ok": hashlib.sha256(data).hexdigest() == _PAYLOAD_SHA256,
        "payload_sha256": hashlib.sha256(data).hexdigest(),
        "note": "internal consistency only; this does not authenticate an author",
    }
    try:
        files = _parse(data)
    except BundleError as exc:
        return {
            "ok": False,
            "wrapper": wrapper,
            "wire": {"ok": False, "profile": WIRE_PROFILE, "error": str(exc)},
            "integrity": {"ok": False, "why": "wire parse failed"},
            "conformance": {"ok": False, "why": "wire parse failed"},
        }
    raw = sum(len(b) for _, b in files)
    wire = {
        "ok": True,
        "magic": "RSB1",
        "version": VERSION,
        "profile": WIRE_PROFILE,
        "payload_bytes": len(data),
        "files": len(files),
        "raw_bytes": raw,
    }
    integrity = _verify_integrity(files)
    conformance = _verify_conformance(files)
    meta_ok = len(files) == _FILES and raw == _RAW_BYTES and len(data) == _PACKED_BYTES
    wrapper["metadata_matches_payload"] = meta_ok
    wrapper["ok"] = bool(wrapper["ok"] and meta_ok)
    return {
        "ok": bool(wrapper["ok"] and wire["ok"] and integrity["ok"] and conformance["ok"]),
        "wrapper": wrapper,
        "wire": wire,
        "integrity": integrity,
        "conformance": conformance,
    }


def _prepare_dest(dest):
    dest = Path(dest)
    if dest.exists():
        if dest.is_symlink():
            raise BundleError("extraction destination may not be a symlink")
        if not dest.is_dir():
            raise BundleError("extraction destination exists and is not a directory")
        try:
            next(dest.iterdir())
        except StopIteration:
            pass
        else:
            raise BundleError("extraction destination must be new or empty")
    else:
        dest.mkdir(parents=True)
    return dest.resolve()


def _extract(files, dest):
    root = _prepare_dest(dest)
    count = 0
    total = 0
    for path, blob in files:
        _validate_path(path)
        target = root.joinpath(*PurePosixPath(path).parts)
        target.parent.mkdir(parents=True, exist_ok=True)
        parent = target.parent.resolve()
        if root != parent and root not in parent.parents:
            raise BundleError("extraction path escaped destination: %s" % path)
        if target.exists() or target.is_symlink():
            raise BundleError("refusing to overwrite extraction path: %s" % path)
        target.write_bytes(blob)
        count += 1
        total += len(blob)
    return count, total


def _info(files, data):
    mapping = dict(files)
    tracks = _tour_tracks(mapping)
    return {
        "name": _BUNDLE_NAME,
        "wrapper": "oxbow-self-extracting-v1",
        "magic": "RSB1",
        "version": VERSION,
        "wire_profile": WIRE_PROFILE,
        "payload_bytes": len(data),
        "files": len(files),
        "raw_bytes": sum(len(b) for _, b in files),
        "doors": [p for p in ("READ_FIRST.md", "START_HERE.md", "BUNDLE_LAYOUT.md") if p in mapping],
        "tour_tracks": sorted(tracks),
        "payload_sha256": hashlib.sha256(data).hexdigest(),
    }


def _orientation(files, data):
    info = _info(files, data)
    print("%s  (Oxbow bundle, self-extracting)" % info["name"])
    print("  %s files, %s bytes raw, %s packed" % (
        format(info["files"], ","), format(info["raw_bytes"], ","), format(info["payload_bytes"], ",")))
    print("  doors: %s" % (", ".join(info["doors"]) or "none"))
    print("  tours: %s" % (", ".join(info["tour_tracks"]) or "none"))
    print()
    print("  --read-first        print the front door")
    print("  --tour [TRACK]      print a guided tour/start surface")
    print("  --verify            verify wrapper, wire, manifest, and handoff conformance")
    print("  --list / --ls       list bundled paths")
    print("  --doc / --cat PATH  print one document as text")
    print("  --extract DIR       unpack everything into a new/empty directory")
    print("  --payload-out PATH  write the inert .oxb data twin")
    print("  --info              machine-readable summary")
    print()
    print("Security note: this file is executable Python. For an untrusted wrapper,")
    print("inspect it with a trusted Oxbow CLI instead of executing it.")


def main(argv=None):
    ap = argparse.ArgumentParser(description="Oxbow self-extracting handoff bundle")
    ap.add_argument("--info", action="store_true")
    ap.add_argument("--verify", action="store_true")
    ap.add_argument("--extract", metavar="DIR")
    ap.add_argument("--read-first", action="store_true")
    ap.add_argument("--doc", metavar="PATH")
    ap.add_argument("--cat", metavar="PATH")
    ap.add_argument("--list", action="store_true")
    ap.add_argument("--ls", action="store_true")
    ap.add_argument("--tour", nargs="?", const="default", metavar="TRACK")
    ap.add_argument("--payload-out", metavar="PATH")
    a = ap.parse_args(argv)
    try:
        data = _payload()
        if a.verify:
            result = _verify()
            print(json.dumps(result, indent=2, sort_keys=True))
            return 0 if result.get("ok") else 1
        files = _parse(data)
        mapping = dict(files)
        if a.info:
            print(json.dumps(_info(files, data), indent=2, sort_keys=True))
            return 0
        if a.list or a.ls:
            for path in sorted(mapping):
                print(path)
            return 0
        if a.read_first:
            path = "READ_FIRST.md"
            if path not in mapping:
                print("READ_FIRST.md not found in bundle", file=sys.stderr)
                return 1
            sys.stdout.write(mapping[path].decode("utf-8", errors="replace"))
            return 0
        doc_path = a.doc or a.cat
        if doc_path:
            _validate_path(doc_path)
            if doc_path not in mapping:
                print("%s not found in bundle" % doc_path, file=sys.stderr)
                return 1
            sys.stdout.write(mapping[doc_path].decode("utf-8", errors="replace"))
            return 0
        if a.tour is not None:
            tracks = _tour_tracks(mapping)
            if not tracks:
                print("This bundle ships no tour/start surface.", file=sys.stderr)
                return 1
            track = (a.tour or "default").lower()
            if track not in tracks:
                print("no track '%s'. tracks: %s" % (track, ", ".join(sorted(tracks))), file=sys.stderr)
                return 1
            sys.stdout.write(mapping[tracks[track]].decode("utf-8", errors="replace"))
            return 0
        if a.extract:
            integrity = _verify_integrity(files)
            if not integrity["ok"]:
                print(json.dumps({"ok": False, "integrity": integrity}, indent=2, sort_keys=True), file=sys.stderr)
                return 1
            count, total = _extract(files, a.extract)
            print("extracted %d files, %d bytes -> %s" % (count, total, a.extract))
            return 0
        if a.payload_out:
            p = Path(a.payload_out)
            if p.exists():
                raise BundleError("payload output already exists: %s" % p)
            p.write_bytes(data)
            print("wrote inert payload -> %s" % p)
            return 0
        _orientation(files, data)
        return 0
    except (BundleError, OSError) as exc:
        print("error: %s" % exc, file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
