#!/usr/bin/env python3
# Generated by Oxbow. This is executable Python containing an inert Oxbow payload.
# For untrusted wrappers, prefer a trusted `oxbow bundle verify FILE.oxb.py`
# rather than executing the wrapper directly.
"""Standalone runtime embedded in generated .oxb.py handoff files.

This module intentionally depends only on the Python standard library. The
payload is data; this runtime provides bounded parsing, integrity verification,
orientation, document access, tours, and safe extraction for the locked public
Oxbow wire profile.
"""
from __future__ import print_function

import argparse
import base64
import hashlib
import json
import lzma
import os
import re
import sys
from pathlib import Path, PurePosixPath

_BUNDLE_NAME = 'oxbow-standard'
_FILES = 54
_RAW_BYTES = 231728
_PACKED_BYTES = 55458
_PAYLOAD_SHA256 = 'd38ad6cba553c4935d4686f1a5520d5202e182438f93718e17f41fb3d6526c81'
_PAYLOAD_B85 = '''
Qd2@P1poj50000000036W@&6?a{x8~Hp~U!23i8dT>t=tjp%3#&?<Y_*@`hDl?%IW<3gY#Sq;A>GYVc$uWCSEqBbbhc;AZV)#GI}
M@#^OVbkGnzve({lm+Qyt%KOI!^pU^?eSD$qj>{?I%%@-
1d?#GjP|_O5n~Wh)BCJF$0z+hBvbHXrm2bBmDSI6Ep~!8EF_&eV+e$_L=ld!T6fjPGKO6bPQuuFj9F?^DrA=dj!qbrA9%={G!}f;
Uj+ogYyT##JNnO$63fY(5u~Lx%Hy1PUdrUKRnDE$;2^CUE<xyF>c__?p8r!qo#%L9-
waQ}jvb;eQ_R)%lw*j@{LZU)1NJW!6b+J_r~abpbc~_^X$~S8ZZVS_0jBI~ok<fK+w)3LYT%~Zn=o(w7bM3mZka7SDH;wQ+{)DWJ
kw5}iIva8lwBv>BC+sgXf+w~bb{mv|G2U{<Td)b%%GikfarjL%Q~q>`X;te+4-^rhE}4}3rjbi4vkiy51i8a0y-
QOB9}k!^Y}|STiYZLt}t)Xo#MG^>Ruk}sumisFAHRkuW|PN?gDXM7>ItwsoN^geLg#br9fXCn#B5#tnTE+PFRgxLG|@rCk0YR*p4
{4`&E}HnKJ+E-&$w6bveW1<eObAgZmD%{gj<hd>Asg8~m9FOv-)G)Tfh0uZ|E72l-
R|34aV4b1^2RLzEQ4oC|zi)a3)qF0r{BcF3_z4<djSuyZCDe5onZe)i<8Be?=sR}2R3NW<;0F#4uI7UyZ@!39F_+m!TLWzYia6y6
2G{rxZ`F)23hAQ~;t))NbWKsJEzdgT|t3*;FgO=Mm?mxJIUf4NozyVl`GSz@?WDer_uUZdVH>7mDcLU^0xm+l~;J`aMs6<V|hMR(
o%7G(@x%3xGT7-
?YbhvE=M575w@+24Pr3X;I0I($2S+!)goS^NnOxORYHFD?!W0)PN;0RU?NkqGG~pcAhMx&yrknnAw>@D<?&z6<yi$sV>C>LRQL_z
8#yrUZG80*3<k0mTB50qO(j3da(@1>8f}2dG6+l@cSAiUG$Mz9X{R0iZ19DZd?+paJ9)^E{m<$t1^F0G)r!3z0RQIDkw5$EpM4i7
(YZT>ue?2FJn(_^3}%5m!(YreT<RI-JHHKxj?O3qN+}-
!W+IGUb;^DFQenDZHsph3X&2i#AyC!<;+D7*s*$9qcCF(B;D$FyxNDFTNRn{6&*90kpmJX6M?i?JciIYuAK2n=}D59a8M4HdkKLu
s}9jixn<wQ<%vQ?`5^=OYPcV5n{{2Necf=1@koK=|6D9(5t8wiI|tJ$Xjn5fg6v?1xG|#;l7qfRIW-W-#GVb>AfKcd7if-a>-
S6!#D7CrOb*PGy-cbDLJHd^s!h2@G2WxA_pbBETFx{Oe?qV7zWrkzhN9tj%ddriTyPXu|&#FUOUy~p${_!kSR>OjX?EOJPpu9%N*
JC+Za=LN_vMmI_r!KWyWgSSUZ_zPc;mjh_xj>EPNJ*+5fCkxG6zJh$x7}dh+RQ6Zp2(z(ANwR{7#OBZvdc8+^0z9-q7Q-
!GmhgDfwAoa@!;G|P?#Tb3Lf`IhPbzfuqKgN427a2(L%>=s|YxnPiZw`_<*9lEmC7PIiKS!d}Y$z}ucp-
4{#2XFDO)n3QNgNl+@c$tMo{#W=pSC6%%l@m0j$5bUYXw0TtXm=_e+(c=E-NaEZm-K?k?)kaftErri({FfR%ZnG%{Z=Fyt-G-
@{p`7)n~p{$tA7j=Xz+Xw4m>Bwv~3r;kT|>gUPsPuyz+>;YWnLWW8$%b+W_R;7wO4#bAa~asMq?2d$_Ri2K}xw{Wrsf!97Zo#3y}
C1UYGFa3jkbG1H^ZH&F0BRYYE5sYW8^8jUIc=hH;>hA8{6jZ&~yRX51Jg?8Ttop8mjX&G1t!9Y;%S}n6t)QZjc4)C0-
>F?y^P_(VBrl}ZV;37{@b-&HNpI<$)WZh`VQ_rhMy+VcGZu&`THSBn=-e@Gk@@rRVc-wmeK)M640cm&=VJ6%6@ljXfmP*~PU=Nps
n9LXxEC=QELJSeePJ>ycvhD<%rJsFFSxXfZlG_udB<8%?+giLeio~W^M(JHak8;x-S~SrodB(AgXH-2TG3#CX?ljj_<MInF%T-
00KSg~WN7>HAwr7?D-XiL_g`P;2-
SIyNPkCIu$;LRIJdvPg^^92um=&ow<3S#0*BhVw_OR4`Mu^x|S@4unhZ)wJ=3U$#4zu}ajQTDSjDH941Ej$M^xVlz#_IIGPk~4@#
j+y6pZgYJO2|MRr`{9LHNFf2eM9{`RRCFo_S<*wog=b<Bp*I<jUS=s5&9mxe=BKkeJ7+V$39}^hEk}_f$&fR$*!s~Rlyj~v<;*CX
oaZ7U9F984_}%G5`N0G*I_xaFy;?7#C-y8(GMJMl?L|cL3U~WJ%emx%Vz4+)ub<XQ#9}F6A*@*Q`av6Dvu-
>c09O{0jaVMqp<e~&*CZpCyY+Q9m<%|LO&{^hn@UcLlYIRUkZ>cxB9>ep;KHh(b&;@{d7^K+vq8qE?=-
X8YuWmF&DyCLZdQQnJw)ufq`K-+#o=6__M}Yb9+u|BIKnqe-fbUU+wq;qH=B+XRvdtZ(r>usn<3Wh?G4&sWN@ciL7&~-
qQ&d_|sYT9?xhnvXs!cuEaSs=mhj9l0gv-
g<nIFZQ#p>=c4A$OODV=UpYv_0ev7ys`MVbfbDe+0r(^LWY_&ShuB&_$BZ*#m_6%O771l!-
X?c{9LqmKcYO@)G%g#<SY%WMNRn`_kTwzvmP(KnWFWHumjgVh7fWjWB_bulV`b#tV2TyPbfpIlr16dGg;5RVa7cWwX&@mRGC+A&s
0irC``7E{unu17&AUkFDNau%sBdqV@^e?lqY=<to!r+0`zQKLa-w@uBwNO&cWqj;qw)MLBG9x@!d2r^p1R4$-
n{g*sDLw9e`)tShF1Am-qMir9@-DFo*wA9>5MW_C0eJCjtbo?ec@27z1UU1yOA=*z;a?^DRTeMO38D(`E-!}oBw$d3NVxr2ZSmD-
`#o^Ac^4u564JW;l{a%(I!dtDZ~0~tfze_mU$kmvLm|_2#V8N-
|XrV0XO5KF%gR+)?5|s4MC<BSo$~8Y$9y<mWe|UoGxu#6KH(h?7i&*eW>u?+=zxagQKRQpvVk@!GLgxkI|A80!3DtO>vrFe$ak8Q
F#rdzP|SCsTsLDtjUmUk~*s=B6BJnI4L~00s%TTdnDXU$pHh|$L0?M=ealp?2R3KieihcWT<D_<uZeYb=`5IcY<0Tf?#Bq*$z^bQ
Y3|hIxbHCYB{HvT?jyukpA&e5Btd^y$X)eS~7NiV@jj#)1yMfm=B$nNAbVq0W0=~sguYEcYula-
F9Cc*=7NIe<W!l3Wu?tFGc0y*)|qn1e`PIl|Ig9HR-
+ZXIId;MrSLCi0rbxyn;vIlKBwik3=Ver+Nn|xWW(aqvY`705e0Hz4aRA|Bnk`Md}P+Czx)b?QE<Xv#@p{vK^IN@JZA%0T`V}NFB
~fD<xkr)^Af>ZxUtO9u?WF9yaM6Ayz*Kv8Y-
Di)MFZN!Tl+)P|}{K=SUYboq4KHX*>7LoW3Ormt68r+c2Xnq;#tN1&WeR+Bl|_hOnnN3Ys-
6C>ZDr}3cyqFhDHzh>i$YkVoJ8@FVUjq7U05EL&;pLh}@9-QcxR2GRcN4ZL>(Ivr61PFUudG%Myb^FC~-
zP3!c7Wt*IG{19nW{7{VzERrFy4tCof@j5NXN2un8fX2I*-JU8s_#YuNwk)5?f}D$mx)6ON`5R=*{&vt(9E(_K$}-
{iiITyQ45MF`~nHACQJ(SYj-xLLupL5amb<C?EwaT+(K#>;ko5Avtx+P>%G0mLVuT^PpQE#XiYE^0t=)S0>5qx4&aZth<-
^4yFft90XAkp{PJ<=s=gKrj<#I8dy!?Jlf^B&G-c>+bsmab+c$Ldx<pU;6-
44JtMza6bgVpZnq+Ul7OQc*dOP%+oz!&6K0zOZb|%MI_QnXe8edQ15iuQcZPaY6V?D9jDAy5AG=@WzIQ2C%`ls|0!3cAhF)qZCtI
K@s|$Nh2VQMA14AJzbyicAM#EkRbN|8ZDC_Shdpq8VkF)=(;ngtrdm1|2jEYq5P=QA=q*^gq+%vF}a9oT7kn~)3yk*mCtcU~z-
}=t5;~gwnoR9MZ2QNWc9d8fPKZToB8~Ir)n!@l}CIW{7zv8SR2DR8S{#VGJHsR%~tx}YTlw!30bKYODrjvnuSsspJv1;)}Ki94Y=
f6xyMF55EFdlZ|H?Z<G=f3xcbu;>HIdR%AT9vk~ZV~@JE)Uf=Jz{1rA%xf(5Ast5Ll$i0@XbmUwI}v_EK#aTx^v8%Z2>|bMF4ImX
DAkXPzsQ2MfMhvI8=HH99!2`VhE`cx@puz0K3LM>cl@-v%-oyES%poZRUH}H4N8YQo`)$lC58wqL~BTtO<{tiQg@a_QT<zW-
o94)COYyt+BtB9Me~t?ksWLJKzcb2t!MexT;onSPmH{WX#><l^y;9*u*(MV7`fjl(<`+fFDm_z}4}+Mf254i`Ew1wwq7|5JcVr>?
4-Ku`!>wK{TKN;5s_IyXqzc^XB@|k#W?nxizpO!gPq>^wSQcUIRP3OGj5MCgJtymSvhQ-M$_%s;be7v^p~r-
U<$a>xUgEqkP&WvOJ=KNWSz~edecHQ*VYW>uv0{6{zR+N+&QaSU-Lwuef-
1`}$ktLy+%ob5cAf+)Emim0YFVUf|0L9Rl$>?bzzWz~(;VMdEbqrNeE)4j{yzwG!CC@?AxmT`+#=<p?i)p@|40+y`YwRNmfdc{gc
2M=xeOIFV!O%=;5jlwo1W)6h+N)$bfR5`uLa{_vQ@Z%CEMjD0124}B!v*jF$6(rBfX!eijUEnN#H_DeBj(H>mSKY;|<9pdpu7-
$cTPUSw;MU>2*>)>(3T=7X^RF4D`Mm+9aTT>MomwRx%ECd(7t{$39X-
ZBH2mc0DZt_b=D4W>P)7yb3o|oobP}YWa{p3Caoe3~c)kMBD23ftR&DvqR{w)NvXZv;45MAUIZGmZ})Q>=naIKDDU$k7TF016`L2
?ek`lnk7zSk_PPf*2?apO#)YKs3_l%r}qWB+@J3Ia!PV7OQ;vuqIF8G3Sh^v{Id0>*s9*y(B^uqTz4J>T$_SC-
n>#^>!B91Xul8wn{ABffB}10NNq3E}D9LWSG+$lpX^StA>-t+Po-
VTAOf>MsXgc3-BTnULPq6>dSD{5<Lgr6iCHXlTG8L@jFZX~>%BYI}N3SbRU&!LAe1@vyz4`O+yaETY5tNAy-akNM~EZjorR`tL<h
3P#B0Jei(!%7&V+h`-
o=JW*O*y^il((g7pXL3!HlXmCxKd({~#*Pzq@;4ztH9~uZEBrjX$772oGG}&OndwU1Sp_UiefBQEgO!2jPh|^8UX%odYht0EOfkM
VKmT0jL71ZT+dn5|e!Y*)VZCSF`tF?+4Q)bflS#zD<$c#Eo$;E}kzjjLIkc$Ajxi`IswG94X#^P6vwg!w(0=`9f%V;^JOm3B3oc9
0Tn5FlVzq2Vw@Q!1`pI>^zOr_kV*Izk33JQ>xJ}!*-&oa3lbecI|35sOvSDtaT1j_(b#MqnVPW-ia9Vx<&RJdFW1=~ZL<c<`@eMw
DW8MG*tV~HE{^+ha|Hj+WMS_x4Y=tEEH03tyry0DIn-I$~P0|U8=Zm<)A$b=m=$(+*2-H%1{e!A_zus^MJ)3m>lVky0Q&K2Yi#R-
Y^N7D<j%c*93jHJ>x?!Aiue?pp(1|i*;MfhGw6kDH{dOQ|_-
BeFA(ohL01Ia=fuj_Z<&<T#Ws!X3ykoxq&?h5wC=}Us*9eZEsLmN(y(asT##(bQX9>gGn9*m9^Nm^5`f`_e=GXgw^LD{9{+w5u*y
mCCOk}S8am}Ay24_ah<uHx#`<R)T#p`o2xHF{(r2teAoBDV-6aD4J}t;`?J-
_&*fY}z=nX3zEDUq0Bb+)#1^9Djnmfn1JVvguPffVV%wr7BII1(`dD-
7^pH0=|f32EVn;!nfU|X0b2e5ugnL!PW4GH)!%WLPQp#ZsIeOmR!I6liW=6l4;qGg+D0b>!;6Zuw8gnWi{>$sj(B{1xQj2OIu*oK
4vG~uQ>$SNZe+han|(*_Jq;&d=7n;RvLO`4BakrNS$?jG(kr~DMV3MyEnevS`U!LyWT^9c3A$(lRhAwXWgKu^*_V-
{9;L_g2pcZJo5eUR<(hwKnV3oi^;U^{fP2dUY?djS5Ih>BN7+zy_NB@a58RhgEEC_1~l7e1`!jx3W?dWxxW$7(xI}us7!s1@^iEc
{VQbk>^%JEJc7v`V*zD~!u~Ge)<s=Vi*ivi+jdQl1)nL9{i$Hjdf<RwB7%ZEtHkK2#e;7(Zb}V35<I1l7!gULiI2QQtAt}@VMWdl
EjM;ruY?v2i!#pn4(x|Z@#@slqEGO7nQyCbZ9ACmiXDs^Ugm|^W2bLW!88E#(d^hlAj3_iNrWpuqxH%aThi~n{>&qrc#Tl6_Jub!
@O=!WHw9p|FMEg&jt91D*c)Zu0+s@ehG^q99(qKMM}Mudv=8t$VaTIlFb9HK7HpE*Nf1Q7$vXAG8`JP`)7AgMfmZ>2Et0XMxg3Ru
V-
}wr*3_LK%HF^^=!*5?Y^@Es8qOl1@>)<c5Je45f9HVX@Jg>MX<(Ssc=}em<g!JK)J4V$gD<IG_ERgK2rHv^_(}Vx+%ori+{UN9{6
Caq3n$a&eYDk}%t0JZ8=f_!CD#qI4Qtf@TVP5}^y@`kQzs2d+-
gFG*V!Tu?nw~5&&>+Gwp`64u&^rFoX!OKp;`>v#0{0OqAzDQ&=x<goc6Gtm1~mORY3IC1Vpel=aP%KkXxby2tHZKWS{|Jfbvesg6
du6{AlrK9jxZxg2{$)u~lDXWO*N@%A*sYFZ?ydsQcZi{zNp6{!!#N%`aP$9|X}~lrv!x?+4Ey9mV#XQf}J!msV8n9pri_c1#2uT%
%>Fg}2I<o6*qiv|M_H4u+=i7(lq-IC?Eqf-`_n5OHwr1Y+Up(rKt^v`NNpMzQ&Jilxt-PF>C^p-EOBT)Jc-B^c_s-V+-
o`UPBB1J!9fY#b;vMBqlvWrfaTr59{>HhKOr{q8HYR7wLB9_JZxi89)?X2vw|+z4ZJVXkS(tcUY~E|rg}jTBKbN9Zh<$fr3^v0Za
&-mPjW_}xdmjWNEFp+TH-VEvRN)-^^tA@C-}TT|-
T#Z6#fomW<?M~So04IM&#0$*A9szb1hO0AbSfnFlMr#&MBlxmX#neLG_NmU6*cu6TkRNFQKuG+^Omq0!g<gspDA0;o3Fdi<**~?B
Q<QP$+HI(wT@+H3WZ%dYhP+I1vy($0;LqLn9WXY~E(il0JFVajN_uU=eY~&;7-R5ZpM^7h+ZeS08+R^~R0*piWd&Y58w`66V5-
_MvvRL7l>NpU<$*k_TEoWZ&*PDMZ(KuFZ<<v|=Rw?G@CYRgrLkXRpBeEZym`KM6VTQ^T;c>hy6#QD&K#?6hVdRd)j|C1i<^<S&PU
{AOBxt}MK=U;y;CyhppNv9#&qVuu<P-
a<9LZ=O3ZS1aH728HnO8MU_9xm_+Q$(V|J7Fr{i_(N#)se`nhhioD{1XyGGT+v1o5H*xk-
u~d4O3ke`q#?M=!*9;3S4Lz6{IQ10s<u(^gdk!_j54jIUTOL}N7G?v;gd8q;_g`Ie8}Dt1D(tG?I(HHvQO$7Dn=?GdI{SEq%WKps
nsytorsrh^(daLoW)R{z_Qb`O+0Jhsou#WyqTrxco`{33FrN*gh&H)4RS6J169bC<5F=DKVK)r-
R^Chr6L{eqZI2o!J(Ll{kbEO9PI(laDA8sN(#r{Pky@x|?9=t+`3Z%Me2P5@xEO9fh~wU$bw-k3FZUU6T`@In0%r@i}C-
{$Bf(92i`;s}Fn2spq!YHMv%I1>%rlp0#!;D3BFnv)LG71*lbkR*+*+ss_IH?;a1<}?Ie!LOPgL~XY}=ID)#byR_y!^o=WSp<nN%
e`D%O%E!&SX^KhW;3a!-U~!#XnJ+)voaNWl-`v5A-TI?HpyZ5#=2wP@jsN{*qMikcF>ej3nT;d4=ET^QYR46qIR?kuRWT-
U=N1r?4@#(Nhe#4!t#p|tc%#|_z$^=oK=&YNlQ*@NK605NFtM^tO#(vZ~4;zi!e)*U{qjTQqps=01wxzIus=G3%E&>*lGZsGi;@&
272iinKFd^xvfWr{#_o<>tnaYX5ILCQd)QHraMD9xvW8|e#H2bTh%$JmOKnW6jOnWviXRFBCv{?l|T$UWA|QPY1jc|77i;g97tAl
te?HnEouIDn=bc+Du+(mi{<HPV94v>bTm#jN&<qcXL>>cPuR}TIKL>bI~t~O;_mHf>SBh3G5=J-
h3p(O!+hd2NgSE+pTJ=S*^a?4Sl4XuExo%XpTKe9TmEh@(*b$+6VcM#<f@sgxJ1^EpW|_pRASKAI6%~e%>wMaQ+PU5?1!B~OOsa_
wacHHdq}Rue_e5n^nT7$NkC;ta5xgfxr?pz#aO2uk=VVY3~ubYoC!m*W?@HV@xv@jDx_ui?^$vf0{uM;_La*Ekd0LVs*rW-
G=xZ*{QlldNzZEp2aw!)e(_KK@m0Sg*j2>35r*Aee`!j+PePVV-S6+G5oy*jIDcKerY1#}5Gqk6lHDus7}}*wcJm8D-
Al49sE?Fb4v@O5lcaFkbRtgq9uS<<r){-juoe+e7jjF9ogVF{@t)X>eyNy))u`*@3Wf{0)*sV(@>}rZTvsl@%`V-
Z8^4CM4@ms3iV&@>p~&6u-SQl6O=^ZnE{G|mgaI`ivSl|$-XqnFsqZhJ$$>!a_3$BJl-w-gR!{T~Wndto1aqmQ12$^;bn-mV8plK
(jY=8)uGu0I1T%V}_;<>uTR1%@RC7s%#v)*7LBn9A5P?0BJ;D$y9v6m=oE_xL_Xk5gB&}hQO0@l<JJks+J1zb2kC70JOVeAfK(%-
x$pWfBPHw0TJeu+lC}7W%IhR&WtPU~?W~gorJBI4Kh+JYh8!n+?(o2JJ>CL5exDhLK^K<;_IiVCeH-
L~a+Bu&7(wGIuKSG7_udjKGK%rHDl8OXd#3xvsy&I@9E$bg^@491iumE{7-
F@5wq9Y!@D8dGAG^qr8(<z~+k|I#^7(x6?1NRyfi|U+_(j(WjSK+61EpK|9!IR9A7N8}{s+Imzi}v@fDy0<AwaO5S%;)8|bY3DX2
8I5bAA^$k!|Hjy-rY!QS!W7GL!sT0Ie^w_ka}{z2CKfp<*>Zl-?ncCB2Ndct!mof8k5WzI(NtF-
D<uij)sA0g6`nwGTTja!q%(#aVp6w0)TkbW*tC2p<IGKzY4M<z3x<RisYnY-GHMWTavH3IePc~q<J`!_qWk;6BzQG3a7Enp_tVHu
(q#<&0u#qprX2)gy$po2gV*9vCr*gNqG#?q=*8H^+^>)5uNZi{gq!l#Ixo4lv|Q-
2nX_mmeN>K;_yvD`!csUP$phP?0Nf7@UCc*OoO*$QZQUXuqb50_qL@=N)6^1hV(400}@l~4-
9sO&^(O#Em8r2QuS^EZc$GT(r&yRe-
Y|j%Vo1NQu8AjQjXNN72=Et9qubKLCiTppoG7*#n|5IA`90(sb36cUWJ{MhGfuEtZWdYF2UHtSi}i9Iws}2*A0eeJ_$zoJ($*ASp
k7kj<)v2L!jpI-
z!(zUCMoX)`mVmkn;!$Fz2iIhrMjTZNmLduV_0PdQFX((*kn6s|$ic6%^zd0Z<67ll~lpy~h=K>zx<I_5jcO!C3#oBhtk@>F*o((
q!gbhQ^vGZY<rWAjGeq44Kc3>Q)3+?smShMnHz7z7_M5E$)V+0s+K~=1#*Majm15*r}$B6rr^?c|au*9e?1ig<pmeu&(cfDM>R<D
jBcJJ^8a^{qYkWFrWqiHN2x}5|dL#%Bxy!dq1Foek{EQ`>_OMYpXh}4s}08SbdmgOeZTvE={ozKkP%}^Y`dZ_2ROnM(7EW4Bho;P
wF#VDelC(VDZRD2!-zEit7-
5gAbW(ef;%Dz!$J3jhM*TOPG3=R4i+jz5yB_O`qMHql?5Okvzsal%=9|Fwxe4mA^<|;MH<mV&=WCNL&wrl3VVpOIvKUrrn#|e^DE
0bNJB3g!QUC=?~8z#TPRP>qST=-
r{>NJzoTlIrsQaQF}j<C<G(Hp(vQQ*$=Lr9ReA7QR3EWeJ)ZWO!U`U2Iy_Iw)<bS8dx>R052$h`LsvM;Ncd<L`3}k>ctzB>xzP*8
+xP0XER2Ed=Fdg-
0d<;p9LQ3XUZgVCu~!^*$0WFkXJ&teKe_x<7ipZJ^7LcT?++FEuP$|&^t(656))7r1aW2YecH(4UMrVD@>LvM4{$X_XLWv4mfAIu
NnB^PLMyRti&$fNza=%1rgynCQ5j8QqZ$}$Cwa$FI+_FW_BPt4Q5i^U~3Z%$aT+Zx;jq>`Uk4KH@jyKdmWPVNI$fSH+Nx0sGmt)>
S0{{(e6Plj-Q3tIgss2tt&fQim6VW;dA3Z5PuN-
0N4)RCzAI6A$MQa#pi$4Px+_qL+x@kM<wcr1oN+IFfhKBIqL~stYIg0Us_r1z#bJ*#Ys8?`uR2~z2^kqcB6o;HV#1o8df6Trvshm
+Z|cN-
n<R2Unj%>{6Mv1rV~d939ua4H28>PDx^?JopP1IN9cN`jpU|xJb1?MOCLcv1h;{rGq*#sIKI03XSRy8E>gp&>iSkB_=g6$0#@y9(
Il79UxHOhkzBSAcwON+pShJ4&bt;dA4~1f;8KjR!05mD*1`QsNFIZy3u}O)SlJ}I3Wg83s!eFSZ(}P?-
A_3ci@}$;@D*J6SeG|Bq)@AHAPD{775;4fNUY`HGKV?bFa!^IAQM6@lfsH(<)(O2M{-N5kU^mx;Vuf$uZKe;D0-
6+hx$ysVs3(?@VuAM``U}k{i-6rViITB+L*gZm_zM?JTNfYO%D=Nt~^QR6-
GxcN0`yUx@Rfzq5NC8=?N(8GZ`?GE{b;tvsfkL_>|SVv#*Y@rQFA*hlt0Lr?dDi0WCEI{1S~F4I2{7tWh=w!EOT|?bG(ikDg;Knh
u@$4k&`y3t}~?%Nogy7}qVu-P>?WqpHX3RI_12{|zuiE3f~CTzymaKHVeGI?6N*p!^5ZnmX)>-
@tUleFK!x1K^nQF7XlvR+`|K7}I;DC5_t1(;g+ozBHa<v#DE~_pL@0Ny#ff9`gE;Wvg;*Y^Xy{I&i`Y5iWjf<!{joM)E7IFWvf`r
-?#&O9wEiADHB$&-
lu|W*knIq*_m`n|>Dg#|uJ(Acp_?N}N?a)W0BJWWS!QsMAP<1U<7w|6~($QO!94$fW;SjAy{8UqiIm?(cKf?uRe97rrLqz}hi;B|
ciTZ1O3>AU;r>`#h1P-)H;7w<L!+4mWjJnwric3Yt**?gaT`sUpJNlVFdQXU);`quDFaoiD9{l-
Qssaw|>Bo|d5&SitP;Kn}`;bX`*WPqP&c2&H(h<20l-3)ma{kF_JLwBR+E?$CW?I+9@p@3tQ=5fz)6r-
JEGIj$f)eqy>a(Ffse!pyt!pY0Bq4qCFt(C0V^H~C{q7;(`9jGlr+(ha+0xgA!~Hr7$A7#`FYQU?CS@Jx5X-
<jf7zqX7JU(u4xbZRDkNJge-skbq~*9);Y$|ijQ|6Qvx>vOp?ee79;9%xUQ`TFKC91<<F8ydG~dPVDbD}3>t&+hx)l5=>k3j29vD
S}j=%w+<MQJdXb1s(RIk$g&K<~Ty`h_nI)a7^xtcSJ;#5^5^6s~|i3qr$56&l1-
Qvo}Tg#c0oqLRBay?vh){TqOuu>_CW*(!3fGsE2x|8t>l;smUnqDgW=efu#ZDCNVfvg&Dne<U*+UR(V+|9N|%EFn{sjsgAlJk=9x
vnXxi`f|6{4UU0|XrRPQcY6S))PJ?W+S=YC(aA|LDGcI=&1Qh?Mv6$$iC_3I&4OG6xe(Q}`G@$2W7E-I?LXaz=A)aZ?-mtA|s_}-
XcXVkT#x8o^sPKk+aEOp^IDnepqo*Xk<fNAR0#c|1>ytEOg~@I5yBe0Vys*4mC5@+^T>%2m8&9QR`+_6bI9wTJpM9p(V|5!=HT`V
*kA3jfPPk@a_6SWod;!8@QqD(GKQLklD6X$NpX)x&d7HU*E~>5Jpig5J7g7eQ?lEn0Gd0PHMpo<FD7c@YKYe!2Z?uBt)hvHof4Vk
S99z<M4@(nK6nOEeoE1LKzE^$oHm_T-elWSk@P?LK*MzyUVr>qPald{^1mm^~K7(zSxF;;g7B-
lwFanmer|Gjkpvxd67DaIzGxxHD^7Xv;JfNJetWLZq^VpTAwr9uEd^jSI+2ujo2Ys)H&>sdm6(#bMesfl+L{dvstjCo1{)-
46D8@DLUsOg+Pf-fSCa;EPt<2skD+fs|)D2pp)5Fm^!*hqfgw>|lV+u|#N%?h_#00S3khJLuRifNRMzFd`!y2K9B)_E{ZGQd~#2q
2bvB36_A4wV2-|JeIxo>9^*me7TCjvgzLP6n1w(YV|I;|<IWDLP>|M}F?Sj(#FW;vH9YV<<O5%{0={1DN6g}BibY<V`s=VPaCf-
ms>S+!8>w%g?Y^Go7!t@w6j=ViE!y;{()Hh80NMY7Ry7@Q^<;0niUtR-RONZ={Ser!1!uoC@8c{kuwV2w`yuWO<kSkWQ=2%@zE=f
}k;=?szFF}wJux6U*tU3`C)pz%Miee#jO8cJb?7s$jW!Btiv*kmcd`1{`tKC-{+!!PRN341KO8-WF(MKoyV$aoyQ&)-
`~%wesn*P&YPFhuV<2dL;okX0nr-%uQxKoAFn>doa_-
{J+>QwFqi_J#|3*cQ~DTX3+eRV>#pQ|LZx`@%98w;OPR%_26F&Cj2Ah&ldG@7G6BWv;KXBYc;RKWi7Jh*MD>f%1w)?1<;%pdkJ(_
lsh!mh0m{zzaHjdcOfX@mP5&ht&g;U-s-m-qx-iN#6oF&;jXub*Edvm3eA!_p5}5#8p7g>z={*ZbX@#5hZOG`+qWyO4B2BT47?Oa
JA+5eA!tx^&nPFEN@X2dCC!RUKXU~_7<3wb}_OVdYsHj*QVWher1gtk!IDdn~9I=b?uwO)Vbci!2P@n_i!r5+R&73@Y{q}8=7r$S
*LSiZrh$D+Rj*oL4#d&UYzRna`|h)nMUs7kCTI(?_RzId8&pmOL*KwZ3bK9BJ;1qx=#|P;PUEaMqmyotI20~C0(NZIcGkt<kOVSA
u_Wp`Xl{(jXyF6IScZ&tgMT;uI~FS#67jIhfCe4==Bw}Y-4e%C-
rqF70E`F<ab$Yx&Pg%JLhr?!@}Vp@JZ{Z7zWe?NnOWbANBXR{HIH$k~sQI)DB&G{`Oo&;7ydX5)`z1k`9fc$|buTJuz`$i7WMW*`
-h+!2P<TUPq`^U>H{XY;>ilFNX{RDei5HkW-
e*ox&>1*DcBWdaSp1S_@7t+qCu2C(o*@7_z*2)0Z5(J11`w?ye^(zSHQSEF=2x0lpaq!(wR!%GtC{kb`Q`+GFLcpwAl{@1ZCmeH@
MH=OO6t3T@_OSU?pP8fdOeC|AS#c73uitJHLFIOnBgcu0i1+F*9?>>ZT}Gkt?OKn@t$M7$(GFHMLV_?-
#M=9=|#%3NzkuBcS(cC4(~@d?LqP&A&~(70cPaMp%<FAGpnmFL>e0y1o{y-)@GzwH%u74{YB&{QfI{!ARyfCtg-QkN+}<he*Kz#*
@uqQ5F8>AIe&rF={;9$O6Qg4?|M7hF^h`LQ`WwJWsSXNlT~@H^uxC+`+}ibIpR6-X2|J!G9))S;yb$N8}<sKX3Q-
?81(AbG~(`i67){a~rClidz+$_R6eDFm%CRA$?!*88pn1*2^;P9A+PzcB(BIJxk}N6<gW;d~5ED8ID++sYC^--
pH~xTe0ND$(ewIe;(pq_g0BDaSPyZtE-
x`$(%&H&I%aEw?+dnO)mm<z%ntO$D7j*nEE`B0dH9ZYXb)1bA*lhL}>&AqudNc~dK(=5ctTA%hU%DAh&OUey2d4O&A5pG0}~eWCe
}MO6W5oL^=(n?HQZjJTY$RK{=KSdxddZxyRd_w43kSa``~s!UoHyRK6nT#XqAYwk|6xJ)IEVV^F1dR<>Qg=bybVFT#a{_nW64w@6
Pd9;R$f)`RYKi8n<KR?6&+S{;~=<@lHs-WtkUHz@%%o(KMI|vfjXc2-
?LQiKj9VLey$KR=n6tolD7+`KARGDw~uD<0_kt<rx8$<BCU-
h9hC=CF|H+f0XJyGjlOW@%7FT_t^GQDf8<&7AKd{UO1mT+}SI>dag(Y}V;HTooMP2qOY$C3{TTWVP9xmG9f6~bq>U7BpeRWf7GS1
AcZPUZH(>Z}i3xSrt_m}ZIpx5ovKj?RIYI9kGi<*j4lAwn?zlr$K<U$*~PMIp%rO{*Z}L+m-O_{_C5r<=_`IORr7vKh}A2-
57>chL<T#@;?u(p0s4cK*CUw)s2f*zp(A&#(6_*ljNCc$L#THzc;|i^2)wuZhQ&Oe_qr!gJ!%4*WW0vJ*S?qA9cX4XuPhOBm6-
szez`BtyuRfYkUoGd{m@{BHNQ0={}|lsuC8S_5ra4VzQ@lj}d{Xd98KzvV11>7JOY;jqaNyIUOVeD^GLnqHwyEs0UB-
9%n)pl!&4etFNBv~+G+`SHp<!Xx_^4LE46OBRl1k{(Iaf>buf@nDVKBXkwx<?@Sbo|fUe9{#~j(6-p&z6ineRq-
1FGHP5n^r}2tIJ><T16})pOqKrZJEI~kIrX?FFP&!dkitNBXlSp?U{<rupxkJ|emkC5hfl_R4)7f4a|OUd5jINRM0vZ@rA_n0MTs
5J$+<{mdI<Tk$Rb2@PqWl7!<}jt0<wm5b{6mOwm@)fd8hzXT~Nq#PQb*61^FVMF98AO=v{^{bO#RJ!d6Pf6O>{~$@AW*cN|Rn(!V
~I3p)XL(urRqapMi>lAb9GrXoIlV(E=V9(am42`Kj#c}HVn(Hd<_A-UMVPpgnGX;g3Jzj9m@6=Mo6umegPDv7)wUtM#)U&($!)S{
lZv4cv9W7$2wa2%qz!$;l4nf<9>T82uTK=YQ1YG()4x07z3*99qx7HD)u(CFS^*Cx?`0-
O)Y<z%S`8Ze<nkxlj<k39Lz7#?wx%D%>yO-*CJE!4@67Oayvc#<JO(xIAdT!bq4{KG})K4-
hj{AvC)A*zg2vGWOwUmQT_xftu0CWifyk!1rWYKO7$%^YlnEI7&kS&syqeVq8Yq&@L42Uzy{ro2ZBTsyeom5G}R5g1+5soo`bNP+
X%gF33L*@|e?452o?(N*V`;yTWOh%$<KQj>Xs^qVLys4%P@d$}*6jF;%*IKEIU5A}kPE}P{Rbc~SdoQ7CKk3R{as-
z}&;cT`kpJmy~gEI&`6R;WN3|e3oyF*4$V9MyDtZve;3=(K7^V9^h|GTxxf5lCr@jJt%KAN(K88%I@arxmy=QI6EUyNxN91y+s%_
@Zu#F)f4h=D_WtNe0s8n)8TwEV;^Nc8`OdW7G02Er?EtnYec9b5&Kl2KK5UuDE@l2T&kK7_3sfz=Qs-
#h<0z^r3`$xnf+HdI4ln?kUUdTJ`gQpxOMUvK9Fgw)_7eL<8Qu0S}3+m7EbSohKiV*!$IsZJ4UhJS}!@YK<Ci%Hy2YQBl^gw_*OY
1_26IDLCIOX>H1b;ajt1pxl6nxLTp?Z1c_@6?YOXW3}&s#xQoP?E7oDQY(h^HL5CRyY1~nSDnp+%vNIANBp8@kwLxMF7)+=K|(xh
ckx6h63{P2A{C6tHzkyUIYk`(yg7T3k_4FHG0$Dp$o`<2)2Lp#)I-
{*goo0dHwu=PeAE6RWnpEtSC!vA`8q>70CHm?WVrnRlH0u#GfN%^I~dv{^hDN408JNP26tPuh)04QNqfPi*s>Mgz0H<mKxt-
a@%9)Ws=~BVKX%~%Nf3!Kc&oy`pzZEd-
T#sVhtTWCnbCCW{P4(tMi9e;Q^L4BA(&?Hy%csnm~V}dOjBZ#>$!&eHhUGuZyFbzW~fw#%?hE#_%l=nm=0&<eRz0IB;3+`Hk6(u5
{%*uSpV@6(*It=VEGl4_5bHV!XiD{)`G9kYQ={L&2umzQA22UZ~X2CLFlMb^C=a1xvoOx>HCeZSoJ!+ohT-6t>))y-
Y8gWcm2c6Jcmg=<5WDpdHf<dwpJ_bsYtSsJWedC8&9vPGBYEV9rj7roEpXg^f?FC?cU&V}6$)SDhSkW(+Oy0Sw$ZJI^wWsUO+88U
AQq?(-E;+g7n~y9&U%mty6c{XW!5BD0VXQSTA{f`gxftFolxZq(3K=f`Sa()oZ8FFLK4&q!<zG95<IGRN)L-
l1t)qO^KR1fQ_k2)EWQtcoDtqt8)S==?LLlb7m}$rM61<kGb%ZPloQp~c(oMG{2!$^h+~E`ch1J9cSAP_uu`zExuG_oEba9mjZf%
#E0a4?sML_FTg;z{BCryqPvs(5K*7(3Pw60buqJMiLDl%QOlx=D`N-AJ>VxmEb5tskS;UE_P0!ex|_vB~ahwiz`ts`OwEe-DhJG&
jV&wLtB)Zn%-e6V`=<*oU&_Az?SljsEN2H+}88Nq`w2YXrp3-!5(aH1a+DaC9jfP`Zh%s;57ZV2i`GAt;Q_D2W+3-ydJqoDdeT-
;AU3qbAaQ~^Hgl!@8Q;f-GE;$0F@Kg;uy}}R>7nqB)J(b!vp6{Z;2dCpD^`QHkhQD|I*(tI6XAGwB#%-
LD;6eMsAaox7P5R5SgX)#KesDCb5QU-RIX_*hhLN0n)VPp?0;@MGbl=KVSPN`iC<4uTSpXOVoRtTgi-
^XHXy>4{`OkHNY5QhdM71bls}_B|KoRo6#9jaY?uwvCDO5cYN^HHC)P1kpm@e_&)JR+e>i@MTWdZ#W+Dzl--
Gva&_aP!pyHWqEJy!Myx!Bnc4Q!y$NN&>1+5xfJtJFf-WNQf}Ojj6@OiXwB|y%34Md5M{r+vyI;{7@pWBluYF5wWw)%F!%-
dUBw7HGC0?t+G8;yDO|k08CwPP5I}>d3vHq;Ej@ja4<!YPz>N>0Mo!!}9B!G6badG(-
>Hld+@Lil2k&Jwof6}a79omVO8uE|Kf6Mk<Xh?0UVMM5TWO-yDfvwS{hGG(O;N0(4>a3$TmxZZ057ybUX^#3Edb9FK`1gS8fcYH;
y_#37n~go>dj7T7pxng@c68-
htr}UCcRC?(lO%EKEjDOuUoa`*IbMvb!o_|chniYvsoV^}>|r^EjDzF7T7^NU$h2ABa^AOCy;>s>3XI08*fvCMRkA6EsT_^?F)54
#>N@#E1pS*U8Dq->ORY#u1<F2T<kbGeW#g3xDyEj=G)D6YUiebHPg0Z}*4=*5@m{C+uOkNSh8;MVUMj~gS;iXS*|IF-qiTR-
Q*HlIc$oFS-
!`eD#zWB1+E+!xvUQGObEXh0_uP$_xsVBj#5XY5_;3F_oZm<k$tlM@9YW`0v6Cq$w)B|knUu?*sm1sP_0~Ki?19j!`T^*}4=12}B
S9?`YY?qkJy)b6KrsR4V<3TLc)S&p-
KU*%=9N9HW@Y+=c19hsq5gYJWkcbJi56y=BksX*t?8k!VFx+4qfHKor?MKx=TU41wCh>gbtUZz)-
KRc&bULOuUp2<p8gOA1I(RbmXCeB9HyBg@g53>6}lUJKyK~^4<3s%M}P&l?(2s{n`r`wV=E-
tcf?`gi2~N5XwQCz=goeAa83)wf710>a+x}w{c0=GsB?UaTdQ@w3Kq8VZzGezQaE6;n1ZdMF@~Ai;31&bTiKy9T0MVd{t+l?*28Z
tMMIJwj+M4_(S7Hmcq-t5@v<e`PF2@-
_<<4Lz&Y$=6FWRzG||`T@zQxHkMCe4<hkqiiQ{j!L1SBB*GlX*tB_2u)^Rv(W#F4r&wJD?vejka;j_AN*6mKFcDq}xT(PALHk)-
Lyd;5dM>bhwRyIR#O{p~_hq^?2_#UjWEI6!N8Y&;wy~|-
`^nY~)gL$Vjk>m#g&r!6dp98X(9M5YSHVbSud&Vq4ZUz>&=}fS#wa1^dZkb<*VNuJgD?=@&&7^Z@AVMX{9kr$ZhMA?tbp5;Yn=uk
~mh&XI27^i^)C<mTk|^!Ro)V;h+$tV_(GwgYbwA2nbOByO-
K#gHdd8@O6_my$FV!Aam=>d$)^2;jD|IWe8XSOGOFHshGWL);&nvx!6pb_J_4ggpGfy4;a$_HOrr4Rvz>H?;j{_6Dsq0!^-
nV1X0yP$JTf%`PR<cD+8kej~2$CL#F25wPCG=X=9eYzNI$jvsKy>j=>Rh$GYPxtSibD=A*^++`Mog~X9{Xq!cL^nCOV%NXEq6hU2
75`bNc};Kv#O~**JT{ycuqE)l0)LCLw)emFOuhU2c{&KckJI&W7WTWd`G`0{wK__Q6zaT9%W8{FMh2)Wu_S#=OnV=nQCk#e2=~bL
Ff;|s%EpA+}PNUYp>bbDZH`n>d?gv3tYzpE?u{@Dms>pG_zJQsLp}M*VtT5s*-Bu2^&jw-
>3dD^?5g6zpVguWdab`^)z3NLY%hk^oPo4GqH3@>{@~cJO_JDz3zvf50J#HT=`gzZsQ3;csQ4$mGS*mb?_@pud^>YLLO3Xbcq)*8
<sV05DfWZsl*?11%BsgXv<7|NDVmFsb8G0G53FVEIg9-CGe_?vo#<oc6P0W--nogwXFp)n<H@p+=Iq&nZi`Kzuz%0N9mmC!f*%h4
GmTKhVcfwn9xUz2${^#{s-QVd=KLDaDZ7%UEfn;9bZ%MGRiAvp{oM3z&-9^ML=${7&LcHe+17M%InwZJ-
2v4+QpFB)hA_sQ2&#Q+W%wzlr80Cq>v~9TAR)r@6r2p-7<rWkQnoK$VyxOa|Khq4XIH3E7&i@yeSw|QM$ZNpI-
2ymOokFDRyY!H_@A|gJbH21SMt%sr`%gV0wmKuSb8N%0n0<&J575TGm9Gpb*PS+S<)L_{0>5ZK`>ZI~vXD0gsP}CLmT{dd8K-
3V7D)RX(k=OaHs`Np^ndo*N&W>u2UG#n=T_DkKN_kH4o!yDL0lEpex@uLLBzm(7EvK{o9ClA0nG&q}FHp_m<>l4a@%KBL+~Xc71}
@30?g(lh=hs3QiiyU(1C56+V?^~SlgLu(CgeG}_IwyvDK7kr`wy3~}3j%87lyI`93EBBih78A!Tuj<zcoYU0_Xqbq}da$!d7ulax
^yBkj^2sqzHTUzf<bhiYs9%GvI3>aPKbp3Toyo_-
`imCE+KVXZ`8spyr~lkL5>C<XU{+#%2x<d!#OR0%0I==~kb78HDJ+qjgntu;0n}O-
{dX7|Jm{pMpy{TbOlUgY&@m)bdi0By0RepO;JFI;_4Nf>56vq-(-Z}D$*#!#Ohj`QEe{q<JI5@&*qFMp)+ojR-
C41%y}<V3j)&UwhRrsZ;uWo7lP(9V`EYV@AY|Bu8?vAg{#p<k7mr~s5BgTGWY5M{g^CSP0Gu;Is1SID@-
#Y|X@ODZG)dlVx%(Uz$?n=|qSP99p4B8FZFkviSwS7#OS5iCYW9C}O+(!rw+K<$eI!8xh>v`HJ>~-
F%+0s9APo)!8F*d`wTGi<jd>6Dg%YC(K?bbY`o$2xbGnE>Wt}vK)C;tLWvI1;-
6u}~|I(RGt~ajIDUIP=Mg`)82)C#3b$CO=SdtjaMIvch@3_eJ86RjwZ<TTW{)093;;Xt9qw%WH&;%=M58-
LgMoNZZnv%k|V!#+WmbQY2G|f!sL8YfP6|@=5)n9?s-
9YSpSm1xUiF^niwnef+R74j2h3aDsA}1NB?~K7l=@|Up*$yUX912>&RaF7myNt{eqSmb~i*!9(6$;$+9(QbbK$2QV!#zN(<<Z-
{1M&%ENsZV_1#Ej~0?1PN$=M>UN<-1Nl4D4w`NgTZ9YzGv$Bs4yXQ_-`Cc@$`-
SFR)*!i}#wYKDA*eOz>R^H)dXFz#0teUfolzgUw0o<+pVt{Tn8t2;!KoT%oH3hOb??OiX#~H%S{)@bbCSF%?@nFu&KG*ze@fR*U#
B-
f;XECkw9hR6~oSHfwnh$KnPdKoyD57fcfI*;K<hk~EfZB`Cw+8VN++EQ~Xi$n_hr2qYdzKM_L0q_NWqISsJtk<IpgZT(fRs_hB<H
!@N)nf94qzN%7-uP#`q7@){UDE05|pLfNClKIio>(|p$OU9q)Wr?;j@rdVxKT<^AMceOTS-
I>^}5c)gVY;$2^(P@;jA0wf_+?+!nAr4;Y1xEr}iA7jS&%*w_T$v+GF@BupYA(5JfSBjtMy{U`KYZ4Px0WJn9b+A-
Z{@Gh3>1>5I)r^zh+-
<R;asF0b6nMF0?3ZjPN=y3ou5@RAc6EAa!JLi<oml6jO>2Gp0|84y+o~L}wCR!Q?NH=gK612G?w@yG7Qh$4@URL7$)^Y4e)f{7ND
kDMrjR)R3pe>hhT+p-PJ&`dHr#qW9-vjf{$K{kFU%<xe0f@L`H6*Z4a{qN;!*g_ChxD-+6Q83I-56U2i6Rm&=a<TRh-
E(Q*r)5q?i#{@>$$rQ7q^JKg1<L^=q25V^!yr3V}0EsGWPad<gy;?{N~4e-6R9|-
}R4v#A9btTEQLjcrfrL%Z=!et(JWJz*aw!!I74n6pV9-4yOrW@eLN>QkK5fy_h|IG(^S4t-
k9jr;`CdEhsf2!tCYD{9`EflLO2m&?MSxc<i$|7KKq-
h9Rr=mtECviVeam$@L^PcOG?(XS!?xUJLQ1dy~AkuoCO6*vH!ovnE@mu5>gMVN+Qw;(=8rKU@8YL+MJ>^MR<<Q`G1<%1ib4H`*ct
l`o(1Nh)$%+8blifuXdtzX4rg_DvIEGn1vfDmrqNe;i2uU?y4<S?r}LtFfXGPX{$UHty7A$WF&TA5<dXJZ#X$o_1-
rtdQ)UCnRE2UF95b6ksz@Q7!Lqlqo{0K0VnoK|s#F88JaB?H$MCLn;}ZEC?f~qwd|TeBRI`S?`Z6bl87rE|CEuDc6+TuwItKuN81
XuRh@KZl}f=&?aM5ZO<OwXsbohcechXdL)XOg%KnoR*608y1;58N8J2`%lisfx#vTYb&e`7h93{J(Sg_lE~rYCZw|xWrZ)bqJV_>
=b>g?XK8p!x-
npb#NQ_vEmK>=a8gA8ppH2?q?mxe{`AoP9@9qdIrG(~Lc6!r!3vinS7zXW4K4?LQZCKpy({8$3^y<gRQchY$;=(~`SC>1jPy~WyW
#~|BI;bXs3L9jtc-FaH#FmZhcZtDE@5G9jQ+IS$&_EhW5|!;D=kKA@z^@cdh<)iEe`bH&DK4$Q;$smLFKB`U7Mc{4<rs)xh~bXip
pSMs(IDSI0>Eu`urwG<k+fy-P&kC9@jE(t+Ghw}kk|lXzxH_E)0_r3SlcTYEPXg^CnZbOKVlvp;uC%c0)Z-
{QpL+~D**{#A5uLjQ8V=`C|<bWQ;MV6Wt*w?8`|BB+}pO-
3s)>YZ2)oA1Gn3*oj>`DS4D`8wIUpfW}7m$8vGUnQ>zDy4q?mB8WGz5mMbZ?>$<vbfRck87?av=OvF9sJ<Hs|hF@1R1*}F}2ZK+<
)b2~2t$g<0-f!8-M9V9TnR3pI*W^6J^GuQ=+k^Blf|Xh^9(&bXt2N~Y4RE%*H&TZ-HY=<8nJ+!UW%LzHO=fmMVW}u1rWjpJBo3<<
W$8gG_uk~tvv+5zxnhTzlyiEF!zX)VdIC{7Q6aH(jGYK=21CKQYJ$i~9rOu<<whJJ%p1E*WwFcDId$NlIR|VV7Cc)hW>jBIIfHU1
p$Xlc-Ancmlo;>$ec_>yXmdZbB)f~g9&0I@tEl6o-
F^86Hk$FF1@cd~QL?Dh+^~nVd(yNF2Xvb53_mR&wL+qQ5<r{XVJ$dS1lkC}I1aqv#|tvDt&at`W-
lYEnn6gAC}Y0ufHq_E6lfz6sc3vL$M=7LpifXtzjVrHkOyXH-
!N#9$5JDKD8S{IWy!&cu#J!mZRoN}0^Ez?2^3k3e@ZF>SMAqk(q%M)RKsGn)sVMkoP+#T!_?%H@bQN|WfV+Zgd9Pa46`xKh&`-
CCT1S8n8rI!5w{X~`bDV#W)P4+squcD#gusS8*;QCjt2F+YSl{S`wU~K;?QyG)i1^|0Z&*6IwZ&0X_oaU03*tEk!OK#hp4B#rRP3
!e5$9j?jG@xLgBF+(CxEj<oc`DLR6=8Pn?d}vym3YQDc}v-
K0*(*pKIKcA8j*E7nJbpV_^gBw;FWRFxCDq;~OM?&7NT0i0;j`jky)QB~IUP~-
e}TtDbDUES4XP#>nFs<Y)v5;Ske(|=0Rl6S!9E!o0av;pE=wi)Oa$|QmM`u>>uRu(*)*Xn;RoE-
%yeLALN>8}$@knLz4*);5A%GxtxCky|45<JWbmjyW}4YM_u(wZ)u`)(F1i`A+SyON_&<*)elVpmU4PRiv;yX7lpILeNj*^u}{#RE
7~>7PwiQjim^@*y!a1^T_Q7qS0MEYDDTj5@_WwcKh-
kti(^OPdO$*2GI5M6#aPD!}lC;<eEBzSBTbHkfUgiITh{o;C;Nj26cbp6CkkUV7ij-tKTj!#RdMidpW{)JVacXJp+|MtG(`vXDsn
q$;8jn8k@jf31Cj35KU)WiNm=TBY%;OsQ08>t*`-
=9Mok>CwvBtoJS?ZKSQB=eJ$tYrxYx&L{_Jn#2!+nq*O_pbTJ6LwojQR|?H8EI`f9n4$qL5+H%GOEc!S$Y%0J^>M+kW!Q0?eh~*x
us+ueAS|y0nV>Be4+h~BBP3XSG6h)z`g;2OEbDN}97(YXj_Z6uZ6!@@VV;_Eiw*O(Lhj09x+7>+evsF;qb3jgj)0;S>|zXKm&S&~
etigY<_bo;eF9-?FdU%8ziMfYlmy9HHh?Nl!O>Rr|KJ-5*~_ZwQ8M*See4&Ovt(KaX-dV#Z!*oXjD56sk;;L-
MXm5YZPGzi3?WtxFEGgbMB62^&L{ROyv@9xe)2ndn&mfgL_;*!_eg{Obav?zlTrpp<cXKoa3G|fPvt^(RM$F|o0@q3LT3rquOru3
PECG+Kw3IepDn{4+6-
X!GV<jZ&WY=zA$SSM2=l!Pu;}e?9vY#bE575Yw%>S*5GFabJs+KPv25o1mLPcyYKgcp4*muTkcJRfP+BW1!lo2K-
M<!KOr_*w`3&vMw4kIxSEbB%nlk`+!#x3YSlujR*b3*PkGn}z64aZ?9d&Qk1P#^s>xYF$VdEyW4R>`9Ct(C{g{uX80HVM4W~<GbW
Eee10}?eJ&*Q-Vy%Fvu`@L9S>6ogEIMNSdo7;+%P}aas+a29>;uKMOFvBFNeo-
+Wk_P9fz<AN_I27U*(=oJ0cW|)?rQGljoC*_#E1o_`#_2za!%lb4tO5=r9_Qqok6cP1&_h1LywOAg#C6e56#?juZtnQ~Fs8tqjz_
?*NVDS;J@GnTRtSd{resudZ1GG|)H!qE6ss{Hkx;4Ip(HI~!7Ot+qq$tt-DT<FT~{UzBHU1cA^*)iS7)*GTNY|ARhJ=hkAoAO9`b
$B0b#44V9U}WaI^!R8VlR_a8+2*C8B%YyQ@UrFEJ~IXVI+OQ_`O1QpQe{n|=vHPZzFRzmMkcv;;q^%JSDW6sX#`cW9)xUI#D(_Q#
=@Xd^)y=8;3I41D{}=9GPuQ2m`3Qf!bHl6#{&Z+)-1ERG~Fxmn8#hsG`!g77_?`Cm~SO)daBgQ<*qx-m_jq2ut&mTbh9IH@|Y)7P
vXJ;5ZTG-0-
~Yvtt96^Ji}Q!uKSnZTV%BjUXM*_T&n6G3ufxsWw7^KF|!3&O=Oh275qc2JGgW?ytgrSoEdT_LU(%+`bbV2wDXP3^>>G*cI|dW<g
0B(}_luIUv5O<|Q?#}`pfAJLJFh^xjo2&E?ml%t(gzav(S-7MY6#|oJ!e~nhgtkK5T8nDumfuUzbOOHyPOruL>O$>^OHEC|r-
;kQO;aJh+F2)?9gdThEm#VDOz1@zmr(;1#-
x1_}_BD{F*MKb%hcBFruL$OZAw9#n$<dDkSJCU=n~x`%ZcED`ny9KEEXCeFGV;sV5Nxk{`k_~rwfs;jQB)iwe3?Q-
{YMbKFvYBL^~FObPzfCd=%WMNO|^8*3?Yq%Vy`bv%vy*&SJn6{(`2vNaO+s!Nbl-cKPhq1Ao;#I%Qb;pr*7V_U^93^dN{$VG&QJs
Q7<{#UAJ2;|KW&cGrcTdo`X^Hl39$;TTBHY`W@21so$m3E68U#lBLD>U0y*$hXkHZMZmD>Bs4{>&6<hug(5qo<>%`sQb0kfpV6&=
lL<N~zU2Th)M2_uj7$GF5YEj`81yJhJMDbDGp)oUL!UfXaJu#%Dn+O@LkocjY{Qj>+tL{uh`eM}$fs+*3z-
d(r}BihwRt{yWe53uv4dvEsf9!a{sK8x#^!s{!TC&|<a=aL?)bivo2a{x8O&>)%Q=PZ_U?m7^O)KZ5PRtqZ1d2`+7jt4t9-
AB)18=wrS02|?IknH=n3_~Du=(Q&7}P&`*HeCWW(pL{*)C!%wH%9{unFco2LvbX$o5G4wG1#kCuW24>Bw)(qJ(O2u*?9jz|MrtP3
qS7?*9`r1dP@7<E`H+uXHk8fHkwp1CG(h>_CSq?N_8*>FYR;&uNkqLan01473Wf(@T;eHAC8bl;br_!@Y!J7c(xmT7$lgi8hL<<h
QMXBlsoHsk;P{EkcWK&c{iN`b~;$eLqLj;1X|sMYKbwSUy-JvCT@=W;OSwn`kpjK_nK35V>dZlT?)xN1CTMZriK4|^zJN?WJlhVW
vh(@Q}j!T_zm-{sQ_9(UK=ol-
}@pft$85YOYQ&4%P)0oZ&9(LB{jmumUl6v2Y8h4a0x3kmfZ)}xr98HUN%OyRE7<Hd*}june^>Y8G}8NH2U%jzmsEulXul%Sl52PZ
Q5sWZO6ucMx*z7T`q28f-
)Ok4@?_<vW=6Q8pM7p}rvQU(|Y=EE8KagAXme(Z$QB6Zwdc(jc2^VM?eG&u5M++rzMx=<3%P2bg)#+e?g{E_aH@n9yca&P(G{)On
=Rgqeok!vF6v?uOu6(S3-
Rt&uWE689CY^e<E5K(BhI)5>c&&`JZX8VHPW2njMOJ%(u1>2$Czm1x5SNe^b0z*i#_Aki4TiribqH%ookRbZu(D2=0EZhs8Nd}y-
M_Clg4a~*>paV=Z5ZJ^h#PZ7E28K8aw2GGBifU-
H2)Xv6UqP#{S+n0WA0tCXWa1Tn!aL9w@j&|DZd9_UG0v_fBeFixMlfc^plGSo0w;l~%C;HvjUo9sn!6w38~)w5fxL{SIB9wUjxcX
BDlGnEMQ^=^=cD!l9;DtUrR@Y?;y^O?sVjYo)p!-E@bTVz4%i*c-=a|Al=n!OM0?|>%&1aknAB-0u^A-
y?&G`<MkI<i1>QLqwpB7XStKnj)|~^(RcGHfM_%5CAhmkxQfM>m9}cQBlK424#$(FT^W5Xbm$>y27?C77=7SpK@r#u89pvP)*8AD
bH%&C<6zNTl%QLcu*-
I*X+3O2qwk0rh?HFs@yD^y&q4S$2vszwo1xRM$b5+8~m%YFg8;HW{fz!u=k@43W4amTVlp&0D?oLIJm2KD@QS!08P`|-
cUn!}B^ZW3uzg<=U^5z$&LHh%%C_AeR6-hL+|9Pjk*pwi*!qqZg=`zfA`7v4IiZb!#OH-fd_)xQTL(af_LF$blE1jBR$*S2Xn-
M?;&NU*1r5&~DiKO1%YrjNyH8b#L44h=(_f;e5E@1Pw3ynZ{j8gwh(3XG5%+Q}v%gpu%-*HChoCU-
XhsJ}Gc}5(7!HVAqZv=Bdm>0&vVlAJ(naDF-zhf%+0a0xvi;!TGlN~F`v;6-
_L<PO{A@FeC1Icc=DrH^5L*Yr1#8C{yss&j(8eS(pu+i>@tmz8Sd`)j69`#=`EcwvHTgrNGBs1vs2Bs05L@*8Vkt9+h_9jeK4D_a
TgT%NB^&B2|Cbm&^+Pmwtf>+?LjI%!Q?Dc{#0Aq|l2%q+IT9{h6XGH*Khw6RNRRrz7&Q$qXV&LlS;E@s4%J#=gyDRr>LaSAwk{@^
^!(8VvnfL6HBh)EdWA#edr7tQMbI%ob&~^Duw0IqZ4S~Z=_RQ-
35QBsRhVRX(p96K>;)6ghwF~AO(i0Nj?^lFK*O@1(&f3jO`t%2Y@^vw^UBtF2cWcBwv$UI)4Du0OYikcny5Cnq`a7&jh|@-
Z_DyGz82@FB*n-IxeBe&$FIIT|wO_3Cg521rA4V3W^>wE;+#1O3z%Y5d4XuX$sHyH{>8KZ-
>C?_cNu$?s5V@=ZP4G)?6Z;K9=Smk;^x(16uE}|hE2mOP{7?`(af_iNOeo-lBqvuRpk2og?o8*tw5^1dA_oPUA~o{pHWjD&?`t<N
q@Gwup#WOfmHWO?@viTC6TP~uVB5+N!LGu!KYp<oy78a5h!T;~odXC?uVsqO%X!;#ttmAC8&FrNTysgWntk!lCi?6wg;TCWkJp`e
)~^Whu9U+@!<W5A7ZeAi3Uj5g?V|at6Hz%noUo3A7DE&yoWigFzw$+_6M{m7;h;eK9`==JP;9H>8x0B|(K8Gsl&G4b84ePRAOHFu
ka<urBWgr1Wo*2gsmPe_J&+v>Z~*3u#ycK>lJ;dszE`Q%w#i7DMx>+PN50*C=~5`Rb{~~JE_v`RcNw}wXaUBh<=%cZ+T_GnH37<H
{)WY?gE@y=Xkb&C1_khPbgvLblLnCFn;Gwqb1%hoyqj8Ryy4)Gz{ObPG(1{v%k43aH_x&=)T`O`xImPnJq8^yF-
#;PWr7!0C0}Au*D3QclM{iXQ}DwK2+jyN@8mo0B!?)N@+B9Nye_KFDU5VvC2-y^QeynS2%Nc#{<#AGKi%u-L)B_=i*^>3O5SY_-
G7b6-g`T1Av~WQwnFRamX);Qc2E&-5Llh}_=DP=Howzdx5BtXj!U>i7*D>7JM>T39)gaBi*W!O@BB&n507WG!X$t(-
4^0rJ6Sy_`qD*1IMQeqql=7;P=O;Hz4^shJBTjeZC>e$>%IY*v)0VA?S_OR=@3mpwQFLMZeIbYD3RED<Y!GQe}yl;<EJHdoR-
a33D)zWX<?p8g;0xyp(-
))tU1hYd)vAPAXAWOL#ZN1A+)Uk)4(q@ech`5?Ueanm^N=DNLG4hTpBNtvW4l2=mMacjb$}ao{(B4uK*g=X&kboNd^Sg7bOuOh1q
`gC;f3*{S!!RsirkMLi_T}#-C`eZ_<%)@p&KEZ}j8Nf51zKQo(Jtk39d{19-
z|7JBw)^C#M^tCSj8X_X`h6H%B@I0v~wJs1ud6(S|D{BM;vfD=O00dtHsd0xq;(U2P&Y)Ai(|DsS@zHw{-
p^St1OUWpweDYvYi10vU;j}*JscO|a)Pw}izwMG!^-W3jIfg>*$$P}-f4a)6)G<Fu>kt-
8)={Meoxhw!o7_U*sazAGQDp01<tLX0jPL2OixdI?Z~XS<pc#D#{%^z{q4Crc1LiBLB?lj@6Mr`ZeL_l2Z@3u|qeK#FK|v-
wiE5aIu@46#n^y3$DmCOS_|14QtsbXZa4(j1k~y6$6}tE`&$aJTZ`+D$rbIG@cg&vmTAgO#oJNjWel{2=E+_RF3PG9+vx+IDD4&I
exRs+rO-
;#9R9d8}`p1D80oHl=!@LSb_I2G2kKVG{%)8%(e?&fy=tzt1Fd%XtBSYj?yW00LiK5(Nt=!Ws?su=*p^tNg_g7yElkqj407X2n?4
id9`5kdf9mI*-kcdR)Yn7VfN{@&pZRd6~juIZgS6c?WNa%vKseI=Qu5>(qBB%K!LmmIO!b40k67TU5O^dgts3reOse+-
t62|6!U4oN3sYPzj7A9U7b|Nyw#tX0DaelH0lt(FNdsNSE`DaR_YI!BZC|{G_wVkK=Pq^*rxj&(;yd64blS3emAm-yc*h+>yDkB8
6c+{@)9fE17ha3tw$N5pS{ZTp2M9gf&pk4SBS;Tlu3AN{v{lv)`>5WVc3FLShRZW>H!@h|Vm!nNGi<c>R*wQXovHa}zkViJD`b;?
ac!F{Iq^=Y7UcU&Cz^bKQrEo#{eFiwPtVu3swu}%vXRWaYNP1?riMA^fIopKY@VxtcFw+}c=HX`3E*bm2ZF(R6Sz7CucKwLSUwvl
UERuqXK8QkcTie?;I-;VaxlAf9yIC9xC|StTkT!(Tb-EpmF^5^A2LG$dc~vuVqWNHqQJC+uG#ti(@m6++4S5Ss!<)J4XqnZM4V8N
iH9qIe!tuv{Hrak~c8))zo0;6vTO+~pC}Y_}utUzWf!Al=_vFVBZH+`RM``s7+-1@4f6NAGLUh7FEs-
1*B+zHn<xEnt^b%0DlHT+s;FV(&iK+bXbU6EqT{8I5Jjb7<Vy`%(mcHx5d}lSwf;@HSw=yHuX#FbgUEu;pB}oF(c(3DCwY^f|dVi
qD1R5O{WP&!QbC0Z>hkZ7`xouiAPvfAXEGz<5)#aih@lK-$-ot2j-
5WxW6k`)cSGxj<CXDNP*OM*FbDI0erKCF_)CWoTS`67k`}hIh{G5<a(GSC>{(d$H=cqOceDE2C0#<hG6V%QhyzWE=!&n0Mi{V2go
ZC#Xp)#40-;M%6Gg2VAqhf<;O((H=h!GYN=67?&x#%LaJhthIMk6OL`yoBL&Z{i8=1D&n0|>m`;LZX-DN`7*5b=Ry6XZoAaeh+01
SVmaS*ajEEg}#z@5z~1U3i}x)t!vxJ~yihr3A@0?(^%=uSecpIh?({@v&Y<%db&pJnxP!hq9P?7X>LzC*J?LqYnE`E$`~hlH`W4w
p92h`NjVTR{WHjx@7=6i$9|WMrt&8uvg#JqUNNa^;9Fn^iAY}QMF^w1)^6aWr%6Dz}D9++-JvtPo6ppA-NC;b2uJo4ENZ}Ey_i^h
&si#jV_;FlqhvQS!KT5(3&#6@o3O2Ke)B3IPbWgBodN8D3EV~<pnQu{@52Tiitiu%I*~DOhpHp>@F1RXE#APi$5E-
ZhW!1d<!fe2n;*p%JP@n94$&tnUBMNGpj87VnJ02z&jewV^td|m9}L_@1slCr2}l_X?DmrXn<9`)@OQzUj?mIB~CL!>%H{d3N)}V
6e)2Xrh^Zh|GZVc3S1VZUJ;iX=Shl2>L14_MH1cW994z2hLL%z;84xoU@HrQKm7S~X2AIH?2Zsx%yOE8Aqo`}kTF5vr4!IJ=dV%r
#ZmH7DOJ@Sy;2>JJqyTb^K3|)DQQuJ+siY7R^;UyVN?n7st9zl7+1t=6hy$T;>ItBKORjl2{8nWtv}5~(MO%~090_Ag}D31FvkML
E`u2sB!JcaCxCIhoJObx1A%=n1o!MyNIXEO@YOevt_qB^oA-
a53HV6CcGg6wtG7#B3CzMoQ_#jNaqXCHpma5)hC}lgR6R=nk&nqWMF#tF!^%~BWLT{g1de0U0+IvzFf9qSvzz7xsT#^zHrs*$z8=
MD5-kTwRjVzP%Y^v8YF0$ab(fY~geLWZG`YId<XBq)D<l5BX`?3I2AEBfZ9h-&z--Yj_INDFIXxG|b19FxI$F7&uumhq8idUDrJ)
()dGDK`{I^9Wwi>x~-9?D#qn!)3-
DzUzL|9#(8=19(VtAYvcUQv*#5gD2Z4SbG|M0)LCyOQ46*KQ^S2rze;0JN45(+pjjq~UGN5NKw6gOVwP_tM=-
+K4D#VMzp)6r^O4I#~|NWDqOD`iB}n)F?WJ*ik(3o(3%`)M&czUTdV#KK=wCiL)ej#|OrX?JGL>qqCyOfRujeYEijwvcbr{Gno;x
&l_j?h?#Tlo61R%{%`o?Z1#J?3Q#<N{-P+V8|4P@H!VS_;kEJc`>Xr&R)~g_Om#>)%=Y9J&(1qAnbr|Wx-f-u-lLhhCdOfavEWu2
#>-
ScdNhMJkCMz9**}ZY*8{=E$Al;aHJ)SIDw<4_I5!4Z%d<6NX8H+)=SiGQ0@I<L1Y|R)fQAF+)K_YBA0f@+wV0yA=X%1gl8jDLmCQ
+p=1Gbv&33{r0|CbqeKWC5CbA8XB)`)<+}F8?YFs13PYt8PTBvzLHt4w4Es<*U6fDeHMw|dgv$yagj;N?1Ga`57j44*y18Z7fx(l
?V|=7;yJvMP(a2_*le>-n-
U!|3>`dtH`7hL;U$IrY_Jl>x6#|z@eHXA^KD*y>rZ~(s;(tY4UM4j2LGOoFTDr~p83U?+`SM0yO}LvUx{6M2MEyR{0DZt{tiOi!d
AN{E>M&RbKHH-
;@Fi(e+j4OhY@coU#2&|zYbvgAD?RdwuX&;GEJu#&0eQlgi+G<UQ&ZP<vL_Ucgu~=($w5T+Ijf+J_}MgFZ0{<9+)pwlfWu#=bJI!
?C)WVR+d@GxM;33Lz$k%r1IyLPT#z*^S>_kE9;Pv%q_+ZS>i>Q^W*@x1u&SCr3_vPLR8Tb1X*?7_NwHjdH}}Au3m)Me6{>Z_!exP
E(z^AWz*a^B($YU4`CzSxt7C_%c?IT}98n^c&4~AK%ezNYIJbHb!aZY(n2Kc&5<B>6(KBV;Xfd`UO`ubpkYHX|=Ze*uu>Ei2?h!d
cHqk0UhbY<%eiZ{)>W{e~bVG^iW3$;1{7n3~&Qie@U#JA^*CsmY1Im=dT5}z3vv<APJB||*gzoeKj^T=s+nBwhW>qj`z>g|ior(>
r0}-
k%L$t?_v9}4L?ga{ubSUcVehL`KsMM={^U$FBEGxj>H)e1tfu;!uZx%zv&7s#*ER+N}%pdZbu6239h#6RsgE$@n#O!08Cl1lD(Kw
o)%8bL#rfHrr9{25bux>LaR@2zuCvhbS?hyM8D6>VMQW0~z>(Ur9>x<5Pzbl{`Aw~X6q68eQdYNzAGc{yq597tFgkKx%(dXXPW@!
(!nl#AM8@&4ke>!BrjN{ww)Vp|%xo1{1G=c{0Ok=|I<o&#Q52=@_{*i(A?rhJhGa|Pzouug0NLtFuibCaV6uTh4RCA^D<C`F6#==
LpOggPQ|0jIkyHwbD<G-
(@+f3JSS8rDfow=1xX)$$+)Yq?WyG%+HwjR`umx}T>)5=7k6)I~8GQlVSxD5&sRk{K+n#2FjSrOdDUC4XL+2I>s`5Kj&V%?^675d
mYF(vPSb9vJ+6r&lYrpxwV%28EH5hx7QY(lq)ElGhH+rh0~Hbq@g@B!ncm0ZnUtE!FG*`vyeV5ihDR%5@(yHcR;n2p-
E;H^~(%(C3YzPo(&y;H^T+P#>!FgpB+q5t`|2kFgncbHG)kIFxBcpt+nZf@w|hF?6mHvNew-nJ!w`HlXMi?UX$2Em;IT;m1S0V@S
~N>p;nJU-$B^Iii<*0p<Lxi4Z6)zbL3zZN!C<~g80&~q12v}Fv;bueKVqu^6dheC5OoOWJ`Ba5V_-`@o|5&c-
X2Mh&RKgmblC5cKnqZwQZS%KZin0cm(k5l>FE2BEW{AD^Nq7I+%g4|hto*z!<FyE3R3GgMb<VS@H8D`i&MMdM1Hwd(j-
PD`ePLBi~NX1)%cBi$1y+Q$$oNcy<W`(jBe2B(JIj6~#mC2u*qJ|DF$TDKNt^un>kd3+lKYxwCA0|C*VYELmuMc?Z*F7H3#f`_Ws
?yvY)>U&Q7X<aV%^p=Z;Eqi*HWiimbNG~HD7=WBMVi8WW>(>yBC<S8n8Y5ey5?knGH^BHtPd$nWk^%T`>XBTQzrag=<_aj$bSLT0
Ik;}lrln{H>ZLEe_{z5B<`wYd1L)LAoCA1iyBHDb6*4HH7)6#S&$VHxD3{BKBC2p1wF1*VxQ4!oQVlfo_}$(^~slm4&@G3dUF&=A
r$x~nL%#;84Yn4%TaYrkMT+@E;Z4<-~Vjf9BOTU*Nvv{01UL8M*%KZ@q>|9x6zUeIy<6-
xafH?8qg|w0ZbMjddM>``lF(iS>G#GRkaqSv~h)d+lNYKM5YsGrwU-pR9985_bPR>m7k1XBI|ts4YbLkfS%9BkpM+WUVUaNh(J+F
&^-I^t}{p^H#KGScRcqEs}DZ-9##fNqW_hsY*;6Ml`L5(?H^d9D-U2Pp)e#6z=Gvcq+CqsQN_4?gZ|g_qZY~fo#eH&-
W4h&aSl(h`stktoQB+<BKwdtOG;P3ewh$|XEhW&asv_CQ3fye2=FJkRry=r9LpY#k895b$L?&=+H{X!oXxx=(Af}#n&Q6!ZJe@*&
A5l;88+jD^jDg|wG!DAB`YkbT=Q!tr#4HLsUB`GTD0cCA%WLc5HI8$2VLPj=^Ftssz+Wf%#=6iY$o)VwPz=v_LvQ#7OTtL>FV_)v
L9SaxvZM45-stA%h&FIZ3Kq4WUq-4(U7nuKL<oWuU<Zaiv&<icQ+~hyya!Xxrgwx1G~}`*PgIrLqc#!g2-
?g&zeiSoPYGw38!19qKtfw^>$e&%VTRSWqkenkfDFhe=StF_b)-
SF_r(Iond9|Xhm4&qE7<&dZIb{5>hg&XtpspeLR5g^&_Sg$9T>me&9j+(IQ<~sR{HFeTa7Y*n>$QEX2gv8Aq;-
%eKMsA_mkgZPSPI?4dI%#hK})w<~?=nHTCCdptkCQ)|jaMt`$Vf7SqHkjHcro6t>|!q-B2-
AYY!Js_mgKrcj@AgOb_pG}<tmI~yI+cbYcEQ7_E_ZDXbouCA$C_T)liT1sgbf8cCpyYCfY^c#Mqy%z7M6$90rYo_+N52s5tjdi)^
xct<u&$wrm$r*k@uo=kGEs1m0pI3y6%#vm;KH!sjjS4~^O7)?2)SL~72wS<4VAh!LRO}I>(SAl1AU|nhO6SU0cvXluz<;MmeJ-Cg
<9+Lnj~xL8GM7xV>pEmsv5)O7K|I|b($z79K)=Tz6^2d5?5U_0pu+OJ%m3G|1Anb^%v^#<=AOFW9D)@boBVp#T8=OKa=hMU4p_+m
VMug&n)1vUZ72tb>Ap5A~<`QL4t}we1+5C1raots&NW%gj-qFQF$@S_@gw0bfQcJ$SXwTu#a|d-
EL7YFoW$aSSUEWC>R~0u<G#M78No=O;qsG!Ps*61$(pqrwbF%k)kl~Z$(obTugMQi4Zm&@*Us^gQpLLN%+e-
I@IL;haqwr52j{j1W7<}z)XtJlUQXDeCJe)CWKY}l#6mpr5GLLY(FOe`NPMcTV2HD7!a~BZo+@DNH?TiWd$6$D>CbZIaR&_Rj-
5}=fiN&)7Zx7a^e(Zg0dh}_4SUj^qM-
`hLD0<om|(6g1VwHdBd{^GEwOvTTj<;<d&vv*?|LT(i1TYXa!EdhjO(KG5@Cbmh7L!XoaT6VAuBPfaeZCoIe`5(j8?rB}+s80g+q
YTlFIGvdcsUUX>i5r{Q58(yadK!Y?VDDwEe4cHdyjT9J{n<RWsmP;v79A-DW)y<^Ci9@i^c;P^48hU+v!!(86${Z*{kzYAF-
BErNN{2}9(XoUD%|A@LWvZiB*HI}jR<>ek%Fj#gjcm_heC}i<>-~PvYacfg3i=ED-
qoylks3HX@0)<^eE8yM#qTxe!0r|Y64h3oL+jF*8eU&4B*9_PnYJ;M;v13GhAJVtS2Fj<VX-go=bXoOb?SO3=qj4|uc<hTh3dZAW
A|!jtc$jFJiXY(kRFSO80o)h*aPumQ2VYpy6Ws(9+3=>O1MotoTB6ZyQB0a3>@W8>ND(-
+tFRa9&nUK|Z4~h0Rh<K`@Fpn!JPYG>qSo_0Ysi>`mfPC&KLO&i1mdvx?bSTl<%|IF5tlg$uLDjZk%tMh=B5goVW(U%G6GX#cP};
FqI7e+`X*ia%uoY-<m~zsKCM3-PvMM$16Ra40JSUK7tR$y&kyI)+=Z?d0+d_XmV9jyh`0`^+F%=Jmq-
4r)>*UM*vTFUL0IGDi+1t{Nl)W~xP1ymmIk>XMf{K)2U|DfC`X94kU>*A05Q}E-
BHM}1Eq2SxK>~+7rXRI>p%uuWjsCiL2GLE@^x<OF$b|CD4BZ5PJoOVi$7WDU9}Hyt%O@2TWS-
5bech11u?sJa~<q7W7$vE?T_4zin*^%lB0R&>1*w1>5tk(Acug;>pWW)w+Vo=vauC!Ux(8D^^N-
j^{EO{W0BA>D_i%$it_`{SnMZ%-
d{7;^ZV*0#Q@nO^|5$&+JYtPX6T4B;pA54A^TC_B&}?E)4}HzU4ShG>$L^tK|Gie!Z=_`2(E0nc}*oVcM6-
i_kJwDE=bRBdPeSa<Q%@gV0hi*a*|Y!iu&e`I`H&!G2%IWvS&ivmedu2JBG7haNnk-
<efgVidM~6hUu6x9_K*LAFyV6uiV*LBKV<%I|^`*7|LQBqc<l|Y41Q(RvD2rG_^VCD4got-ygnM2UlGe9=*D^4W0gzh1P4KYf0bQ
I@Z{q_|_TnLpj-^B^4)AoeXOWlfGlPIohfX9*1pMq_Nly5Ht2ZH|d-
WO1W0dRoF(!b`=zGQ!B1xxO)lWIRps{%2p;7Bt6v>e;cw>(J44m`OC1}X!sPAuBi^JV;2Z!>T!?y)5nd_TAUDo+&&K;H^_F>(Ra2
f;wg!zUPa)VSn=bV!0v>GGCUm|mjg>WRnnIiQPMtx+{Y`i$<vhyhH&_Hn#k8KSaCBNTm_<aWV`W<^PhUP_90GCmIIuP#%trTgRFS
V1I!DuXe{S@g|88G-#9N>&VvdxB&idu?&(!!Z$cH)J&}cpxhS7qaRvvW_b=|UEJqxb;T#B{&{YT<HW9JXf6RS^FsfG2dQa8285l-
#ohCx%3*UeYtucNM&(balxrTc@A-)ofp^KR?jN9>8s-
fp@W>9THzT<x$v8<$F=aXapH8RBs!r+&Ch+&!&$}`(!nTfz|4RPP(j2n#oC|j2_#8Ei}t#Yb@`e|3+0NzOJcj($IvH$)j)9bU#jV
kyi29HC*%Fv8GUE~%>r_4gkCLi_1W18(WTp${7ZgF}?Jw8n-bZ{DBXB**amV3cC9s{rOywQ;Mbe%yp6Nx-
**?Fr51PIBc5oM2Noa?rLqhbtK@-
O6b@61lYsp$uCG))OO*j*<+0#abniBiPN1jg<U+4w915x_DvR|i#P<ai{0bp?*W^kR)<<(YZfIA;`oGn5o^V#l&t36{{~?fBK$`K
EU%%6r=m_A`A@-YBoP!vNEZn`v8|-|tx$`jv@HbK-
7~d6?mWAYZbtkPwXYL2yN%cgOurGx#z8?RTA_uV7JpF{I2`<6!Kmu{crsA&O?9&PN8(9@+UWZea3GbEP7u#DMd8#PK4~*b<6SCeu
@s!V#~hJeR%o1BPja7}-hk95p~9*7({szw7@rpDL=t^Jn({bH1-XT%hZ_1{q22-NMw9Ru<A;e#DE+M(f(-
u#q$IEA!4V=LuzaE{Z-
;WV=52Mi70PLlU7ESfzEJXp#MZx|Eo$GQvggc}|+RhgaB0>LOLTge*HZ60?p5sz7HGaYhi6#YWVy!PeIT{Fbs9D9mM}xev9K3v1`
+It;05$rxB(;7r1v6TFrC-1`A{YFcfVK@ptgS(F<FZdt$HH{%mzvlK<#ED$u^S!|8<ggk%_Hr+nHe`hx|k39?~oh-
7Qi!ANuG>RO)DgkDAvbTg0uZ&Xw(-m!^%`eH3&wr{Ei#PjGyc&z5Sqs<I-d~d8xJ>?v{$mO-xUJ3tC?}t3KL9+FL#Obi&6;VL8(5
;Isq=Y|Bl7g<L3AzktzK)PO;mT-
|6fZ5)={j~u2NvQ(Rt>NZlT%UV7_Jz<<Vs7W9cjnBBUv2eYridX5^V)^1FM)w5j=Edq9^c$_7=~a+q1x+47mCSnDVy*#%4N3hEjs
e4@OSN%Ftww!p$XLDV;rc6N*-s&rRuUT>HAf7aA$F41Ql-
r}&gU|h#HzH{)_AR2x_>=p4W+AH0`K8rt+21JI(Ng#1y)}>Xn6S8BBz}Sh@AGn@I+7_bns)}d1QGL1|-
jb~6)5;RH<+Y<R1ij||TS$_zMqIs036m2pTu#9aR@^qnTlWy6pb^{n;f|A*5=8T?Wz@<|QuUyIkZyJGRUp4ZQEL<t;E7qGXnK0gT
N1jTu@@r~cG`Go*bKPVMm=aV(#HlMt;~^-!X4K<Amno4nLfwRf=|H?r*;d=9lc^TnM@p-
muvS)eZ!;j=Bnieg`b|Mrl0kx$XFW@Oo`jd@0u_Bs=(085r(m^PFe1_f_IlZ{!-
k2H8Q>5qQzruQt$2&X&a&{9%43+fPL4=GDJwxq*#44QLf^#XHh9i0MUR^RQ!jgDS$)f%Eszm;4*=P%(B5w8UkgS20`N1>&Dq}gi_
kOh7>~s7m=$JN!xw9Nc!<1axT3X$=9*GH&08#W@X64G?hPvZo5)>fcX7T>ONyfl}rk>;ZD-
Y#dK^LvIy9$M15@hFP~;YgqYRZiV0kdM*=$B8NZEwz5uSi^JFba>qe7c!<jyUFuw*zx#(FxIaRgfrh9c2NFvI;{NiqB1ra!SyU?@
)0KN~(Wg~;bE99e1X<liM=@N@PpQ4t!IAfEEZV>`RAzhTFIjciRh#$?3bHtUzOJzKjH;$6zY_o&D=0;#{gtAee%xj7c^c6~(Cb<@
8y?a~!v-dJUjPK5b?HpY$L?6br2KXWqVA|5mN9p*!G)FfMKR=H^rxYo}eSiZ}Q+i8#C#M=%h%)IDs&fQxiOQY-_dH_z26mN@Nuni
uQp?}ZYVW~_6_U<+R#B2^YB>K+idy4C7>Xb!Bj1KG_a`=Z(6ZNIkQ>jCHY*#!IvocZ==L7%E`-^enbMs}8T-mk-
7Qgta&I@;vg)ur+^NI($I-?P%QmA2{(aTW#Bo}9IeFPJ{~&`I`tdJ-tnMxzw^8u9vod)HnCLcAd0SOFWl;hM({6e*K!5y(vZ*eN^
MXqBf-1vMF2E=gRdLoDq|v=?m?_^e@@$c&mKc|vKZ{80UaiMd@TU!I)_$bOl@|=S(dyqH+;tG|QSW<}#n_Ke#*moZ@;iQ_);-
d~)Rbam)$JG>AY<L?x+#ll`C5_{q3(HF(DxCSB3*j9%P!iu%#Ib#O9QS-
g=i>PP;bVED_kt$v`pUl6q;(`mTYG2WOQxAORONHzc*C=?&eZ6M>FeZ#RfArMStkb_#^#W(xZLDEr6IIM^s>>2V#cgYWC>g?2v^x
@<m7a7hVTZTeQS1XTgplqu^qSO#LFkDyZR#?mUSO@mS$mfwoXga`t(a>YEvCxQ(oCSgt#VYMPRc`fcWR6TdAbmWJn;dwju#iGU>l
7Wbu8J&bqy$2R4k6$8Qh6dZH09)=^s1~yTe3JSk-Djc~-
t6`XI6$XNQ<ii59ne}BOSIASc{1;Tw?fb!jaiN<!S~dgOSH`7~xk>lrZHDet#TxEl8VX6#wa^)0EMtW9`-
2}`6lRo4GAX)G0lKNNPEVuH6HpVe{jq=_$ia;(M-6;*Rs*DE{*Y*?LZ#sf3nI>42w-
;dZUxcd;PLH~dcD5^gRiH3G&96#Y4I{RgAaL9yWzK1|KZDu`7r@XFtG`4Mnn1TU`qCl$6viZd(~Q=;VgwIm$vk!Og~d-
Ed#}MEpy6k6UF)_Ccm2CY3Z6?%KO0_a;ijQG<Nnzq-@9Xf)skZFxniID8ED0QH*s`qY*#9(x0w31s6S`t`gj-;1x?M<c@=$#P-
83!sEcVaGENt1-&yDf6|Yo0PisjDk7Yu;HhJ<lkI}9Iyp>rOTsYj#=bLUF!Nf>*kE6JG6qJK*^H>p=7myLpWCi`TT1@*b~2H-
zCalCh@*^Ttj`_&0}IOe2n1H|U1TZBzGeIVu(B!HIeZ4FCoTy|iy>lqHMg6TZ)jPGWSM26U!Vv5C1c)xg!zR9?3iNz0Cj>Nv)ZOl
Sjxc2Be)uyHO*A7ZrKD7q_nf-
#Y*6da<oi$sxw&H_=*c(<bSQ^#@ua<H3&R;u1L0X177|bF4i_uhw~9zyifR8e>0TFnH9@+lJFqhfZx__Tb;C|g3|L+T)$ViJm7B@
BowFAI)uoD6e_omFLC_?OqY6)dR^*MI##e_?YP)XkH<Qa_Ff^dNZCRDZ+Ui&mzOamX!g9f-
Sky2L3MuafP^LLs^Q#t<UoSJ8IbMk{<oxSRE!7v7|Eh@;?1(Rj6TQhI>j9q@?~tm#J~Je&5^9UJZ%>&!HmqB!9IHy2`ixWyP4Gy-
_Mx$PR&^$4Puj6cG3vp4hlSlkOMKk?Ygd2V?YV@_n5-
u0X*>?9z~)GDRV;A!qrmKEZC;Uz#~XeXFU+3lY6e)+^!!`FiT8~%(f_H{iFl)M0BfgRSARxX6M_dFE5>~50=53X)V7Gsu0L-
oY?IiO99Y)!;GqBl;3aS=gZacUzfv&+0<yw*UvnKdOnp6;-gk>yFCz@7Knabbs^@-lJ1;i8^gz{XM2~&QE4IdXsE*g%b;79Y-
aXMRi^pApk17-
Htv?{=sX<~JtfTeo}%hyZSPGHrQECF#S~nfj=($a0;P9DN!OF;j8inAKh+#iEn3sbGUb2o*t%@>4@6@xKP4qhjiO+<c9H7CwfD)t
y4VHT@dmBiAN|n+mkH~>ifrOF-
O64J>j?B_<zTx4XyE4Q?Bt+knm<m5S^0Ojg)!ZpIfYY82x=!G5$$aehqkhkXvJe{nF(*|US`Do;mYz`MSga!1@UU3zo_yJ?sA(Bn
*k|``zIgJ7?a?nk3YAuJcS*<z8oz;6At#ut2cx}h+4YhTS>BHjbR(nM{EEEe$^Agpb;Of8zw0u<)|r3@X)$&SAy`;iAx_FfSYxp0
`+aW31N(nd`$fEcu9Ghag5(-K=q*;eO?*8R*IT4M?zpuD-
);*>HB45)`};%+U>L#=Vq0Bd!njVeaXX8IRDwfew4;%V~+UA9JgD<`g>2cbt@_rvkA-NrAVjvuOFSA0*xon;GTsJ710L-
QG2UX8k+r(pbZfS47Vmo(1>%qiw!3AnI5ixeunl!S-uRyLUpiDi&vaKx0w@&uo?D_@w;m-
{w7Fct?c}*vCa@iCbEzdUZLIn286CYQq~#JtfJ76Vdp7>*^-9Ipi_SPSykAygGVrVlKp$yiZ2A-
kFQCoLl0_C&Fg{S9O!;y!IY{8?M3dd`6+~Ay8ZDQS6P0oGVuh*y=5Uz1bM~f_y=UIYNPXr7QYA3L9+Pq6j-yRLmpFqo$-
a2F|pD9`ur&Y)}d`A`2S?&tfDp|y%B=Z!@uM|3ukTmZ1SlQQthu&<7ddd;G=^n0SR;~#_b8x(!&*vf;|g~fOS?Bd?UN#7C-
Rs68Sap<HCLc7H0v;L_Xc-OjR-ig$VSN#OkMECdQ<qITOISzR)_QbLnGgC2Vh}qdrL&@<YWOsROk~?$|m})|Mg(q!eNTl$lc%zDw
8;>fCeW1H<wmwG)I@i0i$%#Ljr!>QmeowBUU6QTv(z=(vhKN|PseDg#d4JkVr{D*1U)R#KO+E_9$yNHE0%?;fx^lTnbVXwKAA+Vx
5t3>AAa7!G#Fq!pF2BPUv#Z!GSGQXBQiNd~sZ#Sb(MkaJV)wJ5VVcC_Z~3mXw1TEMMJJQay>N&82=ps^@Qrx;Z3(CD`>)_TDFz?+
Zjn#AazuRo>6Ay-4@&?yA|XXbHd*+iZt?KP?D)gy)xTZwHf#jpH0zAfdu{jbQ%^h1o+N~06#h4{whV{bWQ`OPA$j%J?m^-
XOZ>iDfxoxq4v$yHS5(q)s)rt!UfqiS`+De>|uSN;&<^l!AhG#yQ`1k2zNs)dz}d+y}r#}mX74@`ngZ{3Sj`FVgKnznFOXa&vmmO
u<TF8DpK2eOdC#(jsJ)3lqM(hR|5fNfT=Bdxfq2kGdUI7^^Fe|*jbVzp3!XPXoqM`%9&pbUQqo(7Z!sZ>VA_pb51{x>>_-
(|p0ij8zv!bVTe2RU#UH;!;MAUp@6|D<1T8gRR3aMGamqLk}1I9LWXz3n?OF9=6g-
PM_4iL_h$kz}}kA3)$u(sAw6XzM)n=}42xEpL(?wyj#DCb+KSBB@VkB}M7wTqM<UVVf8|RH2pb^L=5qqv47@BJnRMH1HKXit7lTJ
_6u^0$~!igSBk*web)Dy~wPiU3VNV97Xz(`mH_`uqrP;u#@knxq}#9?N2tNcZj#EWz;QPOj2}W3L}Tg2vlXmgx*$9eE|{YT;(MLB
Al*5(z>jJ+y5%lMq7-jh`66)8tn_KSz2Joky-AXi6M|eTWnt{8&h_@Q$5mbD?huhzcR__OF@gmB8~(q)O<&=Exk7oq?Bq${e_&E5
uyfmsxdKWO}bKeM`l5%q=F5P3px(E;wCU;q3HLv0t355=}vev0N7nLji{13e!qlvzQp>e&KE?;pv@6lf|0Dy{#T*ikv4os7sy_9;
wE4tY8t2Cez}t$<`_un161$BIftC<gh;ugW+=L=Hh+Z_4XaPo)c*Y(EmHM7o|For)}pdeW6t8Q8xKf36`kvbBop*7h@HT%=gF_*j
uBDGT&z5jC_r?NOP-`FWV>NKeDT3CB8;&<LP@2tqcjWDzRt<s&F_nXK8ax$s~MW-$$}q*O;VAlf_1rl^EHgDIY?ev-
#ln8=hVf$sR5DkY#Qau0H{lQ_;|h*{KsBeF>U;Mxk!PkWvTk>1b)^|GOUToK=&2!1$TR&fwSXUND?d#6gqMr`5J01i*Bw2EVR^?;
XU<-G<l=SdPu;mXitv4EiaGzh2A?Zr-lXBSkCcRB{_Kbl^p_ehMbC0?8x$=Adp`Z!n3iJZw%P-
w#TrI!fQ8eh+5Ju>&e&a6$Onx?>o&dcS?@+kUfj-
F|S>SlJ;P1b9Re{5O=;3|9MO^N@O>r(k#rpEM4zm*FdNI2(`NS!_4<!Tq+Jg0VQ5e#6+e2Q8-qs#m%MLIEj-
W@NhcK@GL3V#zhiwAZc()Y#6@_V)Wc;qa6;!Yt#q-
cX6f!215@I5E)$OW)r5n9#?xoObPq78^JsOfAwU3i6W^C1GH}Xs0ohoxl8ImW#vGeF1<~5^oH5J_iKS?5hP786<;K5?x6#Kx7iG3
rwb97lADa;Fb^X)waW$K1PIJ#Sn_NvCktxmiNB*^fPjO&C5fma;ACh|+_c}w8czlOOjeqAqhl+iign-iEjGM_N5Y)pkqrNQk0cqf
2&<8xO`Ky%(f%&Ej4c@(N;Hs&K4{<C5s;MMRm~K(4!aF?K<;-
FMjyPvthbTd&<V{qLQ?&*bXOY}G_1)hibcz2=h#^Z9z;Odj)ey=f`LFvW(Wug1})FR)MV<{3t8wobJ6J4M^sHJHFb<t$JKkQLvK;
RZPas$zNWN(waW?yH|UIwX<l;hcZ@*~5v$7+5L|`O<AQzISzvYHXJPZ=QD8L7fP2cUR0>0pO=DsNnQ?NOrq-
V%mm3i)B4aDS5>rW5fF-b%wk2=pA<Wk{s(_|T9nElB7ej2I6ySx7soe+4nOL&y-
R%*M2BJUCYR$(<nl14e#fp2Mw0gpagBP?2Tyz|01O6@U`zcQ4@-6E>Z4K)7<n^*JkBNz~SZfl-
g@yXJ8vmz4;xGh8MlsG}5b&*=<!EgI6O9q?36*ky%Bqy820lX(KI%Q4L6#Q}{b9DOP8(OeEE1Z2)*1y&oaQe!4$WdM$Nu{%Aatqp
^NZ93YW4MRMvg1}9c``~9)un24q|J-{^q+s@^ugwC^SI0fa1y@hYlB62I34*A`cfBb9d_={m-
TEXuNz&7SX+Iyq#Z;gw^}mBLduCrArAzU@qeTo+4N~z7WHD=w;2aMV%{ADbT@Y%Hn@UJg65eWmhmOAc?MMq`h+mBT15{@~#ob*y`
QWX~k^J<PBR;&)Pjgm7dy0*Zf<Q4I}8Ib>(eJ7@ZeOax!IO+^BpD5$MhbLG~%d?kJLJl-xo_w3PD{6`_{W^oc^`jINDCu6X;oNDD
GX0F$>@`oKJ_@)~81HhFAhgQfJz*LRmm<2%E`HP#oeh?caR{R%pEJS9~iwHpK_swobLhRrk;E=T|-
9JYT!z?mn?D>+^c$2)&NxB1Hj`uFNN49MJJlL0vX7+_J%D7CfRoC6+;k$?TX4_B2fKBMe^*j(anRaoT|(H-
>32|f?|!g!w$lre4iM#3>-
<O&PQQMTUwo*)FGu?eejgg*@7aTWbmHtElY^dprDFKrNY*^oF^f~~Dt_6N<0m39zfXht;%rNsyyvZsRM&1JA$qRBO(6D=Md&cM_L
f5Vb>OW}Jcx<m+?nwO<_T27)MyU#|%yozweJ)4HL+Miaf<ULsUb4-nEO+7D{s9=?-
eKd88n2O*D^Jjj*H|}YNwQDaJVaKV`sKU?9yYQ@&6voX&daXFT`5P8z*b|b58(yu}^m6wH012S1Y1gt&b1sxiF{~LaZmXVG#9uQU
%6FTU57t`1k>VvVk_jLIf90z@Jw7Du@Vh#6UM^hMZ3GkBJYSFlW$|hHYRJGTyR%S^DIH3ww;yj&(oJzuO)PH;tA<S&;SerNAzG;|
r?N2PA!>JP!uZYC_MlvFKL$bANSB80k2Vn=<)w^N+zh5ZW*)MmXv{u&0G5KW0kWGpJVU_MrqJ4au?OrxpF4;tbQEUqx*@NwmH|!(
J!W{}Nv@!6@F14DKtdKQJEUI<np9@4wc29=a(tDwm#AwtAPJUlU<ZTXs(LU<W+K(!8o=<}h^S5Nco0xA?NT?uS@GvQ#ctM4O*YG&
m`36UAEXPG4qT0mdOJ#6W>Wi1`_i|dO{JzUdPD2$8w@1LGp4AYs@Epbf+>FJ>?B6OuqoSk1w#O`@HIG~*iY#|v-
BZ@sKG`@OnpzN9rB5}>a;RGe)Dq_u9qG^3T#qNsyDRPPIK*IQ`so7?^oDcjRt_+1K@qOV62K8EOn7Jk+eo9<~05_z?tD*jD7~z+_
0NU#*#qh+BOZQRGs`5!&s2w>hGS^;58WF`SXhCu<zj_#Ln&%;0^UMQQvc;qEgEpP}9;?!2Xj;^&aHxiH?ui3*>xveE#8*lp?rQb5
c&GR5ZeBqR>=qHqDM2@jAU(MSPHWRtQsi{3M+Tm4vrGzNuN$D>=l?+-
OAPz;DG8Q*jvFdfishUzlASB&E4X;2^^N8J;>KMGpK&Xs;cSP)$q*`E5+n2>Bd%uMJDp@^$1TtSF&`)DPHRXd`(uKY{2G)aS|<tH
hGz>ynI%nVx2k%P&~mm|s0^&L9^%sWuV>f8*?56gl$IW5XvUy-t^-
sz`}1S_i3nyvtKrp<oXf?1Arq<ji#bCWeJ7$#BdrN~+xOXq_qiAPDYJL+_8zfeRLgTk%VD>*y*NrXey+S|){SEm)=YV_hDruy-
M9GM$m_S}=}<pVVv#B#m~i1-
<A^@<kXU@S1HH_Zkf^l2%Lm97U)XMzADCFb*$sb!o_w>QgK$W}*4zSn4Mn2cD8U<@!U)8D7+F1DEMpE?@}MP17P>`F9r!powzqaP
(moF^q{VpWU~3+S#w&zs7WB;PtKYxq8G~UnBk-
!;4yn#Rgi%B1Kv>qA@EuH+JzN(fWgw3qsic(?LxQUsf=_mSp>ZzQ`8=#}m{c(6xY2s@e`)(fj6q($DV!l`!cDTt34u2r8v&p8GbP
A%vm4anVMzHpw&7Y-{rXps^t#kWc*dT01VEcoes%2m%ZSr@t4NlTc%>)t-Vmzwq!tRlRW!%|d=XGZQPKu5B<Ee(h-
Xm?3X)fQJA)K&lEpc^VnUBKJe@-%x(-
xnzdpKlOFqlk*ZGXE*23hKw2wQ>_*~6x@dcz!~kGlMfjLlx}j?JwEbsJ`r1ZvfWB64HKE(Vg$M)p3doaEEreHoE{xQJh8?gfAKE>
o8pSpGLz|BZ5&z3(t<qFE|0<X+#u=QYH?@JImqD&q?N0y<L1(&P%w5AtZGP6iVQjWz-
8|N!e*Smp@4>YO+d79yd{pvn3OpKE<Fl^wEq0YF<hR5!L_*y>mWm4-
p(h$W(G9lDDR)TSy{t=^5LetOrV>VWH!YF(H0I7u!&?8Z(I<1z}Y#;uyL|u{h>X!Y|nC$Vel4EET*l%as=>{P48J_&Oteg&rmE~R
7Y=l_ZnwtXl&)&_I0$eB0<zlt|*Oxr+BFoIkNmL_ddz02E#^Tk+hSiHayoxVGR1c)WKnj?JK$XF&WW5nBF||uGTU};*|!c-pFT-P
jbzljdSN|3xp!&xIS*syKOTHOV*m6wo=eo%Q6uk+73Y?u>riAwZIUy)!09(5;DiP_zH;oKULLv({;M@fQW_p91#lv=;|)CbBPC=h
12<klOE;I*%3jxx1BNDtL-Sl)mUU#Vn}*%5{k+r_i8JsV?B|t*~@ahBq|lNQ!a>yM`Y)kU&(7S{<o;mq+<|1h#PntUh6adRQ3kHT
&3IY5Ly^9r4h1l9ugFwi-&fU#v`3ep>ZCcH{$QZda^e_t8{x2W|I9X^7C7=!qR{M_l<A&H8RVtRE7UIo=yWT?L-
C7p?Dv~U}|bCuz2$8eP{#sN8^}NIoS~Jv}5O65sX1is8kC-6k9?a01FJsQ-
eBx73OU{uEA;wxTmdoHyzGuBRT}mlm|aGm_hs2Q%j)~R4CPwlqt7ah?EQ-CQc>uqMfk~E_|h|9Z|#1w%WT&ZY>G;6yBhjLU&k!le
mat<2%&f&uDH)w(L}@4(NvsSw*pt%4fG6<JGr=I7*0@l5n_|B*8yvFoB9l%r>iByDVQY01ZjkZpu1&px<wV7jwCC1X-
mc(d3x)%HY$IwAqshO#oOq9Y?`(jn6%|=~~Z2(gmUOGc_Ftl?fY}i<+f9cav=YlO(q<6Kop_TuT2j18(wg`ACguI%skYD5`YKiWH
dTs@*_c>slQVm|`K#X-<h~YHf2$5OQu&$B_2%jU+|`w;d-
$W+~MiP~+xW5WcY3yiEKZ1%#!paG?l1?`^7Mf>$@O?KXV`vsQ18_aiC#s|<xu@S~L5)sgPvvb5!e-
L8GV?>~GtKSFRg9~OhQuS6k0eUPtMmHgeXfdzy+0bzTn2<x+@0e`f}U#lzvp5$!r`}+8V>_Ebpp20T_K)9SLWc(VV@{N+$d7hHKZ
B?5EM^={$aL~4lAk8=gL+ict3M>=J)!t(o{BneAL-)8jI~u%jN&j9;O9`Z42mC3w)}Oi0go6i|VQ&0S_yh%Q7%-
|+bOk{&|F0hPdy?8zrb4aTAYae6LV5ISZ6x+!HuS2vNF!6QB(R^U!QYai!-
QQ%?gOVC?2%Jr1DQQb?n)#^4&tejd#cj9S=so6fZUAFmtJnVE?Qu;Ou$y}1b~b8Xw6)qthOtPgUtAtC+{wrVL?_=N=WRMU?7c9q0
^}?UGcay;_LiFmQ%J_VfXC4Pq`)t;yX>40|!z;A@vF;I+b@fTpHC%W8OzBTS^YBy_ly)5oH42;lk!8bSnIa5W6x6r8DF0`A+5I$k
EV*qZ>~bt`!`yHQ1fPr3)Y1D((t%K-
@BS1Wh_jfa5dsm)~^r=?eEHm)xRKO+HivG~o$kv)s7xYeED)sQDTIBA6(=$W3h*ylOV*gzBzF>>O@JciaxuzKGR2<GOX+*4_?8(K
2$uhf)-%Ia>Pe>M6uE)p0^J-
NJ`w8LPbo10{m+XVT=JPe2E$t8f0E1pp#8fI(q)cdGy~ip1g4CJd*uR?XngLckN3zAE4}Zh(eRDpfw-
6OSKdeT1Wx{Kcx};zX`U?kFBl_xdV;AuY}pqnuu@Yzp2G)lI~p*R5uX6@2jvs^Fk$-?GRGeFlLB-S(}?aacIw3l~mW%@r-
70KQZ4@&m}|2mmMAy{4Q>H(h-Kzc$tQ#B-g0eV{~Nq{(X9xoATkap_ZfHiMq=0bnwu%~#*iyQ-
($6}T7B2Eh4j&qLXksGZW6g1qn}-;)&uul^<7?o;3oVOSe&Pi(YipJ-fP=YYXN!Mjr8VA~0r0B9jmY7zuy!edM2S&dKud--9SOsO
5W6429J+1M-
C!Yv;G$)K`LFB)m&#jAS;&poO}X=p{R0X*gDY_d?<`3k#&y?@M;R=eVWYIidE$PRiAPsbvhN3Dfb=eiM!p9*MUa^q_}vm<E*i%iI
F5Y|V(C}BS4NHG28I1k+i@L7m{8^kI`a%vr;Spe`6Wzgf7==|oIfGn+Dv^e1BH9*K^)8o4jn&?ctdB7pvdae9{wv7=IE60K!9^c3
hz3i~Z5p>G}f0rD)d7IH9M#+SxY3~}F|F?ltMT3_+=k!rm<cDQ-cww|E$GyRVQjrd2XWG;h;YLrw%CzW;ByTZKo?CsqUJx>F`P^h
Lg1j3gA6Dh$CXw8tHQ0aqEm?gf0nhcqTdsS5K_S%L%N)ttVi|+<yuBcy4@b%YBHI@}vT&VG#v)Y+H|lNR$$xZW9K#=%Vn2m)cJ>n
Gv~m@FbY9JqN~8AsRB5M21)VSu6nvu^*749vt{cs9u^UVWw!xPyyTa>7<_}jCOKtol887hRpy=88>^VcvJZ%l!z{>DD)7Ze*MRBC
Ekd&!1^kQw9!higYWo=WUwrOMz#HreapcEPQ+EJBl0(NpCR~IgQ5+_-+TP3J`RsgQF?f-
Nk|3VxlOzBD?Pfg#DR(;=FC3e#|EV2*B-V6QP+}a-DoBybWfXSU%#_5@W4Q{2zDyxPcgB_2(q0_LLlb&EAwSnE{V97>vrgef;-
iJXHLW}Pxs~RqwjX>O%FN}R+b9SB^Ryq)qiA$N7K$r}QRoM2eMsZOR6@`p+t_tuybv}+!<0x^K_!1<WQ~_-`!{-
iBK<|`~?MY#(olEDGsCDbhJoTKwy`b8|>%XURtvKPX{_C*}oyw!fJ8vp7VkQmDF#j^g;jY(D*+2b9(b#-
xzOSWthi8?KX4r8p{5jV1h-
|;LyS0J76&S5g&k$$DRg|_>=H;s_H;CZQQ|83p%+5aKY<UTmLcFg~==0)AzjEi#M|C|vce#sZc_3J(KXoh*o}Vw81yD}r{+d|+yh
2o+JpyIbud_eu?5A~7Rxko`8&~4Y_C|r`5qPrDpG<j_G&vJD4}T;_G>(WU?=3_`OjLOaN*F9++C(nGrj^L$0f$J38JfL@A2SU$R=
YB!ADX}ro%ZGMK=J=T0dQcqp*e4!gpU~V;3bb02qb(v%S4J@Iek;7)Z0rXE42rHrIaV>k+Wz!?8+lTC_n3Uf>P8R6yODZnTEoatc
19HmW8p@#(8w8jb`2j{5aq2g)p_GjsR1#*axh9OxgD@!zXm$2BcXEzru$+PH=}=Uyih?be%a%i_|5-A|DotF*Uf+6*s!r%0R-
d{SQa#z<D6Y0bKYM)Pqb&d8hPw01a4-
Mvy81{tO$Eg&g(%HT?ETxZn#uI|x?Q?tsMvo{@j0GS^c8TBvNnyPGoJPuQ_8z&Vec?ya_L43#vCD!%7rJ|<N32gmO_D6_Uz%ueYE
3pXARXw#kvCMEY3|H+_KE#Mi?J&E86?5xY|Ho=p^w70gu;Zhp=Q`{QI;NH!&kIrm6?)Bik8sSj<hMkm}B)|5B5JZl`Pm%j~dvp0j
1{`KvbbI$=%%FQqeLlO;)kd-(3hjZS;qN|9C4UF%=NpXB&lpK1+4o~fYQ#whBua%gphOd%!RJTW{=-
mAYMyr=9mRl|OE9=D30Ef{5h{Acdc{KW(}oGw9Hh9_N<6G?LUq9@fmxGAaF1t{&5*NefFp$-
4Lp}zsBSGm8U9!(3+8`l@1?D=cPasF<W5oJSXXBF4)tk0f_6wD^|QTrE#cONhEm5-
epq8VHmmTZr_`CXK3%;Rd(5#7L5~RNE7^#!4ESu{-XfHY)t0_i8+#Pnze+&CR@jnvwM&2kOEWG57$mMo-
jb=5u)hfKW(pmSf*b&k@bVllOz-pb0ai8hRM;K)ERxgt9WIB;<}8GbXN|Y`;qhbc)-
X{#qKY1#dEcjl|LIVAmD)*;MU6AM?CDX+MW-=SphS|#A-
V#YkFiJNA$g6|{cVa%_!`96*g@Td&H}Q!g+1ZazQ=z8i<Vb0FmG<<kWK^HL4EHLeehw_np4nW3+n8}^lkP8%ik`xj4+h|Qg_fri&
oha;x<;Wbm<kVlfJ#*nzipdrZQL5Qm{{Zl*}p8=%X_*djS9DZ5_Y|J*?@r{CxA7f~=Wna|G<Mm5UuVC+rKx%|AO&^)7V&z92zypz
FS?Ep9K)M3kO@fCk5Gri%RRPU>odl%ol?u?*2C#+2Cr>F{AH)MR%rt~>OG1pr^*5rDby&^6zTDfG2H-
CH|1KEAQxsfUO{=!tI{kKoqWX(ctts3Zw%^7cC+`<&DodacYkv|5PMPz>=(UIK^sNvR9;b%xLedl0p6e$|xcb82z5BVr3w;*C*0-
Bk-|M~8xpeBB;Aj8<qfN!1U%G$mxF!)^5JYON&x6~kEYB?{Rf-
am8DSp_Mo-q&tba4xm~<+K>>`LgO?fbAzoY(DFSBV%O-IAtuqk%r@CCd4#N7d*!~MS1fcNb-ySH(~_$!&jNVfCFORMy_;_`_Se@o
|`VX<ui)spY5Y6bOY1)jP6DLa`U0Q@7;@WGEftVEU|*=6OG*_t4u0rE}AbK#jHGV$OVvf4-
Gkh%HOB0OdJxd2C#FcJ#s=2Z5yFp73DTF%r8yE6tRQ0Zg-VluY_>Z&Fl%(IKy!KY_yKUsazHWINvL*PF=xMKyBQL?H57s#c16-
NbjDC3sRgp10Wo<EToViE);bKAmSSFdr}}Q07BCQU)kVEwVF{w_S#C#(LX?4Jlc;(6gSxX`5XsApv&3mY74$O?r)7>F4#3*l%mI6
R#)p`GKePgQO;X2MSUN@nqD=pSHavy7dFdbfgH?XQngC~b2BnOsEd_n2_o39h6%jRraqQurDgf7*j~(}bED?7Ee4eVMTa%<rlD+O
HIZ{dgp(>#if)4$V(7W%PrgU^D*jJ2rB2gc=RQmTCibL$$)I?_O#HrAzjr`6+~z%*boVYA){8n5J#2m%8YHIXy`;A?hSC(Qi#Pf9
5-
5s_rZ|h(q0=iS)@qMNVv!>^)q%5eu&^>Brf1hFgw`?Bn>6&eO!DP?iWtRogQiZaIpWJ7`+>?IwyT@UlogG!jtl$f&kic~GS8E5B7
wi&BxX<*BWWN=>BLH4YEd`#YAC_)(Ru4MA|C|P`9TX<Cc7cWzgEJUxTI;z_wg&HL2w=1QTBY2sQHk4h5I`m9|brdpT4J6*;YeTBA
=P7_~(0`&6o1Lrp62uXR7>=H)3SADgMz9?zs{D>NP`Y;prJn8KngxEE#r;Nv4)8bYVXfEHIh~2i{8~0u%{;Q1+0zxID4SNCYvWVP
ATr%jr4NYt(zEH2>N|_U8n2bfXa)paye1UU}`KT4p$b{N~24eZ2g(RLC;~jH2%Wh`_C}Ni5}{G?B9nS9r~+kg-dkeqUAq4;G(fV-
SjB*)xI0mO<U(=S!zi4R>kFaNU>Hp`F9WDHj$@Oj(oTUh8u~9*`#RJ-Tgjrp~Jcg}juOLAO~X1z)8WU3qZ=u6H3UqtZUe)|J=I^8
vf_X)-D5^CBZ>vL2UbMDc(dLT0WOiqv9-2;z7N6_hfR%}fKsi5Z09;epL&@hJV5Pb$-
ggWB}pHgvi#hoq94s2v&Kudy_GElO)vV_03G69uemW$}F%ga282#d@?F#fh2ZCi(NtkE62xJxl&;zfeC~PkSMBvmuCciAqJREEd(
KGWY=|t)v~m0JFWk$%iP;cG|hwg1`1)NfRFAoA2P7fuh~PjEI=IjzF1^{is8B>RBp?-
w6pbiWYWD4+>I*#KK_Z(5(EvBWqAA5Em{6{#nrXK%`C>F|?1}8OP`Er$Le>(6a`#|4LmTj2{6siA0RTE+Y|3D0Ux~twtYymQV6}#
=!+Mi%gnu!pF*`Dl4CLP)_DWKhnhNoUL?IY&>M0adl+Sh!>8-
gcQR>W21fEKa&C?YvlbHweuh~fB5IcoSjfVsQmN+r3B4~V{#f6Rmq#bFSKacW2*>RYBxTdnZ$(}QY_2Z-qZ*)d|g;-
@7+#h6>8pqjtXoPwD>By>2|DF_O>*mn_*gKZFh{vuH#!)1yyqz&AbiG3J(7YMz=%|0at*#nB(-
~N_PY{L+em%eA%5OcLmgk5&#P7Fq*UMS<Qd@5BF|$8x08ewwH4J+iBc2#$&CmRwJO>!~BD?>vqw>ZYun?AuLo=>qxT{`AvZ%#%zA
GXj4I#*!!OF3E|!X6i*Y(>k7L)H&|8Z#{=EUR;3kr9t5D$hj(4Hqn&mr*{&kV0JNN#qvhhDPB+M6FggW=7+4gHQ@Q?N1lc<g+P0>
ORaj<j#z+rth!EyP_T`hFPw<Y#eWVpRv02#$8&qmfn3qR`RBa$GV~WJXPFTA`#gs=UL|9#FG8#B6m5=OE6C%yoU)%{N;)cHm6B=l
mK49a^+An|e_SVBaCl<#Vv3-kPNt!7HCiCvsNs2gX$Le9Nwt6JXP^V7+{7<Z&Gf&@E;IE{oEKg<eTn)I7Cn2Q|T-
oWeBJb^gq7Z<}A9}(*4a|Oyd`0B!=NOj@Rw=9xa3!T=0GyDH#`a$sAwcf86y+&k>SDOSs504l>X0I51dbmC_Wj;t<43uF_&*=v*Z
&s_=fPGF_ob?+C0I$6&+m!6<5l5~!_ijyrZ?fJ;0$Hz<7s9sEAEEw#YJYRDEQ&TbimtRe)Yf0L5pY_yq;UfYLs%~_vVaz)Xhk~98
a7;bnjPJJ*~l$)ZVD$o_?OHnF;;Uo*ZUzv(I$F!!028nQ2ec;QY#F>>*9@9j9#Ekm$lWJ+m#>^-
d?U8B07@y|9@f;;Wb?S0Q0QF~F1v3Tn(r4_hw6zF_kKR9SeXe>J}-tt_-yF#GY~UakRYfWiA90MoQhel<h6Nt+Ybd|DuMNi3ypa6
jS70+Z1n^aupGE`sc~K}g_?cZz0`E!eQF13@Q>9K0!P5cFrN$JKl#gcW46K7ny>Nh;E@fd=#3)#?NdNL9;@xX@?-
x=BGB*1zas&#;%|%7KQ%Ga=FYtJ2yQcj|n<xbX#)vh*lh7fY!-
TZwtRQAa+hSfhf3&Q&V7KZV@cKvr%Wx_Lo&yXo`~=w}s)A57ZgtPMXLxbi2;*Rci&Ue-
)?_Thm3&hKCBJ5^AJF1%v<#$(;c`q?IzPM<~SRuW@E$yN^)%w8KZL^3g#6(rDE=-
0J#bE`Ex4K>&BdctZ>wrr&QSUmjt5(yI&tw!TFKXdVIuk564kDi{+3+^WXvW(4h`n52i85DPEbx0x+u-
2eN?B9ZX`^}I$HGP+1ok?>;0^>48rrj{MztSqQRV8OGZ^>^C-
o{h%Vkr959#3*52mtjzpkms%okH%5xwbx{{$xK6<__b3KK}sV6hdl{kStsLUjGr;UuYsxDM6NrpRM5%Yv)oAZ|Ii?a$b)vtT46^{
C#&OH#^Xi^4$|6p3_>|x2SK2Ah;MZ*B)G`(*rL~<M{P|B~_igA=Kwi9bNCNsOQzaocP%?R$~^_@IzWk=XGD6vY(m1=vv&dD}Sl|f
}Fe0)xc*rl7Hro;#@H-
?FGn!GfIy&b2_u<)W;2>B!}##aOemmX#idEA1kbQb~bRgS)q~1FdIuqsrO|Blh3u$bjVQZbE@IqbvKOgd+F+$nIoJ_^U~=~%6&(+
l5_0<c2=EatIF3T_|-
0IbbtW_zBN5oY)p15<!P>+$6)Jsg|>7rVFIDPkvvuKnNe~@OpV)=qwI~r02wUc>e~=(a+HRst{@k^*Y`_(>Pc%BB_CW*$z?GRdZ;
^Ca9j)c6j0v5CF0;VN3wSW9$zS_UtV<<qHqf*q)-YoPv5<>^xPs8mV@rU1GD`Tc(zWghC<dLE1r3m!j>KX^)Qe7>mGZ(8}J`E-
16uYzKjFVs_sd0XJED#(j(q&s1mVV_nmB%$sRmEU)f5Pt8xn<oVMj(9hAr{{^4xH^x4-
1oehetK@v5Bt|=_zU#3I@7K5^sFtWobLjQKbgn-{T`gb$BJlRo=UAXHDS>sT{^8tG<z%GNn3anUfw-Flz^Z+;uWlBSjiH+<2wh4{
i628sHqjbC}bqnR7*Q#oL!Rd{>gT!Q~BeZB+^i7w@HxN(2%c)B=@V?&H=KL9YRUtI_9JGR0i@dm*>oJ&}QsL`}-
M$2*>IL~ktBoeWcD@Z}!BX?(os2w>Le9;5HO6UBNA#diPfWX{{U91<*te+zTq1FEV@MvB<C_29&Q{KX!5;F&d33pIu;^NRa!Oc&M
rL64$Df99f9=^cux#|e)y6iSHLymwzIdjjIc!XG19}^86Y;Ww^>NJLq^>>k2#)yWo?)85!WLA3UBP|OPfck=e3AV5h;Zt!*)w~dV
JsgY``{?%3|>=FRm!<jyOf4oWe<)!2hD&WSv-oR=UEmW2Ap7MefU$BaUOvvFLHQ_EV!jE;1)$<y_8JeP=q!;Np~2EPl;8e<-
OmB3=6}fY2v8iFxjT&X{Iy6vk}yn*^N8glm1kS4hFJ(U=<pL!v|E9#bJ7F;OX0ad!i`wShI+HbHE?S3zZ1+x@~y+BTG3H=%rFr#<
@r&P5YE>tP`tDHU;d?6^GRG1KdrnenAu#%Wj?mGxNr8;&PT85VB?sqPAwUEe|E1M57%@%{9ig=i~<J#ud}Rl0I7YvpB5LYtjr?-
7wjLSGnJfLtf>(uij8-
fD2w1J?!<EJ_eB|vpvE;_c}*bmB=~yMksZ&rO^VKX>pQg$hBnKvy^g6RhTA!Db{+_U;JMNd%1BBeU>>zWzIHqKO+qm=Jd=uw%G*H
tC0-
l>jIESFl72UTBxW`Ouq)gUwvx(LCpU5&KOxPEel7JEWw*$wJ)Aq(nwLM!v`)>)nCoLp98?;Z1#&Z6qr!cj|#9e*2^9Q7(HLM?3YS
P45GL<-2smrv+`{mbrHN^Vw%zkjf#m48>eRk=y~W#p%J0x7&nuUZ%&14n8EhyW|<$mTl9qWY|w0I3lrrUG#=3%-H||VDAR-
A6n*g9BxJ0^wuafrp3vVz+T^X<wLviAiI|?=@XOzaLA8;JR$l7OWE4rLz*dtE=_MT~Z3x&eS<)_G@>Gahmyy-
Y1N*0aPhsaphs_1-
RyFAw0Es_8Y+NlYr2d8Rw*yK6l=0<g=zsgS$5ahHwguqq=E^JX!keDNCqibsiM#ikteQjz&nTldRhQaMf5Ue1Y=@T)Ha{Z=faagC
%K*RCb6Wrr(n$jZf+|I_*Wnblb5Wb1K-`7ST!QReBIVq=PvMbe+26in5?<<rT$k4>6y2|XIr#v%(b1U6Dt&u+pw-kIfX*2<TbWY$
1aEMFJ9Qu}?EDe>xGo86wyi^O9zD9CNE4-
%aliE}>w`SX1G)9W2@7Qbmt8sPr}Z@G($nP?Z*q5x2IR;>UTY6C&Ygl<m81l3D#Vq#d+{WEa2FtUh}`FTvI8~fD?(@`BHMYV8PUG
^25!VKdm6SjH_jWyvG(tZZjW^+4<qqNPUIqy=xl-
<YuIBsAghOadP~i=R|@^XRFj|u)%%0STvgpKQY@Q~r(ePz!rCR^!g=l%tuvDngK>(hU8aSSZ}>WzbovJR-
R1<6ANouy@g%zk+7BPgaCzVxd#_=bpR0FpsWfXGl@iId?em}32&SvyLro6Xb56kZxU0}l@LTIO(-
E%Z*ZCozXb?6+sPs*JKFDi~581!N-nV=zr?|?PLNIchHBU-Tdx0dJX`skB$-
c}g?}J63=Gi+!mCBz_JKPq8L5}4h{atKZ;J6?I;H8*Ra~*0N6)xu0zhXgc>cpAbi|&7{j{wuUJ6NqlIM@8x?;mzCmk=UY8l{ia$E
|cvAR$#thaF0I*nLnvpT<$}d6Al5K;-HYA#w`okH5C+kQNYeBKmLHOb|xZj-yQwu^*daV7n8Q!#W(Y$2#EEN8hl1{mle5?QKN+S@
<xE86Gxl9Rp95shAUATO(6v>Z=qf#iLzRjk-
H%rDRA4V~dchIj>r3Z$zxP0K<;{8|9F}eiJM4JF{vnc4bEh1K#ToupU)TlzX!^!aTGUQS$!6$*>8cS}$uh<o}if4qr4%{1!puL4E
)HQY!8k>1(K5^W%L|XfXVJEOprKr#SjAA7r5$-Hw<TOi`{3$_x}`G{u3q(d9S_pu>+w^5$Ty#N=du)gtlV6oxZU-
@8(Uz3RFBh&|Obf)KaE+X4TcrX}pY_qj*7_`tQ$iO}5zdBj*$!`V5FFE4J(U*IGN+gD^BuKtNTZbu=|)Y3_|&!U79xF(+?xlE~!p
CKSC`dkobsX(0R@6`v!m&df$(!N}b4T7}TXcbWAwm3gNV;enITUAZ5&1Y+rA83cp^dQ3hmwPD7ku9QS>p(f)kXaaPlE%(?mAPU5m
t5zQO3M1e;1G0>m=Buj&PHVR`ZNqH)6!c^Oq9B!pimjrom<r3KmkuPi1=zGBIYMs$G%D*<6bUWPT~w5-
F$*SCLZ9ZEe4aJ08CTzxSANcU)2i``5LSM4dDe^;TD-`=7d|eXqLg=_=%(pBXKO-
C0X@sicNa4v6{`#>$<drur7UatyPXa_ro|QyQ`ZisHX|?8Qso_fs%vxNe}r-2zN=UJst-pPc(#>z%8oZ=#yF@O(CaI&`BTl_w&Mc
rOSW!Bo4%f$HNSl72N)%f^5#zv<2J_$q>Hwwk1A76Y|ioRw^1J0!!$bu2eoZR_e2-(-
Jm@{;?pr(M`<$b&K(mf&p8%wWmK+(z@MS^8zZ$U+|)lwU~|aTZlS6dq;@dBG2%XJ&`!1mtk(K5)TlQm<VC*3h!y#@~Wi<(*<UH2<
^5=GgVCm6E3{}Ulea-uImk-jw)u5cL$YziE?dus(7^f#ZAZgN^ShDIC`acRXx>h6LL2cnz+iCOX=r}9q|4{mZh|-%MZ*^1M-
i1uTbb~YlM4K9oSt^<*U1oG8CO5wwWJo^8@W6Ps<J+EJNp$bZ$<kkY*$AG^^GBbxJfdCq?93m|Ck_rErL3Qxcj4Tx<E-
zEcrZpvXMFCG|(-l$HVh-Uwk^F`U)0;7}-
ZVU?K&8_0XO(KYU+K+_A=m##i9tL80AO~h_C1EjeNriff*?i3N4cgQ(ax{DO_U0js<^1+eR1sHG4M<GX1b)c5{{1JgM+QPcWV~jh
1SYYf(?(jzC7&U%>_K9)!X+`xdk>P}D`JHz!De_Zp4w(sAIY!(v<q;eCgKh*g+#moK-PW%T2X|SzCQ^OHp<%WTDMubQ9>b5%VYc+
eH!y1VlBO+Lq*bU_Pb`aIenF0$VJ{Hkd`f;iFM;+4%Hu_*$t6OG%ZGQyL`Sgm?6_cnB*yXd;J|&u7cAq!y*ptV?onTeO3e_LoPdv
ecRhBgx6Tm~;a5wpJ}bhID<BP7?YUnSxWBioT`n_a)4W$ECAcSIG*gM7(AK^=P(=U`Z6I3fD06+1Oz~QjuEC<N^B@)fkJ3T7F=f^
?7)5F*75=%V1{IoR)7%c3!ZS7^iMIm603sExEhg0q*7z&)#~qG)w4Cl$K~p$R0DMw^maQ~k?U-
JrtuQe}1cyOFOq0Ex{HsXKXm)`eD{1^|I~OR0f<SUzdAR8t8|o-
$$fl<=otI+usBj}V8wWbtV(VAu8z2560BndJJvP>1KfEjDdt4$ZrzmNP&3^z3M)`pw=77l|xV{Np?#H4&ysRDCl!S}S9us=<j?_S
Y0;mxrHX+Ahxa&35e*sTi!1DSRk;;`U+}qcSgW1{I#}$o$2S(f~8eDe7Q^9;E!Q@6Ak$Gm<r1Ob44OSCdSq!)?LW&FN7zk&p<vOd
9PBN1m_=W(_WD$wftT62Z5<2UHnRr8V?5}Cll<o7rEdrHq$0z~{10a;{R?d;<affEn#GTq}d8pQ<EA(&<<IgZjfqQdoyV%AaeP9l
S#>&9{;`C86Uk4JLa)`QzOBox+PpbvUbWOdHR@k!@Z>w6BPd6=kz;}CilNLFZIMI_zBT9;8;YT7?*TxZf`kQ7EN-bzDWl3WN<>j2
yhq4y$*_30bCF<Cuj&=BUqE*j0>*j3y=x4Jgb=>4vX*g{98X3HR1(_VN;M3*3e(+$o62sU)O2vfS9W%oN@p^*={K59+ABO5K4I~y
plc_ZS<q3&7Vm?33wfw2mR|q1SO%eDamd|xveh2jUo$7IG)FH%Qp__ZW!!c?Q=QS?~K$;+$!uA+(#_CFl%wkRS|A7r|FP_3dYP)Y
fEojq0sRvl}dAg?DA|>hlfPAdPBvGnN`}guRIb=kEF$bKMI^w6=`xy?I9<dOvlu=g$kZU=}45uif3-
pWA(jh&qqN(vV!&ZPwV>VNoYr==6O-NZ~nlsA)BfH41>glTI{4~1c0LNi-lRw}kHE$Zr{P8%f_`KV&Titnualg(EbOPLcT4Osi#U
DnP(9q4#@mC3uZ@81S6mD6?jC<SjuP3CnCQ+x7-rH9<4uoc1%38-
w%~R%d20I$E2Q6UrDxjfbaBS;Sce!(Dx3dC1Ms>N5)7Ofqh&YK+qA%D`H7szTU9bQipN#9c665)Sf42*UWaL?m>)-
>4{F&d{RK|uokqTCF`zIE+=@8dycPpOO6FG6y{>rg!M26W>_#bbnnl6w&h^l6nf-
<gM*@ZK>&%_7#17nXLA>LBSfBW_Q=@B+O(@g3uNacQQ`7UH}bha6A8k=c|o;6hv#MvA$yBMpb+I-
s>t&NGi)q2Du6CNEp3Z=VhU945RxQw_b0n?9cLV?utc0%olJ+#>v^higdC__6d(#*o0LX?KDCb344uwI_qUr@2qvaHx(3ELdYnw*
;qVoUwq)JSqVC5up6#lTqEbt3`J!0fd<cQ(-c4J}ek#ZvVb7kmHj&q1UgdJZDKP)lwiWR&-
ET#D7uc{k3&DaH``jt|V^wQRFAZIgcn*!d)2mA3hT@A$5%t{_7WjDeiKNhx{3IFEcd|H=!-$Q6}sMFpisgQ>fcawbL3Y-
9ox<`2I7@W{J+A~OClg;>Lj?@1jyn)85O3wFvO#MilWF@p}@C}D9Ql&+;CmHR*~GiC!lYaq8j{MKaIhLZi*$O^4e1OK+7`3Z&FGs
tdN(!=fv7I7M8`(~b5_4<miAga)E{*!T6x1_SXt>UxxxMa^zJS8x0pA3-
pV9#9vFPHnc9Bxi{6m4Px=$HGz88XE7S(j!>CcV%XDZXx7K9>CA#T3y^_DM-
Y&k72J02HheVaZ)J3aSEd!XIbSx+c3zGv*8qSVYG86g*JKbeRni;#Wlz$4(YXzUp(~K`s;LI&`c;GuPo<$64n!*qa?cQhPBCEki1
yW2y6NnOFxlJ5`}%7)o)f_;1h`h^_0RXA@w6cX4;WhjCCCFUL91is}co3@$Vgja>;$EJ7Wdvwjv6FC`AC^hZGwWWa~dmqTYHlin+
(iY}v<AiXTk9~G+iGxIEqx~A8XUA|=&IERqu)Ge`1za#l-cL57?V_`HMcse%6FIds9#V}s8x*>RiB>LibHAx|*m0aw-
8gh~Khh>X^-L!%^YfySCap>=MYoDFxFas`g{rirP$z)4U1)$74yuYCA8)(B*g8(xfaG*O<o&=9sK-DsStTx1*!W0-
xw*fQ#1V_sQR&Nuql!-Lj@!JpIeCM&by!pAor#r7pns%5NDdqi?pR1>cM~VU#@P><}f#e5?bDe|$eKj&-
*ZC&(CeDiqLSB;D|3V;Nr#J#MHK;uh{%TgJSFI9`${+576(mAT&ByeI*+NC_Ur*b?x3)M^t3hhT*x-
40%Ny&>Um|Irq0)w(l^+6KwNHq#M`v&+yE!=YN~tvjhGxjW4Ip)W<)<smky-
2nqx&zfB8IBz`Oszs`fK*5R>XUQ>=}_p{h5L(Av1S~&;r=2Vw*mcV^bkg9Z`URdQ0Syx(@UX7KK~MNfJ^KS$eIEH%{H}t`Q}#Y@B
R{WHKh&4J)C(hR)n~NG)1qcZ=c{(cG~s*Psn*kavQLdd?-)4m*u?xow#1G_9D#0JEq*4z=koMImIU-
hJ?fcwXbMv(E3o7ZZS8rB{rL_SixoTmQmD){_UjeDm!c#UTv~L1vt6b)Lz-YulZ%PIyma;*q1EI>nQY^PJZbw?6BzL&heZ#FrP8c
$Y5moYRw_o~`xzQqQoFWK6>rJr!iKF2drdGMWOg^Ya3exDy;|^#1lOisdnjp$EMbh_zF;K{%-
!nJFe0B^F&%ZA7oF8E(~+kDi}+ELuhGOl7cF)gYbVLdOy2kAAJAiQf=-
(#{^^QAwe661YyKAu=9$FLnRKIKwzO^*u?=O6G)uhk84~LeycSqzgOK(y0)rEDEWnXC37EQ-yBP;oH;Q8w$uoj474=@*knpzxOGf
q|fOl|8C}PAx#jxWz5s4&6C*`GTU{s0;zTptCO5dc@QzKXiYf*+K3{;fVN}-C)>nQJo~!kRDHqWmZ^9A6^N`Ri@Jg$9q|_@-
i3cfwLHedR5EZ$MI{aGA6A97u<0G$m1=-
jk+A$)NY?u&_bpk4gdIy`Cpv%qv|E70Y@|hQKO72>2Zp>!fN#N^x=m}N#YoVtaCj3Wm78hKsw97}!#b?(F+}B%V{|~uHr5>irG~m
}U|DWAUQA9w*&FUQiOC>FgmA@>pMGv&0&8doCpT;3kdf*Dh2GRdAGx&-&-
k>$w}?Dxp3tiElzv4Y&`>Bsp~KZ4w(Qvz2|t+5wmGt%bGQv(T`pl^&QvN)H+%YmwtCEPOml2=omM6b@6LJ-
O{HZJE_xS_*{h1%X7grRQH7||JW-
p*jz*mF0I=@d`By0Fz}NN+y)h~&Esv2WgYdlHibg)eYVsjHGNMoM0crtm^?M)vDfFqjn58li5j#hmGTj!hM=*iJ_3Ki3r!$t)8CO
MkYMu~pu_wLZumgZ!Eqnr%z|dC&Ogq91Own6PaGnyXEZmV?j9zFdq~;2p14#fRg4g%ek^B}{<XIh-
r>B0Re74m}7dhM*VOuHqY1r|u$+3!2`9Pco1@WuhF_fk>0EOvF=m^gPMaJch2zW&NSWSSLgmnQ>EEP48_s)#PRPNL#KE}s%z(&(Z
Yc#ETbj9s7))N0yV2?cC-fQfH0mmlH?w*LT`!4OtA8bsvCN7Oyd#W`rR}X-b(KS|V%+Uok)<RXbj;YZnnlCU8LA|GZ*qv{&tIn-
|Vq>A3Ak86l+@5P6etjjZ`jTn^03rB$iGy*Dw3Bi!#k41@!P)v4D3tL>rh5fM=l*}=yyJEjj4C_m68-ODgd^a+3`7y@>W8-
dERr!oae(Q1Ot^F|9-~kNW571)qtG6IjPTFaMh71JJ2Db{3P<6~A;+FP>!^Mjqs{gEVO`Kxnwn8JTX8M-
f5~U0odVe1v!r5ZI{Vb2pOgRSmpEfK2}wlyXZ!yED-SS#UmH#Fg>K9xgJ9t>CL>z2h5A-
|zm5vafWa0_izt@_y+>G``}TE`*`ZZV6j;1R@Q2E~Y1CK?Xjzwib~YW-^IQjq@ooyRDpUN0Dd3ttzuyLX!6^x?HtL-KT^>DZSw(Z
tJ<z5Oj=ez0hjrW_tSOZuIr}GwE}pEffjvt%OH=vy=F=XE3@&v<;NQa7Re?tkCDij|k)k@JV@5`fdt4R?yh}s08t4P*z*yy@s`vY
q?#`}M54xz&3s2YJa$d=no=A{C+GBL3eG9)5)Qu`>8<U9&CnZ5NOpT3R84xFJ8!M4hT)-
0X93SrvR!zXv_1kZ78ct9f^rCV5?JhfP6`vkm{MI+LewM#5?S-
Tz>^Xq|G_M6PgbfT!|1*~rt){qjZmtqCU;$HgK<fTz3)N|Kr`zMpBkA95R9wC-Uo{}{hwhLgm^cz2efk*ralQtIXFjVk1SqYfMmQ
)~L!L`1|3uzL26quqjm2@}24}}fj&5P~n~`#<$R~%lz%@tq-
w(Bx2n`aZ8|iPg&aC)K?o&6U4J<2_4wy2Vh6(EhFt4qx2aB*faJIXWhFxUO&ay2OyI&LG{p%F3^yj45V4cSUqsCD9>-
A*niY(#5hd%wrmf}XfC3ZRz(C|z)6rYl*d%Whm`$mwGcp$j<(w8x3Sz-~lLDHdB8Uw4&h2pa-
3E_r%!fPh_w>g^pI)$X+d~rb51oY8ABX2aU#WMZd&-
RDl$|zD<X2WVvvCUd(MHBM!8|R&QV0Hru=`RlT9Dp|;{@$QBSCnp9Fp!zXe-tO6{yPh$lAUkqzJ6aFZFLrCW<>?zaRTrmU=Wv9%~
k_WOu|bb`T^83<XyivrG>L#V{Ym^&z#kMmh(DdBzCCFV6(4WIfpc?vjSP6gp*vNZR>0V)pC**<oo171joi#vG1w(5Ve9|6Q`>=Dq
RYCO(kmR9UU~xVrsyIQ}KXkeBf29#~%~Aqsfhd$0{Z`C$nfwWOZOy#+pJx<JR+@O)BB%yg=3r&3%$?xbE<{3A=|EJcW!|9$8(o$s
=%N42ZwKhU2@iLOn7;c*b+@urV2JV^_v-6@P2hqoZTp5n>g9fdVdHH%9$Edxn&Bp@e4-
t+`5&jxm)}(`6K<o}yD<2nBvkTP56g1hZA9*)+g=Kph027N{jiW>tp6?`}7k)!g*1kq(kUaErCFH^ep$Q{$$oHCh#XOGFO;Epl;$
j%ehA<sohbodZ!O(Fq5)zkTq}>4(zUjE5|MhMNoy#!sg+e0FRxJnNxoe2&!uh72j+0v^Qr(Rl9VfnMT%injE>76Pwfk6;nTLHlQ|
0G4Qf9%Geh!4FAFE_?;j(dJ}am4pGgEw};2lyr+zOIGH|^Dee<LSL)N)4|MwtJhEwfUlxaHY1?q1+>Yj{&an(O&Y$~V!@(kbDH-
j9c|YxtO*Q+*Gh4v0fB=5KqbOoKVP;w{h}&#69zhq;5~Do-rM-~?U7$~#~gYA1AVxOva|<XWNtfh>y{<4H(81eyh)g>2HbK*-
WBG7X;vb}8@gI*W3fuzO_DBm#R~Q}q3y$#QDfZ*+LGl;!{_`Rw;|T3xkg#cMJ-
%<dFLKXiOlhcl=FY7Eq3pTZQA%f#8ETBc2q!f*ojK;=&guaSSH;NRDP66a;@rB#;@U}u}s>qPWOBxq7>DVj#H9CI{=#<WRrq~#ix
%tlko@>jWtc9Hgq)ARIWi(y^ky@3zVaDz&N_5Ha&7}qr;Yc8Q#Vvs!uqK(PAZ_7VpmX0A*{z3jy;t1Uy28`k=#HAhnyTx_zZ%T0W
Z>JXL3|qI8WZBdy;BdBE(32nZ5VPUYi#N@2IZE5+B)^N0w*=wXdl(kTxD+8Uam=}#`Jxp^h>Opb!6`mAWt0*Nd~nN-
=EGGo^r=@cooxaDqB!&Ry2B*Z!V7%~9ANdeqb*ZWaH;I1td`zkLW@geKkkGeQ<oakY6%FOV@(Jv24jCUkn`8BD&<KFI>7x}rsta(
iREF32z`ZOGaJ%Ut-GHe*%AO<UoxQ7=x@xsoo-e2N*Q)8KOdH`z59(|Q@nH2V90EjmvS@NsVMh9-
S_E>e@aj@>@_o5=l*^~ZH@i5DaGzc!t;HO#18K4P{8m<a&B`<E^S||3^d~(@@C&+iU)+_%&k#%1>7EyWp=Gra&bZ>|@WT@=Q7e)j
$dNq3E9t?re8(ZX~02Kv365a=5@UZdxJGtZ8F}FZ!BnWY3rdHP2`wR>Y%>}wLd?>KS-
N(o|TIjaGu%dxjdE>r2mQjzTlbc=^ao2FM0N+1b{nNQX({fskN%`s4X$V62FDP}1WYh)FCozOi{H$Gqi$=c0ZCb~Pbe<@|Whz8?{
c}Cn{fVR!JX1E`tXk>b7JsZb*Ff(T9}hZrMTc(xp?0rVu@Fzt3dkv6Hfy+L^PL{ZY0mzeL=RAJ3K!;l@O1LJ)Dmfb-
1EtOk1aj(>QzPKax20(0XwxQ4{EFXb-uIh@LnyK3Bh0P+im9uD<~v$4sPN!_@cGwX>xWL<B0k6R>03FzzfL&T|huY?r=fHs~raT1
8rRZ#n+-10__6gXdL_RVfvL(2nLK?9|8U1Cx!M1{)mwXnO%mQr1zi!ly-GygX1BTprXioOEaj^T6R~{E%%nb<&P$!7Gl5mwqaggM
P$=A`><e&gwObXG@ePgrOglc)H;n&MGyZV<@F1h)x}KqK70b2<vfod!KVzbE}!Z?k=YoEm9=v4uyRbC365d-
_)Z_7QB$%b_lIu{3q#^J??k#>Bpkhb4s{Rr*g=+QQ@axN{F1TWiV_Bcc#%VY`18TNvNa#o9#`ef=OKK|`6MQjiNxQGI#fWBZ+2un
43RuZa_-
n+@wKXd&r;wV3D=QzL8oR=rO*fMq(PYYlW<}rA<}t>yD`QOtR#x^D4KqYr0HUOsyCu!(|_9uR(AQQtgK!cW$`Q|WNObpm>IT{X7z
pB%Pf~Rgd{>k*S)3cTk0p)BbF2unGkK(Qa>MIuGOt*8%PzKD1x;7KvN-MXv%B|<;3KVhi@KgXPvPS{EWFcO8WZ|??teydp_wm%v_
f~2KMg={N++Nquu3jzGP0c_g+2yI(tAvDxeWlc}>Ty1}X_I#Fog#pqyemmfN{8dSv_>;+Rpy!FpV(UTikv8bRK4B%yOZCHjq%b6L
B$Su<s!oW13uq>p}at%TTEJAsx3;Y3KYk{6@A;yG^3-PrwqBkgG7+vI{Lov-As4}*Z+KAIi8sfGq|-
p0)NkdHotEyrAxmY(&YE}e_@V5C7C;*|R=LMeqUfYpX=gHK(D<i4T8B$&68yuC`g^Fzgc?Ez0-
aP*o>IQ`>PrPNLn7yp&3u?vjBY5sIS`$kbtuJwsmGtqgr*rV7(r);i^LHe0qO9EWMTfs%#+pCxGIQJaTRdP~o6eOQ5PMvU0H2cKk
$%F9$Ik(UAPKz0!(!k=*Ld}rwHpEUh>{B-
2!1a>OR8#5HNO~7&_*^;BmU3j!k0*Ouj6;;&zECb_u5J7l(EI8<Lr^qy0{HmGTg0FTSqM!&r_QDQII%&Dt^Qp2NL{mihTcs0i09i
Pk%MW`5WP?AdFE)?&+VEmh2CBsIMd*5=)zkX!LVw$aZg<Fa$?BW3R(+RyoJMYiEt66vfx#al2xN@N1^{vZ2XDqoByoq83?z^C(Q>
d=&xQLVhzh=R{4;TWk0iv5j0M?GThqDQdxFhS(RQzfQnR_?Uv~WOspbHo0?5*NU;L~8gXI3=K6+1xqUmAmJ0T2!mS&}&lnJE6f2$
+noq0o#0rzaa2s?_R6x^KrW3L_N#xf|`>Ad=RMKcnXbFh7R>GU8u4*-
rC!2(?uBOMkfZbXOOWk7W=mLPXC_(`qIN0oM>Sd=y&Dbx0EJ8`UhM%A2x|D(j734+L(h!2Q;TzuP1k?`|9%qCHaHch0d}Bw#<X>*
5j((%2?8jlM+FJq#hoKF$*!&9!Eanz{dn_FKi5G2<;pG<=3?d;RR04H10j*%#o^DvOWcyp+W2^MEr>b)1EauH12q;ipO(&myCx08
B@j?mV%q_gU{qh8uAO(1h;b3#5oExpTZ-
V3$H>KxSDw5$+j{Zk*cHcvi0OHfahLLmbQf}+(_swTcb9$N!+*8C@scWa{H7sbnG6U{w2klh@<ZVd&&mE8iSVEaaj4kw3NTk~0Y)
O(iD8y?+Dsi)`%$zt%R@g<S1dPYCQ*p5=NAKwAdX52vO5AozUJ2RqR0h-MEHcMX=T1MOuZb?eBGWcTLsctTh_=p#+Vbf-
F)En8u$b5rMZ0gZ=Y;^QzK4_>M#h}#%{;hK{GC=#9(}4MnxVI&4y;m^lD}NMcZw`gZnt2fL`0WPv}GIhweA!@L=f7EG%1ug7q>Wj
?ZtQ<afp5VowyW{Q58NZ&!PvIb!yozS6_;UFLc5L8;BO}b~<jCPI*f{QHG|d!@ei^f1-
t*KuM?18tNY<=U_6tz4c?cG+I0(`w_hw5e`z)MvnZiHjrHcZcO`MlEnyck4u0oH_Mop(M5Ni*LA`QPD|Qd6_Q)urUo0UjF%JiH{)
@AKl$nQni+4(;*;QsNz5+XXB`c(!$tMtIOSC#`Ph@pg{hcFK9bY-jHQxzp6Ekp{SUB#blI_utX_XqBn9$CL7S!^i^{O3Wq}6;ppr
y~;1S`M1;pgn9P~TlMHN@Wf81PXy`289?H5LnTdmP%ma@CFz>r>DWaxV=pt=ZHW*dWn#s|8~vegHK3*hj9;UaHTb0$rZiL?GZrV|
o8Fd&L&#>GU2_b>|h>SwfLKwt5Mc;<?-
Gv~ewyqcqEWT>g%Ypu~Wemun}!JN=GtpE8$FLKH|ditf$dD6_`W4vKIkzj`yy}O+Jx(5Sjvu|I{&C@WS%OcyoS4G4Rw`r?gXeGll
RRD`{Y-tj(o`?t@fcx&SeGW5>Z66e=48<^6RXAUWm01dTP{(7CTn{d$=n_a$e_8zPY|U&ru4E$9p27^?J&H$=-
wa(mvQGmL`KB*}9lRXEGJPFWaza%8Q+@S@z$O@VbCQx4o)knlO>%FJxL7bVK?Y~)gYi5^n8^+2?s9C_o_HW$`(~$1bxrI4B5MO7a
f{;Yv(^0|7|zw-e{tLvJL09})d}|`MbW6T>Q^f4rIyzgfo;5U3yx4xk(TqovR$inubgl7G;<WpHtPF=>+Z)RLAh-bncLe^4^TE-S
P{-=vV&sOw@o1D3q3ST2$yZam*1UjC&X1a*!3<3FSXwh_mO?gF5DTqZ7`_OyW~N1fhu?<sz@_Q4hO_h&+RldhsaBFP3sN=d*-
P)ycVn@tL!0dt;KA|XHCAMozzwh*B0&*pY#?56U$D4r){jrNRSOn?2Z8?d(k-mD!X;$Kt^t_fsn~oOJ`lCq|T>op6c)-
H4gYAz%c_jOvdt53vS*EKG@KkU_qVBvj1YHyF<?5o$?Y+h!~rc)Xx(x;w`PPW+11{lS33JtWa!YG?ZIm*O+pt>Akg=(E&N;WjDF}
4{RvT&Z6*+2+apO>946zeMzW_>PSS;K|fA-
#7MpnqW*t}YvzT?g;+7W>*;J<br9Io%NsAW)Mp$aMC^qyez}efRP*cVx9`08uBig7rtr3EPjC+xC{$|HxFeQF1a|>EGP5cBzz&3K
rG=F4*GahujF?p(EUxOtEF=o5IYva)%01q6E`Gr4Z)JFIp`k{1-29<okO*JH?A?-
ccP29;9a~;E2%3Kb@mt$Enw(Mp{jq518_y>crwC`>&nB#2f&D9vkYqE~V`*oB9#8#A)lO56z4|Y4I+$QH<4$^*dAa`SuO8B_M^2d
H_7sNdhxXpgoM{HGUo7>Z9>QCPj>HJa5A(0%6pGwj8>z8<BPq9$pp=bfNc-
9lb(gRFL3|G}i;~cv_;WqZJB|qNS|m(he|^zaS}7!kFgqef#D0?n;@<vm`^IXY;tib6JG11!LuPhrtCGk@OELDE89kbG*S<3*YKE
y?6FAhv+_gI4reX!S9RrhOEz;GLUylzfcSdoUmL|`}4D6YK90+D4>vkI-IC5H<w^Y^j`T}cN;bna~^%6Qk0@(y79-
kBxmRISC{8amcNjcp*4QgR&aPPC9|KyWmmT4^@4g#{^vy6Q#@b+f4mAmi)??4UZL4AnAQuBB5=k|`M?xen}fWQs0y*%$*s(eh<d_
kHTS>r`jzslzE(WNMqh$zJii7`>~HU6I>eJYZ@pDt3s8AEMT|0i0*J~|`;17!3}|M4}*W}NBZW<chWOKJiDNCI)bQ#O=j42y!YdB
2E13bg2&TG@FuzioZ2qbnFo5epntkvtf1A<H&A;j{%yiU`Y4e9bw-CM6{6tgOlXG0msKRmz#{-
%xn6jl%dvOVt}8w+d!|DYg752J}4b@?AKc2EU33GSYW>dzh7?CTw0p5zk(vVDaTvy63r$r;zP!*GZWR2LLZ@2^aFVa?0mjXudGvj
c#;)iry^y)DrTexFfhNm)S$tQIGE;6jDT?Jy|L}EqF7Ze}IOxr(TpwfYLN?6JP8kZFZtqWGs&)1!i@zu}&&3EJb43g$es7(Gw$33
<erv8>&OtVy7g9(&E*#Rde$pt_+FGl9SeM03SX?+r=AABn%3WpzX<@)Q)W@Yz8a3JEfH`y+tu*LDCH|<X4~0!EzoW6q@P^J^6k|I
Y<Ggr2IYXAD&{gD9H##jQnjY#x_y-
&C=UL4z33ISb;rq(xfp5WbpaRS*E28lW&AaA#VIrbkI4>5Y#!MJg4yD0cA#YjZzWG)Onujez&DlKNzn9b}{i-zHOzTgV|-
~(WH~^ekpF@_&XinOG4t^gDE85LXC4#n|i-
W1cH3%U5GYOGMU4unYO{eaMGPLhb#{Z|DIUwzMpyPS)>=w4TLI##aW_I3OW?hTEj7e1n7}DLp6U;j2m^!4u4YAGPl|9)ftG(g~Mm
X77A+CXRmTPK{}-
7m74c^$$C_3XXk7*+vV)=`)jFpOYTU06u*i>)S1$e{LLrNuuu(yV|v<@CmVfN4)?4XFW5LVBX?kov3}M$tKsc6T5E5?*@h|ET9E)
RV`|=N^98^}pX<t()K;XnM!%@R2I1AfPoYaY&njzO+@E!$k477L^2I#p76cJ9=77H$;JVEsBs)X<D3d?9LxF-It<N99ABW-vPnp!
{a1j7pW2BMi;XqjLECe80E=l4#>3Q+<v?8)A^BJ?}^o|-
S_U`8~Wqb2&YA>$@Ya8eNYA}#W>TnCY>aFD_S^`&$LadC2TNV~UTMnN7LQ!A|&g;b=nOXaDWTIQ6Vii?9L#CmVKC&7UNyBJj?me!
fFFIj{{GDQ{GtF3Vk?rFFTg>uPtCZ`hRsEF!P)aK?39d<T%UkOF0^h%GRfkSZBO$`_yRwy6wZUHXn>^Qj=7oXqsqv}V6aeBO(_^|
{TiQTgcCm@ugQe5WeYxNe4D=+!ibj7;nRc!@L{gM*7kPw@nHOH@8NF|Ta~cn^j9JaILwJg}5!=A^*ydr+b8<|ZskBs<W-
55Uz`Rf<K7gy?fZ&_>eR{h)&R(sa#0ahN&yN`bcY{y$kp~0hM8p#Fiu`l%ANf@7<;?g!jvX=m*47?j&bV%xXkUdicg!4aVIomIP=
CXEi@rP}qiR)4`eE5*ZP_}GT+Q%_RM0C&fe|spn64{>Tcg<+G-e3-
<!us?YbqR}eCWKg)R}X2uL}v6)hcvxDZx2}VZU|}U9)Z5iD8nnHwxPrS12F<8@k8lMa;)q(W-
7REZ~s7%om}Jh0oZzT$GT8n&;I@BH2E}Cg{l0GR=o9`Zq`<n3fiKw8CL9+Q0^ujPr-ENcfC!!38r+?=N&tM-BRvGUsn=DMkj7Az7
5WtL#RnM*N@6f35;iS(q5YE{?t2yhZC2C3SAmo@4wJxp3TQq5UVRYnZqkpb@zJLJV^S?A8EP6Y|}PIC-
|d(*MoOI(T3ws&J{r`rs3m3TGdohq>2PxCsmM_PXi9#!N>GC1Semc+q!J9vpt7mOwS5e(Puwc-
h%pfzH+<AQV3kpb1Nz&qiuX9jYV#viu@Fm1TNB%jcgh-GWFJJ|s)2zChr=zMzI(U9?4|Ns*<9k`+xW7@6gB7>%qPgI>gsmnqH_@B
X#ATZYY4^!?geWdfHTGPF9@mjc*YT)@4J%dApEPLJA4BN!V*a=@i80-&bqGB2~yAfugoXxlh`HY=J+5z}X8#Vq?c^hf67bA-
8#r{($bxEL&sIFtn%rqCj1ASKT+bIm;qS*Fe`2xoNm+-
<kzIc3vJ>bpN2#o1^C1D)7NP|=s0lU|(`;rRL~QKd#rvM_fZzVN4=&<A`{_mS;WOM;a6%lFT|MCdoXj>F`GB+9_ZUH`12CXl1OBM
&Kp$93j$TbFFwVJ(sx?Q*!3o&dp?n`^y|gX>7P@THl5U9+CyZ8<cu2a&~CF<YLxw2a<>jxGpIBP4JHRy+0biTyrDfkZk1=jvf=p(
Mc@mM>Iv-36hJBolx+vq3gXf5Kd@f^Svik<Km49%k-
+NgzN!ZUBmd<{T51o%3F12MQRPQcPpmc}zCAapRGG23~GuYiKah{6<L8%a6#zPtKAGk20Y})LPoK#i}~lDZsAT0m5aFSLutAJU22
F2T{b`nai<rZ2F0$pUM6nLO}qA%xO$xs_ks~*PHo_I&l5qZrsLDOqV^agaoAgkzK*>pL1bx_w~@p2Hs0kC*B^y0F0DGg3DDn*;?9
|MNeUCTPAouLxI{BNhGKrzwmeoOB$@V8JvBllrXl2;L<pAUN~y*r<j3p_9A3}A_-hvt#xClRqUnF)tt7<J)E3=4`%P_sXL?~Q1UJ
cuT(wJ@m!vN&4gRt&IE)zoP13Mn$<=f1o7xfM4IRK$%tV>qNvx_b>MF9utJ>qm)bIaPl4)0iJF*+5V43o!&ZNeLAA?Edap%2*@+v
7Y)8X6g(>BZ{-Q{8fzO6JdPC7vYJ_JOQKIP;<*^O%$y9Z-xHjxo3<8+-kK)KWntwd8-zTD!f$$pw=cJ{X^Z%MQF-*zU)0)-
yOfJgyg=IYwb)J2~eC4U`CEEZr$d%yETCKIrcZ<qTbjDpmf|Aacz$7gpxWqe>ch&uUk9oK3mW_lFAq9;QL6Q2GER#qwcQK?Uhz6!
jFlC?Mo%V1a*}<tTcVnt*hW?&y9iuM=u>AkkvbuV8-pbl`<GTuH#%8UAUK_}Qp7-
YdysR1tpNc%fRdpg6jIi7sp$97!^XP@7ES+D8P{d~;5#sFP;SMc<5T*n|^$M?u=S2DI<I4(qflRa6$G8SbiPW%<0~ENA;Pe~Ae$~
?|6JwHEn;Y;LptGm4T3|E<wZ2k^(#6<FhVAY2IOmg>ATS&r?=pm(u_PxT!=!~KcS<K5(jaz|A4j^P;p^rbDpFwY^&Pgun-
?N^g6iBAj_P&vrr-
9h{Ifr{!Ci>k%g)Fl85Jf8<tZPWGSPmWZjA;1N!FWYXa(sYpY4T$?78o8w;?VbG>z4|`)p@9TPFU_*+ehSw|$d%cq&1n7LCjYJAP
}7U%5MW_=^?3U?D10o+o;OWUDnZ<VVQ638RfrB<~67v7$gLUm4fjphXR6z)m0yL2PSlnFnp8j6eeA$#VXQK_MV9t-
*je7%o6xo`dfs+aOh!l%gXTGNy#aKpIR3lz6pf;f@N8cHRrPMsr-kIvtAVq!Z`)=K-v!+G<}QC8u|~`e1@_Hy?$SqEqx~Nu4h-
9O=C40~dwuK~T**yoyX{5;|r!A}VH*1f?Q5=zFJ~$j(??CoK#nulm<in|x(07jbzri-
v0Xdiq_vv(JkhvQFkYm?KOTpH@=nf}R?&3lmOg;1|v$>vIeFqld$(GQWgG4{|WC*WHmP%qRH6u-8(FF0-
#M)9F%v1sMK;T9c0gTib>J;TV7ox4Z8v)OH)ig7bkvo+m;b5w|xiiq2)9&)hFOLFKkCGPPOOwTJM1LB_L}O!E@>U`wlkh`DJ+y6<
@IGxM=Z=LdtRJjO?@&{FK(`U)SfY|6yNUs{+P{Cc1C$=LqKcrp5yrQT-
>k!V0Azk^x4cjNs%`G#ekno%e<t&P^i0WHR;3#yJ3?P#X{w7Y7-4!hvN;bI8l*ryc3*F=QMZVQdB3xX$$7h}P3?_hYWZVKA-
j(vk?_TVt8jD=u88R61Jf=<fhf3N0){q^k~h)z1DL=WPLej}Ne++~@&H94v~7A6t1xiZD}a|v=x(SJqw`&>gKNf$3!V{>;#2T#X4
7WL2X77lqrf@`E>XD7K*_<*Z@MB%rb`-
Z@%TRp7nEx8Bi*&5&PXxAj9H+{A8JbdX0R2#Q_zi4HfV<=@j_d&q#NlQzO$F?As<?_>I$I5ob8XtC5pPLL&)sYv=MnLH7IzEIqr3
i+To)IfZ)w@aciVK_-
*umkxih!#y3S?0PwUyZ|LcjakUqx<nIvilY*fsMWXH_CJVJFYHB{lK`5Qcy@xoJEt4gCO%w_{;qUWI@eiW39&E5BGup)lsfKoxlw
VsnN$)m*Tb%dQ}?v#(vnd^kH#k94D2GQyx8u?2e>J!TBmnCl=8^4I>Ju>-
xm#AEyv#77k1^nIAqKTR?ZPhoo#Ulbw!h>5Kq{9_2l+1Z<45vy%!WPKBnz!qMm;h?JW_&Uc8=}g{jV5CwD^=QVlSE)W>!*+~9aP_
c|EzfvSv;BhN7YzXD684xrU}|dlLn@}f3kg1Oc9pY4E_*xY9LfMRWev5wPhJcV@mKuPhTre9)*3SBD<&rOqtw3%V>W?RL#lipDRh
vxd=2dYz<W-!^<jYAba_p9s7&a)=R)H<46qp|%xZf=<x3Rx8G(=K2!knqwMZH?D*JCi1d2?Lim?)-%+-
9$2!;x)Eu1?OdVZjLYa9i~3Q~Ax>b-
}EkSSMXLT)J<e9>pI`#kzobyL4k%A7KX)b~ZJINq3qH|xEMQyu|69s>^qY!U&b9SP*2xTFY`2ZcEG(<YdhyV|ZEgJ&YH0JubHalA
;>(t{Ot*hqhrc53yYI=sHbKk{Kcrv9&^li%KFZt6sNfflP@#5cXsFcRV&8~%J3<t5u}VY<5Cbkj;f1e@5Zw_l&QS~o)rg+~pXvRA
{NX%8CyJ9G`!xGIx${{#$4xQ8?hJ9&gx5863V32MN=scHj@bbiT9y_p@i5(o*C<jF9^HqNmQY^J<WFrp4`gq(Rx)|U0q#530*({`
|7k$o!k16oe05b=Rd<b|LEsq1yWI0lrD*-zsopQyYf6H_yQB86-
Se2Z)M62gJzX^^j{!LAjZLcR_fhTWfj`(jbhG1DN`2pbC6EIz(<G6^5YwoE>S_#0Ty)tjmmt^1{aJPfbr4}9RT+{`#r6hNB?HSx<
^n<U5aLN2mpCao?)Vp(OZiOMQ3N~RbuR#3P!3lr=0rkVjePM6?w#7M7g@u}C*mLoliP~6?lU9EOyVWRona2xzv)V43dz+hTi4jR}
Ip5;6^vLQGZmy`Kb`52fQ=1+iyRAGp;s~>4Ci(d6{wPv5>icn)6gN<ISA${#iR+9hj!u@X!4BHj4HhDNNfYspkWP7~X_lFv-
W=H4r(Qr(rvu%#6dQo~*w|qYvX*mWm;dL52%i#V&4F+mSii1{%{RoYh7@Mwm6sIZaWLQ{oYXX}!1I-
e)R8^0ffN&aOW~Cr4h_s~$*=^T7nMXT``8c@fTVQ<YWd2KHPZL0m0}~68-
yte0)EDRbgO0Wek?g*_%y;VdL3T)hcTvhUvJeVlyxz%EEYqo_eTS>YZCrTj2p>%u{p&c9r<Mt;2YnL)_aR1>LWta;l^K(xMTbKmY
($3cVFAg}g$2wiO`>di%qn?>(U2ap3_O7j)G<*74>jUU(ue3~OBq0#LD#Rq%DY13YZ8IzF&-}^qZ(Jx^iGVujmocW8m-
P}JEJx$V)v>9{EKoi>{t0KfOq^k#Ua0riOb(G9Fm5vAgm{<rT}eND}&@z$PSXodQ=WD5%Q%F&+vIBkXC{M*fvL5ZgWQf1WN13u)3
;RpO;~}=K<pgI09|wA*liRV$y4Zze&@+mxOZ{qcL=lf~*P$XgVDjg<e>sX%!Rzs3(n$$`685KOKN9*o{8q#LPC+-
(vmziJ~~OWIAPq4>Mw(_Z#TiU6b3x<5>FPuVwBxir(YH_a(~!@JG2LZZRTmfOwlA!#-UNBA+Mx2SoirjLf65VZLiH-Queehti-
v=~*3$;og`5I#NV9l%|Aq__YGSwy-39U^5`-
3%m#9`r?bHG~ap@tKFggP#E+DqO@<l;V2dm1XtSil>W6h&yn{fUgMeyJ`Y9ix@i$=_gqDIbNt`Hxx5VTT$$EP>FUdnhNa^VP){w-
3JM>ojT4#HE@pq@2&^D0;B1-
hGWRakb9GKg&gmM3@}aGCcZ+KhT;arh!Wg9_Brw4Ta{C<hY|10}lZ_=c&DHY^R1)5MokIWIQ40HVQp+v`ADw|q=}P1KiRWj|8wJC
f8?X=D_dQXmPdLs^qdoZ>4hxa~qG@53r>mSAI&^T4K}|MkNXBc$M|`;c!|oWbAif8n>@Up0n6k!Ie^IkazRt=xzHL3%Q$AcREgOl
sP>rtJ7)bU%=>TaWWt5c0_(w9qtnIXJ!bdX|znoI;tyJRrCbO5@dcaJ%JZ7zG<be0WA|af<8VS_Ds!pI;TuQH%+e7ayde@{`$H;|
f$r-HNPMfQr?})^PDQ$(q$g@A|Ce$Outl9i)vP>cWD8o2gNkf>FDc^6r4}it0KerJlPVgYJ#ul|B91T{MF@C@|b@5&RS^x
'''

MAGIC = b"RSB1"
VERSION = 5
WIRE_PROFILE = "rsb1-v5-public-kernel-1"
CONFORMANCE_PROFILE = "oxbow-conformance-v1"
MANIFEST_PATH = "manifests/MANIFEST.generated.json"
MANIFEST_FORMAT = "oxbow-manifest-v1"
PUBLIC_SECTION = "files"
REQUIRED_ROOT_DOCS = ("READ_FIRST.md", "BUNDLE_LAYOUT.md")
TOUR_ROOT_DOCS = ("START_HERE.md",)

MAX_BUNDLE_BYTES = 256 * 1024 * 1024
MAX_FILES = 10000
MAX_TOTAL_RAW_BYTES = 512 * 1024 * 1024
MAX_FILE_BYTES = 128 * 1024 * 1024
MAX_PATH_BYTES = 4096
MAX_SECTION_NAME_BYTES = 64


class BundleError(ValueError):
    pass


def _rv(data, off, max_value=(1 << 63) - 1):
    n = 0
    shift = 0
    for _ in range(10):
        if off >= len(data):
            raise BundleError("truncated varint")
        b = data[off]
        off += 1
        n |= (b & 127) << shift
        if n > max_value:
            raise BundleError("varint exceeds allowed range")
        if not (b & 128):
            return n, off
        shift += 7
    raise BundleError("varint is too long")


def _take(data, pos, n, what):
    if n < 0 or pos < 0 or pos + n > len(data):
        raise BundleError("truncated %s" % what)
    return data[pos:pos + n], pos + n


def _lzd6_bounded(data, max_output, what):
    dec = lzma.LZMADecompressor(
        format=lzma.FORMAT_RAW,
        filters=[{"id": lzma.FILTER_LZMA2, "preset": 6}],
    )
    out = bytearray()
    feed = data
    try:
        while True:
            remaining = max_output + 1 - len(out)
            if remaining <= 0:
                raise BundleError("%s exceeds decompression limit" % what)
            chunk = dec.decompress(feed, max_length=remaining)
            out.extend(chunk)
            feed = b""
            if len(out) > max_output:
                raise BundleError("%s exceeds decompression limit" % what)
            if dec.eof:
                if dec.unused_data:
                    raise BundleError("%s has trailing compressed data" % what)
                break
            if dec.needs_input:
                raise BundleError("truncated %s compressed stream" % what)
    except lzma.LZMAError as exc:
        raise BundleError("invalid %s compressed stream: %s" % (what, exc))
    return bytes(out)


def _validate_path(path):
    if not isinstance(path, str) or not path:
        raise BundleError("empty or non-text bundle path")
    if "\x00" in path or "\\" in path:
        raise BundleError("unsafe bundle path: %s" % path)
    try:
        pb = path.encode("utf-8", errors="strict")
    except UnicodeEncodeError:
        raise BundleError("bundle path is not valid UTF-8")
    if len(pb) > MAX_PATH_BYTES:
        raise BundleError("bundle path exceeds limit")
    if path.startswith("/") or re.match(r"^[A-Za-z]:", path) or ":" in path:
        raise BundleError("absolute, drive, or colon path is not portable: %s" % path)
    parts = path.split("/")
    if any(part in ("", ".", "..") for part in parts):
        raise BundleError("non-canonical bundle path: %s" % path)
    pp = PurePosixPath(path)
    if pp.is_absolute() or str(pp) != path:
        raise BundleError("non-canonical bundle path: %s" % path)
    return path


def _payload():
    encoded = "".join(_PAYLOAD_B85.split()).encode("ascii")
    if len(encoded) > int(MAX_BUNDLE_BYTES * 1.4) + 1024:
        raise BundleError("embedded base85 payload exceeds input limit")
    try:
        data = base64.b85decode(encoded)
    except Exception as exc:
        raise BundleError("invalid embedded base85 payload: %s" % exc)
    if len(data) > MAX_BUNDLE_BYTES:
        raise BundleError("embedded payload exceeds bundle-byte limit")
    got = hashlib.sha256(data).hexdigest()
    if got != _PAYLOAD_SHA256:
        raise BundleError("embedded payload sha256 does not match wrapper header")
    return data


def _decode_offsets(raw, count):
    pos = 0
    arr = []
    cumulative = 0
    for _ in range(count + 1):
        delta, pos = _rv(raw, pos, MAX_TOTAL_RAW_BYTES)
        cumulative += delta
        if cumulative > MAX_TOTAL_RAW_BYTES:
            raise BundleError("offset table exceeds raw-byte limit")
        arr.append(cumulative)
    if pos != len(raw) or not arr or arr[0] != 0:
        raise BundleError("invalid offset table")
    for a, b in zip(arr, arr[1:]):
        if b < a or b - a > MAX_FILE_BYTES:
            raise BundleError("invalid or over-limit file offset")
    return arr


def _decode_paths(raw, count):
    pos = 0
    rows = []
    seen = set()
    for _ in range(count):
        if pos >= len(raw):
            raise BundleError("truncated path table")
        pool = raw[pos]
        pos += 1
        if pool != 1:
            raise BundleError("public wrapper permits only local binary pool")
        ln, pos = _rv(raw, pos, MAX_PATH_BYTES)
        pb, pos = _take(raw, pos, ln, "path")
        try:
            path = pb.decode("utf-8", errors="strict")
        except UnicodeDecodeError:
            raise BundleError("bundle path is not valid UTF-8")
        _validate_path(path)
        if path in seen:
            raise BundleError("duplicate bundle path: %s" % path)
        seen.add(path)
        idx, pos = _rv(raw, pos, max(0, MAX_FILES - 1))
        rows.append((path, idx))
    if pos != len(raw):
        raise BundleError("path table has trailing bytes")
    return rows


def _parse(data):
    if len(data) > MAX_BUNDLE_BYTES:
        raise BundleError("payload exceeds bundle-byte limit")
    if len(data) < 5 or data[:4] != MAGIC or data[4] != VERSION:
        raise BundleError("not an RSB1 v5 payload")
    pos = 5
    for i in range(3):
        n, pos = _rv(data, pos, MAX_FILES)
        olen, pos = _rv(data, pos, MAX_BUNDLE_BYTES)
        _, pos = _take(data, pos, olen, "global offset stream")
        clen, pos = _rv(data, pos, MAX_BUNDLE_BYTES)
        _, pos = _take(data, pos, clen, "global codec stream")
        if n != 0 or olen != 0 or clen != 0:
            raise BundleError("unsupported legacy/global pool %d" % i)

    nsec, pos = _rv(data, pos, 2)
    if nsec != 1:
        raise BundleError("public wrapper requires exactly one section")
    name_len, pos = _rv(data, pos, MAX_SECTION_NAME_BYTES)
    name_b, pos = _take(data, pos, name_len, "section name")
    try:
        name = name_b.decode("utf-8", errors="strict")
    except UnicodeDecodeError:
        raise BundleError("section name is not valid UTF-8")
    if name != PUBLIC_SECTION:
        raise BundleError("unsupported section %r" % name)

    nt, pos = _rv(data, pos, MAX_FILES)
    nb, pos = _rv(data, pos, MAX_FILES)
    ng, pos = _rv(data, pos, MAX_FILES)
    np_, pos = _rv(data, pos, MAX_FILES)
    if nt != 0 or ng != 0 or nb != np_:
        raise BundleError("public wrapper permits one binary record per path only")

    plen, pos = _rv(data, pos, MAX_BUNDLE_BYTES)
    pcode, pos = _take(data, pos, plen, "path table codec")
    max_path_table = min(MAX_TOTAL_RAW_BYTES, max(1, np_) * (MAX_PATH_BYTES + 32))
    praw = _lzd6_bounded(pcode, max_path_table, "path table")
    rows = _decode_paths(praw, np_)

    if nb:
        olen, pos = _rv(data, pos, MAX_BUNDLE_BYTES)
        ocode, pos = _take(data, pos, olen, "offset table codec")
        oraw = _lzd6_bounded(ocode, min(MAX_TOTAL_RAW_BYTES, (nb + 1) * 10), "offset table")
        offsets = _decode_offsets(oraw, nb)
        clen, pos = _rv(data, pos, MAX_BUNDLE_BYTES)
        ccode, pos = _take(data, pos, clen, "file data codec")
        concat = _lzd6_bounded(ccode, MAX_TOTAL_RAW_BYTES, "file data")
    else:
        offsets = [0]
        concat = b""

    if pos != len(data):
        raise BundleError("payload has trailing bytes")
    if offsets[-1] != len(concat):
        raise BundleError("offset table does not reconcile with decoded bytes")
    indexes = [idx for _, idx in rows]
    if sorted(indexes) != list(range(nb)):
        raise BundleError("binary indexes are not an exact 0..N-1 permutation")

    files = []
    for path, idx in rows:
        files.append((path, concat[offsets[idx]:offsets[idx + 1]]))
    return files


def _manifest_records(doc):
    errors = []
    out = []
    if not isinstance(doc, dict):
        return out, ["manifest root is not an object"]
    records = doc.get("files")
    seen = set()
    if not isinstance(records, list):
        return out, ["manifest files is not a list"]
    for i, rec in enumerate(records):
        if not isinstance(rec, dict):
            errors.append("manifest record %d is not an object" % i)
            continue
        path = rec.get("path")
        size = rec.get("bytes")
        sha = rec.get("sha256")
        if not isinstance(path, str) or not isinstance(sha, str):
            errors.append("manifest record %d lacks path/sha256" % i)
            continue
        if not re.fullmatch(r"[0-9a-fA-F]{64}", sha):
            errors.append("manifest record %d has invalid sha256" % i)
            continue
        if size is not None and (not isinstance(size, int) or size < 0):
            errors.append("manifest record %d has invalid bytes" % i)
            continue
        if path in seen:
            errors.append("duplicate manifest path: %s" % path)
            continue
        seen.add(path)
        out.append((path, size, sha.lower()))
    return out, errors


def _verify_integrity(files):
    mapping = dict(files)
    if MANIFEST_PATH not in mapping:
        return {"ok": False, "error": "manifest missing", "checked": 0}
    try:
        doc = json.loads(mapping[MANIFEST_PATH].decode("utf-8"))
    except Exception as exc:
        return {"ok": False, "error": "manifest unreadable: %s" % exc, "checked": 0}
    records, errors = _manifest_records(doc)
    if doc.get("format") != MANIFEST_FORMAT:
        errors.append("manifest format must be %s" % MANIFEST_FORMAT)
    expected = {}
    for path, size, sha in records:
        try:
            _validate_path(path)
        except BundleError as exc:
            errors.append("unsafe manifest path %s: %s" % (path, exc))
            continue
        if path == MANIFEST_PATH:
            errors.append("manifest must not list itself")
            continue
        expected[path] = (size, sha)
    actual = dict((p, b) for p, b in files if p != MANIFEST_PATH)
    missing = sorted(set(expected) - set(actual))
    unexpected = sorted(set(actual) - set(expected))
    mismatched = []
    checked = 0
    for path in sorted(set(expected) & set(actual)):
        size, sha = expected[path]
        blob = actual[path]
        bad = []
        if size is not None and len(blob) != size:
            bad.append("bytes")
        if hashlib.sha256(blob).hexdigest() != sha:
            bad.append("sha256")
        if bad:
            mismatched.append({"path": path, "fields": bad})
        checked += 1
    ok = not errors and not missing and not unexpected and not mismatched
    return {
        "ok": ok,
        "checked": checked,
        "expected": len(expected),
        "actual": len(actual),
        "missing": missing,
        "unexpected": unexpected,
        "mismatched": mismatched,
        "manifest_errors": errors,
    }


def _tour_tracks(mapping):
    tracks = {}
    for path in mapping:
        if path.startswith("tours/") and path.endswith(".md") and "/" not in path[len("tours/"):]:
            tracks[path[len("tours/"):-3].lower()] = path
        elif "/" not in path and path.startswith("TOUR") and path.endswith(".md"):
            name = path[:-3].replace("TOUR", "").strip("_- ").lower() or "default"
            tracks[name] = path
    if "default" not in tracks:
        for path in ("START_HERE.md", "READ_FIRST.md", "BUNDLE_LAYOUT.md"):
            if path in mapping:
                tracks["default"] = path
                break
    return tracks


def _verify_conformance(files):
    paths = set(p for p, _ in files)
    missing = [p for p in REQUIRED_ROOT_DOCS if p not in paths]
    tours = _tour_tracks(dict(files))
    if not tours:
        missing.append("START_HERE.md or a tour surface")
    return {
        "ok": not missing,
        "profile": CONFORMANCE_PROFILE,
        "required_root_docs": list(REQUIRED_ROOT_DOCS),
        "tour_surfaces": sorted(tours.values()),
        "missing": missing,
    }


def _verify():
    data = _payload()
    wrapper = {
        "ok": hashlib.sha256(data).hexdigest() == _PAYLOAD_SHA256,
        "payload_sha256": hashlib.sha256(data).hexdigest(),
        "note": "internal consistency only; this does not authenticate an author",
    }
    try:
        files = _parse(data)
    except BundleError as exc:
        return {
            "ok": False,
            "wrapper": wrapper,
            "wire": {"ok": False, "profile": WIRE_PROFILE, "error": str(exc)},
            "integrity": {"ok": False, "why": "wire parse failed"},
            "conformance": {"ok": False, "why": "wire parse failed"},
        }
    raw = sum(len(b) for _, b in files)
    wire = {
        "ok": True,
        "magic": "RSB1",
        "version": VERSION,
        "profile": WIRE_PROFILE,
        "payload_bytes": len(data),
        "files": len(files),
        "raw_bytes": raw,
    }
    integrity = _verify_integrity(files)
    conformance = _verify_conformance(files)
    meta_ok = len(files) == _FILES and raw == _RAW_BYTES and len(data) == _PACKED_BYTES
    wrapper["metadata_matches_payload"] = meta_ok
    wrapper["ok"] = bool(wrapper["ok"] and meta_ok)
    return {
        "ok": bool(wrapper["ok"] and wire["ok"] and integrity["ok"] and conformance["ok"]),
        "wrapper": wrapper,
        "wire": wire,
        "integrity": integrity,
        "conformance": conformance,
    }


def _prepare_dest(dest):
    dest = Path(dest)
    if dest.exists():
        if dest.is_symlink():
            raise BundleError("extraction destination may not be a symlink")
        if not dest.is_dir():
            raise BundleError("extraction destination exists and is not a directory")
        try:
            next(dest.iterdir())
        except StopIteration:
            pass
        else:
            raise BundleError("extraction destination must be new or empty")
    else:
        dest.mkdir(parents=True)
    return dest.resolve()


def _extract(files, dest):
    root = _prepare_dest(dest)
    count = 0
    total = 0
    for path, blob in files:
        _validate_path(path)
        target = root.joinpath(*PurePosixPath(path).parts)
        target.parent.mkdir(parents=True, exist_ok=True)
        parent = target.parent.resolve()
        if root != parent and root not in parent.parents:
            raise BundleError("extraction path escaped destination: %s" % path)
        if target.exists() or target.is_symlink():
            raise BundleError("refusing to overwrite extraction path: %s" % path)
        target.write_bytes(blob)
        count += 1
        total += len(blob)
    return count, total


def _info(files, data):
    mapping = dict(files)
    tracks = _tour_tracks(mapping)
    return {
        "name": _BUNDLE_NAME,
        "wrapper": "oxbow-self-extracting-v1",
        "magic": "RSB1",
        "version": VERSION,
        "wire_profile": WIRE_PROFILE,
        "payload_bytes": len(data),
        "files": len(files),
        "raw_bytes": sum(len(b) for _, b in files),
        "doors": [p for p in ("READ_FIRST.md", "START_HERE.md", "BUNDLE_LAYOUT.md") if p in mapping],
        "tour_tracks": sorted(tracks),
        "payload_sha256": hashlib.sha256(data).hexdigest(),
    }


def _orientation(files, data):
    info = _info(files, data)
    print("%s  (Oxbow bundle, self-extracting)" % info["name"])
    print("  %s files, %s bytes raw, %s packed" % (
        format(info["files"], ","), format(info["raw_bytes"], ","), format(info["payload_bytes"], ",")))
    print("  doors: %s" % (", ".join(info["doors"]) or "none"))
    print("  tours: %s" % (", ".join(info["tour_tracks"]) or "none"))
    print()
    print("  --read-first        print the front door")
    print("  --tour [TRACK]      print a guided tour/start surface")
    print("  --verify            verify wrapper, wire, manifest, and handoff conformance")
    print("  --list / --ls       list bundled paths")
    print("  --doc / --cat PATH  print one document as text")
    print("  --extract DIR       unpack everything into a new/empty directory")
    print("  --payload-out PATH  write the inert .oxb data twin")
    print("  --info              machine-readable summary")
    print()
    print("Security note: this file is executable Python. For an untrusted wrapper,")
    print("inspect it with a trusted Oxbow CLI instead of executing it.")


def main(argv=None):
    ap = argparse.ArgumentParser(description="Oxbow self-extracting handoff bundle")
    ap.add_argument("--info", action="store_true")
    ap.add_argument("--verify", action="store_true")
    ap.add_argument("--extract", metavar="DIR")
    ap.add_argument("--read-first", action="store_true")
    ap.add_argument("--doc", metavar="PATH")
    ap.add_argument("--cat", metavar="PATH")
    ap.add_argument("--list", action="store_true")
    ap.add_argument("--ls", action="store_true")
    ap.add_argument("--tour", nargs="?", const="default", metavar="TRACK")
    ap.add_argument("--payload-out", metavar="PATH")
    a = ap.parse_args(argv)
    try:
        data = _payload()
        if a.verify:
            result = _verify()
            print(json.dumps(result, indent=2, sort_keys=True))
            return 0 if result.get("ok") else 1
        files = _parse(data)
        mapping = dict(files)
        if a.info:
            print(json.dumps(_info(files, data), indent=2, sort_keys=True))
            return 0
        if a.list or a.ls:
            for path in sorted(mapping):
                print(path)
            return 0
        if a.read_first:
            path = "READ_FIRST.md"
            if path not in mapping:
                print("READ_FIRST.md not found in bundle", file=sys.stderr)
                return 1
            sys.stdout.write(mapping[path].decode("utf-8", errors="replace"))
            return 0
        doc_path = a.doc or a.cat
        if doc_path:
            _validate_path(doc_path)
            if doc_path not in mapping:
                print("%s not found in bundle" % doc_path, file=sys.stderr)
                return 1
            sys.stdout.write(mapping[doc_path].decode("utf-8", errors="replace"))
            return 0
        if a.tour is not None:
            tracks = _tour_tracks(mapping)
            if not tracks:
                print("This bundle ships no tour/start surface.", file=sys.stderr)
                return 1
            track = (a.tour or "default").lower()
            if track not in tracks:
                print("no track '%s'. tracks: %s" % (track, ", ".join(sorted(tracks))), file=sys.stderr)
                return 1
            sys.stdout.write(mapping[tracks[track]].decode("utf-8", errors="replace"))
            return 0
        if a.extract:
            integrity = _verify_integrity(files)
            if not integrity["ok"]:
                print(json.dumps({"ok": False, "integrity": integrity}, indent=2, sort_keys=True), file=sys.stderr)
                return 1
            count, total = _extract(files, a.extract)
            print("extracted %d files, %d bytes -> %s" % (count, total, a.extract))
            return 0
        if a.payload_out:
            p = Path(a.payload_out)
            if p.exists():
                raise BundleError("payload output already exists: %s" % p)
            p.write_bytes(data)
            print("wrote inert payload -> %s" % p)
            return 0
        _orientation(files, data)
        return 0
    except (BundleError, OSError) as exc:
        print("error: %s" % exc, file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
