"""Generate transparent self-extracting ``.oxb.py`` wrappers.

The generated wrapper embeds the exact inert ``.oxb`` payload as base85 and a
small stdlib-only runtime copied from ``wrapper_runtime.py``. The runtime accepts
only the locked public-kernel wire profile and keeps the same path/resource
limits as the installed reader.
"""
from __future__ import annotations

import base64
import hashlib
import subprocess
import sys
import textwrap
from pathlib import Path
from typing import Optional

from oxbow.bundle import kernel

RUNTIME_PATH = Path(__file__).with_name("wrapper_runtime.py")
WRAPPER_FORMAT = "oxbow-self-extracting-v1"


class WrapperError(ValueError):
    pass


def _name_from_output(output: Path) -> str:
    name = output.name
    if name.endswith(".oxb.py"):
        name = name[:-7]
    elif name.endswith(".py"):
        name = name[:-3]
    return name or "oxbow"


def render(payload: bytes, *, name: str) -> str:
    verify = kernel.verify_bundle_bytes(payload)
    if not verify.get("wire", {}).get("ok"):
        raise WrapperError("cannot wrap malformed/unsupported public payload")
    if not verify.get("integrity", {}).get("ok"):
        raise WrapperError("cannot wrap payload with failed manifest integrity")
    if not verify.get("conformance", {}).get("ok"):
        missing = verify.get("conformance", {}).get("missing") or []
        raise WrapperError("cannot wrap non-conformant handoff: %s" % ", ".join(missing))

    view = kernel.parse(payload)
    source = RUNTIME_PATH.read_text(encoding="utf-8")
    encoded = base64.b85encode(payload).decode("ascii")
    wrapped = "\n".join(textwrap.wrap(encoded, width=100))
    replacements = {
        '"__OXBOW_BUNDLE_NAME__"': repr(str(name)),
        "__OXBOW_FILES__": str(len(view.files)),
        "__OXBOW_RAW_BYTES__": str(view.raw_bytes),
        "__OXBOW_PACKED_BYTES__": str(len(payload)),
        '"__OXBOW_PAYLOAD_SHA256__"': repr(hashlib.sha256(payload).hexdigest()),
        '"__OXBOW_PAYLOAD_B85__"': "'''\n%s\n'''" % wrapped,
    }
    for old, new in replacements.items():
        if old not in source:
            raise WrapperError("wrapper runtime template marker missing: %s" % old)
        source = source.replace(old, new, 1)
    header = (
        "#!/usr/bin/env python3\n"
        "# Generated by Oxbow. This is executable Python containing an inert Oxbow payload.\n"
        "# For untrusted wrappers, prefer a trusted `oxbow bundle verify FILE.oxb.py`\n"
        "# rather than executing the wrapper directly.\n"
    )
    if source.startswith("#!/usr/bin/env python3\n"):
        source = source.split("\n", 1)[1]
    return header + source


def write_wrapper(payload: bytes, output: Path, *, name: Optional[str] = None, self_check: bool = True) -> Path:
    output = Path(output)
    if output.suffix != ".py" or not output.name.endswith(".oxb.py"):
        raise WrapperError("wrapper output must end in .oxb.py")
    if output.exists():
        raise WrapperError("wrapper output already exists: %s" % output)
    name = name or _name_from_output(output)
    text = render(payload, name=name)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(text, encoding="utf-8")
    try:
        output.chmod(0o755)
    except OSError:
        pass

    if self_check:
        cp = subprocess.run(
            [sys.executable, str(output), "--verify"],
            capture_output=True,
            text=True,
        )
        if cp.returncode != 0:
            try:
                output.unlink()
            except OSError:
                pass
            raise WrapperError(
                "generated wrapper failed standalone verification: %s"
                % (cp.stderr.strip() or cp.stdout.strip())
            )
    return output
